### PR TITLE
Feature/psq dascale plotting enhancements

### PR DESCRIPTION
**Pull request by t-b**
Created from: http://stash.corp.alleninstitute.org/projects/ENG/repos/mies-igor/pull-requests/1083/overview

### CODE REVIEW

**Comment by t-b** [comment]
- [ ]  frequency calculation seems to be off (should be 10hz):

grafik

**Comment by t-b** [comment]
@timjarsky Regarding the spike frequencies, I'm using the number of spikes *found*, see https://github.com/AllenInstitute/MIES/blob/feature/psq-dascale-plotting-enhancements/Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf#L1304, whereas you say I should use the number of spikes in the DA wave from the wavebuilder? If yes, how should I handle the case of multiple epochs with different number of spikes?

**Comment by timjarsky** [comment]
>.... whereas you say I should use the number of spikes in the DA wave from the wavebuilder? If yes, how should I handle the case of multiple epochs with different number of spikes?

@t-b No, it is just that in this case they should be equal.

**Comment by timjarsky** [comment]
@t-b spike frequency calculation fails in the test case where I use a pulse train to simulate spikes. This is in part because I think it uses the pulse duration, rather than the epoch duration to calculate frequency. I also noticed that`spikeDetection` has a minimum of 1.  Just want to discuss with you first to make sure that this is limited to my test config.

**Comment by t-b** [comment]
@t-b: Does it handle the case with no spikes at all properly?

**Comment by timjarsky** [comment]
> @t-b: Does it handle the case with no spikes at all properly?

@t-b No; it reliably returns a non zero frequency value.

**Comment by t-b** [comment]
@timjarsky The fix was a bit complicated. But it's fixed now.

**Comment by t-b** [comment]
- [ ] polish local patch with search range for spikes

**Comment by t-b** [comment]
@timjarsky Spike searching is now done only in the range of the pulse and the frequency is rounded.

**Comment by timjarsky** [comment]
@t-b looking good. Last remaining item is the resolution of the spike frequency:

image

**Comment by t-b** [comment]
@timjarsky Next try with the frequency rounding.

**Comment by timjarsky** [comment]
@t-b 

has the rounding issue become an axis range issue?

Also, why is the fit off?

image

**Comment by t-b** [comment]
@timjarsky Can you upload the file?

**Comment by t-b** [comment]
@timjarsky I've pushed some changes. But I think they are not really related. What you are seeing are most likely floating point rounding issues. Both `a` and `b` are close to the double precision of `1e-15`. And the slope output is not wrong with `258a%` as that means `258` atto (10^-18).

Do you expect spike frequencies which are flat like that?

**Pull request merged**
