### PR TITLE
Add chirp analysis function

### LINKED ISSUE #496: New analysis function chirp for IVSCC
- Read input resistance value from lab notebook (or other stimulus)
     - This could involve a quick ‘search’-type stimulus set
- Scale sine wave stimulus to that value (analysis parameter)
- Use DAScale for scaling the stimset
- Monitor min, max peak to through voltage deflections caused by sine wave stimulus (mid sweep), stop sweep and adapt scalar if outside desired range (four analysis parameter with lower_min, lower_max and upper_min, upper_max bounds)
- Adjust scalar and re-run
- Pre and post stimulus QC functions identical to existing stim
- three part stimset: pre, XXX, post
- 3 failures -> Set QC failure
- 3 passing with the same DAScale
- Enforce at least 3 sweeps in the stimset

### PR DESCRIPTION
**Pull request by t-b**
Succesor of #531.

- [x] Update flowchart
- [x] Update dashboard
- [x] resolve todos in code
- [x] Add tests for new spikeCheck code
- [x] Cleanup commits
- [x] Add CheckDashboard calls

Close #496.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready for test.

**Comment by timjarsky** [comment]
@t-b is the statement below backward/inverted?

```
LowerRelativeBound: LowerRelativeBound must be larger than UpperRelativeBound
```

**Comment by t-b** [comment]
@timjarsky I think so yes.

**Comment by t-b** [comment]
@timjarsky Ready for testing. All fixes from our last session are incorporated.

**Comment by timjarsky** [comment]
@t-b i get the following assertion when no levels are found. 
image

here is the AD waveform:

image

here are the stimset param:

image

**Comment by t-b** [comment]
@timjarsky Thanks for the very good bug report! I've pushed a fix.

**Comment by timjarsky** [comment]
@t-b Same settings as above, now the sweep is passing (no assertion), but I think it should fail because the amplitude of the 8th cycle is outside of the range specified in the analysis param.

image

**Comment by t-b** [comment]
@timjarsky The current code does not check that the condition is fullfilled for each cycle but only for all cycles. Code and flowchart agree on that. Is that incorrect?

The issue, https://github.com/AllenInstitute/MIES/issues/496#issue-585096277, would allow both interpretations.

**Comment by timjarsky** [comment]
> @timjarsky The current code does not check that the condition is fullfilled for each cycle but only for all cycles. Code and flowchart agree on that. Is that incorrect?
> 
> The issue, [#496 (comment)](https://github.com/AllenInstitute/MIES/issues/496#issue-585096277), would allow both interpretations.

@t-b What is the purpose of No. of Chrip cycles (optional param)?

**Comment by t-b** [comment]
> What is the purpose of No. of Chrip cycles (optional param)?

It currently says how many cycles should go into the evaluation, once we have acquired that much cycles we do it. So if you pass 5 we will wait until we have 5 cycles and then do the evaluation on the 5 cycles.

**Comment by t-b** [comment]
Rebased to solve conflicts.

**Comment by timjarsky** [comment]
@t-b new feature request: spike check

in mid sweep, check for a level crossing (level defined by user param).

if level crossing is found, repeat reduce da scale, repeat sweep

**Comment by timjarsky** [comment]
> @t-b new feature request: spike check
> 
> in mid sweep, check for a level crossing (level defined by user param).
> 
> if level crossing is found, fail sweep, reduce da scale, repeat sweep
> 
> goal: to keep the chirp from inducing the cell to spike

@t-b i want to modify the above slightly; the mid sweep check for a level crossing should happen after the baseline period (normal baseline qc should catch spikes and respond appropriately).

**Comment by t-b** [comment]
@timjarsky 
- Is that spike check optional? (no)
- Is the level relative to the baseline or absolute? (relative) The min/max values for the bounds checks are relative.
- I would allow to adjust the dascale via our common Value+Operator analysis parameter duett?

I've added my rookie guesses in parantheses.

**Comment by timjarsky** [comment]
> @timjarsky
> 
> * Is that spike check optional? (no)
> * Is the level relative to the baseline or absolute? (relative) The min/max values for the bounds checks are relative.
> * I would allow to adjust the dascale via our common Value+Operator analysis parameter duett? (yes)
> 
> I've added my rookie guesses in parantheses.

@t-b 

I like your suggestion to make the spike check optional. So, let's switch that to yes

The level is defined in the same way as the PA plot (absolute).

Let's discuss the last one, to make sure I follow, but I think the answer is yes.

**Comment by t-b** [comment]
PSQ_Chirp changes:
- Spike check in Mid sweep event
- Same approach as SC_SpikeControl, if level crossing is found, fail sweep early without repurposing time for ITI, ,
  reduce da scale, repeat sweep
- Only look during the chirp for spikes
- Analysis parameters:
  - FailedLevel (absolute)
  - DaScaleModifier and *Operator
  - SpikeCheck [optional, default to yes]

**Comment by t-b** [comment]
So I've pushed some code which implements most of the spikecheck code. I'll be tuning it over the weekend.

Some corner cases/observations:
- We haven't specified if the, by failing spike check adapted, DAScale should also be rounded to full PA. I would say yes. We are rounding to full PA, so that we have a chance of having multiple passing sweeps with the same DAScale values.
- AFAIU we can't adjust the DAScale in more than one way as all paths immediately finish the sweep early
- I did not do skipping back one sweep, as that breaks the POST_SET_EVENT I'm currently using.
- We fail the set if we have three failed sweeps. Should failed sweeps due to spikes during chirp also take part in that counting?

**Comment by t-b** [comment]
@timjarsky Ready for prime time.

**Comment by timjarsky** [comment]
@t-b chirp asserts out with spike detection enabled

```
  The analysis function PSQ_Chirp aborted with error "", this is dangerous and must *not* happen!
  !!! Assertion FAILED !!!
  Message: "Unexpected value of numberOfSpikesReq"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L92 [MIES_DataAcquisition_Multi.ipf]
AS_HandlePossibleTransition(...)#L97 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L130 [MIES_AnalysisFunctionManagement.ipf]
PSQ_Chirp(...)#L3632 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_SearchForSpikes(...)#L906 [MIES_AnalysisFunctions_PatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-04-21T14:06:33-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [4]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2021_04_21_135257 (Packed)
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-1110-g75e3e4747
Date and time of last commit: 2021-04-11T19:15:39+02:00
Submodule status: 
160000 3fa58754bb50a399a190d7eaa014779f72af7ae0 0	Packages/IPNWB
160000 5ffbdab2c5d42b54f86054c9bcd0cea6e5f07829 0	Packages/doc/doxygen-filter-ipf
160000 42276ed677273c02bc7b457324081dd463bb0d6b 0	Packages/unit-testing
```

**Comment by t-b** [comment]
@timjarsky Please retry.

**Comment by timjarsky** [comment]
@t-b i figured out a way to test the spike detection. Sweeps are being terminated early; nice! They also cause the sweep to fail QC BUT the dashboard doesn't show any failed sweeps [1]. It also appears that the stimset is being failed after two sweep failures but the stimset still had enough sweeps in it that if it had proceeded, it could have passed.

What does `NumberOfChirpCycles` mean. If it is set to 3 does that mean the evaluation happens on, and only on, the 3rd cycle?
For the stimset to pass, are we requiring that the DA scale be the same for 3 passing sweeps?

[1]
image

**Comment by t-b** [comment]
- [ ] NumberOfChirpCycles: Number of acquired chirp cycles before the bounds evaluation starts. Defaults to 1.
- [ ] Selecting failed sweeps from dashboard does not work
- [ ] Make PSQ_CR_NUM_SWEEPS_FAIL an analysis parameter and default it to 3

**Comment by t-b** [comment]
@timjarsky Ready for another look. The dashboard issue was not restricted to Chirp but rather all PSQ analysis functions.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
