### PR TITLE
Rework SF labnotebook and add anaFuncParam

### LINKED ISSUE #1845: SweepFormula: Use different colors for traces from `data`
But only when the traces are in the same graph and are from the same headstage.

### PR DESCRIPTION
**Pull request by t-b**
- [x] anaFuncParam
	- [x] Documentation, add link to anafunc entry table
	- [x] Tests
- [x] https://github.com/AllenInstitute/MIES/issues/1845, use meta data something like a color group
- [x] Add link from labnotebook SF docu to lBn entry table
- [x] Override tooltip to show all values when hovering over multiple traces
- [x] commit cleanup
- [x] finish color group
- [x] Adapt tests for labnotebook
- [x] Wait for https://github.com/AllenInstitute/MIES/pull/2109 and update the MR

Example code:

```
sel = select(channels(AD), sweeps())

labnotebook(["USER_DA Scale f-I slope", "USER_DA Scale BL QC"], $sel, UNKNOWN_MODE)

and

AnaFuncParam(["MaxFrequencyChangePercent", "AbsFrequencyMinDistance", "AbsDAScaleMinDistance", "AbsDAScaleMaxDistance"], $sel)

and

AnaFuncParam("OperationMode")
```

Close #1845

### CODE REVIEW

**Comment by timjarsky** [comment]
> @timjarsky THis has the changes for accepting multiple labnotebook keys and the new `anaFuncParam` operation. See above for examples.

Thanks, @t-b. I'm excited to take a look. When you get around to the documentation, can you add a link to the lab notebook entry descriptions in the documentation?

**Comment by timjarsky** [comment]
@t-b nice!

image

**Comment by t-b** [comment]
Next revision:

Code:

```
sci  = $sci15
sel = select(channels(AD), $sci, all)

data($ep, $sel)

and

labnotebook(["Delay onset auto", "Delay onset user"], $sel, UNKNOWN_MODE)

and

AnaFuncParam(["*"], $sel)

and

AnaFuncParam(["SlopePercentage", "SamplingFrequency"], $sel)
```

grafik

We now have unique colors per sweep if all data is from the same channelType and number, and also wildcard support for `anaFuncParam`. Without that there is no way to figure out what parameters are available.

@timjarsky If that is good, I'll polish it.

**Comment by t-b** [comment]
Now the SF `labnotebook` command also has support for wildcard syntax.

**Comment by t-b** [comment]
I've implemented the tooltip for labnotebook and anaFuncParam as it is quite helpful.

**Comment by timjarsky** [comment]
slick! Thanks @t-b 

image

**Review by timjarsky — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@t-b I'm seeing the data plotting style change in the middle of the plot. It seems like the method for changing the style depending on the number of points is being applied to the same plot

image

**Comment by t-b** [comment]
Tim will provide data.

**Comment by t-b** [comment]
> @t-b I'm seeing the data plotting style change in the middle of the plot. It seems like the method for changing the style depending on the number of points is being applied to the same plot
> 
> image

This is also present in main. I've opened https://github.com/AllenInstitute/MIES/issues/2281 to track that.

**Comment by t-b** [comment]
@timjarsky I've integrated the new select PR and adapted the code. Do you want to have a look again? If not I would just merge once CI passes and #2109 is merged.

**Comment by timjarsky** [comment]
> @timjarsky I've integrated the new select PR and adapted the code. Do you want to have a look again? If not I would just merge once CI passes and #2109 is merged.

@t-b I think it makes sense for me to test select with PSX before merging.

**Comment by t-b** [comment]
> > @timjarsky I've integrated the new select PR and adapted the code. Do you want to have a look again? If not I would just merge once CI passes and #2109 is merged.
> 
> @t-b I think it makes sense for me to test select with PSX before merging.

The question was for the anaFuncParam PR.

**Comment by timjarsky** [comment]
@t-b Sorry, I got confused. Yes, please go ahead and merge.

**Pull request merged**
