### PR TITLE
SF: Adapt tp operation for new fit mode

### LINKED ISSUE #1155: Auto TP: Make baseline fitting routine available as sweep formula

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1247
close #1155

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@timjarsky This is in a state for initial testing and tryout. The new command is:
`tp(mode, ...)` // the first argument changed

for mode you have to use one of the following operations:
`tpbase()`
`tpss()`
`tpinst()`
`tpfit(exp,amp,250)`

where `exp` is for exp_Xoffset and `doubleexp` would be for dblexp_XOffset fit function.
The second argument is for the return value displayed, options are:

`tau` // if doubleexp max tau, otherwise identical to tausmall

`tausmall` // if doubleexp min tau, otherwise identical to tau

`amp` // if doubleexp then amplitude of maximum abs amplitude

`minabsamp` // if doubleexp then amplitude of minimum abs amplitude

`fitq` // sum(residuals^2) / numXPoints

I have not tested User TPs yet.
Display of full fit result in debug mode is not implemented yet.

**Comment by timjarsky** [comment]
@MichaelHuth I get a compile error; expected assignment operator
```
				WAVE/Z/T nextEpoch = EP_GetNextEpoch(numericalValues, textualValues, sweepNo, XOP_CHANNEL_TYPE_DAC, dacChannelNr, epBaselineTrail, 1)
```

**Comment by MichaelHuth** [comment]
@timjarsky I forgot to push a part of the changes epochs code. Sorry for that. It should work now.

Also special output is in when debugmode for sweepformula is enabled. In Debugmode I recommend not so select too many sweeps, otherwise the output can get a bit overwhelming.

**Comment by timjarsky** [comment]
Hi @MichaelHuth 

In debug mode, the fit never extends past the end of TP_B1 (see below). Does the end of the fit trace indicate that the baseline epoch following TP_B1 is not being used for the fit? 

image
image

**Comment by MichaelHuth** [comment]
@timjarsky Could you upload your example case as experiment file? The start of the following epoch at 78.005 is a bit suspicious.

**Comment by timjarsky** [comment]
[TPfittesting.zip](https://github.com/AllenInstitute/MIES/files/10016202/TPfittesting.zip)
zipped .pxp file. Data was generated from the PR @MichaelHuth

**Comment by MichaelHuth** [comment]
Diagnosis:

The issue is that we calculate the Length the TP uses at two locations differently. This breaks the consecutive epochs.
For the TP wave the length is retrieved from `TP_UpdateTPSettingsCalculated` with
`calculated[%pulseLengthPointsDAQ] = trunc(TPSettings[%durationMS][INDEP_HEADSTAGE] / (DAP_GetSampInt(device, DATA_ACQUISITION_MODE) * MICRO_TO_MILLI))`

The other location where this plays a role is if `Inserted TP` is enabled in the DA_Ephys panel. Then the ms are calculated with
`TP_CalculateTestPulseLength` and written to the GUI control `Onset delay (ms)` and reduced to 5 digits after the . because `%g` is used. This value is then used to calculate the effective onset delay in `DC_ReturnTotalLengthIncrease` with
`onsetDelayAutoVal      = round(GetValDisplayAsNum(device, "valdisp_DataAcq_OnsetDelayAuto") / (samplingInterval * MICRO_TO_MILLI))`

The result is that the onset delay that defines the start of the stimset is not the same as the end of the inserted TP. This gives a few missing ms in the epochs and the stimset epoch does not start when the TP epoch ends - thus it is not the next epoch.

**Comment by t-b** [comment]
@timjarsky I'm chatting with Michael about a fix. I'll do the fix so that in the future we have no gaps in the epochs again.

I presume you also want to analyse existing data with gaps?

**Comment by timjarsky** [comment]
> @timjarsky I'm chatting with Michael about a fix. I'll do the fix so that in the future we have no gaps in the epochs again.
> 
> I presume you also want to analyse existing data with gaps?

@t-b I'm not sure. For now, I might prefer to make an issue for handling gaps rather than solve it now.

**Comment by t-b** [comment]
>  I'm not sure. For now, I might prefer to make an issue for handling gaps rather than solve it.

It's relatively easy to ignore the gaps, so how about now?

**Comment by timjarsky** [comment]
@t-b sure

**Comment by t-b** [comment]
https://github.com/AllenInstitute/MIES/pull/1554 has a fix for the epoch "gap".

**Comment by MichaelHuth** [comment]
I added a workaround for the gap that can be enabled by setting the constant EPOCH_GAPS_WORKAROUND in MIES_Epochs.ipf to 1.

I also added tests.

**Comment by t-b** [comment]
@MichaelHuth Can you fix CI? Thanks. Linting is `tools/check-code.sh`.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b 
(1)
I expect combining avg with tp to return a single average value, that's the average of each tp formula return for each sweep.

Instead, it returns the same values as TP formula alone but plotted vs. sweeps.

image
image

(2)
In voltage clamp, the following error occurs sometimes:
image
Here is the data file
[QN22.26.030.14.07B.03.zip](https://github.com/AllenInstitute/MIES/files/10149336/QN22.26.030.14.07B.03.zip)

(3)
Since the user can set the time for the exp fit, should we remove the 500 ms hard cap? e.g., tpfit(exp,amp,1000)

**Comment by MichaelHuth** [comment]
> @MichaelHuth @t-b (1) I expect combining avg with tp to return a single average value, that's the average of each tp formula return for each sweep.
> 
> Instead, it returns the same values as TP formula alone but plotted vs. sweeps.

The issue here is the following:

The operation avg average the data within a sweep. So if you do an avg(data(...)) then it averages the points from each sweep independently. In developer speech data returns multiple independent result waves and avg is applied to each one.

Now tp returns multple data waves as well, for each tp times sweep. The result with exp is a single point and thus, avg averages over each of these single point waves independently. But you want now something else, you want to average over the data of multiple result waves. This would need a different average operation that works in the other direction.

Regarding the different plotting: tp suggests to the plotter to plot against the tp number on the x-axis. After avg is applied this suggestion is cleared, as it would in the general case make no sense any more. Thus, the default kicks in for data that was somehow sources by sweeps that it is plotted agains the sweep number.

**Comment by MichaelHuth** [comment]
@timjarsky regarding 2:

TP operates this way "If a single sweep contains multiple test pulses then the data from the test
pulses is averaged before analysis. The test pulses in one sweep must have the same duration." (copied from docu)
So the issue here is that there are 4 TPs in the sweep and the first tp epoch is 100 ms, whereas the others are 60 ms long.
The operation does not average TPs with different length as this will likely give no senseful result.
If you adapt the expression to
```
TP(
tpss(),
select(channels(AD),sweeps()),0
)
```
to exclude the first TP it will give a result.

**Comment by timjarsky** [comment]
> 
> The issue here is the following:
> 
> The operation avg average the data within a sweep. So if you do an avg(data(...)) then it averages the points from each sweep independently. In developer speech data returns multiple independent result waves and avg is applied to each one.

Hi @MichaelHuth Thomas reminded me we already have an issue for this #1552.

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
Review:

Please rebase against latest main so that NI passes.

52e8875d (SF: Add operation tpss, tpinst, tpbase, tpfit for setup of tp mode, 2022-11-04)

Good!

eb524741 (SF: Add new tpfit mode, 2022-11-07)

Unneeded ` + 1` for EnsureLargeEnoughWave. This seems to be a persisting issue. Does the documentation need improving?

Wrong indentation:
```
if(debugMode)
	return output
endif
```

Unrelated changes are part of the commit! All the epoch additions should be in its own commit. Tests are missing for EP_GetNextEpoch. And that function also does not handle multiple next epochs which can happen with user epochs, I'm fine with asserting in this case if you think this is the easiest approach.

b829e470 (SF: Change TP annotation to be aware of invalid sweep numbers, 2022-11-10)

The commit message should explain why this change is needed. How can that bug happen in real life?

ccc45138 (SF: Add tests for tpss, tpbase, tpinst, tpfit, 2022-11-11)

Good.

3898d0e0 (SF: tp operation tpfit add fit length information to output in testing mode, 2022-11-14)

Please add newlines around `#ifdef /#endif` blocks as these are a new logical unit per our coding guidelines.

7189a16d (SF: Adapt tests for tp operation with new tp mode parameter, 2022-11-14)
bc471524 (SF: Add tests for tp operation with tpfit mode, 2022-11-14)
ad6c05ed (EP: Add workaround for epoch gaps for EP_GetNextEpoch, 2022-11-18)

The commit message leaves the reader clueless why gaps can happen. As the MR in question is not yet merged, I think it is in this case useful to refer to https://github.com/AllenInstitute/MIES/pull/1554.

EP_GetNextEpoch: Is the new optional parameter `checkGaps` named correctly? For me this looks more like `ignoreGaps`.

I think `EP_GetGaps` can be made static.

18c22363 (EP Tests: Add Tests for EP_GetNextEpoch, 2022-11-18)

Tests are good, commit splitting not, see the comment for eb524741.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Review by t-b — APPROVED** [review]

**Pull request merged**
