### PR TITLE
MIES Configuration, enhance to save/restore also notebook contents as plain text

### PR DESCRIPTION
**Pull request by MichaelHuth**
This enhances the MIES Configuration module to be aware of notebook windows.
For notebook windows the content gets saved as plain text and restored as plain text.
The SweepFormula help notebook was excluded from saving/restore as it contains formatted text.

close https://github.com/AllenInstitute/MIES/issues/646

### CODE REVIEW

**Comment by t-b** [comment]
Review:

434dcfa0 (CONF: Extend window state saving/restoring to notebook windows, 2022-10-01)

Yes!

245f3a77 (Move two static constants from MIES_Configuration to public area, 2022-10-01)

Okay.

72d85a81 (Set DataBrowser SF help panel to be excluded for GUI configuration saving, 2022-10-01)

Nope. We should not set the exclude flags at runtime as we always set that in the recreation macro.

So I would add the SetWindow calls in DB_ResetAndStoreCurrentDBPanel and regenerate the panel macro. We normally use the "UserDataEditor for Controls" but that does not work here. Feel free to also just edit the panel macro (and test it!).

Looking at all notebooks in the databrowser from a saved window config

```
$ grep -C1  NotebookText test.json
    "DB_ITC18USB_Dev_0#BrowserSettingsPanel#WaveNoteDisplay": {
        "NotebookText": ""
    },
    "DB_ITC18USB_Dev_0#BrowserSettingsPanel#sweepFormula_formula": {
        "NotebookText": "data(\rcursors(A,B),\rselect(channels(AD),sweeps())\r)"
    },
    "DB_ITC18USB_Dev_0#BrowserSettingsPanel#sweepFormula_json": {
        "NotebookText": ""
    },
--
    "DB_ITC18USB_Dev_0#SettingsHistoryPanel#Description": {
        "NotebookText": ""
    },
(
```

I think we want to ignore the others as well.

f9f8a883 (SF: Add test for Configuration notebook saving/restore, 2022-10-01)

Nice!

**Comment by t-b** [comment]
@MichaelHuth Thx. LGTM.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@t-b PR works! Thank you both! Minor item: in the PR title, it says #1495 but the branch name indicates #1494

**Comment by t-b** [comment]
> Minor item: in the PR title, it says https://github.com/AllenInstitute/MIES/pull/1495 but the branch name indicates https://github.com/AllenInstitute/MIES/pull/1494

Thanks for pointing out. We'll have a look if that happens again.

**Pull request merged**
