### PR TITLE
Make the inserted TP length calculation consistent

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add test differing dDAQ delay for epoch info
- [x] Nicify commits
- [x] fix onset delay calculation for GUi
- [x] Fix GetTotalOnsetDelayFromDevice
- [x] Investigate test failures

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth Please have a look.

**Review by MichaelHuth — CHANGES_REQUESTED** [review]
It is working and code looks good to me.

Still, there is one thing that should be unified:
We have a test pulse pulse length calculation in https://github.com/AllenInstitute/MIES/blob/8c1a53b5c54656f1199cd2c739de8fd9eaf056df/Packages/MIES/MIES_TestPulse.ipf#L1499 for the creation and in
TP_CalculateTestPulseLength for the whole length and in TP_CalculateBaselineFraction for the BL fraction.

It would be good if this is more condensed in the code at one location or maybe even one function.

I am also fine to postpone that to an issue.

**Comment by t-b** [comment]
@MichaelHuth THx. Done.

**Review by MichaelHuth — DISMISSED** [review]
LGTM

**Comment by t-b** [comment]
The failing NI test, SF_InsertedTPVersusTP, is fixed in #1559.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
