### PR TITLE
Adapted PA_Average to support incremental averaging

### PR DESCRIPTION
**Pull request by MichaelHuth**
Generally for incremental averaging the function has to return
the sum per row as well as the counts per row additionally.
For this the new optional parameter getComponents was introduced.

To keep auto indexing calls to MIES_fWaveAverage possible, instead of
using MRS the function now returns a wave reference wave with 3 rows.

The first row is the average wave as before.
The second row are the sums and the thrid the counts.
The second and third row are only setup with valid return data when
getComponents = 1 was used.

Having the sums per row and counts per row, it is also possible to call the
averaging incremental. Previous averaging data can be given by the optional
prevAvgData wave reference parameter.
The first entry must contain the sums and the second the counts per row.

This data is then included in the averaging of the yWaves.

close https://github.com/AllenInstitute/MIES/issues/733
close https://github.com/AllenInstitute/MIES/issues/673
close https://github.com/AllenInstitute/MIES/issues/207
close https://github.com/AllenInstitute/MIES/issues/716
close https://github.com/AllenInstitute/MIES/issues/713
close https://github.com/AllenInstitute/MIES/issues/698
close https://github.com/AllenInstitute/MIES/issues/695
close https://github.com/AllenInstitute/MIES/issues/705

### CODE REVIEW

**Comment by timjarsky** [comment]
When setting up to test this PR I noticed that in `main` (and here), it takes almost twice as long to remove a sweep (in OS with PA plot) as it does to add a sweep. @MichaelHuth @t-b do you know the reason for this?

**Comment by t-b** [comment]
@timjarsky "Adding sweeps" has a fast code-path as that is what needs to be fast so that it can be used during DAQ. "Removing sweeps" does currently take the same code path as "full update".

**Comment by MichaelHuth** [comment]
@t-b Could I get a hint why the CI fails?

**Comment by t-b** [comment]
@MichaelHuth "Test from repo" does compile testing and executes RunAllTests.pxp. You can execute that as well. It usually is a compile error.

**Comment by MichaelHuth** [comment]
rebased

**Comment by timjarsky** [comment]
@MichaelHuth @timjarsky my standard test case result (using the new timers):

```  PA_GenerateAllPulseWaves  3.27871090002441
  PA_ApplyPulseSortingOrder  0.00890579998779297
  PA_ResetWavesIfRequired  0.038705200012207
  PA_MarkFailedPulses  0.202974800048828
  PA_ZeroPulses  0.1646295
  PA_AutomaticTimeAlignment  0.2175215
  Cache Miss All
  PA_CalculateAllAverages  0.4534515
  Preprocess  4.36896790002441
  Showpulses  1.22116769995117
  All  5.59336179998779
```

In this PR, after selecting none from OS, then selecting a single sweep in OS I get the following:

**Comment by timjarsky** [comment]
@t-b @MichaelHuth when testing incremental updating:

image

results looked pretty good up to that point;

```
  All  0.459486200012207
  All  0.292831299987793
  All  0.402526199951172
  All  0.243284799987793
  All  0.288254099975586
```

**Comment by MichaelHuth** [comment]
@timjarsky I could reproduce the second bug. I already have a lead and fix it tomorrow (It just made my IP8 crash hard without dmp). Maybe the first is a follow up issue from that.

**Comment by timjarsky** [comment]
> @timjarsky I could reproduce the second bug. I already have a lead and fix it tomorrow (It just made my IP8 crash hard without dmp). Maybe the first is a follow up issue from that.

@MichaelHuth you are right in that the first bug recipe wasn't from a clean start. I can try and reproduce after the fix for the second issue is in.

**Comment by MichaelHuth** [comment]
@timjarsky The missing waves errors should be gone now and the Igor crash too. Also starting from an empty graph should be good now. A known problem is when the image gets new axes, -> this is in the queue. 

A few other things are fixed, like setting a starting/ending pulse range that is beyond the actual pulses as well as a offset in the deconvolution plot when using time alignment.

Getting the current speedup for incremental updates involved some ground level changes in the handling of the wave note meta data. So don't hesitate to check the data consistency once more.

Next things are: Giving MarkFailedPulses a revamp to not eat previous time when actually not changed. Adding a speed code path for the case of removing plots.

**Comment by timjarsky** [comment]
@MichaelHuth 
I'm still seeing the issue. Here is the full history - I thought the timing of the assertion messages relative to the timer print statements might be helpful. All the assertions came at once.

**Comment by timjarsky** [comment]
@MichaelHuth the recent changes fixed the bug and made incremental updating even faster!

```
  All  5.71652280004883
  All  0.108925
  All  0.136182599975586
  All  0.154273799926758
  All  0.148223300048828
  All  0.246816700073242
  All  0.196369599975586
  All  0.297328599975586
  All  0.229893300048828
  All  0.246664599975586
  All  0.278001199951172
  All  0.300140199951172
```

There is what I think is a new old bug with image plot though:

```
  !!! Assertion FAILED !!!
  Message: "Unexpected abort"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_ButtonProc_ChangeSweep(...)#L1275 [MIES_BrowserSettingsPanel.ipf]
OVS_ChangeSweepSelectionState(...)#L321 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3570 [MIES_MiesUtilities.ipf]
PA_Update(...)#L909 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-23T09:34:03-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  ################################
  ** ModifyFreeAxis gave error: Specified master axis not found.
```

image

**Comment by t-b** [comment]
@timjarsky The PR is probably not rebased to main.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b incremental update with image plot (not trace) plot.

I can make it bug out with trace plot too but I figured we should deal with one issue at a time. Let me know if you think differently.

```
  Message: "Unexpected abort"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_ButtonProc_ChangeSweep(...)#L1275 [MIES_BrowserSettingsPanel.ipf]
OVS_ChangeSweepSelectionState(...)#L321 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3570 [MIES_MiesUtilities.ipf]
PA_Update(...)#L957 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-23T13:06:22-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-372-g0fb69553
Date and time of last commit: 2020-10-23T21:58:48+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 b890ee01f65722475338602ff998abadad66b76f 0	Packages/unit-testing
  ################################
```

image

**Comment by MichaelHuth** [comment]
rebased

**Comment by timjarsky** [comment]
@MichaelHuth @t-b recent test results using PA image plot and incremental updates with overlay sweeps. Feel free to let me know if I am testing too frequently to be helpful.


1st debug instance
image
No assertion.
2nd debug instance
image

Associated assertion:
```
 !!! Assertion FAILED !!!
  Message: "Unexpected abort"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_ButtonProc_ChangeSweep(...)#L1275 [MIES_BrowserSettingsPanel.ipf]
OVS_ChangeSweepSelectionState(...)#L321 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3570 [MIES_MiesUtilities.ipf]
PA_Update(...)#L1035 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-26T19:26:04-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  ################################
```

**Comment by timjarsky** [comment]
I also see:
```
 !!! Assertion FAILED !!!
  Message: "Missing horizontal axis"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_ButtonProc_ChangeSweep(...)#L1275 [MIES_BrowserSettingsPanel.ipf]
OVS_ChangeSweepSelectionState(...)#L321 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3570 [MIES_MiesUtilities.ipf]
PA_Update(...)#L1033 [MIES_PulseAveraging.ipf]
PA_ShowImage(...)#L3073 [MIES_PulseAveraging.ipf]
PA_DrawScaleBars(...)#L1902 [MIES_PulseAveraging.ipf]
PA_DrawScaleBarsHelper(...)#L2005 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-26T19:36:02-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-375-g406128c3
Date and time of last commit: 2020-10-27T00:50:53+01:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 b890ee01f65722475338602ff998abadad66b76f 0	Packages/unit-testing
  ################################
```
image

**Comment by MichaelHuth** [comment]
@timjarsky Intense tests are always helpful, though currently we identified some issues where the current concept of generation and display gets to its limits for incremental (or later removal) updates. We need to gather and save more state information at generation time to keep track how the sets of traces change. Specifically when on add/removal of sweeps the layout of the sets in the graph changed, e.g. from 4x4 to 5x5 or the other way around. With the original concept this could not be covered by incremental updates.

**Comment by t-b** [comment]
Some feedback while testing 42890008 (PA: Reenabled PA_AxisHook for redrawing scale bars., 2020-10-30) with latest IP9:
- Turning on "Show average" takes ages

```
---
  PA_ApplyPulseSortingOrder  0.0001535
  Preprocess  0.0167092000000477
  Showpulses  37.1646794
  All  38.1218191999999  
---
```

Same with "Deconvolution".

- Turning off deconvolution with multiple graphs on gives

```
 ** ReorderTraces gave error: trace is not on graph
```

- When using a fixed pulse length the average is wrong

grafik

- Changing the "Ending pulse" value does not update the trace plot

- The image and trace plot disagree on failed pulses

grafik

**Comment by t-b** [comment]
@MichaelHuth Before you start fixing these issues we need to derive some automated tests to check for that.

**Comment by MichaelHuth** [comment]
rebased

**Comment by timjarsky** [comment]
@MichaelHuth the image plot looks good if all the OS traces are displayed at the same time. With incremental updates it looks like:
image

**Comment by MichaelHuth** [comment]
@timjarsky Thanks for the feedback, I could reproduce that and fixed it in 1bab7a0. It also helped me to find another issue appearing as side effect of a specific constellation from sweep 17 to 18, where the averaging data for some sub plots were lost.

**Comment by MichaelHuth** [comment]
Good for more testing

**Comment by t-b** [comment]
Note to self:
- Investigate why average/deconvolution is not taking 5% anymore. Move to 10%
- Check if sort order pulse and sweep are correct or if they are flipped

**Comment by t-b** [comment]
@MichaelHuth Needs a rebase.

**Comment by MichaelHuth** [comment]
@t-b @timjarsky I think this is ready for more intense testing. It passes the tests from UTF_PA_Tests and I fixed quite an amount of issues.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b the vertical space for the average and deconvolution lines in the image plot is too small.

There also appears to be an alignment issue in some cases (left column).

image

Sometimes when no sweeps are displayed in the databrowser, either by selecting `none` in OS, or unchecking all selected sweeps, I get:

```
 ** GetDataFolder gave error: Expected a Data Folder Reference.
```

**Comment by MichaelHuth** [comment]
@timjarsky Average and Deconvolution line size: currently on incremental update the size is kept constant as it was on the last full update. I you start with a single sweep it is likely 1. Our current idea that allows to keep the average and deconvolution line sizes always x% (5 atm) on incremental update is to put the average and deconvolution on the side where the new pulses are added.
In the current design the average/deconv is drawn on the side where the first pulses are. So if the vertical size changes on incremental update and thus the average/deconv area size changes then a full update would be required. The upper idea would allow to combine the speedup of incremental update with a fixed percentage line size for avg/deconv.

HS removal: Yes currently in this PR the vertical (same region other channels) the pulses are not removed.

Offset on the left: The onset of the shifted pulses is exactly at the x zero line. Could it be that the pulses have a maximum value exactly at the beginning, such that the time alignment moves them as seen? If you see something like this (that might not be correct) it would be good to have the data to diagnose what is happening internally.


I will see if I can reproduce the GetDataFolder error.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b 

1) Feel free to move the location of the avg and deconvolution lines. 

2) 
>Could it be that the pulses have a maximum value exactly at the beginning, such that the time alignment moves them as seen? >If you see something like this (that might not be correct) it would be good to have the data to diagnose what is happening >internally. 

I don't think so, as it only occurs with incremental updates, not when the plot is regenerated from scratch. It also only happens with sweeps that are removed using headstage removal in overlay sweeps - so, my assumption is this would get fixed (indirectly) in the PR that handles how headstage removal works in the PA plot.

3)
The recipe for the GetDataFolder error is as follows:
- use analysis browser to select NWB file
- in sweep browser, enable OS
- uncheck sweep 0

**Comment by MichaelHuth** [comment]
@t-b Ready for feedback on the code.

**Comment by t-b** [comment]
@MichaelHuth 

All PA_Tests pass. Nice!
I've looked not too deeply into the algorithms. But only on the general code style.

Please don't rebase this PR anymore.

Feel free to schedule a meeting with me if needed.

Questions:
- [ ] Does the comment regarding sortOrder in PA_LayoutGraphs in PA_GetAxes still make sense?
- [ ] PA_SetDiagonalityNote: Are you not using multithread on purpose?
- [ ] PA_GetSetWaves_TS: What does "combined getModes" mean?

Needs Documentation:
- [ ] CA_RecursiveWavemodCRC and make it static as well
- [ ] PA_CreateAndFillPulseWaveIfReq: This function should also explain all wave
  note entries, which are created in this function or in total
- [ ] PA_GenerateAllPulseWaves: Explain new incremental mode in docu
- [ ] PA_InitPASIInParts
- [ ] PulseAverageSetIndices: Try to make it detailed and succint. This must also
  include dimensionanlity of waves and other things we usually document in the
  wave getters. PostPlotSettings has examples how to document structure
  elements. Please also explain what the 2 in setWaves2Unsorted means. If there are other
  places which document something, just link to it and don't duplicate the
  documentation.
- [ ] PA_GetSetIndicesHelper
- [ ] PA_UpdateIndiceNotes
- [ ] PA_StoreMaxAndUnitsInWaveNote: Please also explain what the return value means
- [ ] PA_IsDataOnSubPlot

Dead code:
- [ ] GetPulseAveragePropertiesText
- [ ] PA_PROPERTIESTEXT_INDEX_EXPERIMENT
- [ ] PA_GetGraph: junk
- [ ] PA_ClearGraphs: junk
- [ ] GetPAAverageBuffer:

Changes:
- [ ] PA_GetUniqueHeadstages: Should use GetUniqueEntries. This also checks for one point waves.
- [ ] Please keep the timing statements but use something like a define to hide
  them by default. We already have PA_HIDE_AXIS which does that and helps a lot
  in debugging. These should also have less duplicated code.
- [ ] In general print statements should be converted to DEBUGPRINT
- [ ] PA_MakeAverageWavePermanent: KillorMoveToTrash accepts a null wave
- [ ] PA_GetPermanentAverageWave: This should be moved to MIES_WaveDataFolderGetters.ipf. If not I need persuasion why this is the right place ;)
- [ ] PA_EquallySpaceAxis: Should be moved into utils next to EquallySpaceAxis. And don't pass default arguments like ";".
- [ ] GetPulseAverageProperties: This still includes unused columns or? IIRC we dropped at least DiagonalElement.
- [ ] I think `#ifdef AUTOMATED_TESTING` in UTF_PA_Tests.ipf does not make sense. We never have that in test suites.

**Comment by t-b** [comment]
@MichaelHuth I've fixed the spike control test failures see 0fe7b17.

**Comment by t-b** [comment]
@timjarsky Tests are passing. Ready for more testing.

**Comment by t-b** [comment]
@MichaelHuth Is `PA_PROPERTIES_INDEX_ACTIVEXX` still used? I don't see that.

**Comment by MichaelHuth** [comment]
@t-b I added a fix in OVS, where for additionalData the index was posted instead of the sweepNo.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b using a `Fixed pulse length` removes  `zero traces`

**Comment by MichaelHuth** [comment]
@timjarsky I could reproduce that and not only ZeroPulses but also TA was not executed in that case. It should be fixed now.

**Comment by t-b** [comment]
@timjarsky Once this is good, just approve and merge.

**Comment by timjarsky** [comment]
@MichaelHuth 

Using my standard test file, select recovery stimset in overlay sweeps
PA plot show avg, not individual traces
Select none in overlay sweeps
Select sweep 31 in overlay sweeps

```
  !!! Assertion FAILED !!!
  Message: "A sweep with the same number is already plotted. Multiple sweeps with the same number from different experiments is currently not supported."
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
SB_PopupMenuSelectSweep(...)#L529 [MIES_AnalysisBrowser_SweepBrowser.ipf]
OVS_ChangeSweepSelectionState(...)#L371 [MIES_OverlaySweeps.ipf]
OVS_EndIncrementalUpdate(...)#L819 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3620 [MIES_MiesUtilities.ipf]
PA_Update(...)#L1165 [MIES_PulseAveraging.ipf]
PA_PreProcessPulses(...)#L1834 [MIES_PulseAveraging.ipf]
PA_GenerateAllPulseWaves(...)#L623 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-11-24T09:13:17-08:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.3 (36607)
  MIES version:
  Release_2.1_20200723-564-gcf828ae4c
Date and time of last commit: 2020-11-24T14:06:41+01:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 4b67466116212d042ca5c7427b51ddcb60630117 0	Packages/unit-testing
  ################################
```

**Comment by MichaelHuth** [comment]
@timjarsky I have commited a fix that should solve the last problem.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
