### PR TITLE
Record sweep formula and add store operation

### LINKED ISSUE #431: SweepFormula: Store analysis results in NWBv2
~~https://pynwb.readthedocs.io/en/stable/pynwb.file.html#pynwb.file.NWBFile.add_analysis~~ `/scratch` is the best place for that.

### LINKED ISSUE #1222: SweepFormula: Store formula in LBN and add new function for storing results as well
- [x] Store the complete sweep formula under "SweepFormula code" code each time it is executed in the textual LBN (entrySourceType: UNKNOWN_MODE)
- [x] Add function `store(YYY, XXX)` to allow storing `XXX` in the labnotebook (entrySourceType: UNKNOWN_MODE) under `SweepFormula result [YYY]`. Only store the first `numSweeps * NUM_HEADSTAGES * 10` values from `XXX`, complain loud on too many values. `XXX` can be a scalar or array with numbers or text.
- [ ] Add PopupMenu in databrowser' SF tab to browse old "SweepFormula ZZZ" entries and rexecute them

### PR DESCRIPTION
**Pull request by t-b**
- [x] Document new results wave in labnotebook_docs.rst
- [x] Add all things like sweeps, channels, cursors, device, experiment
- [x] Add proper GUI controls for querying old SF code
- [x] Allow browsing result waves in databrowser/sweepbrowser
- [x] notebook/rst documentation for store
- [x] Tests for store
- [x] Adapt TextWaveToList for 4D with tests
- [x] Write results wave into NWBv2, verify in tests
- [x] Read back in analysis browser, select the correct ones for the sweepbrowser
- [x] Merge https://github.com/AllenInstitute/IPNWB/pull/31 and update IPNWB
- [x] https://github.com/AllenInstitute/MIES/pull/1240
- [x] PopupMenu for old code does not work. 
- [x] Use Extended popup menu for old code

Close #1222
Close #431

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready for a first test. Needs quite some testing as I have changed quite some stuff. I've went the whole nine yards and export the new results waves into NWBv2, read them back in and also allow browsing them in the databrowser/sweepbrowser.

**Comment by t-b** [comment]
Extended popupmenu is done.

**Comment by timjarsky** [comment]
@t-b I get the following assertion after executing a formula and trying to access it via the popup menu

``` !!! Assertion FAILED !!!
  Message: "Defined sub menu entry is empty"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
PEXT_ButtonProc(...)#L523 [MIES_GuiPopupMenuExt.ipf]
PEXT_VerifyAndSetMenuWave(...)#L553 [MIES_GuiPopupMenuExt.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-01-12T11:13:34-08:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.10 (37840)
  MIES version:
  Release_2.4_20211216-87-gd10bda759
Date and time of last commit: 2022-01-11T22:44:43+01:00
Submodule status: 
160000 f3493461480eaafa97939940693ed693860048a6 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 675eacfee28bd192ce6c28087c594fe59abd7206 0	Packages/unit-testing
  ################################```

**Comment by t-b** [comment]
@timjarsky Thanks. Should be fixed.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
