### PR TITLE
Feature/add scalebars for pa

### PR DESCRIPTION
**Pull request by t-b**
- [x] fix wave read error
- [x] allow multiple PA plots, i.e. one PA plot for a browser
- [ ] place the y-scale bar *exactly* over the y axis

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b v-clamp scale bars looked good. I-clamp bars aren't optimally positioned:

image

**Comment by t-b** [comment]
@timjarsky Looks like my positioning hack is not as good as I hoped. I'll get that properly positioned without hacks.

**Comment by t-b** [comment]
@timjarsky Updated. Regarding the y scale setvariable: When you change between sweeps with different clamp modes, the user currently needs to adapt the y scale so that it is not totally off scale. That is IMHO not very pleasant.

**Comment by timjarsky** [comment]
> @timjarsky Updated. Regarding the y scale setvariable: When you change between sweeps with different clamp modes, the user currently needs to adapt the y scale so that it is not totally off scale. That is IMHO not very pleasant.

@t-b in the DA tab of the DA_ephys panel, we handle a similar issue by having separate controls for I- and V-clamp. We could also manage this, the same way as the x-axes. The concern with the latter approach is the need to constantly update when with each new sweep - my preference might be to only update once per RA cycle or something like that.

**Comment by t-b** [comment]
Resolved conflicts and rebased. Will merge once CI passes.

**Pull request merged**
