### PR TITLE
Allow resaving NWBv1 files into NWBv2 files

### PR DESCRIPTION
**Pull request by t-b**
- [x] Code cleanup
- [x] Proper commits
- [x] Move marked code into IPNWB once #918 and #954 is done
- [x] Collapsed experiment names don't work
- [x] Only load the stored TPs for reexport
- [x] ~~Do we need to load the stored TPs from pxp as well~~ No
- [x] Reuse overwrite checkbox to avoid asking the user
- [x] Add NWB version/PXP to the analyisbrowser list box

Close https://github.com/AllenInstitute/MIES/issues/911

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b analysis browser won't load NWB V1 in this PR (loads in main). I uploaded the NWB file (2021_05_25_160129.nwb) to the FTP. The file was generated from this PR/branch and during acquisition.

**Comment by t-b** [comment]
@timjarsky Thanks. Should be fixed.

**Comment by t-b** [comment]
@timjarsky Ready.

**Comment by timjarsky** [comment]
@t-b Is there a trick to selecting a file in the analysis browser for resaving as NWB? I keep getting:

```
  Please select an experiment to use this feature
```

image

**Comment by t-b** [comment]
@timjarsky Thanks, fixed.

**Comment by timjarsky** [comment]
@t-b would it be possible to have a 'resave all' to NWB option?

**Comment by t-b** [comment]
@timjarsky Sure.

**Comment by t-b** [comment]
@timjarsky Done. I'm now always converting all loaded experiments.

**Comment by t-b** [comment]
@timjarsky This is how the output now looks like:

```
  ####
  Folder: E:\tim-data\nwbv1-loading-analysisbrowser\
  NWbv1: Experiment35-compressed.nwb
  NWbv2 (new): Experiment35-compressed-converted.nwb
  ####
```

**Comment by timjarsky** [comment]
@t-b thanks for printing the file path with slashes instead of colons. Everything looks good. Can you remind me of the differences between an NWB2 file generated from a NWB1 file vs a .pxp?

**Review by timjarsky — DISMISSED** [review]

**Comment by timjarsky** [comment]
@t-b how much work would it be to add a column to show nwb file version to the analysis browser?

**Comment by timjarsky** [comment]
@t-b what happens if the converted file already exists?

**Comment by t-b** [comment]
> @t-b thanks for printing the file path with slashes instead of colons. Everything looks good. Can you remind me of the differences between an NWB2 file generated from a NWB1 file vs a .pxp?

I haven't really examined it, but I don't think there is a practical difference. Still converting from NWBv1 should only be done if the pxp is not available anymore.

> @t-b what happens if the converted file already exists?

I think we append into the NWB file. This is probably not what we want, or? Is it okay to just overwrite the old one?

> @t-b how much work would it be to add a column to show nwb file version to the analysis browser?

An hour or two.

**Comment by timjarsky** [comment]
> > @t-b what happens if the converted file already exists?
> 
> I think we append into the NWB file. This is probably not what we want, or? Is it okay to just overwrite the old one?

Can we let windows handle this the way it normally does; ask the user what to do?

> 
> > @t-b how much work would it be to add a column to show nwb file version to the analysis browser?
> 
> An hour or two.

If you are up for it, let's do it.

**Comment by t-b** [comment]
- [ ] Reuse overwrite checkbox to avoid asking the user
- [ ] Add NWB version/PXP to the analyisbrowser list box

**Comment by t-b** [comment]
@timjarsky I've implemented honoring overwrite checkbox and not touching the files if they already exist and overwrite is off. And also display the NWB type in the analysisbrowser.

**Comment by timjarsky** [comment]
@t-b beautiful!

image

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
