### PR TITLE
Fix enabled/disabled channels in DAEphys panel with JSON configuration

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I get:

```
  !!! Assertion FAILED !!!
  Message: "Could not query the device info wave"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
CONF_AutoLoader(...)#L318 [MIES_Configuration.ipf]
CONF_RestoreWindow(...)#L442 [MIES_Configuration.ipf]
CONF_RestoreDAEphys(...)#L639 [MIES_Configuration.ipf]
CONF_JSONToWindow(...)#L1122 [MIES_Configuration.ipf]
CONF_RestoreControl(...)#L1342 [MIES_Configuration.ipf]
PGC_SetAndActivateControl(...)#L230 [MIES_ProgrammaticGUIControl.ipf]
DAP_ButtonProc_LockDev(...)#L4822 [MIES_DAEphys.ipf]
DAP_LockDevice(...)#L4959 [MIES_DAEphys.ipf]
DAP_AdaptPanelForDeviceSpecifics(...)#L4990 [MIES_DAEphys.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2023-01-11T19:55:06-08:00
  Locked device: [ITC1600_Dev_0]
  Current sweep: [NaN]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: Untitled ()
  Igor Pro version: 9.0.1.2 (39200)
  MIES version:
  Release_2.6_20220606-710-ga503c850d
Date and time of last commit: 2023-01-11T21:42:15+01:00
Submodule status: 
-e46385bee5c53a0daa1eca0c1d6af44d19677c13 Packages/IPNWB
-56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf
-873dee901d747ceedfce01e66c058c8791a3b046 Packages/unit-testing
  ################################
```

**Comment by t-b** [comment]
@timjarsky Thanks. PLease try again.

**Comment by timjarsky** [comment]
Looks good @t-b 

image

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
I've fixed CI. Will merge once CI passes.

**Pull request merged**
