### PR TITLE
SweepFormula: Add findlevel operation

### LINKED ISSUE #281: SweepFormula: Add FindLevel operation
Add `findlevel(data, level [, edge])` with the following parameters:
- data: some wave data
- level: numeric level to search a value passing through
- edge: Type of crossings to search: 0 (default, both increasing and decreasing), 1 (increasing), 2 (decreasing)

@timjarsky @ukos-git Does that make sense?

### PR DESCRIPTION
**Pull request by t-b**
Close #281.

- [x] Change layer assertion to `<=`

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b findlevel with multiple sweeps is working differently than I expected; the level X from the first sweep is being used in the second sweep.

e.g., 
```
data(
[(findlevel(data(
cursors(A,B),
channels(AD1),
sweeps()
),0))
,
(findlevel(data(
cursors(A,B),
channels(AD1),
sweeps()
),0) + 10)],
channels(AD1),
sweeps()
)
```

gives:

image

from:

image

Is that as intended? I expected the spikes from each sweep to be in the formula plot from the zero-crossing forward in time.

**Comment by t-b** [comment]
@timjarsky At the moment `findlevel` is treating its input as 1D wave. Therefore what you expect is probably not yet implemented.

A MWE is

```
findlevel([[10, 20], [11, 21]], 15)
```

as that only returns 1 entry at the moment.

Should it return two?

**Comment by timjarsky** [comment]
https://github.com/AllenInstitute/MIES/pull/339#issuecomment-548572804

@t-b I would expect the same behavior as min, max, or mean. Does that make sense?

**Comment by timjarsky** [comment]
> [#339 (comment)](https://github.com/AllenInstitute/MIES/pull/339#issuecomment-548572804)
> 
> @t-b I would expect the same behavior as min, max, or mean. Does that make sense?

I guess my comment isn't helpful; I just checked and min, max, and mean don't work with the example array above.

**Comment by t-b** [comment]
@timjarsky Jeep, got it.

**Comment by t-b** [comment]
@timjarsky Should be done. I've also introduced a generic FindLevel wrapper which does not need to copy around data if used on a 2D wave. We can use this wrapper also in other places in the future. I'll make an issue to do that.

**Comment by t-b** [comment]
@ukos-git The example from Tim requires us to have different ranges for each sweep. I've hacked something into it right now, but that does not work yet. We need to discuss how we could handle this.

**Comment by ukos-git** [comment]
A union function would be a better and simpler solution.

**Comment by timjarsky** [comment]
@t-b is the assignment still correct? If yes, I'll go ahead and approve.

**Comment by t-b** [comment]
@timjarsky Thanks for checking. The assignment was wrong.

**Comment by timjarsky** [comment]
> 
> Possible solutions:
> 
> * Let `data` return a wave reference wave with the correct x scaling for each extracted sweep
> * Use the union of all sweep ranges and fit the data into it
> 
@t-b @ukos-git  If we have the resources, I propose we only resample when necessary. For example, averaging two waves together will require resampling, but taking the mean of two waves does not. In this way, we can mostly avoid issues that come with resampling (changing the data, ringing, etc.) but the user experience is seamless.

**Comment by t-b** [comment]
@timjarsky I've fixed the layer issue.

**Pull request merged**
