### PR TITLE
Move to github actions

### LINKED ISSUE #1563: Move from bamboo to github actions
- [x] Install runners on ITC/NI hardware machines and the VM (TB)
- [x] Ask Tim for admin access to ITC machine for runner installation (admin powershell)
- [x] Label them correctly (TB)
- [x] Ask central IT to add a new github runner (docker is sufficient, concurrency 5) to their openstack instance
- [x] Try it out
- [x] Copy IP binary folder to something versioned (`r39935`) on all three instances
- [x] ~~Think about how we want to organize our docker images used in CI. Separate repo and push to ghcr.io? Right now we are always building them from scratch which is a bit wasteful.~~
- [x] FTP account for storage of artefacts (TB)
- [x] GH action runners fail with hardware tests (TB)

Add runners with labels, see [here](https://docs.github.com/en/actions/hosting-your-own-runners/using-labels-with-self-hosted-runners):
- [x] self-hosted, Windows, IgorPro, NI
- [x] self-hosted, Windows, Certificate
- [x] self-hosted, Windows, IgorPro, ITC
- [x] self-hosted, Windows, IgorPro
- [x] self-hosted, Linux, Docker

Jobs:
- [x] A: Build CI installer (Windows)
- [x] B: Build installer and release package and sign it (Windows, Certificate)
- [x] C: Linting (Linux, Docker)
- [x] CC: Build documentation (Linux, Docker)
- [x] D: Compilation test installer with hardware XOPs (IgorPro)
- [x] E: Compilation test installer without hardware XOPs (IgorPro)
- [x] F: Compilation test repository (IgorPro)
- [x] G: Testing Basics.pxp (IgorPro)
- [x] H: Testing PAPlot.pxp (IgorPro)
- [x] I: Hardware Testing: HardwareBasics.pxp (IgorPro, ITC)
- [x] J: Hardware Testing: HardwareBasics-NI.pxp (IgorPro, NI)
- [x] K: Hardware Testing: HardwareAnalysisFunctions.pxp (IgorPro, ITC)
- [x] L: Hardware Testing: HardwareAnalysisFunctions-NI.pxp (IgorPro, NI)
- [x] M: Validate NWBv2 files (Linux, Docker)
- [x] (Validate JUNIT XML files is being dropped)
- [x] O: Deploy documentation, installer and release package, main branch only (Linux, Docker)
- [x] P: Deploy installer and release package, latest release branch only (Linux, Docker)
- [x] Q: FTP Artifact upload

Job dependencies (draft):
- O/P needs M
- M needs I/J/K/L
- I/J/K/L needs D/E/F
- G/H needs D/E/F
- D/E/F needs A/B/C

Misc:
- Only official actions from github, see https://github.com/actions, are allowed to be used!
- Archive all artifacts to FTP, by branch name and commit
- It would be nice if we could have executing tests in IP as reusable workflow
- The jobs can be matrixed if useful and sensible
- No need to add github actions to the release/2.6 branch. Only prepare for next release.

Artefacts:
- A: CI installer
- B: Installer and release package
- CC: Documentation (compressed zip file)
- D-L: JUNIT, Igor Pro logfile, Cobertura(main branch only)
- I/K: NWBv2 files 

Current secrets:
- [x] EV certificate PIN
- [x] ~~SSH private key for gh-pages deploy and tagging latest main~~
- [x] ~~github API token for start/finished messages by @mies-bot~~
- [x] ~~release artifact upload~~
- [x] FTP credentials

IP versions:
We should also keep old IP versions on the CI machine. The CI setup should then reference the IP version/revision in the CI setup. This would allow us to run old versions from a year/two ago again on the CI machines.

Once this works:
- [x] Turn off bamboo plans (TB)
- [x] Stop bamboo agents on machines (TB)
- [x] Remove `.credentials` folders
- [x] Remove ssh deploy key from MIES repo
- [x] Remove API token for mies-bot user
- [x] Remove bamboo in code
```
git grep -iI bamboo ':/**/*.ipf'
../UTF_HardwareHelperFunctions.ipf:  expensive = GetEnvironmentVariableAsBoolean("BAMBOO_EXPENSIVE_CHECKS")
../UTF_HelperFunctions.ipf:  instru = GetEnvironmentVariableAsBoolean("BAMBOO_INSTRUMENT_TESTS")
../UTF_HelperFunctions.ipf:  return !cmpstr(GetEnvironmentVariable("bamboo_repository_git_branch"), "main")
../UTF_HelperFunctions.ipf:  return !IsEmpty(GetEnvironmentVariable("bamboo_repository_git_branch"))
```
- [x] Update CI documentation 
- [x] Turn off linux mint box (TB)
- [x] Tell Brian we don't need bamboo anymore (TB)

### PR DESCRIPTION
**Pull request by t-b**
Close #1563.

### CODE REVIEW

**Comment by t-b** [comment]
I've just merged #1695 which changed some of the test run scripts. We now collect the diagnostics folder contents and logfiles as bamboo artefacts. GH actions should do the same.

File patterns (from the repo root)
```
*Diagnostics/*.*
*.jsonl
```

Those are present for the IP test runs. The Diagnostics folder can be empty.

**Comment by Garados007** [comment]
Github has an incident regarding Github actions. Lets see after it's resolved...

https://www.githubstatus.com/

**Comment by Garados007** [comment]
The tests do not succeed because Address space layout randomization (ASLR) is enabled or unset. You can checkout the log file for [`test-itc-assets`](https://github.com/AllenInstitute/MIES/suites/12915641174/artifacts/697508412) in `Packages/tests/HardwareBasic/HardwareBasic_2023-05-15_16-10-29.log`:

```
  Please choose a device assignment for the data browser
  Start of test "MIES with HardwareBasic"
  Entering test suite "UTF_VeryBasicHardwareTests.ipf"
  Entering test case "VeryBasicHardwareTesting#CheckInstallation"
  Checking system properties:
  Igor 64bit: 9.02, 39935
  Windows 10: True
  ASLR: True (Very Bad)
```

After checking the code I have seen that the error counter is incremented after that line and the test fail.

**Comment by t-b** [comment]
@Garados007 Nice find. We need an exception for IP as the ITC hardware drivers don't work with ASLR. And due to the new location of the IP binary, we old exceptions did not catch that. I've adapted the exception script and also added an exception manual on both hardware CI machines. As I now only use the executable name this needs to be done only once. I've also pushed a commit.

**Comment by Garados007** [comment]
The Igor binary returns with a status code 127 in ITC Tests / HardwareBasics.pxp. There is no error from igortest and I didn't found something in the jsonl error logs but I don't know what to look for.

When looking in the igortest log file found many occurrences of
```
  BUG: Unexpected magic value in IgorStringClass::v().
  Stack Trace:
  	Stack trace is not available
```
and many `Bug: ` reports which seems unusual. Maybe this has something to do with error 127 or not. I don't know.

**Comment by t-b** [comment]
@Garados007 I've just merged #1703 which should make ITC crashes less frequently in CI. Please rebase.

**Comment by t-b** [comment]
I can't approve as I have added commits as well so I just merge.

**Pull request merged**
