### PR TITLE
Fix ddaq display issues

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add regression test with more stimsets to catch that as well
- [x] Devise a method to fixup buggy region data

@MichaelHuth Any ideas for the fixing up buggy region data? This seems to be quite complex in the general case.

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth I think I have something for fixing up buggy region data:
- Only the very first region is affected as we reset the wave reference `baseRegions` in `if(yoked...` on the first iteration
- buggy data is sorted but not compressed
- all the regions from the first region are duplicated in a buggy entry but offsetted by the offset of the second region

**Comment by timjarsky** [comment]
@t-b works nicely

**Comment by MichaelHuth** [comment]
@t-b I think I got a rough idea what the problem was, but we should probably phone about that briefly.

**Comment by t-b** [comment]
@MichaelHuth Implemented fixup method looks good. Please have a look at it as well.

**Comment by t-b** [comment]
@timjarsky We've added a fixup for buggy entries.

**Comment by timjarsky** [comment]
@t-b tested on a file with corrupted LN data and it worked. Thank you for the fixup.

**Comment by MichaelHuth** [comment]
> @MichaelHuth Implemented fixup method looks good. Please have a look at it as well.

Looks good. Just a minor comment, I think the comment description with "more than three" should be "more than two".

**Comment by t-b** [comment]
@MichaelHuth Thanks for careful reading fixed.

**Pull request merged**
