### PR TITLE
Adaptations for Tests in CI with Instrumentation

### PR DESCRIPTION
**Pull request by MichaelHuth**
A few adaptions and workarounds that MIES should run with Instrumented tests also in the CI.

This can be tested with this branch.

This PR is NOT intended to be merged later, it is only a test bubble for application of the new IUTF features.

- [x] Make MIES work again with latest IP9
- [x] Rebase and fix merge conflicts
- [x] Get IP9 license on CI machines
- [x] Investigate if we can make it faster by dropping some more boring functions
- [x] Cleanup commits
- [x] Control instrumentation by environment variable as alternative to `runWithOpts` param, off by default
- [x] Read that environment variable to disable failing checks
- [x] Allow to run instrumentation only on selected MIES files
- [x] Run instrumentation only when doing CI for main
- [x] Switch bamboo jobs from IP8 to IP9
- [ ] Switch required check jobs in gitub config

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth You forgot to update the UTF submodule. It currently does not compile.

**Comment by t-b** [comment]
I also raised from job timeouts.

**Comment by MichaelHuth** [comment]
@t-b What is the issue with the NI tests?

**Comment by t-b** [comment]
Can we have a 32bit XOP for TUF as well/

**Comment by t-b** [comment]
> @t-b What is the issue with the NI tests?

The NIDAQ mx XOP was missing for IP9. I've fixed and will restart CI.

**Comment by t-b** [comment]
ITC tests passed.
"Test from repo" had a too small timeout. I'll rerun that one.
NI is still running. I also had some crashes with NI tests, I've reported them.

**Comment by t-b** [comment]
The TUF XOP I'm building here is 200k smaller then the one which is checked into the MIES repo.

**Comment by MichaelHuth** [comment]
@t-b I updated to the unit-testing framework with a new version that features exclusion of functions. I also added some in UTF_Main.ipf for RunAllTests as example. This should speed up the instrumented tests a bit.

**Comment by t-b** [comment]
@MichaelHuth I'll do some CI tweaking for this test PR.

**Comment by t-b** [comment]
@MichaelHuth I've setup an special bamboo CI plan for this PR. The reason the standard plan does not work in "Test from repo" is that it executes all tests which don't require hardware. But as it instruments all of them the second always failed.

Now it reinstalls MIES before running instrumented tests.

**Comment by t-b** [comment]
- [ ] Add GetMIESPathAsString to tracing exclusion list

**Comment by t-b** [comment]
The ITC hardware tests run with instrumentation for 82 minutes (IP9) and without 51 minutes (IP8).

**Comment by MichaelHuth** [comment]
> The ITC hardware tests run with instrumentation for 82 minutes (IP9) and without 51 minutes (IP8).

Ok, so I change that in the IUTF documentation to ~60% slowdown.

**Comment by t-b** [comment]
> > The ITC hardware tests run with instrumentation for 82 minutes (IP9) and without 51 minutes (IP8).
> 
> Ok, so I change that in the IUTF documentation to ~60% slowdown.

Jeep, please do that. We might be able to bring that down by further excluding functions, but that is of course then not the whole truth.

**Comment by t-b** [comment]
@MichaelHuth Hold on. This includes the time it takes to generate the RTF output. And that is 15 minutes (!!) so we have 51/67 which means a 30% slowdown.

**Comment by MichaelHuth** [comment]
ok

**Comment by MichaelHuth** [comment]
Looks good to me.

Do we have an issue for the PS_ tests being execution speed dependent?
Since these are dependent on an actual sample clock, I guess only faster code or a faster CI machine helps.

**Comment by t-b** [comment]
> Do we have an issue for the PS_ tests being execution speed dependent?

Jeep, https://github.com/AllenInstitute/MIES/issues/998.

Thanks for the review.

**Review by t-b — APPROVED** [review]

**Review by t-b — APPROVED** [review]

**Pull request merged**
