### PR TITLE
Work load class tracking in ASYNC frame work

### PR DESCRIPTION
**Pull request by MichaelHuth**
- ASYNC_PrepareDF now setups a work load class name as well
- ASYNC_Execute registers now work loads by their class name
- ASYNC_ThreadReadOut tracks now work loads by their class
- ASYNC_IsWorkloadClassDone allows to check if a specific class of work loads
  finished. It also allows to remove the work load class when finished.

close https://github.com/AllenInstitute/MIES/issues/101

### CODE REVIEW

**Comment by t-b** [comment]
FYI the CI tests are still run on IP8.

The test result is:

```
UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

UTF_AsynFrameworkTest.ipf:97:59: error: expected comma

```

**Comment by t-b** [comment]
@MichaelHuth 

Documentation build:
```
Errors building the documentation
Doxygen says:
/home/ci/Packages/MIES/MIES_TestPulse.ipf:866: warning: The following parameters of TP_SendToAnalysis(tpanalysisinput *tpInput, string panelTitle) are not documented:
  parameter 'panelTitle'
/home/ci/Packages/MIES/MIES_TestPulse.ipf:886: warning: The following parameters of TP_WaitForAsyncTPToFinishAndRemove(string panelTitle, variable timeout) are not documented:
  parameter 'panelTitle'
```

Review:
- Please make `panelTitle` the first parameter in `TP_SendToAnalysis` this is our unwritten convention.

```
+/// @param workloadClass string naming a work load class for work load attribution like "TestPulse"
+///        The string must be compatible with dimension label restrictions.
+///
```

... The string must follow strict object naming rules.

And then please also add an ASSERT using IsValidObjectName

- dbc83f35d80dd5c9826810c4db25b20d0a16007e looks like an oversight
- `TPWaitForAsync_IGNORE` can now be replaced with something using `TP_WaitForAsyncTPToFinishAndRemove` or?
- `TP_WaitForAsyncTPToFinishAndRemove` is there a reason this is TP specific? I can imagine needing the exact same logic for other cases as well. I think this should live better in `ASYNC_XXX`.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@MichaelHuth Good to go from my POV.
@timjarsky Do you want to have a look as well?

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
