### PR TITLE
Format some code files

### PR DESCRIPTION
**Pull request by Garados007**
Add some commas for some operations

### CODE REVIEW

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@Garados007 CI is right in https://github.com/AllenInstitute/MIES/actions/runs/6201200560/job/16838351141?pr=1897.

```igorpro
	CreateAliasShortcut/Z/P=$symbPath "file.txt", "alias.txt"
```

does not compile

**Comment by Garados007** [comment]
> @Garados007 CI is right in https://github.com/AllenInstitute/MIES/actions/runs/6201200560/job/16838351141?pr=1897.
> 
> ```igor
> 	CreateAliasShortcut/Z/P=$symbPath "file.txt", "alias.txt"
> ```
> 
> does not compile

You are right. I found out the correct syntax would be (according to documentation):

```igorpro
CreateAliasShortcut/Z/P=$symbPath "file.txt" as "alias.txt"
```

**Comment by t-b** [comment]
@Garados007 Please assign me once this is ready. Needs also rebasing.

**Review by t-b — APPROVED** [review]
LGTM.

**Pull request merged**
