### PR TITLE
Enhance QC reporting for IVSCC functions

### LINKED ISSUE #893: Return qcResult variable from IVS VC QC functions
IVS_runBaselineCheckQC, IVS_runInitAccessResisQC, and IVS_RunGigOhmSealQC all contain a variable called qcResult, or they call a background function that contains the qcResult variable, which indicates whether or not the qc parameter was passed. If  the qc parameter is passed then the qcResult will contain the value of that parameter or it will be 0 if the qc parameter failed.

Example:
IVS_runBaselineCheckQC calls the background functions IVS_FinishBaselineQCCheck which contains the variable 'qcResult'. This function will get the absolute value of the baseline average and check if it is within the acceptable range:
 - if (abs(baselineAverage) < 100.0)
and if the baselineAverage value is within range then it will run the sweep and assign the value of the baselineAverage to the qcResult variable, otherwise the qcResult will be 0. Right now, qcResult is being printed to the Igor terminal but is not being returned from the function.

We would like to have the qcResult returned from these functions so that our workflow sequencing engine can access the qcResult and use it to determine how or if the rig operator can proceed with the experiment based on whether or not the qc parameter was passed. 

Please let me know if you have any questions or need any additional information for this request

### PR DESCRIPTION
**Pull request by t-b**
@ru57y34nn @timjarsky This is a quick work-in-progress PR which shows how queryable QC reporting could look like.

Ohh and a new ZeroMQ XOP with lots of fixes and enhancements is also included. Among other things there is now some more info on function aborts if available.

All QC decisions are made in background tasks so there is no direct way to query what is decided there. I therefore introduced a wave IVSCCQCResults, fetchable via GetIVSCCQCResults, which holds all QC result entries. Each entry holds the background function name, qc result and description. The entries are always appended. So you need to call `IVS_ClearQCResults` to clear that wave.

My idea how that this would work:
- WSE calls function which starts background task
- WSE fetches IVSCCQCResults every x seconds and looks into the last written row (`Index -1` from wave note). There it finds what is the current state is.
- WSE clears this wave if required via IVS_ClearQCResults

Does that go in the right direction?

As I can't test this here, this is only compile tested.

Close #893.

### CODE REVIEW

**Comment by t-b** [comment]
@ru57y34nn @aleonlein Another approach compared to what I outlined above would not require the WSE polling a wave.

We could introduce messaging from MIES into the WSE using zmq. This could e.g. involve PUB-SUB sockets [1] where MIES would be the publisher and WSE the subscriber. The WSE could then subscribe to something like a QC-state change and get a message with the new value in JSON format everytime the QC value changes.

[1]: https://zguide.zeromq.org/docs/chapter5/#Pub-Sub-Tracing-Espresso-Pattern

**Comment by aleonlein** [comment]
@t-b I already have a PUB-SUB socket (I call it the Igor - router node) which continuously polls igor for responses. I like the latter approach where I can subscribe to the QC state change. Either way, whatever is implemented will work for me. 

Btw: All the updates from your first message look great!

**Comment by aleonlein** [comment]
@t-b @timjarsky  Full disclosure: It wasn't necessarily clear from the comments if this build was ready for test however, it looked ready given the checks completed in the CI process. That said, after downloading the Installer build artifact, I running the MIES binary but am getting an error when I try to run installation. I am using an admin account


image

**Comment by t-b** [comment]
@aleonlein Thanks for testing. Yes the installer should work, I'll investigate.

**Comment by t-b** [comment]
@aleonlein @timjarsky Ready for the next try. 

(No need for CI to pass by the way, it will probably not pass due to our beloved bamboo configuration being too advanced for the old release branch.)

We now publish IVSCC QC results via ZeroMQ publisher sockets. Documentation is at the top of MIES_IVSCC.ipf. I've added a very basic test to check that publishing works here as well. See also https://github.com/AllenInstitute/ZeroMQ-XOP/#direction-igor-pro---world for some basics about how the pub/sub sockets are implemented and should be used.

I can of course tweak the qc messages, I've just come up with something which sounded useful.

If something does not work, I'm happy to help fixing it. As usual a MWE, python is fine, for issues helps a lot in debugging.

**Comment by t-b** [comment]
@aleonlein The installer issue should also be gone now. The installer must only run once as admin so that the new vcredist packages can be installed automatically.

**Comment by aleonlein** [comment]
@t-b I will try it out now

**Comment by aleonlein** [comment]
@t-b That worked! 

I am out of the office until next week. I will be ready to test when I get back but it shouldn't take me long. Thank you for all your hard work on this.

**Comment by aleonlein** [comment]
@t-b I wrote a small subscriber in Python to grab the 'ivscc' message published by Igor on port 5770. I did not receive a response from Igor so I tried to filter on the 'heartbeat' and still did not receive any messages. I then tried to receive the full message and nothing. 

I wrote a publisher to connect to my subscriber on the same port to test my subscriber. My subscriber can digest messages fine.  

Then I used a socket program to determine if the server was active. I only see the port for the ROUTER/DEALER active on the network. Shouldn't I see both PUB/SUB and ROUTER/DEALER ports? I see some other ports but they don't look to be in the range you have previously used as they are in the upper 50000's.

**Comment by t-b** [comment]
@aleonlein Thats weird. Can you post your python script so that I can try it here? I just verified and at least my in IP tests with pub/sub work.

Can you also verify that you have the correct MIES version? You can see that in MIES Panels->About MIES. It should be `Version: 2.1_20200723-77-g36fd96a2c`.

**Comment by aleonlein** [comment]
@t-b THis must be me. I have the incorrect version of MIES (MIES-Release_2.1_20200723-76-gc22572d1).

**Comment by aleonlein** [comment]
Could you link me to the build? I know you said something about it being broken in Bamboo but I do not see where to gain access to this version.

The version I am using has the FFI_GetAvailableMessageFilters function and has the port information in the MIES_Constants.ipf. It must be very similar to the latest version (based on the changes to the source code in the current commit)?

Here is the code I am using

```
import zmq
import json

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.RCVTIMEO = 1000
host = 'localhost'
port = 5770
socket.connect(f"tcp://{host}:{port}")

# # import pdb; pdb.set_trace()
# topicfilter = "heartbeat"

socket.setsockopt_string(zmq.SUBSCRIBE, '')

count = 0
while True:
    try:
        print(f"checking........{count}")
        count += 1
        message = socket.recv_multipart()
#         message = socket.recv()
        print(message)
    except zmq.error.Again:
        pass
```

**Comment by t-b** [comment]
@aleonlein http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN385-RP-3/artifact has the installer. I'm currently trying to understand why your script does not work.

**Comment by aleonlein** [comment]
@t-b Thank you for posting the link. When I run MIES, I see the subscriber port in my windows PID list so I will keep working on debugging the subscriber I wrote. I know these context objects can be finicky.

**Comment by t-b** [comment]
@aleonlein The error lies in the new ZeroMQ XOP. I'll post a new version today.

**Comment by aleonlein** [comment]
@t-b So glad you found the error! Thanks!

**Comment by t-b** [comment]
@aleonlein I've pushed an update. The fault was entirely location in the ZeroMQ XOP. I now get immediately heartbeat messages after starting IP with python. I've used the below script which also outputs monitoring events for debugging. 

```python
import zmq
import json
import time
import sys
import threading

from zmq.utils.monitor import recv_monitor_message

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.RCVTIMEO = 0
host = '127.0.0.1'
port = 5770

EVENT_MAP = {}
print("Event names:")
for name in dir(zmq):
    if name.startswith('EVENT_'):
        value = getattr(zmq, name)
        print("%21s : %4i" % (name, value))
        EVENT_MAP[value] = name


def event_monitor(monitor):
    while monitor.poll():
        evt = recv_monitor_message(monitor)
        evt.update({'description': EVENT_MAP[evt['event']]})
        print("Event: {}".format(evt))
        if evt['event'] == zmq.EVENT_MONITOR_STOPPED:
            break
    monitor.close()
    print()
    print("event monitor thread done!")

with socket.connect(f"tcp://{host}:{port}"):

    monitor = socket.get_monitor_socket()

    t = threading.Thread(target=event_monitor, args=(monitor,))
    t.start()

    socket.subscribe("")

    count = 0
    while count < 10:
        try:
            print(f"checking........{count}")
            count += 1
            message = socket.recv_multipart()
            # message = socket.recv()
            print(f"message: {message}")
        except zmq.error.Again as e:
            print(e)
            time.sleep(1)

    socket.disable_monitor()
```

**Comment by t-b** [comment]
@aleonlein And you need to jump to the next active build in bamboo. The github CI status has "Installer and release packages" where Build #4 is the latest.

**Comment by aleonlein** [comment]
@t-b Thanks! Last time I didn't have access to this build (the Installer and release packages was greyed out) but it looks like I have access now. I will get this tested on Monday. Have a great weekend

**Comment by aleonlein** [comment]
@t-b This looks good. I was able to thread the SUB socket into my app. I see the heartbeat every 5 seconds and can get QC results. Thanks for your work on this.

**Comment by t-b** [comment]
@aleonlein Could you approve the PR once it works for you? I've taken your last statement as a "I can now start working with it" and not as "Everything is working and its done". Thanks.

**Review by aleonlein — APPROVED** [review]
Everything is working and I consider this release done.

**Comment by t-b** [comment]
@aleonlein Thanks for the quick reply.

@timjarsky Anything you need to test before I rebase and merge?

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
