### PR TITLE
Fix ni tp md caching

### PR DESCRIPTION
**Pull request by t-b**
My TP caching did not work with NI hardware.
I've fixed that now and also added the missing test which should have been part of the original PR.

### CODE REVIEW

**Comment by MichaelHuth** [comment]
I think that beside the test that the wave arrives in the cache, there should be a second test that starts the TP twice. This would test if the TP works when retrieved from the cache.

**Comment by t-b** [comment]
@MichaelHuth 

> I think that beside the test that the wave arrives in the cache, there should be a second test that starts the TP a second time. This would test if the TP works when retrieved from the cache.

The test runs the same sweep three times so with the given large inter trial interval, we run the testpulse multiple times.
And that is checked in the REENTRY function as the HITS column of the cache stats wave has an entry larger or equal 1. And that means that we already fetched the wave once from the cache.

**Comment by t-b** [comment]
@timjarsky I've restarted the tests. The reason for the failure was that the discs were running full on the windows 7 box. I'm now making space again.

**Comment by t-b** [comment]
Next try without typo in GetNIDAQChannelWave().

**Comment by t-b** [comment]
@timjarsky I've rebooted the windows 10 CI box. Now everything passes :)

**Pull request merged**
