### PR TITLE
Cache HardwareDataWave in Testpulse mode

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b is is noticeably quicker to transition between the end of a sweep in TP during ITI.

```
Total time: 70.1249, Time in Function code: 24.392 (34.8%)
Top function percentages:
Function MIES_Utilities.ipf createDFWithAllParents: 12%
Function MIES_Async.ipf ASYNC_putDF: 9%
Function MIES_DAC-Hardware.ipf HW_NI_ReadDigital: 8%
Function MIES_Oscilloscope.ipf SCOPE_ITC_UpdateOscilloscope: 6%
Function MIES_Oscilloscope.ipf SCOPE_UpdateOscilloscopeData: 4%
Function MIES_Cache.ipf CA_DistDAQCreateCacheKey: 4%
Function MIES_MiesUtilities.ipf ParseDeviceString: 4%
Function MIES_Async.ipf ASYNC_AddParam: 3%
Function MIES_MiesUtilities.ipf KillOrMoveToTrashPath: 3%
Function MIES_DAC-Hardware.ipf HW_NI_WriteAnalogSingleAndSlow: 3%
Function MIES_Async.ipf ASYNC_PrepareDF: 3%
Function MIES_Utilities.ipf DataFolderExistsDFR: 2%
Function MIES_Utilities.ipf ExtractStringFromPair: 2%
Function MIES_TestPulse.ipf TP_ROAnalysis: 2%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 2%
Function MIES_AmplifierInteraction.ipf AI_SelectMultiClamp: 2%
Function MIES_ThreadsafeUtilities.ipf TS_GetNewestFromThreadQueue: 1%
Function MIES_WaveDataFolderGetters.ipf GetDevicePathAsString: 1%
Function MIES_DataConfiguratorITC.ipf DC_PlaceDataInHardwareDataWave: 1%
Function MIES_MiesUtilities.ipf GetHardwareType: 1%
Function MIES_WaveDataFolderGetters.ipf GetTPResultAsyncBuffer: 1%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 1%
Function MIES_TestPulse.ipf TP_AnalyzeTP: 1%
Function MIES_TestPulse.ipf TP_RecordTP: 1%
Function MIES_Async.ipf ASYNC_Execute: 1%
Function MIES_Utilities.ipf IsEmpty: 1%
Function MIES_WaveDataFolderGetters.ipf GetChannelClampMode: 1%
Function MIES_AnalysisFunctionHelpers.ipf AFH_GetAnalysisFunctions: 1%
```

**Comment by timjarsky** [comment]
@t-b how can a string declaration account for 10% of the total time in function?

**Comment by t-b** [comment]
@timjarsky The line numbers are propbably off by one, the culprit here is

```
DFREF dfr = $dataFolder
```

**Comment by t-b** [comment]
@timjarsky Ready for action.

**Pull request merged**
