### PR TITLE
Add epoch information for unassociated DA channels + display in DB

### PR DESCRIPTION
**Pull request by MichaelHuth**
Checked: 
- [x] EP_CollectEpochInfo: works on basis of DA channels and already collects unassoc DA
- [x] EP_FetchEpochs: works on all DA channels
- [x] NWB_AppendSweepLowLevel: Saves already unassoc. DA channel epoch info L1232 and L1243
- [x] TestNwbExportv2: Tests already unassoc. DA channels as well L528 ff.

close https://github.com/AllenInstitute/MIES/issues/1765

### CODE REVIEW

**Comment by t-b** [comment]
- [ ] Write test for SF `epochs`/`data`

**Comment by t-b** [comment]
I'm doing a review now so that you can incorporate the feedback when writing the tests:
de85bb0f (EP: EP_CollectEpochInfo remove headstage variable as it was unused, 2023-06-12)

Nice find.

c5bfdbdf (BSP: BSP_AddTracesForEpochs add support for unassoc DA channel epochs, 2023-06-12)

That's is a hodge-podge of changes.
The change from GetLastSetting to EP_FetchEpochs is a good one. But this should be it's one commit, and also handle the case where EP_FetchEpochs returns $"" and also keep the "present since" comment. Doing that as an upfront change can be motivated in the commit message with "In a future commit we want to ...".
I'm fine with introducing `DB_AXIS_PART_EPOCHS` but in it's own commit upfront and also replace all occurences.

`// epoch info for associated DA channels` this comment is now wrong.

bf7e0c4f (BSP: BSP_AddTracesForEpochs, put trace creation in a loop, 2023-06-12)
84988fc1 (BSP: BSP_AddTracesForEpochs correct loop vars j, k -> i, j, 2023-06-12)

Both are good.

**Comment by t-b** [comment]
Very nice! Also the test is succinct and complete!

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
@MichaelHuth Please rebase and fix the conflict. I'll merge once CI passes.

**Review by t-b — APPROVED** [review]

**Pull request merged**
