### PR TITLE
Async NWB writing

### PR DESCRIPTION
**Pull request by t-b**
- [x] Check if the code works
- [x] Add documentation and tests for new ASYNC functionality
- [x] Code cleanup
- [x] Add documentation how NWB writing works in the code
- [x] find a proper solution for WaveModCountWrapper issue in preemptive threads
- [x] Wait for #942, #940 being merged
- [x] ~~Decide if we should store stimsets/tpstorage as well. Order is Sweeps, LBN/userComment, stimset, tpstorage~~
- [x] Write all stimsets in NWB_PrepareExport
- [x] Check if we need to clear the preemptive threads datafolder hierarchy on each invocation

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready for testing.

**Comment by t-b** [comment]
@timjarsky How did the testing go?

**Comment by timjarsky** [comment]
@t-b testing went well; I didn't find any issues and noticed a speed improvement.

**Comment by t-b** [comment]
@timjarsky Ready!

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
