### PR TITLE
Add support for Sutter DAC

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add new sutter device in DAEphys panel and internal data folder structure
- [x] communicate with Sutter support about open questions from the provided Short-Documentation
  - [x] how does the acquisition setup has to be with multiple IPA devices attached?
  - [x] format of gain factor wave?
  - [x] supported sample rates for input/output?
  - [x] Get missing information regarding channel specification ambiguity
  - [x] Got an updated XOP
  - [x] Reported an issue with demo code about incorrect effective sample rates when acquiring, got an updated XOP
- [x] Add setup of waves in DC_DataConfigurator
  - [x] support for different sample rates depending on channel type
    - [x] extend minimum sample interval getter
    - [x] adapt creation of DA / AD / TTL waves
    - [x] extend TP setup
    - [x] revise creation of helper waves for scaledData and TPOsci
    - [x] Add entries for different sample rates to LNB
- [x] Add sutter hardware acquistion in DAC_Hardware
  - [x] Add zeroDAC feature
- [x] Add headstage and clampmode information in config wave
- [x] DQM_FifoMonitor: Revise fifoPosition handling for different DA / AD positions
- [x] SCOPE_UpdateOscilloscopeData: Update only AD / TTL channels, use new helper waves
  - [x] Add chunked TP handling for Sutter
  - [x] Support PowerSpectrum also with TP during DAQ
- [x] Sweep Data storage needs new format with independent sweep waves (no 2D wave)
  - [x] Change to WaveRef wave -> issue with LoadData not supporting WaveRef waves -> change to text wave with relative paths
  - [x] Adapt SplitSweepsIfReq to support new and old format and automatically apply upconversion
  - [x] AnalysisBrowser: Make sure loading from old format sweeps and new format sweeps works
  - [x] AnalysisFunctions: 
    - [x] Rename structure elements to reflect changes
    - [x] Check functions to use correct input data from either DA / AD ...
  - [x] NWB Export: Adapt to support old and new sweep format
 - [x] Disable Hardware DA/AD channel popupmenus on DAP locking (reenable on unlcoking)
 - [x] profile acquisition start time and optimize if possible

- [x] Tests

- Add support for controlling Sutter Headstage Amplifier (in separate PR)

requires #2079

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b that's enough to merit MIES support but I think asking them to extend to 8 is still worthwhile.

**Comment by t-b** [comment]
Passing tests ✨

**Comment by t-b** [comment]
Note to self: The CI issues with some of the analysis function tests [1], [2] are due to:

`IUTF background monitor has reached the timeout for reentry`

which looks like an ASSER/Abort kicked in.

[1]: https://github.com/AllenInstitute/MIES/actions/runs/7051510355/job/19195416984?pr=1667
[2]: https://github.com/AllenInstitute/MIES/actions/runs/7051510355/job/19195416291?pr=1667

**Comment by t-b** [comment]
@MichaelHuth The test-ni-assets from https://github.com/AllenInstitute/MIES/actions/runs/7037089691?pr=1667 have a failing NI test which says:

```
  Entering test case "PatchSeqTestDAScaleSub#PS_DS_Sub2:NI"
  TEST OVERRIDE ACTIVE
  !!! Threadsafe assertion FAILED !!!
  Message: "Sweep and config waves are not compatible"
  BUG_TS: Encountered pending RTE: 2, DimDelta;expected wave name
  BUG_TS: Should never be called during automated testing.
  !!! Assertion FAILED !!!
  Message: "Unexpected wave x unit"
```

is that something you fixed between yesterday and today? Or maybe this is flaky due to the duplicated wave note issue still present?

**Comment by MichaelHuth** [comment]
This is actually something that I am still investigating, so the diagnostic is that
IsValidSweepAndConfig check fails at the start of SplitSweepIntoComponents in that flaky HW AnalysisFunction fail.
The following bugs are some fallout.

SplitSweepIntoComponents gets the scaledDataWave in that moment as input. I can not reproduce that locally here, I already tried like slowing down the DQM_FifoMonitor calls artificially...
There seems to be a situation where scaledDataWave is borked up.

**Comment by MichaelHuth** [comment]
rebased against #1953

**Comment by MichaelHuth** [comment]
Tests with HW AnalysisFunctions, default sample rate 12.5 kHz, HS0, disabled sample rate check in DAP:
PSQ_Chirp: PS_CR14 fails
PSQ_Ramp: PS_RA7 fails
PSQ_DAScale_Sub: PS_DS_Sub10 fails
PSQ_DAScale_Supra: works
PSQ_SealEvaluation: PS_SE9 fails
PSQ_SquarePulse: PS_SP8 fails
PSQ_RheoBase: most tests fail, looks like some precision issue from lower sample rate?!?
PSQ_PipetteInBath: PS_PB7 fails
PSQ_TrueRestingMembranePotential: PS_VM8 fails
PSQ_AccessResistanceSmoke: PS_AR8 fails

**Comment by t-b** [comment]
IIRC we wanted to do the task item

>  Add support for controlling Sutter Headstage Amplifier

in a new PR or?

**Comment by t-b** [comment]
The "check each commit" CI job should be fixed. Please rebase.

**Comment by t-b** [comment]
@MichaelHuth I would like to start reviewing this PR. But there are merge conflicts. Do you want me to resolve them or you want to resolve them yourself?

**Comment by MichaelHuth** [comment]
@t-b rebased

**Comment by t-b** [comment]
Review:

4ed20970 (Sutter: Add API.zip and preliminary PDF documentation from email, 2023-01-20)

- [ ] Please move these to Packages/Sutter.

72c423a3 (Add inital Sutter XOP (2.45) for hardware from Sutter Instruments, 2023-02-20)
faf02be5 (Update SutterXOP version 2.54 (4 Oct 2023), 2023-10-05)
73b0b182 (Update SutterXOP to version 2.55 (28 Oct 2023), 2023-11-22)

Good!

bde2e54d (Packages/Sutter: Add example procedure files as zip archive, 2023-08-30)

Nice!

17317203 (Constants: Add constants for sutter hardware, 2023-12-06)

- [ ] There is still a todo left. Now or issue?

38bcae1f (WaveGetters: Add / modify getters for Sutter, 2023-12-05)

```
@@ -5852,14 +5879,14 @@ Function/S GetNWBFolderAS()
 Function/WAVE GetDeviceMapping()
...
-        Redimension/N=(HARDWARE_MAX_DEVICES, -1, 2) wv
+        Redimension/N=(HARDWARE_MAX_DEVICES, 3, -1) wv
```

- [ ] It probably does not matter in this case but the wave upgrade procedure is now
broken for the `v1->v2` case.
In 8c6bc992 (Device Map: Drop internal device name, 2018-11-09) we went from 3
layers to two layers, but you are now keeping the three layers instead of going to 2.
- [ ] GetSUDeviceInfo: The list of rows should use a proper markdown list. See
  e.g. GetDeviceMapping() we also tend to have a newline after `@brief`
- [ ] Same for GetSUDeviceInput/GetSUDeviceOutput/GetSUDeviceInputGains
- [ ] GetSutterDACTTLSampleInterval/GetSutterADCSampleInterval: Missing
  function documentation about the unit of the returned sample interval.

a5ea90e5 (GlobalVars: Add Sutter device list and globals for acquisition status, 2023-12-05)

- [ ] GetStopCollectionPoint: `next power of 2`, This is only semi-correct,
  please just refer to DC_CalculateDAQDataWaveLength.

12a4e16e (DAC: Add hardware access functions for sutter, 2023-12-06)

Good.

- [ ] Please use lower case for doxygen commands like `@todo`, I've opened
https://github.com/AllenInstitute/MIES/pull/2002 to prevent that in the future.

8cb0007f (DAC: Determine deviceInfo for Sutter only once, 2024-01-09)

- [ ] Please keep the DEBUGPRINTSTACKINFO call at the function top-part below the variable definitions.

74ea0547 (DAC: Add support for zeroDAC, writeDAC and readADC for Sutter HW, 2024-01-05)

- [ ] foregroung -> foreground

d7144122 (DAC: Call SutterDAQReset in HW_SU_StopAcq only if acquisition is running, 2024-01-09)

Good.

939286ac (Utils: Add hardwaretype Sutter, 2023-12-05)

Nice.

92ae1065 (Util: Change GetSamplingInterval to be channel dependent, 2024-01-11)

- [ ] I haven't checked but the changes to CreateTiledChannelGraph look buggy.
  You are calculating xRangeStart/xRangeEnd using the DA sampling interval but
  the are then using these ranges for AD data as well. This is only an issue if
  dDAQDisplayMode is on.

```
-    params.samplingRate = ConvertSamplingIntervalToRate(GetSamplingInterval(s.DAQConfigWave)) * KILO_TO_ONE
+    params.samplingRate = ConvertSamplingIntervalToRate(GetSamplingInterval(s.DAQConfigWave, XOP_CHANNEL_TYPE_ADC)) * KILO_TO_ONE
```

- [ ] You can't use the ADC sampling rate for all channels! This needs to be
  now set per channel. And we also need a test in
  UTF_TestNWBExportV1.ipf/UTF_TestNWBExportV2.ipf, for which we might need to
  adapt IPNWB::ReadChannelParams so that the rate is also read.
  NWB_ClearWriteChannelParams then also needs adaptation as we want to clear
  the sampling interval.

- [ ] We now support `_FFR` for acquire data so you don't have to call PGC for `popup_setting_FixedFreq`.

- [ ] The labnotebook key "Sampling interval AD" does not exist at this point. 75f1f45d needs to come earlier.

In order to ease review it would make sense to have this commit and 75f1f45d in
another separate PR. This PR would then also close #1938. We call this new PR XX.

35310404 (SampInt: Return channel dependent sample min interval for Sutter hardware, 2023-12-11)
f4a3a9b2 (DC: Add support for sutter hardware, 2023-12-06)

All good.

d8055fe8 (DC: Do not rely on DAQDataWave for sample interval of scaledDataWave channels, 2024-01-12)

Can also be part of XX.

0dc963fe (TP: Add chunked TP logic for Sutter, 2023-12-05)
17b92d69 (DQM: Add handling of sutter in DQM background task, 2023-12-05)

Jeep.

ae0d9f7f (SCOPE: Handle Oscilloscope update for sutter hardware, 2023-12-05)

Fine.

a5b32d35 (DAP: Extend DAEphys to include sutter devices, 2023-12-05)

- [ ] `ASSERT(0, "If that location is reached a case was not handled that
  should be handled.")` can not be reached as the switch before it has a
  default branch.

1cd31a7b (DAP: Disable AD/DA channel popup menus when sutter hardware is locked, 2024-01-04)

Jeep.

ccb3125a (DAP: Adapt tooltip help for sampling interval related controls, 2024-01-09)

Very nice!

c8741ab8 (DAP_GuiState: Return proper error when ctrl not in GUIState wave in debug mode, 2024-01-10)

Nice fix.

b8460e1f (Separate AD/DA channels for HS and non-HS, 2024-01-10)

Very nice commit message.

For the future please separate refactoring, here the introduction of
DAP_CheckAsyncSettings, from adding the auxOffset check. Otherwise you are lost
in a normal git diff without colored move detection.

- [ ] GetDeviceInfoWave: empty comment line after `@brief`
- [ ] GetDeviceInfoWave: Missing Redimension call in upgrade path

4ac59de3 (SWS: Extend SWS_GetChannelGains to support sutter and add to description, 2023-12-05)

- [ ] We need a test for Sutter which uses async channel, unassociated channels
  and 2 TTL channels. And then check that everything is working, including NWB
  roundtripping. The later test CheckIfConfigurationSavesAndRestores goes in that direction.

06711d40 (AF: Add /WAVE type for scaledDACWave field and update description of field, 2024-01-09)
81de69e4 (AF: Do not lock DAQDataWave for Sutter for V1, V2 AF functions, 2023-12-11)

All good.

c321250f (AF: PSQ BaseLineChunk evaluation is based in DA sample interval, 2023-12-13)

Commit message misses reference to commit introducing the bug.

8869f59a (AF: PatchSeq return 50 kHz as Sutter default samplingFrequency, use sampMult 1, 2023-11-22)

Good.

e0085b74 (AF: PSQ_Ramp Add modification of DAQDataWave for sutter hardware, 2023-11-22)
0fcb2ec0 (AF: PSQ_Ramp use scaledChannelDA for adding Ramp epoch for correct unit check, 2023-12-13)

All good.

9df8ce98 (AFM: Do not call analysis function MID_SWEEP if fifopos is zero, 2024-01-11)

That is an interesting bugfix. I think this could also fix the CI failures I'm
seeing in #2001 so I've cherry-picked that commit for that PR.

75f1f45d (LNB: Introduce channel type dependent sampling interval entries, 2024-01-09)

Should be part of XX.

8e766bfe (Struct: Update description for samplingInterval field of DataConfigurationResult, 2024-01-09)

- [ ] Should also be part of XX
- [ ] Can we rename the structure member and introduce ones for each type? The
  usage of samplingInterval in EP_CollectEpochInfoTTL looks suspicous. Is the sampling interval always the same for DA and TTL?
- [ ] Please also check that we have an epoch test which uses TTL and only one HS.

214c8adf (CONF: init device lists properly and adapt control setting for Sutter, 2024-01-11)

- [ ] Please move the SVAR initialization out of the switch in
  `CONF_PrimeDeviceLists` and also keep the order of the "globalX" variables
  the same when assigning them in the switch.

c03be9a9 (Add SUTTER Test setup, 2023-12-11)

- [ ] Commit message is too terse. It would be especially interesting to describe what happened in the pxp files.
- [ ] Comment in DeviceNameGeneratorMD0 mentions NI hardware
- [ ] GetMinSamplingInterval: prefer `#elif`.

9b6e91e5 (Tests: UserAnalysisFunctions.ipf Add sutter as hardware for AF struct checks, 2023-11-22)

Jeep.

122180d7 (Tests: Use always Headstage 0 for sutter PSQ tests, 2023-12-13)

Obviously correct.

67eaac45 (Tests: Change async channels for analysis function to 2, 3, 2024-01-10)

Makes sense.

06ec75d5 (Tests ANA: Adapt DAQDataWave lock check for V1, V2 AnalysisFunctions, 2024-01-11)
9275b4b2 (Tests: Adapt TP Basic HW test CheckTPBaseLine, 2024-01-12)

Nice!

4b605640 (Tests: Make EpochTestGeneric aware of Sutter hardware, 2024-01-12)

Makes sense.

bd1f28bd (Tests: Add Configuration test that saves/restores a DAP with sutter config, 2024-01-16)

Good!

748f208d (CI: Increase timeout for check that each commit compiles, 2024-01-18)

Nice.

**Comment by MichaelHuth** [comment]
> Please also check that we have an epoch test which uses TTL and only one HS.

The tests 
* EP_EpochTestTTLSamplingFrequency
* EP_EpochTestTTLSamplingMultiplier
* EP_EpochTest18

use one HS and TTL channels.

**Comment by t-b** [comment]
@MichaelHuth @timjarsky Merged!

**Pull request merged**
