### PR TITLE
Feature/1689 Extend SF operation div for data sets

### PR DESCRIPTION
**Pull request by MichaelHuth**
- [x] Once the new div extension is considered good:
    - [x] Adapt parser to always parse primitive operations (`+-/*`) to two JSON elements
    - [x] Get rid of SF_GetArgumentTop for those
    - [x] Create issue for switching other callers away from SF_GetArgumentTop, https://github.com/AllenInstitute/MIES/issues/1690
    - [x] Adapt other primitive operations to the same approach as div

close https://github.com/AllenInstitute/MIES/issues/1618

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b How about this solution for our primitive SF operations?

**Comment by t-b** [comment]
LGTM, but needs approval from Tim as well.

**Comment by timjarsky** [comment]
@MichaelHuth 

```
d = data([1000,1500], select(channels(AD0), 6...10,all))

$d

and

$d / -5
```

gives the error: `operand for / must be numeric`

``` $d / (-5) ``` works.

**Comment by t-b** [comment]
@timjarsky The sign handling improvements are done in https://github.com/AllenInstitute/MIES/pull/1692. But if you say that `$d / (-5)` works as expected, I would say `/` works as expected and we can continue here.

**Comment by MichaelHuth** [comment]
Rebased, `$d / -5` works now with 1692 merged.

**Comment by t-b** [comment]
@MichaelHuth Jeep works!

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
