### PR TITLE
Add enable/disable button to SF

### LINKED ISSUE #347: Add "enable" checkbox to SF tab
> can the SF tab have an "enable" like PA does so it doesn't continue to generate plots if you don't want it to?

### PR DESCRIPTION
**Pull request by ukos-git**
The SweepFormula gets an enable button and is disabled b default to
allow omitting calculations on DB update.

Closes #347

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I like that it is possible to edit the SF when disabled, but it would also be helpful if the SF tabs were enabled- is this possible?

**Comment by t-b** [comment]
@timjarsky Yes this is certainly possible although it deviates from what we do for the other controls. We can chat about that tomorrow.

**Comment by timjarsky** [comment]
>  it deviates from what we do for the other controls. 

@t-b In this case at least, I think it makes sense to mimic the `prevent update` checkbox in the waveBuilder.

**Comment by t-b** [comment]
@ukos-git @timjarsky I've rebased  and fixed the conflicts. We handle the proposed changes wrt to the enable buttons in general and in a separate PR.

**Pull request merged**
