### PR TITLE
Add epoch information for TTL channels

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/855

### CODE REVIEW

**Comment by t-b** [comment]
Its way too late here for a proper review but I think that in 5149f3d9f9dc2dfdf70051cf41c91cefa3c7f0fd the indexing of `statusTTLFiltered` is wrong. It should be by active channel aka `i`. See how DC_ITC_MakeTTLWave does it in main.
Also the commit changing behaviour should also have the changed tests.
And every commit which adds/changes labnotebook entries (including the meaning) should raise the labnotebook version. Otherwise I don't find all the places where the LBN was changed with `tools/create-changelog.sh`.
2a04ea57556a3374f9d151650c4efff75d6e6716 needs a "introduced in XXX" part of the commit message and an explanation why this was not found earlier including the consequences of the bug. And a tests which fails without that fix.

**Comment by MichaelHuth** [comment]
> Its way too late here for a proper review but I think that in [5149f3d](https://github.com/AllenInstitute/MIES/commit/5149f3d9f9dc2dfdf70051cf41c91cefa3c7f0fd) the indexing of `statusTTLFiltered` is wrong. It should be by active channel aka `i`. See how DC_ITC_MakeTTLWave does it in main.

statusTTLFiltered has NUM_DA_TTL_CHANNELS, thus indexes over the channels. Whereas in main the loop in DC_ITC_MakeTTLWave also indexed from 0 to NUM_DA_TTL_CHANNELS after the change I index over the number of active TTL channels (0 to s.numTTLEntries).
The active channel number is retrieved through the config wave by `channelNumber = config[i + ttlOffset][%ChannelNumber]`, that corresponds to `i`in main.

**Comment by t-b** [comment]
> > Its way too late here for a proper review but I think that in [5149f3d](https://github.com/AllenInstitute/MIES/commit/5149f3d9f9dc2dfdf70051cf41c91cefa3c7f0fd) the indexing of `statusTTLFiltered` is wrong. It should be by active channel aka `i`. See how DC_ITC_MakeTTLWave does it in main.
> 
> statusTTLFiltered has NUM_DA_TTL_CHANNELS, thus indexes over the channels. Whereas in main the loop in DC_ITC_MakeTTLWave also indexed from 0 to NUM_DA_TTL_CHANNELS after the change I index over the number of active TTL channels (0 to s.numTTLEntries). The active channel number is retrieved through the config wave by `channelNumber = config[i + ttlOffset][%ChannelNumber]`, that corresponds to `i`in main.

No, look at the code https://github.com/AllenInstitute/MIES/blob/main/Packages/MIES/MIES_DataConfigurator.ipf#L682 for ITC.

**Comment by t-b** [comment]
@MichaelHuth How should we proceed here?

**Comment by MichaelHuth** [comment]
@t-b The part of new commits after https://github.com/AllenInstitute/MIES/pull/1797
starts with 61b4c533 (Tests: Fix UnassociatedChannelsAndTTLs numRacks determination, 2023-06-28)

**Comment by t-b** [comment]
Review:

5e5897be (DC: Assert if entry is empty in DC_DocumentChannelProperty, 2023-06-23)
b8005113 (DC: bugfix DC_GetConfiguration get numTTLEntries from TTLList instead of DAClist, 2023-06-22)
a4cacdc6 (DC: Collect epoch info after TTL channels were setup, 2023-06-22)
53aff978 (Add LNB function support for TTL channels for read/write, 2023-06-22)
ad3cf0b6 (DC: Use DC_DocumentChannelProperty to save TTL NB data, 2023-06-24)
fa33bf2c (DC: Move creation of TTL wave at the begin of DataConfigurationResult creation, 2023-06-26)
faac0c2a (DC: Add more DataConfigurationResult structure fields for TTL, 2023-07-04)
6267eeaf (DC: Use DataConfigurationResult structure in DC_WriteTTLIntoDAQDataWave, 2023-07-04)
3380af09 (DC: Introduce DC_SetupConfigurationTTLstimSets to gather TTL info, 2023-07-04)
147df167 (DC: Rewrite of DC_NI_MakeTTLWave and DC_ITC_MakeTTLWave, 2023-07-04)
56b85898 (DC: Initialize new TTL fields DC_GetConfiguration, 2023-07-04)
c2bbe113 (Tests: The decimated StimsetLength are now saved for TTL channels in the LNB, 2023-06-28)
e43bc9a4 (Tests: Adapted test Test_GetHeadstageForChannel, 2023-06-28)
ff0e4945 (Tests: Remove test that checks if Epochs from TTL channels are invalid, 2023-06-28)

other PR.

158ce175 (Tests: Fix UnassociatedChannelsAndTTLs numRacks determination, 2023-06-28)

Good.

b48347da (Add channel types support to EpochsWave as chunk index, 2023-06-21)

Please update the function comment. The comment also says `For these three formats we have tests in RPI_WorksWithOldData(). When changing the tags format this test needs to be updated.`.

Comment for SWEEP_EPOCH_VERSION needs updating. I also think `SWEEP_EPOCH_VERSION/write` should be raised (which you could not know.)

3716b1ce (EP: Add channelType support to EP_AddEpochs, 2023-06-21)
d287b505 (EP: Allow EP_FetchEpochs to retrieve epoch information from TTL channels, 2023-06-21)
244c5bf1 (EP: Allow TTL channels in EP_GetEpochs, 2023-06-21)
bec26252 (EP: Add support for channel type to EP_EpochWaveToStr, 2023-06-21)
c51e20c4 (EP: Add channelType support to EP_GetEpochCount, 2023-06-21)
8dfc82de (EP: Adapt EP_GetEpochs to epochs wave with channel type as chunks, 2023-06-28)
0fb5d89f (EP: Add TTL channel type support to EP_AddUserEpoch, 2023-06-21)

All good.

d9be36c4 (EP: Add TTL channel type suport to EP_AdaptEpochInfo, 2023-06-21)
2b52af9e (EP: Add channel type support to EP_SortEpochs, 2023-06-21)

Both good.

a948065b (EP: Adapt AppendLBNEpochs to for new EpochsWave format with TTL chunks, 2023-06-23)
172cc574 (EP: Rename EP_AppendLBNEpochs to EP_CopyLBNEpochsToEpochsWave, 2023-06-23)

All good.

adbb2229 (EP: Write epoch information for TTL and DA channels into LBN, 2023-06-22)

I don't understand why

```
+        if(configWave[i][%DAQChannelType] != DAQ_CHANNEL_TYPE_DAQ)
+            // skip all other channel types
+             continue
+        endif
+
+        channel = configWave[i][%ChannelNumber]
+        headstage = chanType == XOP_CHANNEL_TYPE_DAC ? AFH_GetHeadstageFromDAC(device, channel) : INDEP_HEADSTAGE
```

is part of this commit. And why do we want to change how unassoc DA data is stored? And why does the tests pass with this change?

1cfe130c (Add entries to sweep text NB for TTL epochs, 2023-06-22)
Needs to raise SWEEP_SETTINGS_WAVE_VERSION.

c2891eb1 (EP: Move collection of DA epochs to own function EP_CollectEpochInfoDA, 2023-07-06)
ac7bf0b7 (EP: Remove getting config waveref in EP_CollectEpochInfo, 2023-07-06)

Nice!

4305ff62 (EP: Add channel type support to EP_AddEpochsFromStimSetNote, 2023-06-28)

Good!

c61b6a27 (EP: Add function EP_CollectEpochInfoTTL that creates epochs for TTL channels, 2023-06-22)

C&P code uses EPOCH_SN_BL_DDAQTRAIL. Can we have a test for the TTL epoch names as well?

if `startOffset`  is zero you need to set epochBegin/EpochEnd to zero as it is not zero for guiChannelNumber > 0. Or don't read `epochEnd` in `epochBegin = epochEnd` and just recalculate it?

Please also prefer `i` over `guiChannelNumber` per our coding conventions.

916e4416 (BSP: Add TTL channel support to BSP_AddTracesForEpochs, 2023-06-22)

Move `BSP_GetChannelNumberTTL` to MIES_MIESUtilities.ipf with documentation.

Can we keep `EP_FetchEpochs` out of the switch statement and also not remove the `// present since ...` comment?

The code block

```
-
-        if(IsEmpty(epochInfoStr))
-            continue
-        endif
-
-        WAVE/T epochs = EP_EpochStrToWave(epochInfoStr)
-        SetEpochsDimensionLabelsSingleChannel(epochs)
-
-        sprintf name, "epochs_sweep%d_HS%d", sweepNumber, headstage
-
-        Duplicate/O/T epochs, dfr:$name/Wave=epochs
```

was only added in b48347dab8c1818e6534e2229bf875a7be0770c5. Why remove it here again?

e772d549 (MiesUtil: Add axes for TTL epochs to LayoutGraph function, 2023-06-22)

You just added `DB_AXIS_PART_EPOCHS` before so why not use it?

Various commits have a trailing `f` in the commit message.

**Comment by t-b** [comment]
Please also check with code coverage and the epochs test that `EP_CollectEpochInfoTTL` has ~100% coverage.

**Comment by t-b** [comment]
The epoch name `EPOCH_SN_BL_ONSETDELAYUSER` is also not correct in EP_CollectEpochInfoTTL as startoffset/s.onSetDelay is the total onset delay.

There is the fix for https://github.com/AllenInstitute/MIES/issues/855#issuecomment-1573803631?

**Comment by MichaelHuth** [comment]
reg.: https://github.com/AllenInstitute/MIES/commit/b48347dab8c1818e6534e2229bf875a7be0770c5 (Add channel types support to EpochsWave as chunk index, 2023-06-21)

The addition of the chunk dimension does not change the tags. The epoch information is saved on a per channel basis in LNB.

**Comment by MichaelHuth** [comment]
reg: https://github.com/AllenInstitute/MIES/commit/adbb2229c774777efe9aeab18139f8c3e24d1734 (EP: Write epoch information for TTL and DA channels into LBN, 2023-06-22)

This is indeed some leftover change from some working version which is not needed anymore. I removed that. The tests passed because it does for DA the same as the loop in main.

**Comment by t-b** [comment]
@MichaelHuth Please rebase.

**Comment by t-b** [comment]
Looks good. Couple of minor issues are remaining. Please assing Tim once these are fixed.

- [ ] If you extend the test to also have an onset and termination delay

```diff
diff --git a/Packages/tests/HardwareBasic/UTF_Epochs.ipf b/Packages/tests/HardwareBasic/UTF_Epochs.ipf
index a35ab35112..60e215b01e 100644
--- a/Packages/tests/HardwareBasic/UTF_Epochs.ipf
+++ b/Packages/tests/HardwareBasic/UTF_Epochs.ipf
@@ -1033,7 +1033,7 @@ static Function EP_EpochTestTTL([str])
     string str

     STRUCT DAQSettings s
-    InitDAQSettingsFromString(s, "MD1_RA0_I0_L0_BKG1"                         + \
+    InitDAQSettingsFromString(s, "MD1_RA0_I0_L0_BKG1_TD25_OD15"               + \
                                  "__HS0_DA0_AD0_CM:VC:_ST:StimulusSetA_DA_0:"      + \
                                  "__TTL1_ST:StimulusSetA_TTL_0:"                   + \
                                  "__TTL3_ST:StimulusSetB_TTL_0:"                   + \
```

and then look at the epochs

image

you see that the DA epochs have both B0_TD and B0_TR but TTL1_3 only has `B0_TR`. I don't think this is correct as TTL should have also two different epochs. The test should then also be extended with an onset and termination delay.
- [ ] Parametrize the test using multi multi data test case logic to have a variant without inserted TP
- [ ] Change the documentation in doc/epoch_information.rst for the rename in 6cf95899 (EP: Rename constant for baseline trail to EPOCH_SN_BL_GENERALTRAIL, 2023-07-08) as the explanation now is wrong.

**Comment by t-b** [comment]
@MichaelHuth Very nice update!

**Review by t-b — APPROVED** [review]
LGTM

**Comment by timjarsky** [comment]
@MichaelHuth @t-b  Based on the SF documentation, the SF channels operation should work with TTL data, but I get either: `Unknown channel: TTL0_0` or `Unhandled channel type 3 in channels() at position 0` with `channels(TTL0_0)` and `channels(TTL)`, respectively. Otherwise the TTL epochs look good!
image

**Comment by MichaelHuth** [comment]
@timjarsky Thanks for the feedback, I'll look into it.

**Comment by MichaelHuth** [comment]
@timjarsky The issue is in the select operation. I committed a small preliminary patch that enabled TTL channels from displayed sweeps. e.g. ```
data(
cursors(A,B),
select(channels(TTL),sweeps())
)
```
or
```
data(
cursors(A,B),
select(channels(TTL7),sweeps())
)
```

the fix for select from all sweeps is more complex as the LNB handling for TTL channels is different from DAC/ADC.

**Comment by t-b** [comment]
> Tim Jarsky ***@***.***> hat am 12.07.2023 01:35 CEST geschrieben:
> 
>  
> @MichaelHuth @t-b  Based on the SF documentation, the SF channels operation should work with TTL data, but I get either: `Unknown channel: TTL0_0` or `Unhandled channel type 3 in channels() at position 0` with `channels(TTL0_0)` and `channels(TTL)`, respectively. 

SweepFormula does not support TTL channels. We skipped that back in 2019 to get something done quickly. Unforunately the documentation is not in line with the design decision back then. Maybe `channels` supports it but we would need support in at least `select`/`data`/`epochs` for every day usage. One could maybe skip `labnotebook` for now as that sounds not that straight forward.

So I suggest if we want SF to support TTL, we should do that in a follow up  PR.

> Otherwise the TTL epochs look good!

Very nice!

**Comment by timjarsky** [comment]
@t-b Doing it in another PR makes sense. We should discuss whether it's best to change TLL labnotebook entries (probably not), create new ones that match DA and AD LBN entries, or enhance the LBN handling for TTL channels.

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
@timjarsky I've created #1817 and #1816 to track that.

@MichaelHuth Can you rebase and drop the changes to select so that we can merge?

**Pull request merged**
