### PR TITLE
Feature/add analysis function failed pulses

### LINKED ISSUE #633: Add new analysis function for failed pulse usage
- [ ] Flowchart
- [ ] Discuss that with Tim
- [ ] Code
- [ ] Tests

PRE_SET:

- Open Databrowser (if not yet open), enable PA plot image, and failed pulse search

POST_SWEEP:

- Read failed pulses from `properties` wave
- Store in LBN
- redo last sweep with failed pulses using skip sweeps with an adapted DAScale (clarify with Tim how)
- store pass/failure in LBN

### PR DESCRIPTION
**Pull request by t-b**
@timjarsky First version

- [x] Add more tests
- [x] Flowchart
- [x] Add test for not increasing the DAScales if the sweep passed but single headstages failed
- [x] Dashboard support
- [x] LBN entry docu

Close #633.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready for a first test.

**Comment by timjarsky** [comment]
@t-b the DA scale is adjusted when any of the overlayed sweeps fails but DA scale should adjust only when the last acquired sweep fails.

**Comment by timjarsky** [comment]
@t-b can we add the following control settings to the preset event:

image

**Comment by t-b** [comment]
> @t-b the DA scale is adjusted when any of the overlayed sweeps fails but DA scale should adjust only when the last acquired sweep fails.

I'll have a look. This is the code which is not exercised in the tests, as I'm mocking the failed/passing state.

**Comment by t-b** [comment]
@timjarsky Second try,

**Comment by timjarsky** [comment]
@t-b I think this assertion happened when a subset of the pulses in a train failed and others passed. Prior to this sweep, there were many sweeps were all spikes failed.

```
 !!! Assertion FAILED !!!
  Message: "Invalid failed pulses count"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L105 [MIES_DataAcquisition_Multi.ipf]
DQM_StopDataAcq(...)#L359 [MIES_DataAcquisition_Multi.ipf]
SWS_SaveAcquiredData(...)#L53 [MIES_SweepSaving.ipf]
AFM_CallAnalysisFunctions(...)#L129 [MIES_AnalysisFunctionManagement.ipf]
MSQ_SpikeControl(...)#L1976 [MIES_AnalysisFunctions_MultiPatchSeq.ipf]
MSQ_WriteSpikeControlLBNEntries(...)#L1760 [MIES_AnalysisFunctions_MultiPatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-18T13:54:02-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [19]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2020_10_18_134631 (Packed)
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-321-g7b0ee969
Date and time of last commit: 2020-10-16T23:31:37+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 b890ee01f65722475338602ff998abadad66b76f 0	Packages/unit-testing
```

image

**Comment by t-b** [comment]
@timjarsky Dooh. I'll make a fix my tomorrow morning.

**Comment by t-b** [comment]
@timjarsky Fixed.

**Comment by timjarsky** [comment]
@t-b the adjustment of DA scale is applied to all DAC channels rather than the headstage DAC channel that has failed pulses.

**Comment by t-b** [comment]
@timjarsky And the next iteration. I've also enhanced the update speed when clicking into the dashboard listbox.

**Comment by t-b** [comment]
I also finally made the flowchart. And after yet another tool search I found a tool which works well. It's really old and ancient to use but does the job pretty nicely. It's called dotty, but is available only on linux.

While doing the flowchart I've optimized the code a bit more, and I need to add a test for that as well.

**Review by timjarsky — APPROVED** [review]

**Comment by MichaelHuth** [comment]
[Crash 2020-10-26 20-05-42.zip](https://github.com/AllenInstitute/MIES/files/5440704/Crash.2020-10-26.20-05-42.zip)

Crash dump, happened when running the spike test ipf in UTF / IP8. First default, then second time with debugger enabled, breakpoints and allowDebug = 1.

**Comment by t-b** [comment]
@timjarsky I just fixed one of the tests. No functional change otherwise.

**Pull request merged**
