### PR TITLE
DRAFT: Add Labnotebook entry descriptions

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b What if we added another row to the LN key wave; group. We'd then use this group assignment for each entry to categorize the LN menu. Thoughts?

**Comment by t-b** [comment]
@timjarsky Sounds good. But we would merge #507 before we finish this PR or?

**Comment by timjarsky** [comment]
> @timjarsky Sounds good. But we would merge #507 before we finish this PR or?

In a new PR, I could categorize each column of the LN relatively quickly. Options are: merge #507, and then create a new PR that uses the new LN entries OR wait on #507 and adapt it to use entries when they are available. I suspect you (@t-b ) favor the former?

**Comment by t-b** [comment]
@timjarsky Jeep I favour the former ;)

**Pull request closed without merging**
