### PR TITLE
Show headstage in databrowser/sweepbrowser as well

### LINKED ISSUE #122: DataBrowser/AnalysisBrowser Add option to show headstage on Y-axis labels
The Y-axis label in the MIES browsers presently displays the AD channel. I'd like to give the user the option to display the headstage number instead.

### PR DESCRIPTION
**Pull request by t-b**
Close #122.

How about not adding a setting but showing both? This is what I implemented now.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b is there a way to resize the text automatically so that Y-axis labels don't overlap?

**Comment by t-b** [comment]
@timjarsky Not really. I've played around some more but the only option is either to make the axis labels smaller or show only one of them. I've opted for the latter open.

**Comment by timjarsky** [comment]
@t-b I don't like having the headstage label settings checkbox. Vertical space, but not horizontal space, is limiting. Why not something like:

image
```
HS0
\Z08DA0
(mV)
```

**Comment by timjarsky** [comment]
@t-b one more note: when AD and DA channels are displayed, there are two identical HS labels. In that case, can the DA and AD share a HS axes label?

**Comment by t-b** [comment]
Note to self: Check if it is feasable to have only one HS label when two adjacent AD/DA channels are shown.

**Comment by t-b** [comment]
@timjarsky One can have one axis label for the DA/AD channels here is what needs to be done:
- Figure out in CreateTiledChanneLGraph when two DA/AD channels are adjacent and belong to the same headstage
- Calculate the center of the spanned vertical area length
- Position the axis label there using lblPosMode with margin scaled

Not very straightforward. Now? New Issue? Forget?

**Comment by timjarsky** [comment]
> @timjarsky One can have one axis label for the DA/AD channels here is what needs to be done:
> 
> * Figure out in CreateTiledChanneLGraph when two DA/AD channels are adjacent and belong to the same headstage
> * Calculate the center of the spanned vertical area length
> * Position the axis label there using lblPosMode with margin scaled
> 
> Not very straightforward. Now? New Issue? Forget?

@t-b I think we should take the time to do the above. Will it be possible to restrict this calculation to times where the channel configuration is modified or does it need to be done with each newly plotted sweep?

**Comment by t-b** [comment]
@timjarsky We build the plot from scratch each time.

**Comment by t-b** [comment]
@timjarsky I've added something :)

**Comment by timjarsky** [comment]
@t-b resizing the DB changes the relative position of the label such that it can disappear off the graph. If possible, can the HS label be outside the channel label?

**Comment by t-b** [comment]
@timjarsky You beat me to it ;) Now enhanced with using a free axis.

**Comment by timjarsky** [comment]
> @timjarsky You beat me to it ;) Now enhanced with using a free axis.

@t-b it's looking good. Can the HS label be moved outside of the channel labels and vertically centered between them?

**Comment by t-b** [comment]
Note to self: It should look like 
grafik

**Comment by t-b** [comment]
@timjarsky Go for it!

**Comment by timjarsky** [comment]
@t-b when using >2 HS I get the error captured in the image below.

image

**Comment by t-b** [comment]
@timjarsky Next try

**Pull request merged**
