### PR TITLE
fix EP_AddEpochsFromStimSetNote for empty stimset wave notes

### PR DESCRIPTION
**Pull request by MichaelHuth**
EP_AddEpochsFromStimSetNote was also called for stimsets with empty wave notes
such as TP during DAQ stimsets. This resulted in an ST_B (stimset baseline)
epoch added for this stimset, that is wrong.

Fix: - Added a check in callers of EP_AddEpochsFromStimSetNote to call only if
       the stimset is of a type that should contain epoch data.
	 - Added better checks in EP_AddEpochsFromStimSetNote
	 - increased sweep_epoch_version.

close https://github.com/AllenInstitute/MIES/issues/1063

### CODE REVIEW

**Comment by MichaelHuth** [comment]
Pending RTE handling will be in a separate PR.

**Comment by t-b** [comment]
Review:
- Missing tests
- As outlined in the issue I would like to not see epoch info at all for TP during DAQ channels or third party stimsets

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Comment by t-b** [comment]
Review:

d1f024f9 (fix EP_AddEpochsFromStimSetNote for empty stimset wave notes, 2021-09-14)

```
+       if(IsEmpty(stimNote))
+               return NaN
+       endif
+
````

Does that still make sense? From my understanding this can not happen anymore. If this is the case an assertion would be better. 

095ba1b5 (Test: Epochs added check for analysisFunction string in AcquireData, 2021-09-16)

Nice find!

7055dfbd (WaveBuilder: Added utility function WB_MakeStimsetThirdParty, 2021-09-17)

If you use WB_CreateAndGetStimSet you have a permanent stimset wave in the right place already.

```
	AddEntryIntoWaveNoteAsList(stimset, "Version", var=STIMSET_NOTE_VERSION, appendCR = 1)
```

Thirdparty stimsets don't require a wave note so this should not be needed.

Please use the following pattern to derive the channelType.

```
	type = GetStimSetType(setName)

	if(type == CHANNEL_TYPE_UNKNOWN)
		return $""
	endif
```

c20c01a9 (Tests: Added Epoch tests with TP during DAQ / third party stimset, 2021-09-16)

Looks good. Just a minor nit:

Please prefer CHECK_EMPTY_STR, see https://docs.byte-physics.de/igor-unit-testing-framework/assertions.html#_CPPv415CHECK_EMPTY_STRP6string, instead of comparison with an empty string.

**Comment by t-b** [comment]
Review:

Why do you still have 

```
+
+       WAVE/Z/SDFR=dfr oldStimSet = $setName
+       if(WaveExists(oldStimSet))
+               if(WaveRefsEqual(oldStimSet, stimSet))
+                       return NaN
+               endif
+               KillOrMoveToTrash(wv=oldStimSet)
+       endif
+       MoveWave stimSet, dfr:$setName
```

in WB_MakeStimsetThirdParty? I think that WB_CreateAndGetStimSet creates the wave already in the correct place.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@t-b tested with a custom wave and tp during DAQ

**Pull request merged**
