### PR TITLE
Disable global insert TP for unassoc DA channels option

### PR DESCRIPTION
**Pull request by MichaelHuth**
- [x] Wait for #1783
- [x] Epochs
- [x] Tests

close https://github.com/AllenInstitute/MIES/issues/1764

TP is run on associated DA channels only during ITI. No change here regarding unassociated DA channels.

### CODE REVIEW

**Comment by t-b** [comment]
Review:

Looks mostly really nice. Two minor comments:

- 24452a42 The commit message should say why this is needed.
- c28a84b1 Is adding unrelated changes

I think that the name of the new LBN entry "Global TP insert on unassociated DA channels" is a bit too long, but I leave that bikeshedding to Tim.

**Comment by t-b** [comment]
@MichaelHuth Needs conflict fixes.

**Comment by t-b** [comment]
Please assign me once done.

**Comment by t-b** [comment]
Review:

d1e949a3 (DAEphys: Add new checkbox to panel for o TP on unassociated DA channels, 2023-06-05)

Fine.

33e12d40 (DAP: Make CB "TP on unassoc" dependent from Insert TP checkbox, 2023-06-06)

Good.

d422a4e7 (DAEphys: Increase panel version to 61, 2023-06-05)

- [ ] Merge with d1e949a3. This makes it easier to find the new checkbox.

f71ad3d2 (DC: Add no TP for unassoc DA in DataConfigurationResult structure, 2023-06-05)

Jeep.

2dfcc5c5 (DC: Dont add TP on Acquisition if TP on unassoc checkbox is unchecked, 2023-06-05)

Jeep.

09052281 (LBN: Add new entry for TP on unassoc DA channels in LBN, 2023-06-06)

Fine.

ac61cb04 (EP: Add epoch for No TP on unassociated DA channels -> B0_TP, 2023-06-20)

Good.

2c3c77d7 (Tests: Adapt TestEpochsGeneric to test all DA channels, 2023-06-20)

+1

de798954 (Tests: Add epoch test for unassoc DA channel without insert TP, 2023-06-22)

- [ ] The test should also check that the normal TP epochs are missing on the unassoc DA, something like

```
	WAVE/Z tpMissing = FindIndizes(epochNames2, str="TP*", prop = PROP_WILDCARD)
	CHECK_WAVE(tpMissing, NULL_WAVE)
```

- [ ] It should also check the new LBN entry.

- [ ] We should also extend another epoch test, EP_EpochTest15?, to check the default behaviour of the new checkbox.

**Comment by t-b** [comment]
https://github.com/AllenInstitute/MIES/commit/09052281a11be940211a42e65177409e50a47ecf needs to raise LABNOTEBOOK_VERSION.

**Comment by t-b** [comment]
Very nice! Thanks!

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@MichaelHuth, sorry for this late question, but how are the TP properties (e.g., amplitude) on unassociated DA channels set?

**Comment by MichaelHuth** [comment]
For inserting the TP in unassociated DA channels the same code as for associated DA channels is run. Thus, the same settings apply for unassociated DA channels.
The checkbox to switch the inserted TP off for unassociated DA replaces the time interval where for associated DA channels the TP is inserted with constant baseline amplitude.

**Comment by t-b** [comment]
Let's move the discussion to the issue I created.

**Pull request merged**
