### PR TITLE
Feature/1330 analysis function true resting membrane potential

### LINKED ISSUE #1296: Analysis function: TrueRestingMembranePotential
Name: TrueRestingMembranePotential 
ShortName: Vm (preferred casing, all uper case is fine as well)

Objective: Capture a current clamp sweep where the stimulus is completey zero except the inserted TP and about a second long.

Measure mean potential of stimset (without inserted TP), document in LBN,

One passing sweeps.

MID_SWEEP_EVENT:

2 baseline selection user epochs:
- 0: Short and long RMS, record average voltage of baseline region
- 1: record average voltage of baseline region

baseline QC consists of short and long RMS, and that both average voltages are within the given boundaries. Document both average voltages and difference.

PRE_SET_EVENT:
- No autobias, no holding potential
- Bridge balance and capacitance compensation should be on
- Only one active headstage
- Current clamp
- No TTL
- No oodDAQ/dDAQ

Add baseline selection epochs:
- epoch 0: baseline 0
- epoch 1: something else
- epoch 2: baseline 1

- Check that amplitude of epochs are zero

POST_SWEEP_EVENT:
- sweep QC: baseline QC and sampling interval QC and spike QC (passing is no spikes)

Check for spikes (everywhere) and add LBN entries.
If we have spikes:
- Exclude spiking region from measured mean potential of stimset
- Turn on autobias
- Set target V of autobias to measured mean potential + user offset

POST_SET_EVENT:
- If set QC passes: Set target V of autobias to that measured value, turn on autobias
- Publish: set QC and measured voltage

POST_DAQ_EVENT:
- Set next starting and ending stimset if set QC passes and both are given. Turn on indexing if ending stimset is given.

Analysis parameters:
- NextStimSetName:string (optional)
- NextIndexingEndStimSetName:string (optional)
- Two for absolute and relative average voltage difference like for DAScale
- BaselineRMSShortThreshold:variable
- BaselineRMSLongThreshold:variable
- [SamplingFrequency:variable],[SamplingMultiplier:variable]
- NumberOfFailedSweeps:variable
- BaselineChunkLength:variable
- UserOffsetTargetVAutobias:variable
- FailedLevel:variable (for spike check)

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add test for 6533e453 (DAP_OneTimeCallAfterDAQ: Allow changing indexing state in POST_DAQ_EVENT, 2022-04-26)
- [x] Add test for published message
- [x] Finish
- [x] Increase LBN version
- [x] Merge preparational PRs
  - [x] #1342 
  - [x] #1341
- ~~[ ] Clarify if one of the IVS function should be tweaked to use this analysis function. TJ is checking.~~
- [x] Add entry in list, see https://github.com/AllenInstitute/MIES/issues/1228#issuecomment-1112457383
- [ ] Digital Flowchart
- [x] Digital Testmatrix
- [x] ASCII stimsets
- [x] check LBN entry documentation
- [x] Generate list of analysis parmaters which have differing optionality, #1345
- [x] RelativeVoltageDiff/AbsoluteVoltageDiff: Enhance help how to ignore one or the other Allow `inf`.
- [x] Make BaselineChunkLength a minimum length and allow wavebuilder epochs to be longer

Requested Changes:
- [x] change message to: The specified stimset cannot be found
- [x] In addition to turning off autobias, TrueRestingMembranePotential should also turn off the holding current
- [x] I get average QC check failed result in the dashboard when RMS noise fails
- [x] if spikes are detected, set ITI to optional param (default to 10s ITI)
- [x] Rebase against main and prefer generic functions

Close #1296

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Not yet fully tested, but you can give it a spin if you are eager.

Note: The stimset requirements have changed slightly as you now need another epoch at the end (5ms is enought) to avoid rounding issues due to sampling interval decimation.

**Comment by timjarsky** [comment]
@t-b if NextStimSetName is provided but *not* NextIndexingEndStimSetName, the stimset should be set on passing (without setting indexing). Currently NextStimSetName on its own does nothing.

When NextStimSetName and NextIndexingEndStimSetName are set, it behaves as expected.

**Comment by t-b** [comment]
> NextStimSetName is provided but not NextIndexingEndStimSetName, the stimset should be set on passing (without setting indexing). Currently NextStimSetName on its own does nothing.

I can change that. The current behaviour is what was specified.

**Comment by t-b** [comment]
> > NextStimSetName is provided but not NextIndexingEndStimSetName, the stimset should be set on passing (without setting indexing). Currently NextStimSetName on its own does nothing.

> I can change that. The current behaviour is what was specified.

Done.

**Comment by t-b** [comment]
@timjarsky I've fixed some of the open issues.

**Comment by t-b** [comment]
@timjarsky Go for it! I've now fixed the BaselineChunkLength checks. The wavebuilder epochs must now be not exactly matching but can also be larger.

**Comment by timjarsky** [comment]
@t-b 
```
case "NextStimSetName":
case "NextIndexingEndStimSetName":
	str = AFH_GetAnalysisParamTextual(name, s.params)
	WAVE/Z stimset = WB_CreateAndGetStimSet(str)
	if(!WaveExists(stimset))
		return "The stimset can not be created"
``` 

change message to: The specified stimset cannot be found

**Comment by timjarsky** [comment]
@t-b In addition to turning off autobias, TrueRestingMembranePotential should also turn off the holding current.

**Comment by timjarsky** [comment]
@t-b I get `average QC check failed` result in the dashboard when RMS noise fails.

**Comment by timjarsky** [comment]
@t-b if spikes are detected, set ITI to optional param (default to 5s ITI).

**Comment by t-b** [comment]
>  In addition to turning off autobias, TrueRestingMembranePotential should also turn off the holding current

I'm already disabling check_DatAcq_HoldEnable. Isn't that the right one?

**Comment by t-b** [comment]
> if spikes are detected, set ITI to optional param (default to 10s ITI).

Done. This slipped earlier already as we talked about it already. I have to turn the get/set ITI checkbox off as well for that. I'm turning it back on when we don't have spikes.

**Comment by t-b** [comment]
I've fixed the other issues as well. See the checboxes at the top.

**Comment by t-b** [comment]
Fixed conflicts.

**Comment by t-b** [comment]
- Push changes
- Merge if CI passes

**Pull request merged**
