### PR TITLE
Sutter HW support preparation PR: Change internal sweep data storage format

### PR DESCRIPTION
**Pull request by MichaelHuth**
The is a part of #1667 that includes hardware independent changes required for proper sutter hardware support.

Main changes:
- support for different sample rates per channel
- a related change is that the storage format for sweep data in MIES is changed
- implications on measurement setup, helper wave during measurement, analysisfunctions etc.
- adapted tests

close https://github.com/AllenInstitute/MIES/issues/1954

### CODE REVIEW

**Comment by t-b** [comment]
Thanks for the massive effort. This is not a small undertaking!

Review:

cc6e2036 (Constants: Add DATA_DIMENSION constant for -1 dimension, 2023-12-06)

+1 

e80826b6 (WaveDataFolderGetters: Add and update getters for diff. AD/DA sampleinterval, 2023-12-07)

+1 

2befa706 (Hardware: Add functions for getting channel wave length and DA fifoPos, 2023-12-06)

- [ ] GetFirstADCChannelIndex is not known here.

fa997301 (DC: Adapt dataconfiguration to new scaledDataWave, 2023-12-06)

- [ ] DC_MakeHelperWaves:

```igorpro
		WAVE tpOsciForPowerSpectrum = GetScaledTPTempWave(device)
		Redimension/N=(tpLength, numADCs) tpOsciForPowerSpectrum
```

should only by done if powerSpectrum is true. We have an if branch above already.

```igorpro
	switch(hardwareType)
		case HARDWARE_ITC_DAC:
			WAVE ITCDataWave = GetDAQDataWave(device, dataAcqOrTP)
			sampleIntervalADC = DimDelta(ITCDataWave, ROWS)
			break
		case HARDWARE_NI_DAC:
			WAVE/WAVE NIDataWave = GetDAQDataWave(device, dataAcqOrTP)
			sampleIntervalADC = DimDelta(NIDataWave[numDACs], ROWS)
			break
	endswitch
```

- [ ] is correct but can use the newly added HW_GetEffectiveADCWaveLength/HW_GetEffectiveDACWaveLength instead?

- [ ] We should have a function which calculates the correct length of a single
channel and use that in DC_InitScaledDataWave instead of the ad-hoc calculation
for `size == ...`.

- [ ] Please also unify the handling in DC_InitScaledDataWave as the code for
  ITC and NI hardware is nearly the same except The Multithread statement.

ac2cde95 (Util: Adapt utility functions to new sweep format, 2023-12-05)

- [ ] SplitSweepIntoComponents: Please use backup functions like CreateBackupWave
      instead of hand-coding parts of it.

- [ ] SplitSweepIntoComponents should reference a place where we document the new stored sweep wave format (text wave, previously 2D wave).

- [ ] RestoreFromBackupWavesForAll also seems to be doing the same as ReplaceWaveWithBackupForAll. We should have only one function.

- [ ] ResolveSweepChannel does not have documentation. Same for GetSweepComponentWaveName.

- [ ] The new code in IsValidSweepWave does not need to check that sweep exists.

10ee140d (DB: Remove sweep modification check in DB_SplitSweepsIfReq, 2023-12-05)

Jeep

12274818 (EP: Use times as arguments for EP_WriteEpochInfoIntoSweepSettings, 2023-12-05)

- [ ] SWS_ProcessDATTLChannelsOnEarlyAcqStop is not yet there.

124b558f (SCOPE: Adapt that only ADC channels need to be updated in scaledDataWave, 2023-12-05)

- [ ] This is a change worth documenting in its own commit or not doing.

```diff
-                Multithread scaledDataWave[fifoPosGlobal, fifoPos - 1][i] = NIChannel[p] / gain; AbortOnRTE
+                Multithread scaledChannel[fifoPosGlobal, fifoPos - 1] = NIChannel[p]; AbortOnRTE 
```

19ee4b19 (SWS: Add SWS_ProcessDATTLChannelsOnEarlyAcqStop function to retrieve acq time, 2023-12-07)

- [ ] SWS_ProcessDATTLChannelsOnEarlyAcqStop should use HW_GetEffectiveADCWaveLength.

fc05066f (SWS: Improve decription of SWS_GetChannelGains, how channel gains are applied, 2023-12-07)

Good.

66c9b73c (TP: Add calculation of AD/DA channel dependent properties, 2023-12-05)

- [ ] This needs to be moved earlier as previous commits where already using the new elements.

b7dcaa0f (SWS: Move sweep splitting after EP_WriteEpochInfoIntoSweepSettings, ED_createWaveNoteTags, 2023-12-05)

- [ ] Missing justification.

6976c914 (SWS: SWS_ProcessDATTLChannelsOnEarlyAcqStop add sanity check for AD data end, 2023-12-05)

- [ ] Should be part of the commit introducing SWS_ProcessDATTLChannelsOnEarlyAcqStop.

77e6d9bf (ED: Do no add epochs information to sweep wave note, 2023-10-26)

Good.

5b47a82f (AB: Adapt AnalysisBrowser loading sweeps from IgorFile, 2023-12-05)

- [ ] Please raise ANALYSIS_BROWSER_SUPP_VERSION and EXPERIMENT_VERSION so that old
      MIES versions can properly complain at new pxp files. This is used in AB_HasCompatibleVersion.

- [ ] AB_LoadSweepFromIgor seems to be doing part of the internals of
      ResolveSweepChannel. Can we have a common function doing the internals?

d25abd49 (Util: Adapt RecreateSweepWaveFromBackupAndLBN and AddToSweepWave for Sutter, 2023-12-01)

- [ ] The commit message does not need to mention Sutter. We have changed the sweep
wave format so this is reason enough.

19a149d0 (AF: Adapt V3 Structure and AFM_CallAnalysisFunctions setup, 2023-12-07)

- [ ] Missing documentation for AFH_GetFifoInstimsettime

``
+                WAVE channelDA = scaledDataWave[0]
+                sampleIntDA = DimDelta(channelDA, ROWS)
+                WAVE config = GetDAQConfigWave(device)
+                WAVE channelAD = scaledDataWave[GetFirstADCChannelIndex(config)]
+                sampleIntAD = DimDelta(channelAD, ROWS)
```

- [ ] Can we have a generic function returning [sampIntDA, sampIntADC] with MRS for both sweepwave and scaleddatawave? And then use it in AFM_CallAnalysisFunctions?

- [ ] Unrelated change to PSQ_CreateOverrideResults

```
+    /// last valid row index for DA channels in `rawDAQWave` which will be filled with data at the
+    /// end of DAQ. The total number of rows in `rawDAQWave` might be higher
+    /// due to alignment requirements of the data acquisition hardware (e.g. ITC).
+    ///
+    /// Always `NaN` for #PRE_DAQ_EVENT/#PRE_SET_EVENT events.
+    variable lastValidRowIndexDA
```

- [ ] I thought we prefilled DA data nowadays?

```
+    /// sample interval of AD/TTL channel(s) in ms
+    variable sampleIntervalAD
```

- [ ] Don't mention TTL channels here, we don't use analysis functions for TTL data
(yet). Same for lastKnownRowIndexAD.

d14bf8ac (AF: Adaptations MultiPatchSeq, PatchSeq, 2023-12-05)

- [ ] PSQ_CreateOverrideResults has commented out code.

Rest looks good.

0c79ae89 (NWB: Convert text sweep waves to WaveRef for NWB Saving, 2023-11-30)

NWB_ASYNC_Worker: 
- [ ] Why do we copy s.DAQDatawave here?
- [ ] The assertion should also be in NWB_ASYNC_DeserializeStruct.

- [ ] Can we add some documentation to NWBAsyncParameters.DAQDatawave to say what the format is?

aac9cc3e (Adapt Sweep Reconstruction Test to new text wave format, 2023-11-30)
fdd6b858 (Tests: Reset override Results for AF tests properly, 2023-12-07)
Good

f8c787c7 (Tests: AF determine sweep lengths with new sweep format, 2023-11-24)
5312717b (Tests: UserAnalysisFunctions changes, 2023-11-22)
df92f701 (Tests: Adapted test for analysisfunction help text, 2023-11-23)

Okay

b54f336e (Tests: UTF_TestPulseAndTPDuringDAQ changes, 2023-11-22)

- [ ] A couple of words more like 

Tests: Adapt UTF_TestPulseAndTPDuringDAQ.ipf for new sweep wave text format.
If you reference a file please also add the file suffix so that you can easily
jump into it when viewing the commit message.

c8133c27 (Tests: UTF_TrackSweepCounts changes, 2023-11-22)

- [ ] Same comment as for b54f336e.

7c2a0e0d (Tests: Adapt UTF_Epochs.ipf, 2023-11-23)

Good.

83453e92 (Tests: Adapt UTF_BasicHardwareTests.ipf, 2023-11-23)

Good.

cce7ae51 (Tests: Adapt UTF_HelperFunctions, 2023-11-23)

- [ ] Missing .ipf suffix.

0a359af2 (Tests: Adapt UTF_SweepFormula tests, 2023-11-24)

- [ ] Missing .ipf suffix.

db4532ba (Tests: Adapt calculation of fifoPos for fifoStuck test, 2023-12-07)

- [ ] Please mention for what we adapt here.

fe652ee5 (Tests: Adapt PSX Tests, 2023-11-24)

General:
- [ ] The commit introducing TextSweepToWaveRef should add documentation to the
  function. The use case is probably to create something self-contained?
  The docu should also say if I get a copy of the channel data or not.
- [ ] Every commit must compile
- [ ] Is it now ensured that, after DAQ, every call to GetSweepWave will return a new
  style text wave? If yes that function should document the text wave format,
  and also mention ResolveSweepChannel to get the single channel data.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Comment by MichaelHuth** [comment]
For DC:

> is correct but can use the newly added HW_GetEffectiveADCWaveLength/HW_GetEffectiveDACWaveLength instead?

In the quoted code the sampleInterval is determined, not the wave length.

**Comment by t-b** [comment]
@MichaelHuth Thanks for the quick turnaround!

**Comment by t-b** [comment]
Buggy _bak files. I also used the "Restore" button from the Databrowser.
[HardwareBasic-sweep-format-text-bug-with-bak-waves.zip](https://github.com/AllenInstitute/MIES/files/13650928/HardwareBasic-sweep-format-text-bug-with-bak-waves.zip)

**Comment by t-b** [comment]
Review round 2:

- [ ] TP during DAQ with power spectrum is broken. Fix needs also a test
			`Redimension/N=(tpLength, numADCs) tpOsciForPowerSpectrum` in DC_MakeHelperWaves looks fishy.

e945604d (Util: Adapt utility functions to new sweep format, 2023-12-13)

- [ ] Add a new historic data test to check that UpgradeSweepWave works as
      expected. This can also check that all expected preUpgrade and backup waves exist.
      If needed add more tests so that we have full coverage of UpgradeSweepWave
- [ ] SplitAndUpgradeSweep has suprising behaviour as the wave upgrade depends
      on targetDFR being free or not. I think the upgrade should be determined via a
      flag `doUpgrade` like `createBackup`. And upgrading should also require `createbackup` == 1.

Nice documentation for GetSweepWave!

1136571b (SWS: Improve decription of SWS_GetChannelGains, how channel gains are applied, 2023-12-07)
- [ ] s/decription/description
- [ ] s/calculcation/calculation

I've rebased and fixed conflicts. I've also pushed one fixup commit to handle the removed CreateFakeDataBrowserWindow. I also played around with NWB export and could not reproduce the bug which required the duplicate in NWB_ASYNC_Worker. I therefore added a commit to remove it. Let's see what CI says.

**Comment by t-b** [comment]
LGTM!

**Review by t-b — APPROVED** [review]

**Pull request merged**
