### PR TITLE
XOPS-IP9-64bit/itcXOP2-64.xop: Update it

### PR DESCRIPTION
**Pull request by t-b**
- [x] Needs https://github.com/AllenInstitute/MIES/pull/1396 merged
- [x] HW_ITC_HandleReturnValues: ITCXOPError < 10000 are from IP and can be stringified with GetErrMessage

Upstream version: a4963f95 (Merge pull request #21 from AllenInstitute/bugfix/initialize-return-values, 2022-05-26)

### CODE REVIEW

**Comment by t-b** [comment]
Another thing this PR does, is checking the ITCXOP version in check installation. The ITC XOP finally outputs its repo commit hash.

**Comment by timjarsky** [comment]
@t-b see ITC1600 test results in Slack

**Comment by t-b** [comment]
`runwithOpts(testcase = "MD1_RA0_I0_L0_BKG_1")` fails with ITC18USB.

**Comment by t-b** [comment]
@timjarsky Please try again. I found the issue why this was not working as intended. See https://github.com/AllenInstitute/ITCXOP2/pull/23.

This does not yet have the DSP timeout fixes.

**Comment by t-b** [comment]
@timjarsky I've fixed it again. This is an IP upstream bug I've uncovered...

In your shoes I would wait until CI testing with ITC hardware has finished, before starting the ITC1600 tests.

**Pull request merged**
