### PR TITLE
fix for uninstallation of admin installation as user.

### PR DESCRIPTION
**Pull request by MichaelHuth**
should fix: https://github.com/AllenInstitute/MIES/issues/186

Previously the uninstallation check onyl checked vs same privilege
installation. 
Now always user and admin installations are checked, which means that in the worst case the uninstaller is run twice (for user and admin).

If an admin installation is present and a user tries to install, he gets
a suitable message prior aborting installation.

In silent mode the installation is silently aborted in that case.

As already before: If an admin installs for All Users it is NOT checked if any user on the system has an active user installation of MIES.

### CODE REVIEW

**Comment by timjarsky** [comment]
@MichaelHuth Is there a windows folder that is accessible to all users? Can we create one? If yes, could we place a file in the folder that records the type of MIES installation?

**Comment by t-b** [comment]
@timjarsky The "windows way" of doing that kind of thing would be do write something in the registry and then the user could see that e.g. in `SystemControl/Programs/Add/Remove programs`. Does that sound useful?

**Comment by timjarsky** [comment]
@t-b Yes; I guess I might have misunderstood how registry access limitations @MichaelHuth mentioned[1] were going to limit our ability to detect all installation types.

[1] If a user installs I can try to check if an admin installation is present. If the user has the rights to read the appropriate registry keys.

**Comment by t-b** [comment]
@timjarsky Good point. Well investigate the registry key access conditions and fallback to a file solution then.

**Comment by t-b** [comment]
ShellLink plugin: https://nsis.sourceforge.io/ShellLink_plug-in

**Comment by MichaelHuth** [comment]
I have patched the Shelllink plugin used by NSIS to allow retrieving link targets from admin written lnk files.

**Comment by timjarsky** [comment]
@t-b How does one go about getting the installer for this (or any) PR?

**Comment by t-b** [comment]
@timjarsky 

Scroll down to the "Checks" element. And then you see

grafik

and there as soon as "Compilation of release package" has a details element, this will bring you to bamboo which will have the usual artefacts.

**Pull request merged**
