### PR TITLE
Ping website

### PR DESCRIPTION
**Pull request by MichaelHuth**
- only run once per day, not in CI
- Uploads Igor Version incl. BUILD number, Hardware Device List, MIES Version
- Added to StartOrNewHook

close https://github.com/AllenInstitute/MIES/issues/197

### CODE REVIEW

**Comment by t-b** [comment]
Review:

a77bf3ae (Add userping entries to package settings, 2023-06-01)

Jeep.

e6c97167 (Add dynamic menu entry to switch daily ping, 2023-06-01)

MIES_PackageSettings.ipf is meant for generic package management. Therefore all functions in there don't do MIES specific stuff. I therefore think that PS_SwitchUserPingSetting() needs to be in `MIES_MIESUtilities.ipf` as `UpgradeSettings` does also live there. Or we create a new file with MIES specific package settings functions.

934bcd4b (PS: Add Setter/Getter function for upload ping properties, 2023-06-01)

same comment as previous commit.

ea14b87f (CONST: Add SECONDS_PER_DAY constant, 2023-06-01)

Fine.

6b86bd3a (Add UploadPingDaily functionality, 2023-06-01)

UploadPingDaily uses two versions of the current timepoint `now` and `currentTS`. PS_SetUserPingTimestamp should probably accept `now`.

The uploaded entries should be more structured. So instead of multiple files, version.txt should be kept, upload one JSON formatted file. DAP_GetDACDeviceList is also not the right function to call as it does call `DAP_SuggestIssueForAdditionalNIHardware()` if it could not find any hardware. Instead call DAP_GetITCDeviceList/DAP_GetNIDeviceList.

Why do you use `isBinary = 1`?

bbc31ead (PHP: Add saving of user IP in php upload script, 2023-06-01)

Code looks good. I've also test it, and it works.

I have not found the implementation for the checked todo:

> Add JSON config setting to turn on/off

**Comment by MichaelHuth** [comment]
> Why do you use `isBinary = 1`?

I used the same setting as for the logfile upload. I think it is not required here though.

**Comment by t-b** [comment]
> > I have not found the implementation for the checked todo:
> > > Add JSON config setting to turn on/off
> 
> It is added in [a77bf3a](https://github.com/AllenInstitute/MIES/commit/a77bf3ae46fa59c86a269932f2cf14c0719784da)

- I meant **JSON config** not **Package settings**
- Can UploadPing structure the sent data even more? Have `"DAQHardwareDevices": {"NI" : []", "ITC"}` and also use separate objects for IgorInfo(0) and IgorInfo(3). Also we want to not have any igor style KV pairs in the sent json.

**Comment by t-b** [comment]
Add to json config as global package settings:

```
        "Global Package Settings": {
          "userping": {
            "enabled": true
          }
        }

```

(same level as Position MCCs), write default with true via CONF_DefaultSettings(). On new User

**Review by t-b — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth The menu option and the print outs still say "Daily". Otherwise looks good!

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
I'v deployed the new version of the upload script.

**Pull request merged**
