### PR TITLE
GetSweepsWithSetting: Don't treat textwaves like numeric waves

### LINKED ISSUE #883: Stimulus sets occasionally missing in DataBrowser Dashboard
The Dashboard in the DataBrowser will occasionally not display some stimsets or their status in the dashboard after they have been collected. I will upload a few example experiments (H21.06.352.11.52.01.01.pxp, H21.06.352.11.52.01.02.pxp, and H21.06.352.11.52.01.03) that demonstrate this issue to the byte-physics ftp server for reference. H21.06.352.11.52.01.01 is missing the X1PS_SubThresh stimlus set, H21.06.352.11.52.01.02 is missing X1PS_SubThresh, X2LP_Search, and X3LP_Rheo, while H21.06.352.11.52.01.03 is missing X1PS_SubThresh and X2LP_Search stimulus sets, even though these stimulus sets were collected in all 3 experiment files. This is an issue because rig users need to be able to verify whether these stimulus sets passed or failed the qc criteria.

### PR DESCRIPTION
**Pull request by t-b**
Close #883.

@ru57y34nn This should fix your issue. Please test.
@timjarsky This fix is straight from main.

### CODE REVIEW

**Comment by timjarsky** [comment]
> Close #883.
> 
> @ru57y34nn This should fix your issue. Please test.
> @timjarsky This fix is straight from main.

@t-b will this fix apply to the old experiments? - i.e., can we test by opening an old experiment?

**Comment by t-b** [comment]
@timjarsky Yes, it is a pure display issue.

**Comment by t-b** [comment]
And the bug is only present in the 2.1 release branch.

**Review by ru57y34nn — APPROVED** [review]
Looks good, thanks for the quick turn around on this issue.

**Pull request merged**
