### PR TITLE
Fix power spectrum display

### LINKED ISSUE #441: TP Powerspectrum is broken
The reason is the recent switch to initial NaN values in 1f2ce19b (DC_InitDataHoldingWave: Initialize all channels to NaN, 2019-10-22) .

The following code is a MWE for what we do in `SCOPE_UpdatePowerSpectrum`.

```igorpro
Function Dostuff()

	Make/o/N=(128, 2) data = p

	data[][0] = NaN

	Make/O output = NaN
	FFT/DEST=output/OUT=4/COLS data
	Wavestats output
End
````

An issue has been filed with WM to see how it can be fixed on their end.

### PR DESCRIPTION
**Pull request by t-b**
Close #441.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b The scope window may be showing the same data on different headstages. I can demo.

**Comment by t-b** [comment]
@timjarsky Thinks, I can also reproduce here now.

**Comment by t-b** [comment]
@timjarsky Should be fixed. Please try again.

**Comment by timjarsky** [comment]
@t-b if power spectrum is activated while TP is running bad stuff happens:
  !!! Assertion FAILED !!!
  Message: "ReadOut function TP_ROAnalysis aborted with: a wave read;index out of range"
  ################################
  Stacktrace:
TPM_BkrdTPFuncMD(...)#L305 [MIES_TestPulse_Multi.ipf]
SCOPE_UpdateOscilloscopeData(...)#L615 [MIES_Oscilloscope.ipf]
ASYNC_ThreadReadOut(...)#L239 [MIES_Async.ipf]
  ################################

**Comment by timjarsky** [comment]
@t-b headstage channels are fixed. Thanks.

**Comment by t-b** [comment]
@timjarsky Should we disbable the power spectrum button or stop and restart tp?

**Comment by timjarsky** [comment]
> @timjarsky Should we disbable the power spectrum button or stop and restart tp?

@t-b I favor stop/start. Would you dis/agree?

**Comment by t-b** [comment]
@timjarsky I agree!

**Comment by t-b** [comment]
@timjarsky Done.

**Pull request merged**
