### PR TITLE
Bugfix/1345 same optionality for all analysis function parameters

### PR DESCRIPTION
**Pull request by t-b**
So I've written a test to check that all parameters have the same optionality.

In the following I've listed the differences:

```
"DAScaleModifier":
  - Optional: PSQ_DaScale, PSQ_Chirp
  - Required: SC_SpikeControl

"DAScaleOperator":
  - Optional: PSQ_Chirp
  - Required: SC_SpikeControl

BaselineRMSShortThreshold:
BaselineRMSLongThreshold:
  - Required: PSQ_PipetteInBath, PSQ_SealEvaluation
  - Optional: PSQ_DaScale, PSQ_SquarePulse, PSQ_Rheobase, PSQ_Ramp, PSQ_Chirp

NumberOfFailedSweeps:
- Optional: PSQ_Chirp
- Required: PSQ_PipetteInBath, PSQ_SealEvaluation


SamplingMultiplier:
- Optional: PSQ_PipetteInBath, PSQ_SealEvaluation, PSQ_Chirp
- Required: MSQ_FastRheoEst, PSQ_DaScale, PSQ_SquarePulse, PSQ_Rheobase, PSQ_Ramp
```

@timjarsky How should I unify them? All required, all optional?

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b sealThreshold for PSQ_SealEvaluation is required but also specifies a default value of 1GΩ. Let's make it optional.

image

**Comment by timjarsky** [comment]
```
> "DAScaleModifier":
>   - Optional: PSQ_DaScale, PSQ_Chirp
>   - Required: SC_SpikeControl
```
no change

```
> "DAScaleOperator":
>   - Optional: PSQ_Chirp
>   - Required: SC_SpikeControl
```
 no change

@t-b 
```
> BaselineRMSShortThreshold:
> BaselineRMSLongThreshold:
>   - Required: PSQ_PipetteInBath, PSQ_SealEvaluation
>   - Optional: PSQ_DaScale, PSQ_SquarePulse, PSQ_Rheobase, PSQ_Ramp, PSQ_Chirp
```
optional

```
> NumberOfFailedSweeps:
> - Optional: PSQ_Chirp
> - Required: PSQ_PipetteInBath, PSQ_SealEvaluation
```
Required

```
> SamplingMultiplier:
> - Optional: PSQ_PipetteInBath, PSQ_SealEvaluation, PSQ_Chirp
> - Required: MSQ_FastRheoEst, PSQ_DaScale, PSQ_SquarePulse, PSQ_Rheobase, PSQ_Ramp
```
Required

**Comment by t-b** [comment]
Thanks for the list! I've fixed thise.

But we have some new ones:

```
BaselineChunkLength:
- Optional: PSQ_SealEvaluation
- Required: PSQ_TrueRestingMembranePotential

FailedLevel:
- Optional: PSQ_Chirp
- Required: PSQ_TrueRestingMembranePotential
```

**Comment by t-b** [comment]
> sealThreshold for PSQ_SealEvaluation is required but also specifies a default value of 1GΩ. Let's make it optional.
Done.

**Comment by t-b** [comment]
BaselineChunkLength -> optional

FailedLevel -> no change

**Comment by t-b** [comment]
Ready.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
