### PR TITLE
Feature/spike control enhancements

### PR DESCRIPTION
**Pull request by t-b**
- [x] `DAP_GetHighestActiveHeadstage` is buggy with only VC headstages as the analysis function is still exectuted.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b are you asking if we should adapt SC_SpikePositionsCalcDetail to also evaluate the latest spike?

**Comment by t-b** [comment]
@timjarsky 
> Are you asking if we should adapt SC_SpikePositionsCalcDetail to also evaluate the latest spike?

Yes!

**Comment by timjarsky** [comment]
@t-b with one channel in V-clamp I'm seeing 	ASSERT(!cmpstr(DAunit, "pA"), "Unexpected DA Unit")


```
  !!! Assertion FAILED !!!
  Message: "Unexpected DA Unit"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L105 [MIES_DataAcquisition_Multi.ipf]
DQM_StopDataAcq(...)#L359 [MIES_DataAcquisition_Multi.ipf]
SWS_SaveAcquiredData(...)#L63 [MIES_SweepSaving.ipf]
AFM_CallAnalysisFunctions(...)#L129 [MIES_AnalysisFunctionManagement.ipf]
SC_SpikeControl(...)#L1080 [MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf]
SC_ReactToQCFailures(...)#L785 [MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf]
SC_SetDAScaleModOp(...)#L700 [MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf]
SetDAScale(...)#L924 [MIES_AnalysisFunctions.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-04-01T16:27:01-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [52]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2021_04_01_161820 (Packed)
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-896-gb6ef1a403
Date and time of last commit: 2021-02-23T22:15:52+01:00
Submodule status: 
160000 513e97117a6e3ddad22d9299dae817c59ecbd0ea 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 a184fae75390ce75149d22313397bd5d82d5189c 0	Packages/doc/doxygen-filter-ipf
160000 4b67466116212d042ca5c7427b51ddcb60630117 0	Packages/unit-testing
```

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@t-b fantastic!

**Pull request merged**
