### PR TITLE
Bugfix: Fix find level "level" threshold for PSQ_Ramp and NI hardware

### PR DESCRIPTION
**Pull request by t-b**
@MichaelHuth Can you take a look if my changes make sense especially wrt to NI hardware?

### CODE REVIEW

**Comment by MichaelHuth** [comment]
Looks good. Some minor comment:
In https://github.com/AllenInstitute/MIES/pull/259/commits/94e23a3debf44dac209b130df2366bda63af5203 commit msg I would add that the optional timing parameter in SWS_GetChannelGains is required.

and

In the docu for the split before / after DAQ gains I would add that the idea is that 
before_gain * data(before_DAQ) == after_gain *data(after_DAQ)

**Comment by t-b** [comment]
@MichaelHuth Thx. Will add the requested changes.

**Comment by t-b** [comment]
@MichaelHuth Done.

**Comment by t-b** [comment]
@timjarsky Ready for review.

**Pull request merged**
