### PR TITLE
Feature support for NWBv2

### LINKED ISSUE #22: Add support for exporting into NWBv2 as well
#### Cross links

https://github.com/AllenInstitute/MIES/issues/22
https://github.com/AllenInstitute/MIES/pull/179 (TODO list)
https://github.com/AllenInstitute/IPNWB/issues/5
https://github.com/AllenInstitute/IPNWB/pull/16

Support matrix (read/write):

Igor Pro Version \ NWB Version| v1 | v2
------------ | -------------| -------------
8 | x | x

(IP7 is not supported anymore)

Tests:
- [x] Copy UTF_NwbExportV1.ipf, adapt for V2 and test both exports in all current cases
- [x] Add validation tests using pynwb for V2 files as well
- [x] Update UTF_NwbExportV2.ipf with changes to UTF_NwbExportV1.ipf since last sync

### PR DESCRIPTION
**Pull request by t-b**
#### Cross links

https://github.com/AllenInstitute/MIES/issues/22
https://github.com/AllenInstitute/MIES/pull/179 (TODO list)
https://github.com/AllenInstitute/IPNWB/issues/5
https://github.com/AllenInstitute/IPNWB/pull/16
https://github.com/t-b/ndx-MIES/pull/1

Requires:
- https://github.com/NeurodataWithoutBorders/pynwb/pull/1146

Issues:
- https://github.com/NeurodataWithoutBorders/nwb-schema/issues/410

TODOs:
- [x] Ready to merge according to Wayne
- [x] Fix ISO8601 timezone issues
- [x] Add pynwb read tests as CI
- [x] Fix documentation building
- [x]  Test with I=0 data
- [x] Check that unassociated channels are stored correctly
- [x]  Add pynwb code for using validation via the cmdline tool
- [x]  add schema extension for all our additions
    - [x] clarify recursive folder usage with Ryan
    - [x] Add ndx-MIES repo as submodule to IPNWB 
    - [x] convert YAML files to JSON and store them as well
    - [x] Write ndx-MIES specification to NWBv2 files and check that it validates
    - [ ] add schema extension to ndx-cataloge
- [x] remove some fields which should not be there (units and scale)
- [x] add objectIDs, https://pynwb.readthedocs.io/en/latest/tutorials/general/object_id.html and https://tools.ietf.org/html/rfc4122
- [x] Wait for Wayne doing conversion tests again
- [x] Fix wrong object_id
- [x] https://github.com/hdmf-dev/hdmf/issues/354#issuecomment-630948209

Close #22.

### CODE REVIEW

**Comment by t-b** [comment]
@ukos-git Failed NWBv2 export: PXP and NWB
[HardwareTests.zip](https://github.com/AllenInstitute/MIES/files/3238008/HardwareTests.zip)

**Comment by t-b** [comment]
@ukos-git The worst bug is fixed in cf57690.
The tests still don't pass.

I think we should:
- write "PLACEHOLDER" instead of "" for unassociated AD channels (AD 2)
- Fix the stimulus_description for "DA 2"

**Comment by ukos-git** [comment]
cf57690 should be done like the others above with IPNWB#GetNWBgroupPatchClampSeries(nwbVersion)

I don't like the PLACEHOLDER approach in general.

If stimulus_description is mandatory, it should go to write single channel.

**Comment by t-b** [comment]
@ukos-git Rebased to incorporate the sync-with-private-repo branch correctly.

**Comment by t-b** [comment]
@ukos-git 
> I don't like the PLACEHOLDER approach in general.

The attribute is mandatory but for unassociated AD channels we don't have  a stimset. Don't you think that "PLACEHOLDER" is better than empty?

**Comment by ukos-git** [comment]
@t-b further changes to hdmf are required to read the json specifications from our NWB file. Same problem as before.

our format with simple dataspace
```
{
DATASET "/specifications/core/2.0.1/namespace" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_UTF8;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
   DATA {
   (0): "…"
   }
}
}
```

crashes here

https://github.com/hdmf-dev/hdmf/blob/8ddc8574123853215a4d6c43d27bd2aec908017d/src/hdmf/backends/hdf5/h5_utils.py#L171-L174

**Comment by ukos-git** [comment]
> @ukos-git Failed NWBv2 export: PXP and NWB

Fails at the `IGORWaveNote` entry of the `acquisition` wave.

**Comment by t-b** [comment]
@ukos-git Is the latest IPNWB version pushed?

I'm getting here:

```
From https://github.com/AllenInstitute/IPNWB
 + 44b9cd7...7315b98 feature/nwbv2 -> origin/feature/nwbv2  (forced update)
error: Server does not allow request for unadvertised object 13da2c145a4cbc945f972808050ee0eebdcef74c
```

**Comment by ukos-git** [comment]
I guess, you refer to a339bcd33408cfb1a15373faf6054ed5b295b79d?

**Comment by t-b** [comment]
> 
> I guess, you refer to [a339bcd](https://github.com/AllenInstitute/MIES/commit/a339bcd33408cfb1a15373faf6054ed5b295b79d). Rebase was necessary due to the huge amount of "changes" and "wip" commit messages. We should probably squash all commits per MR and avoid force pushing, as github looses all commentary etc on force pushes.

The submodule commit referenced in the parent repo needs to be available as top commit in one of the branches (in git lingo it needs to be the tip of a branch). This is what the error message is complaining about.

Yes github is still not able to handle force pushes and comments properly. That is the reason I'm mainly commenting with non-commit comments.

**Comment by ukos-git** [comment]
I wanted to say, that you will probably have to do a hard reset on your MIES repo
```bash
git ls-tree feature/nwbv2 IPNWB
160000 commit 7315b98ac805b974a18efe5e5dae0bc131106259	IPNWB
```
That branch is over at IPNWB, top commit of branch feature/nwbv2

https://github.com/AllenInstitute/IPNWB/commits/feature/nwbv2

**Comment by ukos-git** [comment]
should I squash the commits?

**Comment by ukos-git** [comment]
```console
Traceback (most recent call last):
  File "src/pynwb/validate.py", line 117, in <module>
    main()
  File "src/pynwb/validate.py", line 73, in main
    namespaces = HDF5IO.load_namespaces(catalog, path).keys()
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 99, in load_namespaces
    d.update(namespace_catalog.load_namespaces('namespace', reader=reader))
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/utils.py", line 388, in func_call
    return func(self, **parsed['args'])
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/spec/namespace.py", line 447, in load_namespaces
    namespaces = reader.read_namespace(namespace_path)
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/backends/hdf5/h5_utils.py", line 172, in read_namespace
    ret = self.__read(ns_path)
  File "/home/matthias/Documents/Projects/hdmf/src/hdmf/backends/hdf5/h5_utils.py", line 165, in __read
    d = json.loads(s)
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not ndarray
```

**Comment by t-b** [comment]
@ukos-git if you use the latest ipnwb branches the validation against the cached namespace results in the same errors as against the pynwb spec.

**Comment by ukos-git** [comment]
Do you mean the two 64bit integer errors? - I used the ipnwb yaml files without changing the spec but we can not write 64bit integers with current HDF5 XOP.

So it is somewhat expected that cached spec and plain pynwb spec give the same errors.

**Comment by t-b** [comment]
@ukos-git Yes these errors are expected. But I plan to tweak the pynwb yaml spec so that our files are compliant as well.

**Comment by t-b** [comment]
@ukos-git I've looked into the stimset storage for the unassociated channels. For ADC we don't have one anyway. So only DAC needs some thinking.
And I think the current behaviour in master is correct. Unassociated channels are stored as plain TimeSeries and as that they have, especially for v2, no associated stimset.

**Comment by t-b** [comment]
Rebased onto latest master.

**Comment by t-b** [comment]
@ukos-git Please rebase against master as the test infrastructure has changed too much to be able to complete.

**Comment by t-b** [comment]
Documentation issues:

```
$ ./build-documentation.sh
Start building the documentation
Errors building the documentation
Doxygen says:
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:127: warning: Found unknown command `\locationID'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:127: warning: Found unknown command `\locationID'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:127: warning: Found unknown command `\locationID'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Reader.ipf:15: warning: The following parameters of IPNWB::ReadDevices(variable fileID, variable version) are not documented:
  parameter 'version'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:127: warning: Found unknown command `\locationID'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:127: warning: argument 'groupID' of command @param is not found in the argument list of IPNWB::AddDevice(variable locationID, string name, variable version, string description)
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:135: warning: The following parameters of IPNWB::AddDevice(variable locationID, string name, variable version, string description) are not documented:
  parameter 'version'
  parameter 'description'
E:/projekte/mies-igor/Packages/IPNWB/IPNWB_Writer.ipf:338: warning: The following parameters of IPNWB::WriteSingleChannel(variable locationID, string path, variable version, WriteChannelParams *p, TimeSeriesProperties *tsp, variable compressionMode=defaultValue) are not documented:
  parameter 'version'
E:/projekte/mies-igor/Packages/MIES/MIES_NeuroDataWithoutBorders.ipf:437: warning: The following parameters of NWB_ExportWithDialog(variable exportType, variable nwbVersion=defaultValue) are not documented:
  parameter 'nwbVersion'
```

**Comment by t-b** [comment]
Sent out new installer from e45e3be2 (Add Unit Tests for ParseISO8601TimeStamp, 2019-12-20).

**Comment by ukos-git** [comment]
I have updated the specs from our beta state to the officially tagged releases

- 2.0.1
- 2.1.0
- 2.2.0

Unfortunately, the validator of pynwb is stuck in current master. I have validated against a modified 2.1.0 version with the new data types for `sweep_number` and `colnames`.

**Comment by t-b** [comment]
@ukos-git 

Script to validate and read NWBv2 files with pynwb.
```
from pynwb import NWBHDF5IO, validate
import hdmf
import numpy as np

name = 'MIES-e45e3be2-NWBv2.nwb'

with NWBHDF5IO(name, 'r') as io:
    print(validate(io))
    nwbfile = io.read()

    for key in nwb.acquisition:
        acquisition = nwb.get_acquisition(key)
        print(acquisition)

    for key in nwb.stimulus:
        stimulus = nwb.get_stimulus(key)
        print(stimulus)
```

**Comment by t-b** [comment]
@ukos-git  I=0 data: 
[IEqualZeroData.zip](https://github.com/AllenInstitute/MIES/files/4078504/IEqualZeroData.zip)

@ukos-git Could you revert (as in git revert) the documentation build fixes? It currently fails CI.

**Comment by t-b** [comment]
@ukos-git The CI server's linux is too old for docker. An upgrade is planned but not in january. Can we go back to the plain scripts using sphinx 1.8.3?

**Comment by ukos-git** [comment]
docker is not a requirement for the current build.

The pip install of sphinx should be released from a fixated version<2 and updated to a more recent one to build with sphinx>2

If we explicitly want to build with sphinx 1.8 then the commit for introducing sphinx>2 could get reverted. It only needs to radd the sphinxcontrib-images in the conf.py file.

**Comment by t-b** [comment]
@ukos-git Sphinx upgrade is handled separately in #198.

**Comment by t-b** [comment]
build-bot-thomas-says:
```

Collapse | Failed | ISO8601_teststamps:2                                 ISO8601_teststamps:2 in UTF_Utils.ipf (4)                                 History | < 1 sec
-- | -- | -- | --
FAIL: nan == nan: is true  Assertion "REQUIRE_NEQ_VAR(NaN, secondsSinceIgorEpoch)" failed in line 3432, procedure "UTF_Utils.ipf"
```

**Comment by ukos-git** [comment]
> build-bot-thomas-says:
> 
> ```
> 
> Collapse | Failed | ISO8601_teststamps:2                                 ISO8601_teststamps:2 in UTF_Utils.ipf (4)                                 History | < 1 sec
> -- | -- | -- | --
> FAIL: nan == nan: is true  Assertion "REQUIRE_NEQ_VAR(NaN, secondsSinceIgorEpoch)" failed in line 3432, procedure "UTF_Utils.ipf"
> ```

runs fine locally:

```
•RunTest("UTF_Utils.ipf", testCase = "ISO8601_teststamps", allowDebug = 1)
  Start of test "Unnamed"
  Entering test suite "UTF_Utils.ipf"
  Entering test case "ISO8601_teststamps:0"
  Leaving test case "ISO8601_teststamps:0"
  Entering test case "ISO8601_teststamps:1"
  Leaving test case "ISO8601_teststamps:1"
  Entering test case "ISO8601_teststamps:2"
  Leaving test case "ISO8601_teststamps:2"
  Entering test case "ISO8601_teststamps:3"
  Leaving test case "ISO8601_teststamps:3"
  Entering test case "ISO8601_teststamps:4"
  Leaving test case "ISO8601_teststamps:4"
  Entering test case "ISO8601_teststamps:5"
  Leaving test case "ISO8601_teststamps:5"
  Entering test case "ISO8601_teststamps:6"
  Leaving test case "ISO8601_teststamps:6"
  Entering test case "ISO8601_teststamps:7"
  Leaving test case "ISO8601_teststamps:7"
  Entering test case "ISO8601_teststamps:8"
  Leaving test case "ISO8601_teststamps:8"
  Entering test case "ISO8601_teststamps:9"
  Leaving test case "ISO8601_teststamps:9"
  Entering test case "ISO8601_teststamps:10"
  Leaving test case "ISO8601_teststamps:10"
  Finished with no errors
  Leaving test suite "UTF_Utils.ipf"
  Test finished with no errors
  End of test "Unnamed"
```

does the build-bot have a local timezone?
`GetIso8601TimeStamp(localTimeZone = 1)` should not return `NaN`

**Comment by ukos-git** [comment]
> Script to validate and read NWBv2 files with pynwb.

using [the new hdmf](https://github.com/hdmf-dev/hdmf/pull/269), IP files can finally be read with `DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }` datasets as strings.

nwb schema needs to be updated in pynw to 2.2.0

**Comment by t-b** [comment]
@timjarsky Ready to merge according to Wayne.

**Pull request merged**
