### PR TITLE
Feature/1692 Revise primitive operations in SF parser and sign handling

### PR DESCRIPTION
**Pull request by MichaelHuth**
- primitive operations are now always inserted as two element arrays into the JSON
- improved handling of signed numbers, especially when the formula contains spaces
- added support for signs in front of operations and arrays
- error out if * or / is in front of terms
- fix several jsonId leaks in parser

close https://github.com/AllenInstitute/MIES/issues/1527
required for extension of https://github.com/AllenInstitute/MIES/pull/1689

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth Is that good to review?

**Comment by MichaelHuth** [comment]
Not yet, as I want to add the fix for `*1` related inputs from https://github.com/AllenInstitute/MIES/issues/1527 as well here to complete this issue.

**Comment by MichaelHuth** [comment]
@t-b Reassigned for a moment to me, as I'm still putting some refactoring in while I'm touching the parser code.

**Comment by t-b** [comment]
I've played around with SF formulas like

```
c = cursors(A,B)
s = select(channels(AD),sweeps())

-data($c,$s)+data($c,$s)

and

[1, -2]

and

[1, -10, -min(10, -20)]

and

[10, -10]
```

and it works as expected.

The code looks good. And coverage looks good as well.

**Review by t-b — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth Please rebase and fix conflicts.

**Review by t-b — APPROVED** [review]

**Comment by timjarsky** [comment]
@MichaelHuth 

```$d / (-5)``` and `$d / -5` doesn't work in this PR. d is a valid data formula.

**Comment by t-b** [comment]
I can reproduce that as well.

Recipe:

```
d = [0]

$d / -5

and

$d / (-5)
```

**Comment by t-b** [comment]
The "broken" division in this PR is not a regression from main. We therefore propose to merge this PR first and then fix the division at #1689.

**Pull request merged**
