### PR TITLE
SF: Shrink legend text if only sweep number changes

### PR DESCRIPTION
**Pull request by MichaelHuth**
When only sweep numbers change in the legend of the sweepformula plot then the numbers are joined in a comma separated list.
Only one line is shown in the graph legend.

close https://github.com/AllenInstitute/MIES/issues/1470

### CODE REVIEW

**Review by t-b — DISMISSED** [review]

**Comment by timjarsky** [comment]
@MichaelHuth @t-b would it be possible to insert a carriage return every 10 sweeps or something similar? 

If the sweeps are continuous could the list be abbreviated? e.g.,  1...8

**Comment by t-b** [comment]
@timjarsky Yes we can do that.

**Comment by t-b** [comment]
Needs rebase.

**Comment by t-b** [comment]
LGTM.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
Thank you!

**Pull request merged**
