### PR TITLE
Nicify the About MIES dialog

### LINKED ISSUE #454: Nicify `About MIES`
- Add clickable link to github repo
- Add some short text describing what it is

### PR DESCRIPTION
**Pull request by t-b**
- Use a formatted notebook which allows us to create clickable links
- Use a shorter vesrsion string
- Add a link which creates a new issue on github with prefilled
information

Close #454.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b nice improvement. Should we include a link to the license and/or a brief description of the license?  

https://github.com/AllenInstitute/MIES/blob/master/LICENSE

**Comment by timjarsky** [comment]
@t-b nicefy the issue reporting language:
```
- What did you do which led to the unexpected behaviour?
```

to

```
- What was MIES doing at the time of the unexpected behavior?
- Did user immediately precede the unexpected behavior?

**Comment by t-b** [comment]
@timjarsky Done.

**Comment by timjarsky** [comment]
@t-b can the size of the window be matched (made smaller) to fit the contents?

**Comment by t-b** [comment]
@timjarsky Done.

**Comment by timjarsky** [comment]
@t-b I've added to the `About MIES` notebook. Let me know what you think.

**Comment by t-b** [comment]
@timjarsky Looks good. I've fixed the initial size of the panel as it was too small and also moved the pictures into `MIES_Picture.ipf`. Will merge when CI passes.

**Pull request merged**
