### PR TITLE
SF: Support of sweeps with non-matching sampling interval and multiple ranges

### PR DESCRIPTION
**Pull request by MichaelHuth**
- adapted to plotter to handle wref waves correctly as input
  currently only the first element is considered.
- add define SWEEPFORMULA_DEBUG that enables that all data waves are stored as
  permanent waves in the working datafolder. The names are prefixed to
  indicate where the wave was created.

Within the Formula Executor the waveref waves are stored as single element
text waves. The element stores the full path to a permanent wave reference
wave. The element is prefixed to differentiate between an actual single
element text wave from e.g. a user input.
User input are returned by the FormulaExecutor as regular data waves.
If such input is encountered it is automatically converted to a wave ref
input.

Storing the data through wave ref waves offers the flexibility to store independent sweeps with distinctive ranges and meta information in the wave note.

- [x]  In plotter add different y unit handling: collect all units, remove doubles and then create a label like "unit1 / unit2 /unit3 ..." on the y-axis.
- [x] update ifn sweepformula help notebook
- [x] check issues if some are solved.
- [x] check if sweepformula is faster https://github.com/AllenInstitute/MIES/issues/1366
- [x] Warn / Assert if formula plotter should plot too many traces

close https://github.com/AllenInstitute/MIES/issues/362
close https://github.com/AllenInstitute/MIES/issues/272
close https://github.com/AllenInstitute/MIES/issues/352
close https://github.com/AllenInstitute/MIES/issues/1366

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b I added the changes we talked about in our last call. Should be good for a first review.

**Comment by t-b** [comment]
@MichaelHuth Thanks, I'll have a look.

**Comment by t-b** [comment]
I'm only focussing on using it right now.

- `[1, 2]` is a bit confusing as the legend dot looks like a third point. I would hide the legend if the description string is empty and we only have one trace.
- 
```data(
cursors(A,B),
select(channels(AD),sweeps())
) + 1```

triggers: `BUG_TS: Encountered pending RTE: 412, a wave read;An attempt was made to treat a text wave as if it were a numeric wave.`
This does not work in main either as it swallows the other graphs there, but at least I don't expect an RTE.

**Comment by MichaelHuth** [comment]
@t-b I think thats good now for some feedback.

**Comment by t-b** [comment]
@MichaelHuth Thanks, I'll take a look in the next days.

**Comment by t-b** [comment]
Partial review:

- [ ] Once you rebase, you can remove `SF_GetReducedColumn` and `SF_ReCreateOldSweepsChannelLayout`
- [ ] I've opened #1418 with a very small subset of the changes here. This should allow us to split the review.
- [ ] Would it be possible to have no trailing zeros when having `sweeps` as x axis in the plot (ModifyGraph zapTZ(bottom) maybe)?
- [ ] Findlevel returns a single point only:

FTP Data : AnalysisBrowser-SpeedTest/Pvalb-IRES-Cre%3BAi14-201791.06.01.nwb

```
findlevel(data(
cursors(A,B),
select(channels(AD),sweeps())
), -10)
```

A fix for that also needs a test.

- [ ] `log(sweeps())` does not work. Documentation says that the input is returned unchanged. Needs test.
- [ ] 	Enable AD and DA channels and do

```
data(
[200, 300],
select(channels(), sweeps())
)
```

The y axis-unit is wrong. Needs test.

- [ ] store throws away channel information|

```
store("abcd",data(
[200, 300],
select(channels(AD), sweeps())
))
```

creates a red curve

- [ ] merge operation is still mentioned in the ifn files
- [ ] Please go through the issues labelled SweepFormula and check which issues this PR now resolves and update the close statement. Feel free to split issues if we resolve only parts of them here.

I'll continue with the review next week.

@MichaelHuth I'd say this is looking good already. @timjarsky You can therefore also start with playing around.

**Comment by MichaelHuth** [comment]
> Enable AD and DA channels and do
> The y axis-unit is wrong. Needs test.

The thing here is, that we do not have a handling of different units yet. Currently it has several indepentent sweep data waves, with e.g. "mV" and another with "pA" y-unit. With AppendTraceToGraph it uses the label of the first appended trace wave.

How should this be solved?

I could collect all units, remove doubles and then create a label like "unit1 / unit2 /unit3 ..."?

**Comment by MichaelHuth** [comment]
- [ ]  In plotter add different y unit handling: collect all units, remove doubles and then create a label like "unit1 / unit2 /unit3 ..." on the y-axis.

**Comment by MichaelHuth** [comment]
> @MichaelHuth Is #352 also resolved by this PR?

It is somewhat operation dependent, but yes. I added it to the initial comment.

**Comment by t-b** [comment]
@MichaelHuth Documentation build error:
```
Errors building the documentation
Doxygen says:
/home/ci/Packages/MIES/MIES_JSONWaveNotes.ipf:10: warning: multiple use of section label 'WaveNoteJSONSupportConstants' while adding anchor, (first occurrence: /home/ci/Packages/MIES/MIES_Constants.ipf, line 1872)
```

**Comment by t-b** [comment]
Review part two:

I ran UTF_SweepFormula.ipf (RunAllTests). The coverage went from 73.2% to 77.3%. Nice! Attaching it here [MIES_SweepFormula_1372.zip](https://github.com/AllenInstitute/MIES/files/9113748/MIES_SweepFormula_1372.zip)

- [ ] The text wave part should be covered as well.

```
0593|00001482|________|________|static Function SF_PlaceSubArrayAt(WAVE/Z out, WAVE/Z subArray, variable index)

0594|________|________|________|

0595|00001482|00000741|00000741|    if(!WaveExists(out))

0596|00000741|________|________|        return NaN

0597|00000741|________|________|    endif

0598|________|________|________|

0599|00000741|________|________|    SF_FormulaWaveScaleTransfer(subArray, out, ROWS, COLS)

0600|00000741|________|________|    SF_FormulaWaveScaleTransfer(subArray, out, COLS, LAYERS)

0601|00000741|________|________|    SF_FormulaWaveScaleTransfer(subArray, out, LAYERS, CHUNKS)

0602|00000741|________|________|    // Copy max 3d subarray to data

0603|00000741|00000000|00000741|    if(IsTextWave(out))

0604|________|________|________|        WAVE/T outT = out

0605|________|________|________|        WAVE/T subArrayT = subArray

0606|________|________|________|        Multithread outT[index][0, max(0, DimSize(subArray, ROWS) - 1)][0, max(0, DimSize(subArray, COLS) - 1)][0, max(0, DimSize(subArray, LAYERS) - 1)] = subArrayT[q][r][s]

0607|00000741|________|________|    else

0608|00000741|________|________|        Multithread out[index][0, max(0, DimSize(subArray, ROWS) - 1)][0, max(0, DimSize(subArray, COLS) - 1)][0, max(0, DimSize(subArray, LAYERS) - 1)] = subArray[q][r][s]

0609|00000741|________|________|    endif

0610|00001482|________|________|End
```

- [ ] I would also think that all code paths in SF_FormulaExecutor should be covered. We obviously don't care about DEBUGGING_ENABLED.
- [ ] Full coverage for SF_GetArgumentTop
- [ ] SF_ParseArgument: 

```
3956|00001864|________|________|static Function/WAVE SF_ParseArgument(string win, WAVE input, string opShort)

3957|________|________|________|

3958|00001864|________|________|    string wName, tmpStr

3959|________|________|________|

3960|00001864|00001864|00000000|    if(IsTextWave(input) && DimSize(input, ROWS) == 1 && DimSize(input, COLS) == 0)

3961|00001864|________|________|        WAVE/T wvt = input

3962|00001864|00001864|00000000|        if(strsearch(wvt[0], SF_WREF_MARKER, 0) == 0)

3963|00001864|________|________|            tmpStr = wvt[0]

3964|00001864|________|________|            wName =tmpStr[strlen(SF_WREF_MARKER), Inf]

3965|00001864|________|________|            WAVE/Z out = $wName

3966|00001864|________|________|            ASSERT(WaveExists(out), "Referenced wave not found: " + wName)

3967|00001864|________|________|            return out

3968|________|________|________|        endif

3969|________|________|________|    endif

3970|________|________|________|

3971|________|________|________|    WAVE/WAVE wRef = SF_CreateSFRefWave(win, opShort + "_refFromUserInput", 1)

3972|________|________|________|#ifdef SWEEPFORMULA_DEBUG

3973|________|________|________|    DFREF dfrWork = SF_GetWorkingDF(win)

3974|________|________|________|    wName = UniqueWaveName(dfrWork, opShort + "_dataInput_")

3975|________|________|________|    Duplicate input, dfrWork:$wName

3976|________|________|________|    WAVE input = dfrWork:$wName

3977|________|________|________|#endif

3978|________|________|________|    wRef[0] = input

3979|________|________|________|

3980|________|________|________|    return wRef

3981|00001864|________|________|End
```

Can the lower part of the function be reached without having debugging enabled? If yes, please add a test.

- [ ] SF_TransferFormulaDataWaveNote/SF_GetTraceColor/SF_GetMetaDataAnnotationText should also be used at least once. If that is too much work, please file an issue.

I also played around with it some more, and works nicely!

For example the code

```
data(
cursors(A,B),
select(channels(AD3),sweeps())
)

and

min(data(
cursors(A,B),
select(channels(AD3),sweeps())
))

and

max(data(
cursors(A,B),
select(channels(AD3),sweeps())
))

and

avg(data(
cursors(A,B),
select(channels(AD3),sweeps())
))


and

avg(data(
cursors(A,B),
select(channels(AD3),sweeps())
)) + 0
```

gives

image

where the last plot shows that by adding something on data which has sweep info, the sweep info and the units are not shown anymore, as it is not accurate. Nice!!

**Comment by timjarsky** [comment]
@t-b It's nice to see the color coded traces in the SF plot
image


Will trace naming as described in https://github.com/AllenInstitute/MIES/issues/352 been implemented?
```
trace naming
I would also recommend adding dimension labels for the columns and layers so that traces can get named with sweep number and channel type/number.
```

**Comment by t-b** [comment]
- [ ] add human readable trace names
- [ ] investigate expanding naming to deeper levels
- [ ] Is multiple epoch range support possible (here or another PR?)

Data from mutliple headstages
```
data(epochs("Baseline"), select(channels(AD), sweeps))
```

**Comment by MichaelHuth** [comment]
> SF_TransferFormulaDataWaveNote/SF_GetTraceColor/SF_GetMetaDataAnnotationText

The functions are called in the SF_ButtonTest in the HardwareTests.

**Comment by MichaelHuth** [comment]
Speed improvements, values in [s] on my system:

Formula:

**min(integrate(derivative(data(
cursors(A,B),
select(channels(),sweeps(),all)
)
)))**

File: Pvalb-IRES-Cre;Ai14-201791.06.01.nwb
84 sweeps

This branch:
Formula: 2.53 - 2.71
All: 2.66 - 2.83

main:
Formula: 10.66
All: 10.68

File: 2017_09_08_094250-compressed.nwb
108 sweeps

This branch:
Formula: 0.35 - 0.42
All: 0.39 - 0.47

main:
Formula: 0.24
All: 0.25

I would say that there is some additional overhead now in this branch, especially for the nicer plotting. If there is a lot of data to process the gain can be factor  3 - 4x faster.

**Comment by t-b** [comment]
Nice! So I guess we can close the referenced issue about faster plotting with this PR.

**Comment by t-b** [comment]
LGTM.

**Comment by t-b** [comment]
@MichaelHuth a24759068065d897edc1ce642ca764a3da66e9b2 modifies the IPNWB submodule which I guess is unrelated.

**Comment by MichaelHuth** [comment]
> @MichaelHuth [a247590](https://github.com/AllenInstitute/MIES/commit/a24759068065d897edc1ce642ca764a3da66e9b2) modifies the IPNWB submodule which I guess is unrelated.

Yes, I fixed that.

**Comment by timjarsky** [comment]
@t-b the following formula 
``` data(TP,select(channels(AD),sweeps(),all)) ```
gives different errors in main and this branch.
main: ``` sweeps have not the same delta ```
1372: ``` specified range not valid ```

The error message in main makes sense to me. It also makes me realize that the optional parameter in the select formula (`all`) will be of limited use because most experiments have IC and VC traces. We should consider ways to select all VC or IC sweeps (in a separate PR).

**Comment by t-b** [comment]
@timjarsky Can you upload the file you tried that with?

**Comment by timjarsky** [comment]
[Htr3a-Cre_NO152;Ai14-612284.06.03.01.zip](https://github.com/AllenInstitute/MIES/files/9353959/Htr3a-Cre_NO152.Ai14-612284.06.03.01.zip)
@t-b Here is one of the files I saw the error message with.

**Comment by t-b** [comment]
@MichaelHuth Can you have a look?

**Comment by timjarsky** [comment]
@t-b @MichaelHuth the following formula crashes Igor when applied to the file shared above. It works without the Integrate formula.

Integrate(data(TP,select(channels(AD), 4...16,all)))

**Comment by MichaelHuth** [comment]
@timjarsky @t-b I tried with IP9 39241 and I get the "specified range not valid" error (no crash). The reason is that there seem to be no Epoch Information in the textual lbn. Thus, the range returned for "TP" is {NaN, NaN} and it SF_ASSERTs out.

**Comment by MichaelHuth** [comment]
@t-b @timjarsky Sorry, I loaded the wrong experiment on my test, however also with Htr3a-Cre_NO152;Ai14-612284.06.03.01.zip Integrate creates 44255 traces. I will fix that. That is probably why it crashed as well.

**Comment by MichaelHuth** [comment]
@t-b @timjarsky The issue should be fixed now. The main cause was in the meta data transfer from one operation to another.
e.g. integrate got input from data and the meta data transfer set as x_value the sweep number and as x label "sweeps" for the output of integrate. The formula plotter saw then a 1d y wave and a 0d x wave (only one point) and took the branch to one trace per y wave point.
I changed the meta data transfer logic now to only apply the "sweeps" setting if the data waves of the operation have only a single point and no wave units set. All data waves must fulfill this condition to enable the meta data setting for "sweeps"/sweep number. 
Also the formula plotter now only takes the xvalues from the meta data if an x label is set.
I had to adapt a few more operations that return single values where the scale transfer could possibly transfer a wave unit.
If there is no wave unit set on purpose like for derivative "d/dx", it is cleared now for x.

**Comment by t-b** [comment]
@MichaelHuth Compile errors in CI:
```
UTF_SweepFormulaHardware.ipf:514:52: error: got "DirectToFormulaParser" instead of a string variable or string function name.
  UTF_SweepFormulaHardware.ipf:514:52: error: got "DirectToFormulaParser" instead of a string variable or string function name.
```

**Comment by t-b** [comment]
@timjarsky Do you wanna proofread the documentation in SweepFormula.rst? Or should we just take it as it is and extract the relevant parts for the in Igor help (notebook).

**Comment by timjarsky** [comment]
> @timjarsky @t-b I tried with IP9 39241 and I get the "specified range not valid" error (no crash). The reason is that there seem to be no Epoch Information in the textual lbn. Thus, the range returned for "TP" is {NaN, NaN} and it SF_ASSERTs out.

@MichaelHuth Sorry I gave the wrong formula **AND** did not understand the error message in main. In fact, I inadvertently ran the test I should have done in the first place, where I try to plot sweeps with different sampling intervals. It works nicely!

image

**Comment by timjarsky** [comment]
@MichaelHuth @t-b 

In main I get:
image
In this PR I get:
image

The way this PR automatically plots the results against sweeps is great, but I'm not sure what the extra points between sweeps 9 and 10 are.

**Comment by t-b** [comment]
@timjarsky I bet the points between 9 and 10 are the legend. Is that correct?

**Comment by timjarsky** [comment]
@t-b yes, that's correct; just dots, no text.

**Comment by timjarsky** [comment]
@t-b x-axis label is sweeps but user specified a different x-axes data type

image

**Comment by t-b** [comment]
>> but I'm not sure what the extra points between sweeps 9 and 10 are.
> yes, that's correct; just dots, no text.

@timjarsky Should we enlarge the right hand side graph margin and move the legend there?

**Comment by t-b** [comment]
Add unit in plotter (\\U at end of label) for y label if all data waves have the same data unit. Unit in braces "(mV)"

**Comment by MichaelHuth** [comment]
@t-b @timjarsky The recent reported issues should be fixed now.

**Comment by t-b** [comment]
@michaelHuth tools/check-code.sh fails with:
```
18-Aug-2022 09:15:45 	The duplicated newlines check failed and found the following occurences:
18-Aug-2022 09:15:45 	Packages/MIES/MIES_WaveDataFolderGetters.ipf:7479:End
18-Aug-2022 09:15:45 	Packages/MIES/MIES_WaveDataFolderGetters.ipf:7480:
```

**Comment by t-b** [comment]
Testing with Tim 0cc91f2d (SF: Adapt meta data inheritance while formula execution, 2022-08-17):

- [ ] Issues with x axis:

min(
butterworth(
integrate(
derivative(
data(TP,select(channels(AD0), 4...11,all)))),
4,100,4))


and

min(
data(TP,select(channels(AD0), 4...11,all)))

vs

1...8

grafik

IIRC this used to work. This also needs a test.

- [ ] The legend in the graphs should be framed

**Comment by MichaelHuth** [comment]
Changes the rules for x-wave to y-wave mapping:

if there is a single x data wave and its size equals the number of y data waves
and the current mapped y data wave (number n) has exactly one data point, 
then the n'th point of the x data wave is used as x-wave for the y-wave.

if there is a single x data wave and the other conditions are not met, then
the x data wave is mapped to all y data waves.

if there are as many x data waves as y data waves then each y data wave gets a
x data wave mapped.

**Comment by MichaelHuth** [comment]
Changes for default rule for operation meta data transfer:

By default if the out data wave has only a single point and no wave units
  and sweep number meta data is present
  then the sweep number is set as x value and "Sweeps" as x label
  otherwise
  no x label is set (prevent plotter from using x axis meta data)

**Comment by MichaelHuth** [comment]
@t-b With the added wave units as part of the y label I found some issues, where it is wrong. Let's chat about this, to find a solution thats a best trade off of correctness vs. effort.

**Comment by MichaelHuth** [comment]
@timjarsky The issues from your last test session with Thomas are fixed and I also added tests for it.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b Looking great! I'll approve.
image
image

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth Is this PR done from your POV?

**Comment by MichaelHuth** [comment]
@t-b Yes, as Tim has not found any rough flaws I think its good.

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
Thanks both for the immense effort in getting this done and tested.

**Pull request merged**
