### PR TITLE
Document daq stopping reason

### PR DESCRIPTION
**Pull request by t-b**
- [x] Should be merged after #941
- [x] Add tests
- [x]  Add log message for reasons like HW_ERROR, OUT_OF_MEMORY, etc.
- [x] `DQ_STOP_REASON_STIMSET_CHANGED` -> `DQ_STOP_REASON_STIMSET_SELECTION` 
       `DQ_STOP_REASON_BUTTON` -> `DQ_STOP_REASON_DAQ_BUTTON`

This fixes point 2 of #798.

### CODE REVIEW

**Comment by t-b** [comment]
`DQ_STOP_REASON_STIMSET_CHANGED` -> `DQ_STOP_REASON_STIMSET_SELECTION`

**Comment by t-b** [comment]
@timjarsky Ready.

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
also nice: 
image

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
@timjarsky Thanks. Rebased to resolve conflicts, will merge then CI passes.

**Pull request merged**
