### PR TITLE
Fix hooks functions for SweepBrowser

### PR DESCRIPTION
**Pull request by t-b**
This fixes the problem with the missing "restore" button once the settings history was closed.

It also fixes the problem that the really helpful SF hooks did not work with the SweepBrowser.

I also cleaned the code up a bit.

### CODE REVIEW

**Comment by t-b** [comment]
I can't replicate that. Have you used a new databrowser/sweepbrowser?

**Comment by timjarsky** [comment]
@t-b I did, but I'll try it again with a clean startup.

**Comment by timjarsky** [comment]
@t-b I retested and didn't see the error I saw earlier.

A semi-related issue I observed is that closing a subwindow moves the DB behind the next window in the stack (see video).
https://user-images.githubusercontent.com/5693697/199342843-8d160928-0b73-415a-892b-3eb31928672d.mp4

**Comment by t-b** [comment]
> A semi-related issue I observed is that closing a subwindow moves the DB behind the next window in the stack (see video).

@timjarsky Fixed.

**Comment by timjarsky** [comment]
@t-b analysis browser now returns to the top after closing a sub-panel. I guess IP assumes that the next window in the stack should be automatically brought to the top when closing any window?

**Comment by timjarsky** [comment]
@t-b while we are working on this, update the help string for `button_BSP_open` to "Restore side panels"

**Comment by t-b** [comment]
> @t-b analysis browser now returns to the top after closing a sub-panel. I guess IP assumes that the next window in the stack should be automatically brought to the top when closing any window?

I can't reproduce that.

> @t-b while we are working on this, update the help string for button_BSP_open to "Restore side panels"

Done.

**Comment by timjarsky** [comment]
@t-b when closing a side panel, you don't see the whole analysis browser flash?

**Comment by t-b** [comment]
> @t-b when closing a side panel, you don't see the whole analysis browser flash?

I see it flash shortly but it is behind afterwards again. We can also debug today together.

**Comment by timjarsky** [comment]
@t-b I'm not sure the frame rate of a remote connection will be effective in showing the issue, so I've uploaded a short video recorded at 60fps. Note how the DB disappears the second time I close the panel. It also flashes the first time but the video doesn't capture that well.

https://user-images.githubusercontent.com/5693697/200027123-75df195b-a600-4829-8833-993dcdd6b0be.mp4

**Comment by t-b** [comment]
@timjarsky IIRC this is good to go?

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
