### PR TITLE
Bugfix/1062 updating stimsets with all controls

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b bug is still present:

set up `Wave_DA_AllIClamp` and `IndexEnd_DA_AllIClamp`, and check `check_DA_applyOnModeSwitch`. Now create stimset with a name that causes it to slot in above the stimsets selected for indexing. e.g., If start index stimset is named `B`, create a new stimset named `A`. Switch clamp modes and `Wave_DA_AllIClamp` is offset by one.

**Comment by t-b** [comment]
@timjarsky Thanks for checking. So the bug is something else as well. I'll investigate.

**Comment by t-b** [comment]
Found something. Still coding....

**Comment by t-b** [comment]
@timjarsky Please test again.

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
Found and fixed it.

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
@t-b I've approved both PRs after manually testing following the latest commits. If I see that the automated testing passes, I plan to go ahead and merge. Hope that's okay?

**Comment by t-b** [comment]
I've merged the backports PR and restarted failing tests here.

**Comment by timjarsky** [comment]
@t-b Is it okay for MPE to test the release with the backport or should they wait for the test results?

**Comment by t-b** [comment]
@timjarsky No need to wait for the test results. Just grab the installer form http://bamboo.corp.alleninstitute.org/browse/MIES-RELEASE-CRP-216 or here from github.

**Comment by timjarsky** [comment]
@t-b the installer has not content; 0 bytes

**Pull request merged**
