### PR TITLE
Make Databrowser and PA *much* faster

### LINKED ISSUE #555: TimeAlignment with PAPlot is unbearable slow
PA time alignment not the general time alignment.

### PR DESCRIPTION
**Pull request by t-b**
-  [x] Don't use userdata on traces anymore for the databrowser/PA plot. Write directly into the wave which is generated on the fly currently, see `PA_GetTraceInfos`.
- [x] Cache the TraceNameList in graph user data. Add wrapper function.
- [x] Resolve all TODOs
- [x] Fix trace naming in `AR_HandleRanges`, set correct trace type
- [x] Add hook to graph windows to delete graphuserdata wave on close
- [x] Get multiple graphs in PA plot working
- [x] Fix documentation and cleanup code
- [x] Avoid too many trash folders
- [x] Allow removal of traces, by using a different indexing appraoch
- [x] Cleanup commits
- [x]  Fix sweep highlightning for OVS
Close #555.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Very early version ready. This does now not use any trace user data anymore, but our our own code. It feels faster here.

**Comment by t-b** [comment]
Timealigning all `Recovery 50 Hz` pulse average traces from PA-TimeAlignment-Playing-around.pxp

This PR:
```
Total time: 33.4779, Time in Function code: 12.6676 (37.8%)
Top function percentages:
Function MIES_MiesUtilities.ipf RemoveTracesFromGraph: 47%
Function MIES_PulseAveraging.ipf PA_ShowPulses: 14%
Function MIES_MiesUtilities.ipf CreateBackupWave: 6%
Function MIES_Utilities.ipf GetSetIntersection: 4%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 3%
Function MIES_TraceUserData.ipf TUD_SetUserDataFromWaves: 3%
Function MIES_MiesUtilities.ipf TimeAlignmentIfReq: 3%
Function MIES_Utilities.ipf createDFWithAllParents: 2%
```

master:
```
Total time: 870.753, Time in Function code: 861.984 (99%)
Top function percentages:
Function MIES_GuiUtilities.ipf RestoreCursors: 85%
```

Both are done with IP9.

**Comment by timjarsky** [comment]
@t-b works in master but asserts out here.

```  !!! Assertion FAILED !!!
  Message: "Non consecutive traces added"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_CheckBoxProc_PerPulseAver(...)#L760 [MIES_BrowserSettingsPanel.ipf]
UpdateSweepPlot(...)#L5186 [MIES_MiesUtilities.ipf]
SB_UpdateSweepPlot(...)#L397 [MIES_AnalysisBrowser_SweepBrowser.ipf]
CreateTiledChannelGraph(...)#L2592 [MIES_MiesUtilities.ipf]
TUD_SetUserDataFromWaves(...)#L147 [MIES_TraceUserData.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-07-01T09:07:08-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.0_20190602-1026-g8762faed
Date and time of last commit: 2020-06-30T23:25:03+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 9a3f02fb7d007b4b34b29bda1f3fddc0ce64ad33 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################
```

**Comment by t-b** [comment]
@t-b As I said much faster now...

Coming back to the assertion. Anything special you did?

**Comment by timjarsky** [comment]
> @t-b As I said much faster now...
> 
> Coming back to the assertion. Anything special you did?

Displayed 1 sweep, enabled PA plot. I can demo now if you would like?

**Comment by t-b** [comment]
@timjarsky Can you retry with the latest version? After that demo sounds good.

**Comment by t-b** [comment]
@timjarsky Feel free to play around. Turning off PA deconvolution is not yet supported.

**Comment by timjarsky** [comment]
@t-b this is an amazing improvement in speed but it looks like we do need further speed enhancements to make it useful during data acquisition (when used with overlay sweeps). Thank you!!

**Comment by t-b** [comment]
> I see a 20-30% time savings when adding/removing a single sweep compared PA plot enable with 25 sweeps. Is this about what you were expecting?

The time saving should be much larger when we have it implemented. Currently a lot of time is spent in RemoveAllTracesFromGraph and later calls to AppendToGraph. We should be able to save most of that time.

**Comment by t-b** [comment]
@timjarsky I just fixed the "show indiviual traces" button in the PA plot. I'm also hunting another one in the PA plot.

**Pull request merged**
