### PR TITLE
DataBrowser: Added grouped drawing when sweeps are added.

### PR DESCRIPTION
**Pull request by MichaelHuth**
This increases the speed when the DataBrowser graph is updated.

The same logic as in the grouped drawing for the PA plot is used,
with the expension that a structure is introduced to carry the draw
information. This allows to draw the graph elements at a later point in
the code.

close https://github.com/AllenInstitute/MIES/issues/749

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth Review:
- missing JSON_Release for BufferedDrawInfo.jsonID
- Why is bdi optional for CreateTiledChannelGraph and friends? Why not always make it faster? I'm okay with not making the oodDAQ case though, as that would involve postponing the axis enabling/scaling as well.
- You also need to handle AR_UpdateTracesIfReq correctly if you are doing
  buffered draw. Does that still work?
  If it is easier we can also not do buffered draw if that is enabled. Maybe
  this needs a member in BufferedDrawInfo which says enabled/disabled?
- Can you explain why `ModifyGraph/W=$graph hideTrace($trace)=1` in CreateTiledChannelGraph does still work?

**Comment by MichaelHuth** [comment]
* bdi.jsonID is released at the end of TiledGraphAccelerateDraw.
* bdi is optional because the acceleration only make sense when sweeps are added, so for AddSweepToGraph and UpdateSweepInGraph. However all draw calls in the loop from OVS_EndIncrementalUpdate have to be buffered. And other calls in between may not have any dependency on the drawn content. So having a fully generalized approach here requires gathering of all single sweep based draw information to be able to execute dependent functions after the buffered draw.
For UpdateSweepInGraph this would add e.g. CursorState and AxisRange backup/restore.
* I don't see where the AR part depends on the drawn traces from CreateTiledGraph.
* I fixed the hideTraces problem.

**Comment by t-b** [comment]
@MichaelHuth Okay, good points. Let's leave it like it is.

**Comment by t-b** [comment]
@MichaelHuth IIRC this code is obsolete once IP9 is mandatory or?

**Review by t-b — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth It it's done please assign Tim.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
