### PR TITLE
Add variable support to SweepFormula

### PR DESCRIPTION
**Pull request by MichaelHuth**
Example:

```igorpro
s = select(channels(AD),sweeps(),all)
c = cursors(A,B)

data($c,$s)
```

Example2:
```igorpro
s = select(channels(AD),sweeps(),all)
c = cursors(A,B)
d = data($c,$s)

$d

```

@timjarsky @t-b initial version

close https://github.com/AllenInstitute/MIES/issues/276

### CODE REVIEW

**Comment by timjarsky** [comment]
> Example:
> 
> ```igor
> s = select(channels(AD),sweeps(),all)
> c = cursors(A,B)
> 
> data($c,$s)
> ```
> 
> Example2:
> 
> ```igor
> s = select(channels(AD),sweeps(),all)
> c = cursors(A,B)
> d = data($c,$s)
> 
> $d
> ```
> 
> @timjarsky @t-b initial version
> 
> close #276

@MichaelHuth, wow, that was fast! Unfortunately, I have a busy day today, but I should be able to try it out tomorrow. Thank you!!

**Comment by t-b** [comment]
Thanks for the quick PR. I've played around with it and it works in all good cases.

Some bad cases could be catched with a more strict regexp I think. How about something like

```
^(?i)\\s*([A-Z]{1}[A-Z0-9_]*)\\s*=(.+)$
```

This not only adds front and back locking but also the generic "ignore case" and `.` instead of `[\\s\\S]`.

With the current regexp something like

```
132s = select(channels(AD),sweeps(),all) # comment
```

gets the variable name `s`.

**Comment by timjarsky** [comment]
@MichaelHuth this is so much better!

```
d = data(E1,select(channels(AD0),sweeps()))

$d

and

apfrequency($d,0,0,freq,normoversweepsmin)

with

apfrequency($d,0,0,freq,normoversweepsmax)

with

apfrequency($d,0,0,freq,normoversweepsavg)

and

apfrequency($d,3,0,freq,normoversweepsmax)

with

apfrequency($d,3,0,freq,nonorm)

and

apfrequency($d,3,0,time,nonorm,time)

and

apfrequency($d,3,0,freq,norminsweepsmax,time)
```

vs.

```
data(E1,
select(channels(AD0),sweeps()))

and


apfrequency(
data(E1,
select(channels(AD0),sweeps())),
0,0,freq,normoversweepsmin)

with

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
0,0,freq,normoversweepsmax)

with

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
0,0,freq,normoversweepsavg)


and

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
3,0,freq,normoversweepsmax)

with

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
3,0,freq,nonorm)

and

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
3,0,time,nonorm,time)

and

apfrequency(
data(E1,
select(channels(AD0),sweeps())),
3,0,freq,norminsweepsmax,time)
```

**Comment by t-b** [comment]
Works as advertised for me as well. @timjarsky Can Michael finish it?

**Comment by t-b** [comment]
@MichaelHuth 

Why does

```
d = data(E1,select(channels(AD0),sweeps()))
e = $d,3,0,freq,norminsweepsmax, time

apfrequency($e)
```

not work?

**Comment by MichaelHuth** [comment]
What happens is that $e is evaluated to an array, but it has mixed data type content.
This results in `$e = [NaN,3,0,NaN,NaN,NaN]`.

Also when the operation
apfrequency starts parsing its arguments, it sees a single argument. The executor will then replace the $e string with the array from the variable. Effectively apfrequency then sees as first argument (where data should be) the parameter array from $e.

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth THanks for the explanation, so I guess there is no easy way to fix that.

**Comment by t-b** [comment]
Review:
- UTF_SweepFormulaHardware.ipf does not compile
- `a = unknown`

triggers

```
  BUG_TS: Encountered pending RTE: 734, DefineGuide;Illegal dual guide position.
```

178a0d95 (SF: Add utility function ParseFormulaToJSON, 2023-03-28)
066313d8 (SF: Allow $ character in strings parsed by SF_FormulaParser, 2023-03-28)

Jeep.

6883d68c (SF: Move kill of working DF outside of SF_FormulaPlotter, 2023-03-28)

Nice.

1b583539 (SF: Add parse and execute for variable names, 2023-03-28)

- Is it possible to just resize the existing wave to zero rows instead of

```
+    WAVE/WAVE varStorage = GetSFVarStorage(dfr)
+    KillOrMoveToTrash(wv = varStorage)
+    WAVE/WAVE varStorage = GetSFVarStorage(dfr)
```

b83d8840 (SF: Add variable support to formula executor, 2023-03-28)

```
+    WAVE/Z/T varAssignments = $""
+    [varAssignments, code] = SF_GetVariableAssignments(preProcCode)
```

IP9 now supports

```
[WAVE/T varAssignments, code] = SF_GetVariableAssignments(preProcCode)
```

The /Z is implicit (unfortunately, already reported).

Querying varStorage should be moved into its own function SF_FormulaExecutor is way too big already.

965fee7e (SF: Add support to check also variables with the check button, 2023-03-29)

SF_GetVariableAssignments: Our usual convention is to return $"" instead of an empty wave.

10601dfb (SF: Use try/catch approach for checking formula input, 2023-03-29)

Fine.

09f52c9f (SF: Add support for with keyword when checking formulas, 2023-03-29)

Good find. We use small caps "graph" and "formula" in the JSON tab so small caps variable would be better though.

49a543f4 (SF: Tests for variable support in SF, 2023-03-29)

- The test should also check that the correct number of entries and correct name was added to varStorage. It might make also sense to split the passing tests into an own test and use multi data tests for that, but I'll leave that to you.
- Variable case insensitivity should also be tested

- One test where you check that the executor replaced it correctly would also be nice.

- Test also that

```
b = 1

a$b vs 0
```

works and keeps working.

a921e1a3 (SF: Add variable documentation to SF help notebook, 2023-03-30)
0ae46241 (SF: Add variable SF feature to MIES documentation, 2023-03-30)

Both nice!

**Comment by MichaelHuth** [comment]
@t-b Could you give me the test results?

**Comment by t-b** [comment]
@MichaelHuth Sure, UTF_SweepFormula#TestInputCodeCheck fails.

**Comment by t-b** [comment]
LGTM.

**Review by t-b — APPROVED** [review]

**Pull request merged**
