### PR TITLE
Feature/upload crash dumps

### LINKED ISSUE #51: Automatically upload crash dumps once a week
In that way we can get more infos and try fixing the crashes.

- [ ] Use "FTPUpload" to upload the crash dumps into a $computer/$user folder
- [ ]  Either put the credentials into the json config fle or "encrypt" them in the procedure code

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add docu
- [x] Cleanup commits
- [x] Add proper TLS certificate for ai.customers.byte-physics.de
- [x] Add daily upload
- [x] Add menu entry in advanced
- [x] Don't remove the crash dumps/log files. Maybe move into `Diagnostics_old`?
- [x] Investigate missing crash dumps and zero files in upload folder

Close #51.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready!

**Comment by t-b** [comment]
Uploading crash dumps from the CI server fails with

```
<system-out>
Entering test case "VeryBasicHardwareTesting#TestLocking:ITC" ITC Device opened, returned deviceID is 0. BUG UploadCrashDumpsDaily(...)#L5912: Could not upload crash dumps! !!! Assertion FAILED !!! Message: "BUG: Should never be called during automated testing." 0: is false Assertion "FAIL()" failed in line 20, procedure "UTF_VeryBasicHardwareTests.ipf" NAME:ITC_TimerMD;PROC:DQM_Timer;RUN:0;PERIOD:6;NEXT:0;QUIT:0;FUNCERR:1; NAME:ITC_FIFOMonitorMD;PROC:DQM_FIFOMonitor;RUN:0;PERIOD:1;NEXT:0;QUIT:0;FUNCERR:1; NAME:ITC_FIFOMonitor;PROC:DQS_FIFOMonitor;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1; NAME:ITC_Timer;PROC:DQS_Timer;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1; NAME:TestpulseMD;PROC:TPM_BkrdTPFuncMD;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1; NAME:Testpulse;PROC:TPS_TestPulseFunc;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1; NAME:P_ITC_FIFOMonitor;PROC:P_ITC_FIFOMonitorProc;RUN:0;PERIOD:10;NEXT:0;QUIT:0;FUNCERR:1; Leaving test case "VeryBasicHardwareTesting#TestLocking:ITC"
</system-out>
```

I need to checkl why.

**Comment by t-b** [comment]
Fixed.

**Comment by t-b** [comment]
@timjarsky I can't assign you, but it is ready again.

**Comment by timjarsky** [comment]
@t-b I put a OH_NO.dmp in an otherwise empty crash dump folder and got:

**Comment by t-b** [comment]
@timjarsky Thanks. Fixed.

**Comment by t-b** [comment]
Rebased and merging now.

**Pull request merged**
