### PR TITLE
Various Analysis Functions Dashboard fixes

### PR DESCRIPTION
**Pull request by t-b**
Found that lying around.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b the dashboard is showing that all stimsets fail with ```sweep not yet finished``` error when testingIVSCC protocols with a model cell. See attached NWB
[dashboard_issues.zip](https://github.com/AllenInstitute/MIES/files/7629308/dashboard_issues.zip)
image

**Comment by timjarsky** [comment]
@t-b `dashboard failure.pxp` is on the way to your FTP. The history shows an issue querying lab notebook values.

**Comment by t-b** [comment]
@timjarsky Go for it. Extra point for breaking it ;)

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
@timjarsky The CI tests failed and they were right. I've fixed the dashboard for multiple headstages. Please retest.

**Comment by t-b** [comment]
@timjarsky Just in case this got lost in the noise. This is ready to test again, there was a bug with multiple headstages which is now fixed.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
