### PR TITLE
Databrowser set sweep count selection

### LINKED ISSUE #157: OVS: Add option to choose all sweeps from a stimset and a given "Set Sweep count"
This makes the selection more reliable than offset/step as it selects the fifth planned sweep from a stimset and not the fifth acquired sweep.

Add an additional popup menu.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add stimulus set cycles selection as well
- [x] Limit "set sweep count" list items to only have elements with 2 or more counts
- [x] Selection takes way too long
- [x] Only show stimsets which were acquired more than once (aka have a set cycle count of 1 or higher)

Close #157.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky I interpret being assigned that I really should dive in?

**Comment by timjarsky** [comment]
@t-b yes, but the TP work is a higher priority.

**Comment by timjarsky** [comment]
@t-b I propose limiting the list of stimsets in the `DA Stimulus Sets and Set Sweep Count`  category to those with 2 or more sweeps. This should prevent the list from getting large and make enhancements GuiPopupMenuExt unnecessary. Thoughts?

**Comment by t-b** [comment]
@timjarsky Done.

**Comment by timjarsky** [comment]
@t-b Limit "set sweep count" list items to only have elements with 2 or more counts doesn't seem to be working; every set sweep count is present.

The menu can be very slow to respond - locks IP up for several seconds.

I can demo

**Comment by t-b** [comment]
@timjarsky Jeep let's demo and chat about this PR. I seem to have misunderstood how you want it as the sweep count limitation works here as I think it should.

Regarding execution speed, is it always slow or only on the first opening? We postpone updating the menu entries to save some time during DAQ and do it therefore only once on first opening.

**Comment by t-b** [comment]
@timjarsky Ready to test again. I've now removed stimsets from set sweep count/set cycle count which never cycled. I can not reproduce the slowness, but I also changed the code a bit so please retry.

**Comment by timjarsky** [comment]
@t-b we want to find stimsets that have been acquired more than once regardless of the RA cycle. In the current config, if the set was acquired on different RA cycles, they are not listed:
image

**Comment by t-b** [comment]
@timjarsky Next try.

**Comment by timjarsky** [comment]
@t-b I loaded 5 sweeps from an experiment and one run of a stimulus set. In this case, I would expect that nothing would be listed in the `DA stimulus sets and set sweep count` menu because there are no repeats in the loaded data. 
image

**Comment by t-b** [comment]
@timjarsky And next try.

**Comment by timjarsky** [comment]
@t-b i'm still seeing the behavior described in my last post (screen share?)

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
