### PR TITLE
Feature/1358 access resistance check smoke

### LINKED ISSUE #1228: Analysis Function: Access resistance check

### PR DESCRIPTION
**Pull request by t-b**
- [x] Digital flowchart
- [x] Digital testmatrix
- [x] Rebase #1358 is fixed
- [x] BaselineRMSShortThreshold/BaselineRMSLongThreshold optional
- [x] NumberOfFailedSweeps/SamplingMultiplier required
- [x] Raise LBN version
- [x] Check LBN description
- [x] Fix user epoch table for VM and AR
- [x] PSQ_GetPulseSettingsForType proper commit
- [x] PSQ_CreateOverrideResults bugfix commit

Close #1228

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I tried something I have not done in the past with PSQ analysis functions; I used it on a second headstage (only one headstage at a time) using AD1 and DA1. It induced the following assertion on HS1 but not HS0:

```!!! Assertion FAILED !!!
  Message: "Could not find baseline chunk selection user epochs"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L94 [MIES_DataAcquisition_Multi.ipf]
AS_HandlePossibleTransition(...)#L103 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L135 [MIES_AnalysisFunctionManagement.ipf]
PSQ_AccessResistanceSmoke(...)#L5914 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_EvaluateBaselineChunks(...)#L341 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_EvaluateBaselineProperties(...)#L446 [MIES_AnalysisFunctions_PatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-05-09T19:50:25-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [1]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: Untitled ()
  Igor Pro version: 9.0.1.1 (38961)
  MIES version:
  Release_2.5_20220415-132-g5ca5f92b7
Date and time of last commit: 2022-05-07T16:48:07+02:00
Submodule status: 
160000 f3493461480eaafa97939940693ed693860048a6 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 a8d4707e7c72555baefbb9a4d52de920e1d8ebb9 0	Packages/unit-testing
```

[accessResistancecheck.zip](https://github.com/AllenInstitute/MIES/files/8657122/accessResistancecheck.zip)

**Comment by timjarsky** [comment]
@t-b everything else looks good!

**Comment by t-b** [comment]
Fixed.

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
Ready for testing again.

This is now feature complete documentation-wise. The only functional change was that I removed setting the IC holding potential. This was not specified and looked like an oversight.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
