### PR TITLE
Fix scrolling in db/sb

### LINKED ISSUE #1144: Visualization of epochs should not require DA channels to be shown

### LINKED ISSUE #1156: Fix scrolling bug in Databrowser/Sweepbrowser
- mouse wheel part of SB_SweepBrowserWindowHook needs to be both in DB/SB
- epochs also need trace names like `sprintf traceName, "T%0*d%s", TRACE_NAME_NUM_DIGITS, (numTraces + traceIndex), averageWaveName` as otherwise GetNextTraceIndex bugs out as the naming scheme is not held

### PR DESCRIPTION
**Pull request by t-b**
Close #1156.
Close #1144.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b with visualize epochs checked, going from all the sweeps displayed to `- none -` using OVS, gives the following error
image

scrolling using the mouse wheel and control key isn't functional in the data browser or sweep browser

**Comment by t-b** [comment]
@timjarsky I'll look into the bug. Use the ALT key for srolling.

**Comment by t-b** [comment]
- [ ] Reverse the direction

**Comment by t-b** [comment]
@timjarsky Fixed. I also fixed two other small bugs. And also snuck in a fix for #1144.

**Comment by timjarsky** [comment]
@t-b this is shaping up nicely. Two minor comments:

1. the visualize epochs checkbox is disabled when initializing the sweep browser panel. When fixing this, check the data browser as well.
2. 
image

2. I noticed that in OS, display `Stimulus sets and set sweep count` has reverted to the old behavior where if 1 sweep is present in a stimulus set, the stimset is listed in the menu
image

**Comment by t-b** [comment]
@timjarsky Both should be fixed. Please also check the commit message of e3747f8b (OVS_RemoveLowCountEntries: Fix it, 2021-11-16) if I got it right this time.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
