### PR TITLE
Ssweepformula enhance help

### PR DESCRIPTION
**Pull request by MichaelHuth**
- links with operation reference table in sf help notebook
- simple syntax coloring in sf formula notebook
- tooltip based help after marking an operation through e.g. double click in sf formula notebook
- direct jump to help after marking a shift + rightclick an operation

close https://github.com/AllenInstitute/MIES/issues/1229

### CODE REVIEW

**Comment by t-b** [comment]
Tests errors:
```
Errors building the documentation
Doxygen says:
/home/ci/Packages/MIES/MIES_DataBrowser.ipf:771: warning: Unsupported xml/html tag <operationName> found
/home/ci/Packages/MIES/MIES_DataBrowser.ipf:771: warning: Unsupported xml/html tag <operationName> found
```

```
<html><body>
<!--StartFragment-->

Collapse | Failed | UTF_SweepFormula#TestOperationEpochs                                 UTF_SweepFormula#TestOperationEpochs in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
-- | -- | -- | --
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestOperationEpochs", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#TestOperationLabNotebook                                 UTF_SweepFormula#TestOperationLabNotebook in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestOperationLabNotebook", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#TestPlotting                                 UTF_SweepFormula#TestPlotting in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestPlotting", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#arrayExpansion                                 UTF_SweepFormula#arrayExpansion in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#arrayExpansion", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#brackets                                 UTF_SweepFormula#brackets in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#brackets", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#concatenationOfOperations                                 UTF_SweepFormula#concatenationOfOperations in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#concatenationOfOperations", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#merge                                 UTF_SweepFormula#merge in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#merge", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#minimaximu                                 UTF_SweepFormula#minimaximu in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#minimaximu", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#orderOfCalculation                                 UTF_SweepFormula#orderOfCalculation in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#orderOfCalculation", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#primitiveOperations                                 UTF_SweepFormula#primitiveOperations in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#primitiveOperations", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#primitiveOperations2D                                 UTF_SweepFormula#primitiveOperations2D in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
ABORT: Encountered "Abort" in test case "UTF_SweepFormula#primitiveOperations2D", procedure file "UTF_SweepFormula.ipf"
Collapse | Failed | UTF_SweepFormula#waveScaling                                 UTF_SweepFormula#waveScaling in UTF_SweepFormula.ipf (13)                                 History | < 1 sec
 

<!--EndFragment-->
</body>
</html>Collapse 	Failed 	UTF_SweepFormula#TestOperationEpochs [UTF_SweepFormula#TestOperationEpochs in UTF_SweepFormula.ipf (13)](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1-1/test/case/179048801) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048801)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestOperationEpochs", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#TestOperationLabNotebook UTF_SweepFormula#TestOperationLabNotebook in UTF_SweepFormula.ipf (13) History
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestOperationLabNotebook", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#TestPlotting UTF_SweepFormula#TestPlotting in UTF_SweepFormula.ipf (13) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048802)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#TestPlotting", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#arrayExpansion UTF_SweepFormula#arrayExpansion in UTF_SweepFormula.ipf (13) History
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#arrayExpansion", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#brackets UTF_SweepFormula#brackets in UTF_SweepFormula.ipf (13) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048804)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#brackets", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#concatenationOfOperations UTF_SweepFormula#concatenationOfOperations in UTF_SweepFormula.ipf (13) History
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#concatenationOfOperations", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#merge UTF_SweepFormula#merge in UTF_SweepFormula.ipf (13) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048817)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#merge", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#minimaximu UTF_SweepFormula#minimaximu in UTF_SweepFormula.ipf (13) History
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#minimaximu", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#orderOfCalculation UTF_SweepFormula#orderOfCalculation in UTF_SweepFormula.ipf (13) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048818)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#orderOfCalculation", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#primitiveOperations UTF_SweepFormula#primitiveOperations in UTF_SweepFormula.ipf (13) History
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#primitiveOperations", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#primitiveOperations2D UTF_SweepFormula#primitiveOperations2D in UTF_SweepFormula.ipf (13) [History](http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN623-TWH1/test/case/179048819)
	< 1 sec

ABORT: Encountered "Abort" in test case "UTF_SweepFormula#primitiveOperations2D", procedure file "UTF_SweepFormula.ipf"

Collapse 	Failed 	UTF_SweepFormula#waveScaling UTF_SweepFormula#waveScaling in UTF_SweepFormula.ipf (13) History
	< 1 sec
```

**Comment by t-b** [comment]
@MichaelHuth CI fails.

**Comment by t-b** [comment]
You can run that locally via `tools/check-code.sh`.

**Comment by t-b** [comment]
@timjarsky Ready for a first test

**Comment by t-b** [comment]
Please check RunAllTests.pxp on your end. The hardware tests failures are probably related.

**Comment by t-b** [comment]
Thanks. The failing tests seems to be unrelated. I've restarted CI.

**Comment by timjarsky** [comment]
@t-b very nice!

a couple of minor questions/comments:
1) should there be help entries for `and` and `vs`?
2) the font color helps with readability (i like it), but what triggers the color change?

**Comment by t-b** [comment]
> should there be help entries for and and vs?

Yes we can add those. @MichaelHuth Could you handle that? RST and notebook I think.

> the font color helps with readability (i like it), but what triggers the color change?

Currently notebook activation/deactivation.

**Comment by MichaelHuth** [comment]
@timjarsky The coloring is updated whenever the notebook window gets activated or deactivated, e.g. if you click some other control it gets deactivated. I would like to have it done on "modify", but since the coloring essentially rewrites the notebook content it would have interfered with the editing such that after each keypress the cursor would be back at the beginning. Thus, that was no option.

**Comment by t-b** [comment]
Review:

90b6bfca (DataBrowser: add utility function DB_SFHelpJumpToLine to scroll in SF help, 2022-04-26)
3e6b3001 (SweepFormula Help notebook revamp with operation index jump table, 2022-04-26)
6a9681ce (SF: Add function returning full list of known operations, 2022-04-26)

All good.

849caf4b (Extend GetGuiControlValue to support tab controls, 2022-04-26)

Okay.

fec819ca (Introduce full set of constants for WMWInHook eventCode and eventMod fields, 2022-04-27)

Thanks for introducing them. Some nits:
- Please don't start constants with `WM`, how about `WINDOW_HOOK_EMOD_XXX`
- If you introduce new constants for making things nicer to read, it is usually best to convert existing places which don't use the constants. I found some candiates with `git grep -iI -e WMWinHookStruct --or -e eventMod '**/MIES_*.ipf'`

1e551c56 (DB: Change sweepformula notebook to be a formatted notebook, 2022-04-27)
6a155771 (Adapted Sweepformula help notebook for required convention, 2022-04-27)

Jeep.

44772c13 (DB: Add tooltip help and syntax coloring support for sweepformula notebook, 2022-04-26)

BSP_SFHelpWindowHook:

- You are executing code for events which you are not interested in. Functions like LBV_CloseSettingsHistoryHook only have declarations outside of the eventCode switch. This is done so that the hook is cheap to call for other events like mouse over, etc.
- Please prefer an early break so that the indentation level can be decreased
- We have GetNotebookText instead of `Notebook... getData=4`

BSP_SFFormulaColoring:
 - The codebase is now IP9 only so I think using range-based for loops should be preferred.
 
BSP_TTHookSFFormulaNB:
- I think GetTabID is easier to read than `str2num(GetGuiControlValue(s.winName, targetCtrl))`. The latter is preferred if you don't know the GUI control type.
- Same comment about early break and decreasing indentation
- Please don't use a hookResult variable. Just return 0/1. This is also mentioned in our coding guidelines, page 6 bottom. The example code from WM does not follow our rules ...
- Trailing newline at EOF. I'll enhance check-code.sh to find that in the future as well.

41b099b2 (Test: Verify that SF help has a section for each operation, 2022-04-27)

Nice!

**Comment by t-b** [comment]
Works nicely btw!

**Review by t-b — APPROVED** [review]
LGTM

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
