### PR TITLE
RA_SkipSweeps: Fix various corner cases

### PR DESCRIPTION
**Pull request by t-b**
- [x] Check tests. The new limiting probably broke the test. We can also wait to the second IT for skipping back.

The current code did not expect that you call first without
limitToSetBorder=0 and then with limitToSetBorder=1.

It was also not working for -inf and did not adjust the active set count
correctly when limitToSetBorder=0.

These bugs are now fixed. The solution is to first calculate a skipCount
which is limited to the set borders if requested. And when a new count
is calculated using RA_SkipSweepCalc and the so calculated count offset
is used for adjusting count and the activeSetCount.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b with indexing, I'm finding I can skip to the end of a RA cycle but there is no indexing. The behavior I was expecting was that sweep skipping would be limited to the number of sweeps in the active set.

**Comment by t-b** [comment]
> @t-b with indexing, I'm finding I can skip to the end of a RA cycle but there is no indexing. The behavior I was expecting was that sweep skipping would be limited to the number of sweeps in the active set.

We can do that, but that is not what we are currently doing.

See https://github.com/AllenInstitute/MIES/blob/6177df3e29dc3238c254ab8067d1adff0d9307e9/Packages/MIES/MIES_DAEphys.ipf#L5080-L5090 and https://github.com/AllenInstitute/MIES/blob/6177df3e29dc3238c254ab8067d1adff0d9307e9/Packages/MIES/MIES_DAEphys.ipf#L5092-L5102

We would just need to pass `limitToSetBorder=1`.

**Comment by timjarsky** [comment]
> We would just need to pass `limitToSetBorder=1`.

@t-b let's try it!

**Comment by timjarsky** [comment]
@t-b I'm finding that indexing works correctly with skipping back and not skipping forward. 

option A, use limitsweepborder=1 with skip forward (and not back).
option B, make indexing work with skip forward.

**Comment by t-b** [comment]
@t-b Implement option A and add sweep skipping from ITI.

**Comment by t-b** [comment]
Done, I've also added one more test.

**Comment by timjarsky** [comment]
@t-b skipping backward is creating unexpected indexing steps (it indexes forward!). Do you want to limit skipping to set borders for forward and back?

**Comment by t-b** [comment]
> @t-b skipping backward is creating unexpected indexing steps (it indexes forward!). Do you want to limit skipping to set borders for forward and back?

Yes, I'll do that as well.

**Comment by t-b** [comment]
@timjarsky Done. Funny storry, I actually wondered why we would only use limitToSetBorder for one direction and not both.

**Comment by t-b** [comment]
Fixed the new test.

**Comment by timjarsky** [comment]
@t-b with limit to set border =1 and indexing, it is still possible to index backward so we aren't avoiding the indexing issues.

**Review by timjarsky — APPROVED** [review]
Merged with the knowledge that `limit to set border` only works with a single headstage or when the sets have the same length across multiple headstages.

**Pull request merged**
