### PR TITLE
Various dashboard enhancements

### LINKED ISSUE #2026: Make dashboard more intuitive together with OVS
When enabling the dashboard we also enable overlay sweeps (OVS). This can be confusing for users as then the left, right sweep buttons select the new seeps in addition to the shown sweeps.

Remedies:
- Remember OVS state when enabling dashboard
- On left/right sweep and sweep selection from popup menu
  - Disable dashboard and restore previous OVS state

### PR DESCRIPTION
**Pull request by t-b**
Including multi row selection as that is missing, at least I saw that in yesterdays live session.

Close #2026

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b If I push through this error (when enabling the dashboard and selecting passed sweeps without selecting a stimset).

```
  !!! Threadsafe assertion FAILED !!!
  Message: "Wave must exist"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
  AD_CheckProc_PassedSweeps(...)#L1213 [MIES_AnalysisFunctions_Dashboard.ipf]
AD_SelectResult(...)#L1094 [MIES_AnalysisFunctions_Dashboard.ipf]
GetUniqueEntries(...)#L856 [MIES_Utilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2024-03-04T13:14:59-08:00
  Experiment: Untitled ()
  Igor Pro version: 9.0.6.1 (56565)
  ################################
  ```

It's possible to use the dashboard to display multiple stimsets. Nice!

image

I get this error if passed sweeps are selected and there are no passing sweeps:

```
  ** WAVE gave error: WAVE reference to "sweepsWithDuplicatesClean" failed.
  !!! Threadsafe assertion FAILED !!!
  Message: "Wave must exist"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
  AD_ListBoxProc(...)#L1201 [MIES_AnalysisFunctions_Dashboard.ipf]
AD_SelectResult(...)#L1094 [MIES_AnalysisFunctions_Dashboard.ipf]
GetUniqueEntries(...)#L856 [MIES_Utilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2024-03-04T13:28:55-08:00
  Experiment: Untitled ()
  Igor Pro version: 9.0.6.1 (56565)
  ################################
  ** WAVE gave error: WAVE reference to "sweepsWithDuplicatesClean" failed.
```

**Comment by t-b** [comment]
@timjarsky Thanks for testing. We are striving to have tests for everything but you found something which we had no tests for. I fixed the assertion now and also added some tests.

**Comment by timjarsky** [comment]
@t-b, the dashboard is a delight to use now. Thanks!

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
CI build failure is an IP bug. I'm investigating.

**Pull request merged**
