### PR TITLE
PSQ_DAScale/PSQ_DS_ADAPT: Fix DAScale estimation after fill-in

### LINKED ISSUE #2224: Adaptive suprathreshold: Feedback from testing
FTP: issue-2224/H24.51.014.11.53.01.02.nwb

The bug report is that the fillin/overshoot correction is to dense.

Future DAScales:
- Sweep 65: 84.9999980255284;254.285712311242;92.4999980255284;
- 66: 84.9999980255284;254.285712311242;92.4999980255284;
- 67: 84.9999980255284;254.285712311242;92.4999980255284;100.159718920195;

We have AbsFrequencyMinDistance 10 and MaxFrequencyChangePercent 40, min norm DAScale step 1.09 and max 2.19.

The value 100.159718920195 should not have been choosen as we already have one at 100.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Why are we acquiring multiple passing sweeps with the same DAScale?
- [x] TJ provides new data

Close #2224

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Home-built installer is on the FTP `pr-2241`.

**Comment by timjarsky** [comment]
@t-b successful install on rig6, just in time for afternoon experiments. I'll let you know how it goes. Thanks again!

**Comment by timjarsky** [comment]
@t-b I uploaded `AdaptiveSupraExpWithLatestFix.pxp` file with several experiments collected with this PR's fix implemented. Some look good, some look odd. We previously identified that we need to enhance the `APfrequency` operation to have better spike detection, and another experiment where the cell went into depolarization block near the level used to search for spikes in this file confirms that.

**Comment by t-b** [comment]
Rebased to get CI going again.

**Comment by t-b** [comment]
Data from AdaptiveSupraExpWithLatestFix.zip (Date 4.09.24) has multiple MIES versions used:

```
  Dbh_Cre_KI_Ai65_751022_08_06_03: Release_2.7_20230809-1011-g87e194ac3
  Dbh_Cre_KI_Ai65_751022_08_06_02: Release_2.7_20230809-1011-g87e194ac3
  Dbh_Cre_KI_Ai65_751022_08_06_01: Release_2.7_20230809-1011-g87e194ac3
  C57BL6J_758777_11_04_02: Release_2.7_20230809-38-g89aadde03
  C57BL6J_758777_11_04_01: Release_2.7_20230809-38-g89aadde03
  C57BL6J_758778_12_04_01: Release_2.7_20230809-1011-g87e194ac3
  C57BL6J_755865_06_02_01: Release_2.7_20230809-969-g1a0233d30
  C57BL6J_755865_06_01_01: Release_2.7_20230809-969-g1a0233d30
  QN24_26_014_16_04A_01: Release_2.7_20230809-1011-g87e194ac3
  Dbh_Cre_KI_Ai65_751029_11_06_01: Release_2.7_20230809-969-g1a0233d30;Release_2.7_20230809-1011-g87e194ac3
  Dbh_Cre_KI_Ai65_751029_11_06_02: Release_2.7_20230809-969-g1a0233d30;Release_2.7_20230809-1011-g87e194ac3
```

this MR is 87e194ac3 (PSQ_DS_GetValuesOfLargestAPFreq: Only fetch passing data, 2024-08-21).

Mapping from sweepbrowser to experiment:

```
  Window: SweepBrowser8, Title: Browser [8] , Exp: workFolder:Dbh_Cre_KI_Ai65_751022_08_06_03
  Window: SweepBrowser7, Title: Browser [7] , Exp: workFolder:Dbh_Cre_KI_Ai65_751022_08_06_02
  Window: SweepBrowser6, Title: Browser [6] , Exp: workFolder:Dbh_Cre_KI_Ai65_751022_08_06_01
  Window: SweepBrowser5, Title: Browser [5] , Exp: workFolder:C57BL6J_758778_12_04_01
  Window: SweepBrowser4, Title: Browser [4] , Exp: workFolder:C57BL6J_755865_06_02_01
  Window: SweepBrowser3, Title: Browser [3] , Exp: workFolder:C57BL6J_755865_06_01_01
  Window: SweepBrowser2, Title: Browser [2] , Exp: workFolder:QN24_26_014_16_04A_01
  Window: SweepBrowser1, Title: Browser [1] , Exp: workFolder:Dbh_Cre_KI_Ai65_751029_11_06_01
  Window: SweepBrowser, Title: Browser , Exp: workFolder:Dbh_Cre_KI_Ai65_751029_11_06_02
```

**Comment by t-b** [comment]
First experiment I'm looking at (arbitrarily selected):

```
  Window: SweepBrowser5, Title: Browser [5] , Exp: workFolder:C57BL6J_758778_12_04_01;
  C57BL6J_758778_12_04_01: Release_2.7_20230809-1011-g87e194ac3
```

**Comment by t-b** [comment]
The changes in this PR search the sweep with the highest AP frequency and then fetch it's fitslope/fitoffset/etc. to calculate the next dascale value. But IMHO we should fetch the one with the highset **DAScale** value.

**Comment by t-b** [comment]
Have a look with fresh again on monday.

**Comment by t-b** [comment]
A set of fresh eyes still say that the change from Friday is good.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
