### PR TITLE
Inverted growth of pulses in image plot to top bottom in PA plot

### PR DESCRIPTION
**Pull request by MichaelHuth**
Visually new pulses from sweeps are added now to the top of the image plot.
The size of the average/deconvolution reserved space is minimum 5% of the visual y-size also on incremental update. Both are on the top.

Code got slightly less complex.

close https://github.com/AllenInstitute/MIES/issues/742
close https://github.com/AllenInstitute/MIES/issues/645

### CODE REVIEW

**Comment by timjarsky** [comment]
@MichaelHuth this is great. I especially like that the deconvolution is below the avg so there isn't a blank space when it is not in use. 

Could I ask that the vertical space for the avg and decon be increased by ~30%?

**Comment by MichaelHuth** [comment]
@timjarsky I increased the reserved area for the avg and deconvolution area from 5% by 30% to 6.5%. (So both use 13% now)

**Review by timjarsky — APPROVED** [review]

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
Just for the record: I've now added the PA_Tests.pxp to bamboo so it is also tested in CI.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b I just noticed that this PR removed the ability mouse over the vertical scale bar in the trace PA plot and zoom in or out using the scroll wheel.

**Comment by MichaelHuth** [comment]
@timjarsky I will look into that.

**Pull request merged**
