### PR TITLE
Bugfix/make layouting always work

### PR DESCRIPTION
**Pull request by t-b**
Well while I wanted to make it faster, I thought I fix it first.

The major new thing is `LayoutGraph` which updates the axes layout after adding sweeps. In a  future PR this will be needed when per sweep addition/removal is added.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b it won't compile in IP8 because of the variable declaration at the same time as it is being used to capture a return 

[STRUCT TiledGraphSettings tgs]

**Comment by timjarsky** [comment]
@t-b after I fix the compilation issues, I get:

  !!! Assertion FAILED !!!
  Message: "DataBrowser was not assigned to a specific device"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
AB_ButtonProc_LoadSweeps(...)#L2339 [MIES_AnalysisBrowser.ipf]
PGC_SetAndActivateControl(...)#L229 [MIES_ProgrammaticGUIControl.ipf]
SB_ButtonProc_ChangeSweep(...)#L566 [MIES_AnalysisBrowser_SweepBrowser.ipf]
SB_UpdateSweepPlot(...)#L332 [MIES_AnalysisBrowser_SweepBrowser.ipf]
PostPlotTransformations(...)#L3481 [MIES_MiesUtilities.ipf]
InitPostPlotSettings(...)#L3498 [MIES_MiesUtilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-07-13T11:13:59-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.0_20190602-1062-g551608cd
Date and time of last commit: 2020-07-13T19:26:28+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################

**Comment by t-b** [comment]
@timjarsky Fixed. I did not expect that to be IP9 code. I also fixed the assertion.

**Comment by timjarsky** [comment]
> @timjarsky Fixed. I did not expect that to be IP9 code. I also fixed the assertion.

I figured that out last week when I was asking you about multiple return syntax. It does seem silly to require a separate line to declare the object. 

I also noticed that you can't pass a variable into a wave index like: `[wavename[i]] = getVariable()`

**Comment by timjarsky** [comment]
@t-b regarding this PR....I did not find any issues but it did seem a few seconds slower. Is that possible?

**Comment by t-b** [comment]
@timjarsky It should not be slower. Anything special I should try?

**Pull request merged**
