### PR TITLE
Seal Evaluation analysis function

### LINKED ISSUE #1227: Analysis Function: Seal Evaluation [SE]
From https://ai-mies.slack.com/archives/D1P2AN29F/p1643859049062169:

To generate a sweep that IPFX can use to verify a Gigaohm sealMIES already publishes the seal state and the WSE automatically runs a cell attached sweep - the sweep is about 1 min long so that spontaneous spiking can be captured.The sweep will have 3 test pulses at the begining (TP group A) and 3 at the end (TP group B).

Pre DAQ

    check that indexing is disabled
    Verify clamp mode = v-clamp (no check for autobias)
    Include sampling frequency checks - default to 200 khz and sampling int multiplier = 1
    Enforce TP amplitude of stimset = 1
    Enforce 3 epoch per TP

Post sweep

    pass = group A or group B > SealThreshold
    fail = group A and group B < SealThreshold

    utilize SF in the same way as in pipette in bath analysis function to measure TPSteadyStateResistance

Post set:

->Publish:

    Set QC
    Seal resistance (max)

Post DAQ

    pick next stimset

List of analysis param:
- SamplingFrequency (optional, default: 200kHz)
- SamplingMultiplier (optional, default: 1)
- BaselineRMSLongThreshold (required)
- BaselinRMSShortThreshold (required)
- SealThreshold (optional, default: 1GΩ)
- NumberOfFailedSweeps (required)
- NextStimSetName (required, changed in POST_DAQ_EVENT)
- BaselineChunkLength (optional, default to 500ms)
- TestPulseGroupSelector (optional, default to `Both`). Options are `First`, `Second` or `Both`.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Allow to write user epochs in POST_SWEEP
- [x] Store also maximum resistance in LBN, use that for publishing
- [x] Document read/write support for each event in table.
- [x] Implement
- [x] Write tests
- [x] Add dashboard support
- [x] Flowchart
- [x] Add Published message tests and docu
- [x] Discuss chunk indexing with first/second testpulse groups. See PS_SE4.
- [x] Cleanup commits
- [x] Documentation
- [x] Discuss stimset shortening

Close #1227.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Should be ready for a first test.

**Comment by t-b** [comment]
For playing around also LBV_PlotAllAnalysisFunctionLBNKeys helps as it adds all LBN entries from this analysis function.

**Comment by timjarsky** [comment]
@t-b the stimset is failing with:
image
Does `pipette resistance` = analysis param:`seal resistance`

**Comment by timjarsky** [comment]
@t-b increase limits on short and long RMS to 100

**Comment by t-b** [comment]
@timjarsky 

> increase limits on short and long RMS to 100

BaselineRMSLongThreshold and BaselineRMSShortThreshold are required parameters. So you have to set them yourself.

>  Does pipette resistance = analysis param:seal resistance ?

Kind of, this was a C&P error. I've fixed it.

**Comment by timjarsky** [comment]
> @timjarsky
> 
> > increase limits on short and long RMS to 100
> 
> BaselineRMSLongThreshold and BaselineRMSShortThreshold are required parameters. So you have to set them yourself.

Values >20 cannot be set/saved to BaselineRMSLongThreshold and BaselineRMSShortThreshold

**Comment by t-b** [comment]
@timjarsky Got it now ;)

**Comment by timjarsky** [comment]
@t-b 

I think OVS is getting turned on by the analysis function but it should ensure it is OFF.

**Comment by t-b** [comment]
> I think OVS is getting turned on by the analysis function but it should ensure it is OFF.

Seal Evaluation is not turning it on, by I'm turning it off now. Should PipetteInBath also turn it off?

**Comment by timjarsky** [comment]
> > I think OVS is getting turned on by the analysis function but it should ensure it is OFF.
> 
> Seal Evaluation is not turning it on, by I'm turning it off now. Should PipetteInBath also turn it off?

@t-b Yes, have both analysis functions turn it off. The dashboard turns on OVS and dashboard use by end-users is common place. Until working with non-displayed data become an option, careful checking of what is being used in the SF may be necessary.

**Comment by t-b** [comment]
> Yes, have both analysis functions turn it off. The dashboard turns on OVS and dashboard use by end-users is common place. 
> Until working with non-displayed data become an option, careful checking of what is being used in the SF may be necessary.

Got it. I added a workaround if the user or the dashboard did turn on OVS. See 4fcce2a8 (PSQ_PipetteInBath: Handle turned on overlay sweeps correctly, 2022-02-28).

**Comment by timjarsky** [comment]
thank you @t-b, everything is working as expected.

**Pull request merged**
