### PR TITLE
PA: With TA the average wave is restricted to common range of all traces

### PR DESCRIPTION
**Pull request by MichaelHuth**
With time alignment enabled the pulses get shifted against each other,
such that their x position and the maximum position matches.
When average was applied to these sets the different count of pulses
at the left and right boundaries resulted in artefacts due to the
different statistics.

Now the average wave is restricted to the range where all pulses have data.
This is automatically carried over to the deconvolution data.

close https://github.com/AllenInstitute/MIES/issues/752

### CODE REVIEW

**Comment by t-b** [comment]
@MichaelHuth please rebase against latest main.

**Review by t-b — CHANGES_REQUESTED** [review]
@MichaelHuth Review:
- Code to restrict the range in PA_TAAdaptAverageWave looks good
- Test looks good
- But I think CA_OPTS_NO_DUPLICATE does not do the right thing here as you now modify the average wave or? And you should not modify a wave from the wave cache if you grabbed it via CA_OPTS_NO_DUPLICATE. Dropping `CA_OPTS_NO_DUPLICATE` for fetching would be easiest.

**Comment by MichaelHuth** [comment]
The cache issue is a valid point. Though I don't think it makes sense to do the duplicate there, as I do a duplicate directly after anyway to generate permanent waves.

Beside that, Setting a new scale on the pulse waves changes the wave modification and thus invalidates the cache. Thus, I need to do the restriction only before I put the average wave into the cache, not as currently done as after touch.

**Comment by MichaelHuth** [comment]
The other thing I talked about, where I thought was wrong was actually right. It was just some tricky code to allow a WAVE/Z in the function head of PA_StoreMaxAndUnitsInWaveNote (Because WAVE/WAVE/Z does not work).

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
