### PR TITLE
Enable tests for ITC 1600

### LINKED ISSUE #229: Add testing with ITC1600 and expand TTL tests
TTL handling is ITC device type specific and not very much tested at the moment.

### LINKED ISSUE #251: Enable tests with NI hardware on bamboo

### PR DESCRIPTION
**Pull request by t-b**
Close #229.
Close #251.

- [x] Requires #250 to be merged
- [x] apply ASLR fix on Windows 10 CI box
- [x] Remove rack1 TTL tests

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky The tests did not pass, here is the output

```
 Entering test case "PatchSeqTestRheobase#PS_RB7:ITC"
  Available number of specified ITC devices = 1
  DLL Error.
	Error in call to ITC_InitDevice.
	Reported error: Could not load rack FPGA (0x8A513000)
  The ITC XOP returned the following errors: ITCError=0x8a513000, ITCXOPError=0
  Could not load rack FPGA (0x8A513000);Place: User Layer; Connection: LCA; Error Type: Ready; Sequence Number: 0x1; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x0
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  ITC Device opened, returned deviceID is 0.
  (ITC1600_dev_0): Could not find final DAScale value from one of the previous analysis functions.
  TEST OVERRIDE ACTIVE
  (ITC1600_dev_0): Could not find final DAScale value from one of the previous analysis functions.
  DLL Error.
	Error in call to ITC_GetState.
	Reported error: System is not initialized (0x82503001)
  The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0
  System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  DLL Error.
	Error in call to ITC_GetDeviceInfo.
	Reported error: System is not initialized (0x82503001)
  The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0
  System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  DLL Error.
	Error in call to ITC_UpdateChannels.
	Reported error: System is not initialized (0x82503001)
  The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0
  System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  !!! Assertion FAILED !!!
  Message: "DAC error"
  Encountered "Abort" in test case "PatchSeqTestRheobase#PS_RB7", procedure file "UTF_PatchSeqRheobase.ipf"
  UTF background monitor has reached the timeout for reentry
  Entering reentry "PatchSeqTestRheobase#PS_RB7_REENTRY"
  0 == 9: is false  Assertion "CHECK_EQUAL_VAR(GetSetVariable(str, "SetVar_Sweep"), 9)" failed in line 480, procedure "UTF_PatchSeqRheobase.ipf"
  nan == 8: is false  Assertion "CHECK_EQUAL_VAR(sweepNo, 8)" failed in line 483, procedure "UTF_PatchSeqRheobase.ipf"
  nan == 7e-11: is false  Assertion "CHECK_EQUAL_VAR(initialDAScale, PSQ_GetFinalDAScaleFake())" failed in line 487, procedure "UTF_PatchSeqRheobase.ipf"
  nan == 0: is false  Assertion "CHECK_EQUAL_VAR(setPassed, 0)" failed in line 491, procedure "UTF_PatchSeqRheobase.ipf"
  Assumption that the first wave (wv1) exists: is false  Assertion "CHECK_EQUAL_WAVES(baselineQCWave, {0, 0, 1, 1, 1, 1, 1, 1, 1}, mode = WAVE_DATA)" failed in line 494, procedure "UTF_PatchSeqRheobase.ipf"
  Assumption that the first wave (wv1) exists: is false  Assertion "CHECK_EQUAL_WAVES(spikeDetectionWave, {NaN, NaN, 0, 0, 0, 0, 0, 0, 0}, mode = WAVE_DATA)" failed in line 497, procedure "UTF_PatchSeqR
heobase.ipf"
  Assumption that the wave's main type is 1: is false  Assertion "CHECK_WAVE(sweeps, NUMERIC_WAVE)" failed in line 500, procedure "UTF_PatchSeqRheobase.ipf"
  nan == 9: is false  Assertion "CHECK_EQUAL_VAR(numEntries, 9)" failed in line 502, procedure "UTF_PatchSeqRheobase.ipf"
  Assumption that the first wave (wv1) exists: is false  Assertion "CHECK_EQUAL_WAVES(stimScale, stimScaleRef, mode = WAVE_DATA, tol = 1e-14)" failed in line 509, procedure "UTF_PatchSeqRheobase.ipf"
  Assumption that the first wave (wv1) exists: is false  Assertion "CHECK_EQUAL_WAVES(durations, {3, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN}, mode = WAVE_DATA, tol = 0.01)" failed in line 512, procedure
 "UTF_PatchSeqRheobase.ipf"
  nan == 1e-11: is false  Assertion "CHECK_EQUAL_VAR(setPassed, PSQ_RB_DASCALE_STEP_LARGE)" failed in line 516, procedure "UTF_PatchSeqRheobase.ipf"
  Uncaught runtime error 10:"Make;the number of points in a wave must be between 0 and 21470 million." in test case "PatchSeqTestRheobase#PS_RB7", procedure file "UTF_PatchSeqRheobase.ipf"
  NAME:DAQWatchdog;PROC:WaitUntilDAQDone_IGNORE;RUN:0;PERIOD:120;NEXT:69156;QUIT:0;FUNCERR:0;
NAME:TPWatchdog;PROC:WaitUntilTPDone_IGNORE;RUN:0;PERIOD:120;NEXT:34236;QUIT:1;FUNCERR:0;
NAME:UTFBackgroundMonitor;PROC:UTFBackgroundMonitor;RUN:0;PERIOD:10;NEXT:69065;QUIT:0;FUNCERR:0;
NAME:ITC_TimerMD;PROC:DQM_Timer;RUN:0;PERIOD:6;NEXT:33556;QUIT:1;FUNCERR:1;
NAME:ITC_FIFOMonitorMD;PROC:DQM_FIFOMonitor;RUN:0;PERIOD:1;NEXT:33670;QUIT:1;FUNCERR:1;
NAME:ITC_FIFOMonitor;PROC:DQS_FIFOMonitor;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:ITC_Timer;PROC:DQS_Timer;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:TestpulseMD;PROC:TPM_BkrdTPFuncMD;RUN:0;PERIOD:5;NEXT:33553;QUIT:0;FUNCERR:1;
NAME:Testpulse;PROC:TPS_TestPulseFunc;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:P_ITC_FIFOMonitor;PROC:P_ITC_FIFOMonitorProc;RUN:0;PERIOD:10;NEXT:0;QUIT:0;FUNCERR:1;
  Leaving test case "PatchSeqTestRheobase#PS_RB7:ITC"
  Entering test case "PatchSeqTestRheobase#PS_RB6:ITC"
  DLL Error.
	Error in call to ITC_GetState.
	Reported error: System is not initialized (0x82503001)
  The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0
  System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Uncaught runtime error 196614:"ITCGetState2;Problem with ITC DLL." in user hook "TEST_CASE_BEGIN_OVERRIDE", procedure file "UTF_PatchSeqRheobase.ipf"
  Available number of specified ITC devices = 0
  Abort: Can not lock the device "ITC1600_Dev_0" as no devices of type "ITC1600" are connected.
  NAME:DAQWatchdog;PROC:WaitUntilDAQDone_IGNORE;RUN:0;PERIOD:120;NEXT:69060;QUIT:0;FUNCERR:1;
NAME:TPWatchdog;PROC:WaitUntilTPDone_IGNORE;RUN:0;PERIOD:120;NEXT:69060;QUIT:0;FUNCERR:1;
NAME:UTFBackgroundMonitor;PROC:UTFBackgroundMonitor;RUN:1;PERIOD:10;NEXT:69060;QUIT:0;FUNCERR:1;
NAME:ITC_TimerMD;PROC:DQM_Timer;RUN:0;PERIOD:6;NEXT:33556;QUIT:1;FUNCERR:1;
NAME:ITC_FIFOMonitorMD;PROC:DQM_FIFOMonitor;RUN:0;PERIOD:1;NEXT:33670;QUIT:1;FUNCERR:1;
NAME:ITC_FIFOMonitor;PROC:DQS_FIFOMonitor;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:ITC_Timer;PROC:DQS_Timer;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:TestpulseMD;PROC:TPM_BkrdTPFuncMD;RUN:0;PERIOD:5;NEXT:33553;QUIT:0;FUNCERR:1;
NAME:Testpulse;PROC:TPS_TestPulseFunc;RUN:0;PERIOD:5;NEXT:0;QUIT:0;FUNCERR:1;
NAME:P_ITC_FIFOMonitor;PROC:P_ITC_FIFOMonitorProc;RUN:0;PERIOD:10;NEXT:0;QUIT:0;FUNCERR:1;
  Leaving test case "PatchSeqTestRheobase#PS_RB6:ITC"
  Failed with 15 errors
  Leaving test suite "UTF_PatchSeqRheobase.ipf"
  Test finished with 15 errors
  End of test "MIES with Hardware"
```

but the MIES version used for testing is also a bit of frankenstein-variant. Can you uninstall the MIES version you installed for the ASLR fixes? And then I'll try again.

**Comment by timjarsky** [comment]
@t-b could the rack1 TTL checks be conditional? Can we check if the rack is present?

I'll approve so you can proceed as you see fit.

**Comment by t-b** [comment]
I think we can check.

Here is what `ITCGetDeviceInfo2 output` returns for the Windows 10 CI box:

grafik

What does it return on a ITC1600 with both racks?

**Comment by timjarsky** [comment]
@t-b 
image

**Comment by timjarsky** [comment]
@t-b I forgot that the new XOP creates it's own destination waves. Very nice!

**Comment by t-b** [comment]
@timjarsky Thx. So we the output differs on the number of supported channels. Nice! How about we just implement https://github.com/AllenInstitute/MIES/issues/131 which would disable non-available channels in the DAEphys panel?

**Comment by t-b** [comment]
@timjarsky No more wired errors on the Windows 10 box with the two-rack-ITC1600. I've started the bamboo agent as well and now let it run. Let's see how far we get.

I've added code as well to figure out the number of channels and racks for the hardware.

**Comment by t-b** [comment]
@timjarsky ITC1600 tests on Windows 10 passed :)

**Pull request merged**
