### PR TITLE
Extend epochs operation for wildcard usage and multiple specifiers

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1055

Example:
`epochs(["TP_*","E?_*"], select(channels(AD), sweeps()))`

### CODE REVIEW

**Comment by t-b** [comment]
Review:
- The issue also mentions `data`. Does that already work? If yes, this also needs a test

9f46fffe (Add utility functions GrepTextWaveToIndices, WildcardsToRegex, RegexEscape, 2022-12-08)

- Converting from wildcards to regexps is IMHO not the right thing to do. It does also not cover all edge cases of wildcard matching, see the help of stringmatch. Instead I would teach FindIndizes to support wildcards as well. See also f71ffd19 (FindIndizes: Add property PROP_GREP, 2022-04-25).


130eb7a0 (SF: Allow "?" as token in parser to enable wildcard option for strings, 2022-12-09)

`!` can also be used in wildcards as well. Needs tests.
 
ad0cdfa8 (SF: operation epochs add support for multiple wildcard expressions, 2022-12-08)

See first comment about FindIndizes.

6706fae6 (SF: Add epoch tests for wildcards and multiple argument entries, 2022-12-09)
50ebb0bd (SF: Adapt documentation for epochs operation, 2022-12-08)
6571725d (SF: Adapt sweepformula help notebook for changed epochs operation, 2022-12-08)

All good.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Comment by t-b** [comment]
Review:

ac2206db (Utils: Adapt FindIndices to support wildcard as property, 2022-12-13)

Good!

8bcd7a97 (Utils: FindIndizes use col=0 as default if col is not set, 2022-12-14)

Nice!

1966faac (FindIndizes calls, remove col=0 as it is now default, 2022-12-15)

Yeah!

1f458520 (SF: Allow "!" as token in parser to enable wildcard option for strings, 2022-12-09)

Yes!

309ab4f4 (SF: operation epochs add support for multiple wildcard expressions, 2022-12-08)

```
			EnsureLargeEnoughWave(output, minimumSize=index + 1)
```

I don't think the `+ 1` is necessary.

b3300643 (SF: Add epoch tests for wildcards and multiple argument entries, 2022-12-09)
75e725e1 (SF: Adapt documentation for epochs operation, 2022-12-08)
da8b0669 (SF: Adapt sweepformula help notebook for changed epochs operation, 2022-12-08)

All good!

a52578f1 (SF: Allow multiple wildcard epochs as range for data operation, 2022-12-14)

Same `+ 1` comment regarding EnsureLargeEnoughWave as above.

2a9f9264 (SF: Extend data operations test for multiple epochs argument, 2022-12-15)
e1dc2f7f (SF: Adapt documention of data operation for multi epoch argument, 2022-12-15)
da233841 (SF: Adapt SF help notebook for new data op multiple epochs argument, 2022-12-15)

Nice!

Testing with real data works as well.

**Comment by MichaelHuth** [comment]
@t-b The EnsureLargeEnoughWave commen tis correct, but I think the name of the minimumSize argument is misleading here as does not refer to the wave size, but to wave size minus one.

**Comment by t-b** [comment]
> The EnsureLargeEnoughWave commen tis correct, but I think the name of the minimumSize argument is misleading here as does not refer to the wave size, but to wave size minus one.

Good point, I've opened https://github.com/AllenInstitute/MIES/issues/1597 to track that.

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@MichaelHuth Needs conflict resolution.

**Review by t-b — DISMISSED** [review]

**Comment by timjarsky** [comment]
@t-b @MichaelHuth very nice!! Sorry it took me so long to test.

image

**Review by timjarsky — DISMISSED** [review]

**Comment by t-b** [comment]
@timjarsky No worries.
@MichaelHuth Can you fix the conflicts?

**Comment by MichaelHuth** [comment]
Rebased

**Comment by t-b** [comment]
@MichaelHuth Thx. Will merge once CI passes.

**Review by t-b — APPROVED** [review]

**Pull request merged**
