### PR TITLE
Testing: Always use rtFunctionErrors=1

### LINKED ISSUE #524: Fix try/catch without prior ClearRTError()
The following list needs fixing, found with `git grep -A1 "^[[:space:]]try\b"`:

```
MIES_AmplifierInteraction.ipf:	try
MIES_AmplifierInteraction.ipf-		ClearRTError()
--
MIES_AnalysisBrowser.ipf:	try
MIES_AnalysisBrowser.ipf-		ClearRTError()
--
MIES_AnalysisBrowser.ipf:	try
MIES_AnalysisBrowser.ipf-		h5_fileID = IPNWB#H5_OpenFile(nwb[%DiscLocation])
--
MIES_Async.ipf:	try
MIES_Async.ipf-		AbortOnValue var==0, 1
--
MIES_Async.ipf:	try
MIES_Async.ipf-		AbortOnValue var==0, 1
--
MIES_Async.ipf:	try
MIES_Async.ipf-		waitResult = ThreadGroupWait(tgID, 0);AbortOnRTE
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		wName = GetMainWindow(GetCurrentWindow())
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		if(usePanelTypeFromFile)
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		wName = GetMainWindow(GetCurrentWindow())
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		middleOfExperiment = ParamIsDefault(middleOfExperiment) ? 0 : !!middleOfExperiment
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		JSONXOP_Parse/Z=0/Q=0 str; AbortOnRTE
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		excCtrlTypes = SelectString(ParamIsDefault(excCtrlTypes), excCtrlTypes, "")
--
MIES_Configuration.ipf:	try
MIES_Configuration.ipf-		excCtrlTypes = SelectString(ParamIsDefault(excCtrlTypes), excCtrlTypes, "")
--
MIES_DAC-Hardware.ipf:	try
MIES_DAC-Hardware.ipf-		ClearRTError()
--
MIES_DAC-Hardware.ipf:	try
MIES_DAC-Hardware.ipf-		ClearRTError()
--
MIES_DAC-Hardware.ipf:	try
MIES_DAC-Hardware.ipf-		ClearRTError()
--
MIES_DataAcquisition_Multi.ipf:	try
MIES_DataAcquisition_Multi.ipf-		if(initialSetupReq)
--
MIES_DataAcquisition_Multi.ipf:	try
MIES_DataAcquisition_Multi.ipf-		for(i = 0; i < numFollower; i += 1)
--
MIES_DataAcquisition_Single.ipf:	try
MIES_DataAcquisition_Single.ipf-		DC_ConfigureDataForITC(panelTitle, DATA_ACQUISITION_MODE)
--
MIES_IVSCC.ipf:	try
MIES_IVSCC.ipf-		if(ssResistanceVal > 1000) // ssResistance value is in MOhms
--
MIES_IgorHooks.ipf:	try
MIES_IgorHooks.ipf-		ClearRTError()
--
MIES_IgorHooks.ipf:	try
MIES_IgorHooks.ipf-		ClearRTError()
--
MIES_MiesUtilities.ipf:	try
MIES_MiesUtilities.ipf-		ClearRTError()
--
MIES_SweepSaving.ipf:	try
MIES_SweepSaving.ipf-		ClearRTError()
--
MIES_TestPulse.ipf:	try
MIES_TestPulse.ipf-		ClearRTError()
--
MIES_TestPulse_Multi.ipf:	try
MIES_TestPulse_Multi.ipf-		// configure all followers
--
MIES_TestPulse_Single.ipf:	try
MIES_TestPulse_Single.ipf-		if(bkg)
--
MIES_Utilities.ipf:	try
MIES_Utilities.ipf-		AbortOnValue var==0, 1
--
MIES_Utilities.ipf:	try
MIES_Utilities.ipf-		AbortOnValue var==0, 1
```

### PR DESCRIPTION
**Pull request by t-b**
- [x] Wait for feedback on MoveWave from WM

Close #524.

### CODE REVIEW

**Comment by t-b** [comment]
You need the nightly from today.

@MichaelHuth The following test is failing

```
•runtest("UTF_AsynFrameworkTest.ipf", testcase = "TASYNC_RunErrorWorker")
  Start of test "Unnamed"
  Entering test suite "UTF_AsynFrameworkTest.ipf"
  Entering test case "AsynTest#TASYNC_RunErrorWorker"
  !!! Assertion FAILED !!!
  Message: "ReadOut function RunReadOutOfDOOM aborted with: NVAR;NVAR reference to "outV" failed."
  Encountered "Abort" in test case "AsynTest#TASYNC_RunErrorWorker", procedure file "UTF_AsynFrameworkTest.ipf"
  Leaving test case "AsynTest#TASYNC_RunErrorWorker"
  Failed with 1 errors
  Leaving test suite "UTF_AsynFrameworkTest.ipf"
  Test finished with 1 errors
  End of test "Unnamed"
```
THanks for looking into that.

**Comment by MichaelHuth** [comment]
With Debug On Error, the debugger always pops up now when opening Igor:

image

**Comment by t-b** [comment]
@MichaelHuth Thanks for the fix. I'll investigate the Debug on error issue.

**Comment by t-b** [comment]
Will merge when CI passes.

**Pull request merged**
