### PR TITLE
Bugfix/databrowser ddaq display mode

### LINKED ISSUE #803: PA plot and dDAQ option in databrowser does not work together
dDAQ turned on:

grafik

dDAQ turned off:

grafik

grafik

### PR DESCRIPTION
**Pull request by t-b**
Close #803

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b this works but it uncovered a related issue (dDaq doesn't work with averaging and overlay sweeps).

**Comment by t-b** [comment]
@timjarsky Fixed

**Comment by timjarsky** [comment]
@t-b old average trace isn't getting cleaned up when a new sweep is added with OS.

image

**Comment by t-b** [comment]
@timjarsky Fixed.

**Comment by timjarsky** [comment]
@t-b another related issue: dDAQ doesn't handle headstage removal with OS.

no  dDAQ:
image



dDAQ

image

**Comment by t-b** [comment]
Hmm something is wrong here. I'll look into it.

**Comment by t-b** [comment]
I can't reproduce that. And also looked at the code and I'd say it makes sense. I've pushed some unrelated fixes only. 

Can you retry with the latest version?

**Comment by timjarsky** [comment]
@t-b 
with HS removal:
image
without:
image

same test file I have been using for PA plot updates:
image

**Comment by t-b** [comment]
Next try. I've removed a "fix" fromt his PR which introduced that error.

**Comment by timjarsky** [comment]
@t-b dDAQ is looking good"

image

I think I can still find an edge case where trying to use headstage removal in dDAQ mode doesn't remove the sweep. Let's try it out the next time we chat. I suspect it will be an issue for a different PR but I want to check before merging this one.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
