### PR TITLE
CONF_RestoreHeadstageAssociation: Warn if Mies to MCC sync is not che…

### LINKED ISSUE #818: Configuration: Investigate holding apply issues
https://aiephys.slack.com/archives/C01CS4T8MGA/p1612919857017200

We might also want to warn users in `CONF_RestoreAmplifierSettings` when "Sync MIES to MCC" is not checked.

### PR DESCRIPTION
**Pull request by t-b**
…cked when restoring amplifier settings

This will most likely not do what the user expects, as MCC and MIES are
then unsynchronized.

Close #818

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b related to this, I'm finding that the TP is not starting (at the end of config) after getting these warnings (sync to amp is checked during config).

```
  ITC Device opened, returned deviceID is 0.
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the V_CLAMP_MODE.
  The gains were successfully imported for the I_CLAMP_MODE on i: 0
  There was a mismatch in clamp mode between MIES and the MCC. The MCC mode was switched to match the mode specified by MIES.
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the I_CLAMP_MODE.
  The gains were successfully imported for the V_CLAMP_MODE on i: 0
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the V_CLAMP_MODE.
  The gains were successfully imported for the I_CLAMP_MODE on i: 1
  There was a mismatch in clamp mode between MIES and the MCC. The MCC mode was switched to match the mode specified by MIES.
  No devices are presently assigned for pressure regulation on: ITC1600_Dev_1

```

**Comment by t-b** [comment]
> The gains were successfully imported for the I_CLAMP_MODE on i: 0

This should not happen at all, as we have "Sync MIES to MCC sync" checked.

**Comment by t-b** [comment]
@timjarsky Found something. This should also make the config faster.

**Comment by timjarsky** [comment]
@t-b MIES config is still stalling just before starting the TP when the MCC has holding currents on.

```
  Specified StimSet file at \\mp1\MiesHDF5Files\SavedStimSets\production_stimsets_23.nwb loaded successfully.
  Control Check_Settings_Append from config file does not exist in window DA_Ephys.
  Control setvar_Settings_DecMethodFac from config file does not exist in window DA_Ephys.
  ITC Device opened, returned deviceID is 1.
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the V_CLAMP_MODE.
  The gains were successfully imported for the I_CLAMP_MODE on i: 0
  There was a mismatch in clamp mode between MIES and the MCC. The MCC mode was switched to match the mode specified by MIES.
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the I_CLAMP_MODE.
  The gains were successfully imported for the V_CLAMP_MODE on i: 0
  It appears that a holding potential is being applied, therefore as a precaution, the gains cannot be imported for the V_CLAMP_MODE.
  The gains were successfully imported for the I_CLAMP_MODE on i: 1
  There was a mismatch in clamp mode between MIES and the MCC. The MCC mode was switched to match the mode specified by MIES.
  No devices are presently assigned for pressure regulation on: ITC1600_Dev_1
  path: "C:MiesSave:"
  (ITC1600_Dev_1) The configured gain for the DA channel 1 differs from the one in the "DAC Channel and Device Associations" menu (1 vs 20).
  (ITC1600_Dev_1) The configured gain for the AD channel 1 differs from the one in the "DAC Channel and Device Associations" menu (1 vs 0.01).
  (ITC1600_Dev_1) Please restart DAQ or TP to use the automatically imported gains from MCC.
```

**Comment by timjarsky** [comment]
@t-b I can't replicate the history in the previous comment. Maybe Igor had not compiled with the checked-out code.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
