### PR TITLE
Store chunk start/end/name as user epochs

### PR DESCRIPTION
**Pull request by MichaelHuth**
Thanks for opening a PR in MIES :sparkles:!

close https://github.com/AllenInstitute/MIES/issues/1040

### CODE REVIEW

**Comment by MichaelHuth** [comment]
I have added @todo to sweeps where the chunk times vary for different test runs.
I'am not sure how difficult it is to get always the same result for the test runs.
One option would be to allow to set the tolerance of the CHECK_CLOSE_VAR tests. Though this would probably not be very reliable.

**Comment by t-b** [comment]
@MichaelHuth Reassigning to you per our chat for the PSQ_Chirp fixes.

**Comment by t-b** [comment]
I know I'm not supposed to be given feedback when not assigned but still in the spirit of getting this done quickly I'll do it ;)

Review:
- drop reserving commit (creating an empty commit via `git commit --allow-empty` also does the job, and this automatically removed on the next rebase)
- on the next chat we can also take a stab of adding the pre push hook for enforcing the right branch naming scheme
- remove @todo in chirp tests
- Move the user epoch info from epoch_information.rst to MIES_AnalysisFunctions_PatchSeq.ipf. We already have an RST block at the top, you can use that. And while you are at it, please also document the Ramp suppression user epochs from f063c50c (PSQ_Ramp: Add user epochs for special AD/DA ranges, 2021-09-20). The user epochs are specific to the patchseq analysis functions and not for all analysis functions. Sorry for not noting that earlier, you also asked about it already.
- CheckUserEpochsFromChunks and CheckPSQChunkTimes have duplicated code for getting the wanted user epochs. I think getting user epochs should have its own function. I'm attaching my stab. Also iterating only over active headstages should be faster as well.
- Use IsEven/IsOdd instead of homebrewn `mod(XX, 2)`

[patch.txt](https://github.com/AllenInstitute/MIES/files/7520541/patch.txt)

**Comment by MichaelHuth** [comment]
@t-b Ready for another review

**Comment by t-b** [comment]
@MichaelHuth Thanks.

Code and tests look mostly good.

Some minor nits:
- `EP_GetEpochs` sorry for being vague earlier on. This should be `Function/WAVE EP_GetEpochs(WAVE numericalValues, WAVE textualValues, variable sweepNo, variable channelType, variable channelNumber, variable treelevel, string shortname)` the caller should figure out the DAC. Assert out if channelType is not XOP_CHANNEL_TYPE_DAC.  For your use cases the caller can figure out the DAC via `AFH_GetDACFromHeadstage`. 
-  `If analysis functions are enabled the analyzed chunks are saved as user epochs in the following format:` -> `All Patch Seq analysis functions performing baseline QC checks (DA, RB, RA, CR) store the following user epochs:
- Move the user epoch info into MIES_AnalysisFunctions_PatchSeq.ipf not MIES_AnalysisFunctions.ipf
- `RA_UD`/`RA_DA` these don't have the U_ prefix as the analyis chunks in the rst table. I don't have a strong opinion on how to to it, but it should be consistent.

**Comment by t-b** [comment]
@MichaelHuth Please drop `LBN_XOP_CHANNEL_NAMES ` and this is good to go.

**Comment by t-b** [comment]
@MichaelHuth @timjarsky LGTM. Herculescean task in adapting the test cases. I'll don't approve via github to not mess up auto-merge.

**Comment by timjarsky** [comment]
@t-b @MichaelHuth 

1. CH is a common abbreviation for channel. Let's use something different for chunk e.g., Chk. I'm open to suggestions on this.
2. The timing of of the User chunks seems odd. Is it really true that the Chunk 0 (Cursor D) starts before the stimset? (see plot below). Also, is the gap between the TP and the stimset expected?

image

**Comment by t-b** [comment]
Naming: BLC for baseline chunks
Regarding the user epoch for the chunks, we decided to not do anything as this can not be solved in general.

**Comment by t-b** [comment]
So here is what I did:
- fixed conflicts
- Added chunk time test assertions to the testcases from 69a1304f (Tests/PSQ analysis functions: Check for sampling interval QC labnotebook entry, 2021-11-10)
- Renamed the baseline chunks tags and short names. We now can access the Index directly and don't have to do string parsing ourselves
- Nicified the documentation
- Fixed some errors

git range-diff --ignore-all-space @{u}...HEAD

```range-diff
 -:  --------- >  1:  3fc2c8852 Documentation: AnalysisFunctions_V3 -> AnalysisFunction_V3
 -:  --------- >  2:  83362f55f Tests PSQ: Set sampling multiplier and frequency as analysis parameters
 -:  --------- >  3:  0a2679be7 Tests: Add more checks for baseline related labnotebook values
 -:  --------- >  4:  af67d7708 PSQ analysis functions: Enforce that we have the correct sampling frequency
 -:  --------- >  5:  84cf42fad PSQ_EvaluateBaselineProperties: Pass in the full AnalysisFunction_V3 struct
 -:  --------- >  6:  0b2931289 Patch Seq analysis functions: Make the baseline RMS short/long thresholds configurable
 -:  --------- >  7:  0aac885d7 patch-seq-chirp.dot: Remove subgraph
 -:  --------- >  8:  4debaaf0a patch-seq-chirp.dot: Remove wrong "Have three sweeps failed" node
 -:  --------- >  9:  195b3de88 Patch seq flowcharts: Update them
 -:  --------- > 10:  c8ef98179 tools/cleanup-dotfiles.sh: Add script for cleaning up dot files
 -:  --------- > 11:  3c09897e1 Packages/doc/dot/Readme.md: Update it
 -:  --------- > 12:  313cc8c5e UTF_PatchSeqRamp.ipf/AcquireData: Add support for preAcquireFunc
 -:  --------- > 13:  df4a12086 UTF_PatchSeqRamp.ipf/UTF_PatchSeqRheobase.ipf: Remove erroneous comment
 -:  --------- > 14:  1c2893434 Tests/Patch seq analysis functions: Add support for preAcquireFunc in AcquireData
 -:  --------- > 15:  69a1304ff Tests/PSQ analysis functions: Check for sampling interval QC labnotebook entry
 -:  --------- > 16:  94e064fda PSQ_EvaluateBaselineProperties: Rework test override integration
 -:  --------- > 17:  6afd6eb5a MIES_Constants.ipf: Raise PSQ analysis function versions
 1:  ef54b5310 ! 18:  66963917e Epochs: Add Epochs utility function that allows to retrieve Epochs from the LBN
    @@ Packages/MIES/MIES_Epochs.ipf: static Function EP_AdaptEpochInfo(string panelTit
      	endfor
      End
     +
    -+// @brief Get epochs from the LBN filtered by given parameters
    -+//
    -+// @param numericalValues Numerical values from the labnotebook
    -+// @param textualValues   Textual values from the labnotebook
    -+// @param sweepNo         Number of sweep
    -+// @param channelType     type of channel @sa XopChannelConstants
    -+// @param channelNumber   number of channel
    -+// @param treelevel       tree level of epochs
    -+// @param shortname       short name filter as regular expression
    -+// @returns Text wave with epoch information, only rows fitting the input parameters are returned. Can also be a null wave.
    ++/// @brief Get epochs from the LBN filtered by given parameters
    ++///
    ++/// @param numericalValues Numerical values from the labnotebook
    ++/// @param textualValues   Textual values from the labnotebook
    ++/// @param sweepNo         Number of sweep
    ++/// @param channelType     type of channel @sa XopChannelConstants
    ++/// @param channelNumber   number of channel
    ++/// @param treelevel       tree level of epochs
    ++/// @param shortname       short name filter as regular expression
    ++///
    ++/// @returns Text wave with epoch information, only rows fitting the input parameters are returned. Can also be a null wave.
     +Function/WAVE EP_GetEpochs(WAVE numericalValues, WAVE textualValues, variable sweepNo, variable channelType, variable channelNumber, variable treelevel, string shortname)
     +
     +	variable index
    @@ Packages/MIES/MIES_Epochs.ipf: static Function EP_AdaptEpochInfo(string panelTit
     +
     +	WAVE/Z indizesLevel = FindIndizes(epochInfo, col = EPOCH_COL_TREELEVEL, var = treelevel)
     +
    ++	if(!WaveExists(indizesLevel))
    ++		return $""
    ++	endif
    ++
     +	// @todo add support for grepping in FindIndizes later
     +	Make/FREE/N=(DimSize(epochInfo, ROWS)) indizesName = GrepString(EP_GetShortName(epochInfo[p][EPOCH_COL_TAGS]), shortName) ? p : NaN
     +
 2:  3814c80ed <  -:  --------- AnalysisFuncs: Add chunks as user epochs
 -:  --------- > 19:  db26df3fb PSQ analysis functions: Add chunks as user epochs
 3:  e17d0bf30 ! 20:  e86d5afdf AnalysisFuncs: Test for user epochs for chunks
    @@ Packages/Testing-MIES/UTF_HardwareMain.ipf: Function TEST_CASE_END_OVERRIDE(name
     +			endif
     +
     +			DAC = AFH_GetDACFromHeadstage(dev, j)
    -+			WAVE/T/Z userChunkEpochs = EP_GetEpochs(numericalValues, textualValues, sweeps[i], XOP_CHANNEL_TYPE_DAC, DAC, EPOCH_USER_LEVEL, EPOCH_SHORTNAME_USER_PREFIX + "CH[0-9]+")
    ++			WAVE/T/Z userChunkEpochs = EP_GetEpochs(numericalValues, textualValues, sweeps[i], XOP_CHANNEL_TYPE_DAC, DAC, EPOCH_USER_LEVEL, EPOCH_SHORTNAME_USER_PREFIX + PSQ_BASELINE_CHUNK_SHORT_NAME_PREFIX + "[0-9]+")
    ++
     +			if(!WaveExists(userChunkEpochs))
     +				continue
     +			endif
     +
    -+			if(DimSize(userChunkEpochs, ROWS))
     +			CheckUserEpochChunkUniqueness(userChunkEpochs)
     +			CheckUserEpochChunkNoOverlap(userChunkEpochs)
    -+			endif
     +		endfor
     +	endfor
     +
    @@ Packages/Testing-MIES/UTF_HardwareMain.ipf: Function TEST_CASE_END_OVERRIDE(name
     +
     +static Function CheckUserEpochChunkUniqueness(WAVE/T epochInfo)
     +
    -+	variable numEpochs, strOffset
    ++	variable numEpochs
     +
    -+	strOffset = strlen(EPOCH_SHORTNAME_USER_PREFIX + "CH")
     +	numEpochs = DimSize(epochInfo, ROWS)
     +	Make/FREE/D/N=(numEpochs) chunkNums, chunkRef
     +
    -+	chunkNums = str2num(EP_GetShortName(epochInfo[p][EPOCH_COL_TAGS])[strOffset, Inf])
    ++	chunkNums = NumberByKey("Index", epochInfo[p][EPOCH_COL_TAGS], "=")
     +	Sort chunkNums, chunkNums
     +
     +	chunkRef = p
 4:  e1734e396 ! 21:  d96fc6beb PatchSeq Tests: Add Test utility function for chunk time verification
    @@ Packages/Testing-MIES/UTF_HardwareMain.ipf: Function/S GetExperimentNWBFileForEx
     +			endif
     +
     +			DAC = AFH_GetDACFromHeadstage(dev, j)
    -+			WAVE/T/Z userChunkEpochs = EP_GetEpochs(numericalValues, textualValues, sweeps[i], XOP_CHANNEL_TYPE_DAC, DAC, EPOCH_USER_LEVEL, EPOCH_SHORTNAME_USER_PREFIX + "CH[0-9]+")
    ++			WAVE/T/Z userChunkEpochs = EP_GetEpochs(numericalValues, textualValues, sweeps[i], XOP_CHANNEL_TYPE_DAC, DAC, EPOCH_USER_LEVEL, EPOCH_SHORTNAME_USER_PREFIX + PSQ_BASELINE_CHUNK_SHORT_NAME_PREFIX + "[0-9]+")
     +			if(!WaveExists(userChunkEpochs))
     +				continue
     +			endif
    @@ Packages/Testing-MIES/UTF_HardwareMain.ipf: Function/S GetExperimentNWBFileForEx
     +
     +			Make/FREE/T/N=(numChunks) epochShortNames = EP_GetShortName(userChunkEpochs[p][EPOCH_COL_TAGS])
     +			for(k = 0; k < numChunks; k += 1)
    -+				str = EPOCH_SHORTNAME_USER_PREFIX + "CH" + num2istr(k)
    ++				str = EPOCH_SHORTNAME_USER_PREFIX + PSQ_BASELINE_CHUNK_SHORT_NAME_PREFIX + num2istr(k)
     +				FindValue/TEXT=str/TXOP=4 epochShortNames
     +				index = V_Value
     +				CHECK_NEQ_VAR(index, -1)
 5:  3ce10728e ! 22:  170c8a5ff Fix for PSQChirp function to not skip baselineQC check on spikecheck fail
    @@ Packages/MIES/MIES_Constants.ipf
      
      /// @name Analysis function versions
      /// @{
    --Constant PSQ_CHIRP_VERSION         = 1
    -+Constant PSQ_CHIRP_VERSION         = 2
    - Constant PSQ_DA_SCALE_VERSION      = 1
    - Constant PSQ_RAMP_VERSION          = 2
    - Constant PSQ_RHEOBASE_VERSION      = 1
    +-Constant PSQ_CHIRP_VERSION         = 2
    ++Constant PSQ_CHIRP_VERSION         = 3
    + Constant PSQ_DA_SCALE_VERSION      = 2
    + Constant PSQ_RAMP_VERSION          = 3
    + Constant PSQ_RHEOBASE_VERSION      = 2
 -:  --------- > 23:  692814c74 Tests/PS_SP8: Fix comment
 6:  a7c386e40 ! 24:  fa975e7a7 PatchSeq Tests: Add chunk times test for DAScale analysis functions
    @@ Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf: Function PS_DS_Sub8_REENTRY([str]
     +	CheckPSQChunkTimes(str, {20, 520, 2020, 2520}, sweep = 8)
      End
      
    - // The decision logic *without* FinalSlopePercent is the same as for Sub, only the plotting is different
    + Function PS_DS_Sub9_Ignore(device)
    +@@ Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf: Function PS_DS_Sub10_REENTRY([str])
    + 	CHECK_EQUAL_VAR(MIES_PSQ#PSQ_GetLastPassingDAScaleSub(str, PSQ_TEST_HEADSTAGE), -1)
    + 
    + 	CommonAnalysisFunctionChecks(str, sweepNo, setPassed)
    ++	CheckPSQChunkTimes(str, {20, 520, 2020, 2520})
    + End
    + 
    + // no baseline checks for supra
     @@ Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf: Function PS_DS_Supra1_REENTRY([str])
      	CHECK_EQUAL_VAR(MIES_PSQ#PSQ_GetLastPassingDAScaleSub(str, PSQ_TEST_HEADSTAGE), -1)
      
 7:  9ff1bb451 ! 25:  34a198f49 PatchSeq Tests: Add chunk times test for Chirp analysis functions
    @@ Packages/Testing-MIES/UTF_PatchSeqChirp.ipf: static Function PS_CR13_REENTRY([st
     +	CheckPSQChunkTimes(str, {20, 520}, sweep = 3)
     +	CheckPSQChunkTimes(str, {20, 520}, sweep = 4)
      End
    + 
    + static Function PS_CR14_IGNORE(string device)
    +@@ Packages/Testing-MIES/UTF_PatchSeqChirp.ipf: static Function PS_CR14_REENTRY([str])
    + 	CHECK_EQUAL_WAVES(lbnEntries[%spikeCheck], {0}, mode = WAVE_DATA)
    + 
    + 	CommonAnalysisFunctionChecks(str, sweepNo, lbnEntries[%setPass])
    ++	CheckPSQChunkTimes(str, {20, 520})
    + End
 8:  7450dfa0d ! 26:  2b119e3d0 PatchSeq Tests: Add chunk times test for Ramp analysis functions
    @@ Packages/MIES/MIES_Structures.ipf: threadsafe Function [STRUCT NWBAsyncParameter
     +EndStructure
     
      ## Packages/Testing-MIES/UTF_PatchSeqRamp.ipf ##
    -@@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function/WAVE FindUserEpochs(WAVE/T userEpochs)
    - 	return foundIt
    +@@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function/WAVE GetSamplingIntervalQCResults_IGNORE(sweepNo, device)
    + 	return GetLastSettingIndepEachRAC(numericalValues, sweepNo, key, UNKNOWN_MODE)
      End
      
     +/// @brief Retrieve the time interval for the post baseline chunk interval
    @@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function PS_RA1_REENTRY([str]
     +	CheckPSQChunkTimes(str, {20, 520})
      End
      
    - // we don't test the BL QC code path here anymore
    + // UTF_TD_GENERATOR HardwareMain#DeviceNameGeneratorMD1
     @@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function PS_RA2_REENTRY([str])
      	CHECK_EQUAL_WAVES(durations, {15000, 15000, 15000}, mode = WAVE_DATA, tol = 1)
      
    @@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function PS_RA6_REENTRY([str]
     +	[chunkStart, chunkEnd] = GetPostBaseLineInterval(str, 2, 1)
     +	CheckPSQChunkTimes(str, {20, 520, chunkStart, chunkEnd}, sweep = 2)
      End
    + 
    + static Function PS_RA7_IGNORE(string device)
    + 	AFH_AddAnalysisParameter("Ramp_DA_0", "SamplingFrequency", var=10)
    + End
    + 
    +-// Same as PS_RA1 but with failing sampling interval check
    ++// Same as PS_RA2 but with failing sampling interval check
    + //
    + // UTF_TD_GENERATOR HardwareMain#DeviceNameGeneratorMD1
    + static Function PS_RA7([str])
    +@@ Packages/Testing-MIES/UTF_PatchSeqRamp.ipf: static Function PS_RA7_REENTRY([str])
    + 	CHECK_EQUAL_WAVES(durations, {15000}, mode = WAVE_DATA, tol = 1)
    + 
    + 	CommonAnalysisFunctionChecks(str, sweepNo, setPassed)
    ++	CheckPSQChunkTimes(str, {20, 520, 16020, 16520})
    + End
 9:  9a2249d25 ! 27:  1c5355038 PatchSeq Tests: Add chunk times test for Rheobase analysis functions
    @@ Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf: static Function PS_RB1_REENTRY([
     +	CheckPSQChunkTimes(str, {20, 520})
      End
      
    - // we don't test the BL QC code path here anymore
    + // UTF_TD_GENERATOR HardwareMain#DeviceNameGeneratorMD1
     @@ Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf: static Function PS_RB2_REENTRY([str])
      	CHECK_EQUAL_VAR(MIES_PSQ#PSQ_GetLastPassingLongRHSweep(str, PSQ_TEST_HEADSTAGE, PSQ_RHEOBASE_TEST_DURATION), -1)
      
    @@ Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf: static Function PS_RB10_REENTRY(
      	CommonAnalysisFunctionChecks(str, sweepNo, {setPassed})
     +	CheckPSQChunkTimes(str, {20, 520, 1023, 1523})
      End
    + 
    + static Function PS_RB11_IGNORE(string device)
    +@@ Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf: static Function PS_RB11_REENTRY([str])
    + 	CHECK_EQUAL_VAR(MIES_PSQ#PSQ_GetLastPassingLongRHSweep(str, PSQ_TEST_HEADSTAGE, PSQ_RHEOBASE_TEST_DURATION), -1)
    + 
    + 	CommonAnalysisFunctionChecks(str, sweepNo, {setPassed})
    ++	CheckPSQChunkTimes(str, {20, 520})
    + End
10:  760569f2f ! 28:  18a385dad PatchSeq Tests: Add chunk times test for SquarePulse analysis functions
    @@ Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf: static Function PS_SP7_REENTR
     +	Make/FREE/N=0 chunkTimes
     +	CheckPSQChunkTimes(str, chunkTimes)
      End
    + 
    + static Function PS_SP8_IGNORE(string device)
    +@@ Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf: static Function PS_SP8_REENTRY([str])
    + 	CHECK_EQUAL_WAVES(stepSizes, {100e-12}, mode = WAVE_DATA, tol = 1e-13)
    + 
    + 	CommonAnalysisFunctionChecks(str, sweepNo, {setPassed})
    ++	Make/FREE/N=0 chunkTimes
    ++	CheckPSQChunkTimes(str, chunkTimes)
    + End
11:  437c1e849 <  -:  --------- AnalysisFunctions: Add documentation for user epochs added
```

**Comment by t-b** [comment]
@timjarsky I've added  d346f39 to also have that written down.

**Comment by t-b** [comment]
@timjarsky Done. Please reapprove.

**Review by timjarsky — APPROVED** [review]

**Review by t-b — DISMISSED** [review]

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
Approved myself, waiting for CI to finish and merge.

**Pull request merged**
