### PR TITLE
Use per trace pulse information in pulse average graph

### LINKED ISSUE #181: PulseAveraging: Use pulse information from each sweep and not only from the first sweep

### PR DESCRIPTION
**Pull request by t-b**
Close #181.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b this PR is working nicely. Now that it is possible to overlay all current clamp sweep I'm seeing that mixing frequencies results in multiple spikes being plotted. For example, see the one green trace in the PA plot.

dataBrowser:

image

PA plot:
image

Would it be possible to truncate the timeseries so that the next spike isn't included?

Also, I'm not sure what Adam would say if he saw this plot :)

**Comment by t-b** [comment]
@timjarsky I can look into that. Can you upload the data to the FTP and post the link here?

**Comment by timjarsky** [comment]
ftp://ftp10631232-alleninstitute@byte-physics.de/mixed_f_PAplot.pxp

**Comment by timjarsky** [comment]
@t-b if you select Recovery_50Hz_DA_0 (IC) in overlay sweeps and run time alignment in the PA plot you may get something like:

  Igor Pro version: 8.0.4.1 (33614)
  MIES version:
  ################################
  !!! Assertion FAILED !!!
  Message: "Could not find index"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
PA_CheckProc_Common(...)#L934 [MIES_PulseAveraging.ipf]
UpdateSweepPlot(...)#L5018 [MIES_MiesUtilities.ipf]
SB_UpdateSweepPlot(...)#L413 [MIES_AnalysisBrowser_SweepBrowser.ipf]
PostPlotTransformations(...)#L3092 [MIES_MiesUtilities.ipf]
PA_ShowPulses(...)#L731 [MIES_PulseAveraging.ipf]
PA_AutomaticTimeAlignment(...)#L1145 [MIES_PulseAveraging.ipf]
TimeAlignmentIfReq(...)#L3741 [MIES_MiesUtilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2019-06-13T09:48:33-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: mixed_f_PAplot.pxp
  Igor Pro version: 8.0.4.1 (33614)
  MIES version:
  ################################

image

**Comment by t-b** [comment]
Now this required a new level of debugging. I had to open two Igor instances ;)

The outlined pulse is 

```
•print GetUserData("PulseAverage", "T008665AD8_R4_P31_IDX148", "sweepNumber")
  77
•print GetUserData("PulseAverage", "T008665AD8_R4_P31_IDX148", "ChannelNumber")
  8
•print GetUserData("PulseAverage", "T008665AD8_R4_P31_IDX148", "ChannelType")
  AD
•print GetUserData("PulseAverage", "T008665AD8_R4_P31_IDX148", "pulseindex")
  31
```

and looking at the stimset wave note showed

```
  Version = 4;
Sweep = 0;Epoch = nan;ITI = 15;
Sweep = 0;Epoch = 0;Type = Pulse Train;Duration = 236.335;Amplitude = 1;Offset = 0;Pulse Type = Square;Frequency = 30;Pulse To Pulse Length = 33.3333;
Pulse duration = 3;Number of pulses = 8;Mixed frequency = False;First mixed frequency = 0;Last mixed frequency = 0;Poisson distribution = False;Random seed = 0.821411;
Pulse Train Pulses = 0,33.3333333333333,66.6666666666667,100,133.333333333333,166.666666666667,200,233.333333333333,;Definition mode = Pulse;
Sweep = 0;Epoch = 1;Type = Pulse Train;Duration = 997.59;
Amplitude = 1;Offset = 0;Pulse Type = Square;Frequency = 0;Pulse To Pulse Length = 33.3333;Pulse duration = 3;Number of pulses = 31;Mixed frequency = True;First mixed frequency = 10;
Last mixed frequency = 200;Poisson distribution = False;Random seed = 0.136788;
Pulse Train Pulses = 0,13.5720880829745,24.6871359290659,74.395141043112,174.395141043112,256.291513790904,311.219540956209,335.92839868039,366.099280363115,372.204556863453,439.274715555905,466.57834
210828,557.07495682275,573.64722690945,585.929507170608,660.042952081302,700.752005234993,709.854826250123,718.092571112334,754.932886098738,759.932886098738,766.679300337105,786.914958560621,792.4400
27112385,837.424088982692,844.878969211808,905.575192312099,938.914430224942,953.911773634745,972.224359292217,994.585039067215,;Definition mode = Pulse;
Sweep = 0;Epoch = 2;Type = Square pulse;
Duration = 200;Amplitude = 0;
Stimset;Sweep Count = 1;Epoch Count = 3;Pre DAQ = ;Mid Sweep = ;Post Sweep = ;Post Set = ;Post DAQ = ;Pre Sweep = ;Generic = SetControlInEvent;Pre Set = ;
Function params = setvar_DataAcq_OnsetDelayUser:textwave=Pre Set| 500|,setvar_DataAcq_TerminationDelay:textwave=Pre Set| 1000|,Setvar_DataAcq_dDAQDelay:textwave=Pre Set| 0|,setvar_DataAcq_dDAQOptOvPre
:textwave=Pre Set| 0|,setvar_DataAcq_dDAQOptOvPost:textwave=Pre Set| 250|,setvar_DataAcq_dDAQOptOvRes:textwave=Pre Set| 25|,valdisp_DataAcq_OnsetDelayAuto:textwave=Pre Set| 50|,Check_DataAcq1_DistribD
aq:textwave=Pre DAQ| 1|,;Flip = 0;Random Seed = 0.821411;Checksum = 1637283960;WP modification count = 4;WPT modification count = 3;SegWvType modification count = 4;
```

so we have two pulse trains. If you look closely enough you see that the second one has `Pulse To Pulse Length = 33.3333` as well as the first one. This is a bug which is, by accident, fixed since 29d4a0f2 (WB_PulseTrainSegment: Set pulseToPulseLength to 0 for mixed frequency, 2019-05-20).

And as it turns out we don't support extracting multiple pulse to pulse lengths from one stimset in https://github.com/AllenInstitute/MIES/blob/3b8ea4c6fabd474312f16ff428a1f89b53ec622f/Packages/MIES/MIES_WaveBuilder.ipf#L1499. I would suggest to return a pulse to pulse length of zero on that case. This our value for "can not be determined".

Now if you hack using the LBN pulse to pulse length away you should be able to use the fallback length for the pulse length but that does not work due some other issues.

I'll get it fixed,

**Comment by t-b** [comment]
@timjarsky Does it make sense to merge that now and fix the "other" issues regarding PA in a separate PR?

**Comment by t-b** [comment]
@timjarsky I've included the pulse train/length labnotebook removal here.

**Pull request merged**
