### PR TITLE
Sweepbrowser dashboard

### LINKED ISSUE #553: Dashboard: Add explanation as tooltip using helpWave keyword of listbox

### LINKED ISSUE #602: Dashboard: Add enable button
For users which do not use the dashboard it makes sense to allow disabling it, as it takes quite a bit of time to compute the information.

### PR DESCRIPTION
**Pull request by t-b**
Close https://github.com/AllenInstitute/MIES/issues/923
Close #553
Close #602

Requires #579 to be merged.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I really like how the dashboard allows the user to easily display the sweeps from a stimset run. Could there be a default analysis function that could be attached to a stimset (by default?) that just passes the sweeps? This way any stim set could take advantage of the dashboard display features.

**Comment by t-b** [comment]
@timjarsky Sure we can allow using the dashboard for all stimsets. But I would not bother with a default analysis function. I can just add every sweep to both passed and failed if it does not have an analysis function attached.

Let's see if I can make that happen today before the release.

**Comment by t-b** [comment]
@timjarsky Done. I'll get the other two dashboard issues done as well now.

**Comment by timjarsky** [comment]
@t-b failed sweeps are displaying;nice! DB dashboard now shows all acquired stimsets BUT the DB only shows the first sweep in the stimset when selecting the stimset from the dashboard (see image; all sweeps after sweep 61 are from the same stimset). This may be related to the fact that the dashboard is updating after the first sweep is acquired.

image

**Comment by t-b** [comment]
@timjarsky Can you upload the data? Thanks.

**Comment by timjarsky** [comment]
@t-b is it necessary for each headstage to have its own DB dashboard row for the same set of sweeps? I'm 100% okay with merging as is but let's talk about alternatives.

image

**Comment by t-b** [comment]
> @t-b is it necessary for each headstage to have its own DB dashboard row for the same set of sweeps? I'm 100% okay with merging as is but let's talk about alternatives.

The reason is that each headstage has its own stimset and therefore analysis function and therefore I'm going sweep-by-sweep and headstage-by-headstage basis. One could do some kind of compression where we only have one entry per sweep if all headstages have the same stimset/analysis function.

**Review by timjarsky — DISMISSED** [review]

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
