### PR TITLE
Add "NextIndexingEndStimsetName" where "NextStimsetName" is present

### LINKED ISSUE #1351: Add "NextIndexingEndStimsetName" to all analysis functions which have NextStimSetName
And do index juggling like in VM.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Update flowcharts
- [x] Merge #1361 and rebase

Close #1351.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I get;
```
  ################################
  The analysis function PSQ_PipetteInBath aborted with error "", this is dangerous and must *not* happen!
  !!! Assertion FAILED !!!
  Message: "Invald amplitude"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
RA_CounterMD(...)#L356 [MIES_RepeatedAcquisition.ipf]
DQM_StartDAQMultiDevice(...)#L180 [MIES_DataAcquisition_Multi.ipf]
DC_Configure(...)#L81 [MIES_DataConfigurator.ipf]
AS_HandlePossibleTransition(...)#L96 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L135 [MIES_AnalysisFunctionManagement.ipf]
PSQ_PipetteInBath(...)#L4560 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_CreateTestpulseEpochs(...)#L4755 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_CreateTestpulseLikeEpoch(...)#L4768 [MIES_AnalysisFunctions_PatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-05-14T10:59:17-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [52]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: trueRMPtesting (Packed)
  Igor Pro version: 9.0.1.1 (38961)
  MIES version:
  Release_2.5_20220415-136-g740d2fe39
Date and time of last commit: 2022-05-09T21:47:19+02:00
Submodule status: 
160000 f3493461480eaafa97939940693ed693860048a6 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 a8d4707e7c72555baefbb9a4d52de920e1d8ebb9 0	Packages/unit-testing
```

I think this happens when amplitude = 0, but as far as I can tell, it isn't zero.

**Comment by t-b** [comment]
Thanks for testing. I've fixed the assertion messages to be more informative. Can you attach the stimset you are using?

**Comment by t-b** [comment]
Rebased.

**Comment by timjarsky** [comment]
@t-b updated version of the message: ```"Invalid amplitude, expected zero for pre TP pulse BL"```

Stimset name EXTPBREAKN180424

**Comment by timjarsky** [comment]
[PR1362PR_testing-compressed_stimset.zip](https://github.com/AllenInstitute/MIES/files/8750431/PR1362PR_testing-compressed_stimset.zip)

**Comment by t-b** [comment]
With NumberOfTestpulses 3 the stimset has to have 11 epochs. Your's has 14. I've now enhanced the error checking to catch that case better.

**Comment by t-b** [comment]
Done. I'm now ignoring excess epochs.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
