### PR TITLE
XOPs: Update ITCXOP2

### LINKED ISSUE #1201: ITC device vanishes and later on crashes
@timjarsky Has since recently the problem that after using an ITC1600 device it sometimes vanishes, i.e. it can not be opened anymore. Closing all ITC devices also does not solve the issue. Only restarting solves the issue.

The following topics need investigation:
- [x] Write IP code to replicate the issue

Done:
- The NEW/CLEANUP messages of ITCXOP2 are called on Closing/New experiment and those message get CloseAllDevices() called.
- Can we make the XOP transient? No we can't. The XOP Toolkit manual says "XOPs that add operations
or functions are not allowed to be transient". And we do add operations.
- Can ITCXOP2 unload the itcmm library to avoid having us to close IP?

 Not so easily. These are the loaded DLLs by the 32bit and the 64bit XOP:

image

image

And as one might notice only the 32bit version loads the ITCMM.dll, the 64bit version not. In https://github.com/AllenInstitute/ITCXOP2/tree/main/itcmm we have ITCMM32.lib and ITCMM64.lib. Using the trick from  [1] it can be seen that ITCMM32.lib is an import library and ITCMM64.lib is a static library.

We can therefore not unload the ITC drivers for the 64bit XOP as these are not loaded as DLL. We can of course work around that by creating our own DLL und unloading that.

[1]: https://stackoverflow.com/a/6403559

### PR DESCRIPTION
**Pull request by t-b**
Close #1201

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b with this PR and breakme():

image
```•breakMe()
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_0;ITC1600_Dev_1;
  ITC1600_Dev_1;
  DLL Error.
	Error in call to ITC_GetState.
	Reported error: System is not initialized (0x82503001)
```

**Comment by timjarsky** [comment]
@t-b it's more or less the same in main. The only difference I noted was that main doesn't trigger the popup window.

**Comment by t-b** [comment]
```
  The ITC XOP returned the following errors: ITCError=0, ITCXOPError=20024
  The ITC XOP was called incorrectly, please inform the MIES developers!
  XOP error message: Unknown error code: 20024
  Responsible function: HW_ITC_CloseDevice
```

Looks like th recent ITCXOP2 changes broke it 24 is thread ID not set.

**Comment by t-b** [comment]
@timjarsky Updated. The looping logic is now included in the XOP. The ITCXOP tests pass.

**Comment by timjarsky** [comment]
@t-b log and pxp from 1600 testing have been uploaded to the ftp

**Comment by t-b** [comment]
@timjarsky Now this looks really good or? It did *not* crash!!!! Well we still might have some failing tests, but that is a piece of cake compared. Can you rerun the tests again this time without debugging enabled and post the PXP?

**Comment by timjarsky** [comment]
@t-b I'm passing back to you now that I've shared the testing results. Feel free to kick it back to me if there is something else you want me to dig into.

**Comment by t-b** [comment]
I've checked th NI CI box and there is no ITC1600 present.

**Comment by t-b** [comment]
Failing tests are:
```
[[F] TPDuringDAQTPStoreCheck:ITC1600 : TPDuringDAQTPStoreCheck:ITC1600 in UTF_BasicHardwareTests.ipf (5)](file:///E:/tim-data/ITC1600_test_results/Run_0002/test.xml.html#ddc1bd03-38fd-4908-af4c-0368050ca41f)
[[F] CheckThatTPsCanBeFound:ITC1600 : CheckThatTPsCanBeFound:ITC1600 in UTF_BasicHardwareTests.ipf (5)](file:///E:/tim-data/ITC1600_test_results/Run_0002/test.xml.html#946f15cb-b758-49a2-b2a5-d508fa1b6b0e)
[[F] RestoreDAEphysPanel:ITC1600 : RestoreDAEphysPanel:ITC1600 in UTF_BasicHardwareTests.ipf (5)](file:///E:/tim-data/ITC1600_test_results/Run_0002/test.xml.html#4dd2be0e-db66-45e9-93dd-50de7db850e1)
[[F] AsyncAcquisitionLBN:ITC1600 : AsyncAcquisitionLBN:ITC1600 in UTF_BasicHardwareTests.ipf (5)](file:///E:/tim-data/ITC1600_test_results/Run_0002/test.xml.html#f9921dc9-793a-4f4f-8ae6-350946bf87e8)
```

**Comment by timjarsky** [comment]
@t-b If you want to merge this and fix the failing tests in a different PR, go for it. 

Semi-related: when running the tests manually, I may forget to open the MCC first. With the ITC 1600 that seems to lead to a full crash. Is there a way the test code could open the MCC first?

**Comment by t-b** [comment]
> Semi-related: when running the tests manually, I may forget to open the MCC first. With the ITC 1600 that seems to lead to a full crash. Is there a way the test code could open the MCC first?

Well I cant automatically open it, as I did not find a way to choose between hardware and demo mode. So now I at least ensure that the MCC is open *before* locking the device.

> If you want to merge this and fix the failing tests in a different PR, go for it.

I think I'll try to fix it in this PR for now. But we do agree that the ITCXOP changes here, which are in source form at https://github.com/AllenInstitute/ITCXOP2/pull/16/files, work and should be merged?

**Comment by timjarsky** [comment]
> But we do agree that the ITCXOP changes here, which are in source form at https://github.com/AllenInstitute/ITCXOP2/pull/16/files, work and should be merged?
@t-b 
It works with my current hardware setup. Previously, when the second 1600 was available, there were issues. However, given the current testing success, yes, I think we are okay to merge. We can manage future issues with multiple 1600s in a separate PR.

**Comment by t-b** [comment]
I've fixed the failing tests with the ITC1600. None of them were related to ITC1600 but only to an actual amplifier being present. I now also started another test run on your machine.

**Comment by t-b** [comment]
Test run:

The tests passed until 

```
ITC_UpdateFIFOPosition
[...]
  UTF background monitor has reached the timeout for reentry
  Entering reentry "PatchSeqTestRheobase#PS_RB9_REENTRY"
  nan == 1e-11: is false. Assertion "CHECK_EQUAL_VAR(initialDAScale, PSQ_GetFinalDAScaleFake())" failed in line 753, procedure "UTF_PatchSeqRheobase.ipf"
```

which means the device stopped responding.

And then we have 

```
 The ITC XOP returned the following errors: ITCError=0x80303001, ITCXOPError=0
  DSP timeout (0x80303001)
```

for the rest of the tests.

I'm playing around at https://github.com/AllenInstitute/ITCXOP2/pull/17 with something which should make CloseAllDevices more robust.

**Comment by t-b** [comment]
@timjarsky Are you still fine with merging this now and continuing in a new PR? I think I changed my mind ;)

**Comment by timjarsky** [comment]
@t-b let me test with the most recent XOP updates. Then, yes?

**Comment by t-b** [comment]
@timjarsky Sure, we can do that.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
