### PR TITLE
Allow multiple graphs from SweepFormula

### LINKED ISSUE #1079: SweepFormula: invalid looking formula does not throw error
> not necessarily related to this PR, but the epochs function doesn't give an error when the 
> formatting of the epoch name is incorrect. e.g., ```epochs([0], channels(DA1),"Inserted TP;Test > pulse;)``` - no closing quotes.

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/issues/1074#issuecomment-929667578_

### PR DESCRIPTION
**Pull request by MichaelHuth**
Adds support for multiple graphs by using SweepFormula with the word "and" on a separate line.

Also fixed some more SweepFormula issues and revised some code quality.

The jsonId memory leak was not as critical as it appeared only on errorneous formulas.

close https://github.com/AllenInstitute/MIES/issues/300
Close #1079

### CODE REVIEW

**Comment by t-b** [comment]
A quick test from @timjarsky  shows that both graphs display the same data:

```
[1 ... 10] vs [100 ... 110]

and

[1] vs [2]
```

**Comment by timjarsky** [comment]
@MichaelHuth @t-b will graph management be part of this PR? The most immediate issue would be removing graphs when removing/deleting formulas. Other improvements could include linking the graphs and have a way to bring them to the foreground.

**Comment by t-b** [comment]
> will graph management be part of this PR?

I'd say yes.

> The most immediate issue would be removing graphs when removing/deleting formulas

Will do.

> Other improvements could include linking the graphs and a way to bring them to the foreground.

We can add a button to bring them to foreground. About "linking"; we thought about having a later improvement to be able to have mutliple plots in one graph. This should solve the billion-window-issue common to IP. We can also do that now if you prefer.

**Comment by t-b** [comment]
@MichaelHuth CI is working again. Please rebase against latest main.

**Comment by timjarsky** [comment]
@t-b 
> > The most immediate issue would be removing graphs when removing/deleting formulas
> 
> Will do.

Thank you

> > Other improvements could include linking the graphs and a way to bring them to the foreground.
> 
> We can add a button to bring them to foreground. About "linking"; we thought about having a later improvement to be able to   have mutliple plots in one graph. This should solve the billion-window-issue common to IP. We can also do that now if you         > prefer.

A button to bring the graphs to the top will be helpful - thanks

Multiple plots in one graph is another good idea. Yes, a separate PR is aOK. Priority wise, I'd put https://github.com/AllenInstitute/MIES/issues/1056 and https://github.com/AllenInstitute/MIES/issues/1055 ahead.

**Comment by t-b** [comment]
> A button to bring the graphs to the top will be helpful - thanks

Okay, so we'll do that as well.

**Comment by MichaelHuth** [comment]
Ok, the unused formula windows of the specific data browser are closed now on a new display attempt. And there is also a button to bring all formula plots of that databrowser to the front.

**Comment by timjarsky** [comment]
@MichaelHuth @t-b  `to front` button doesn't have the same anchoring as `display` and `check` buttons

image


not necessarily related to this PR, but the epochs function doesn't give an error when the formatting of the epoch name is incorrect. e.g., ```epochs([0], channels(DA1),"Inserted TP;Test pulse;)``` - no closing quotes. I suspect that error checking might be complicated. If that's the case, let's just make an issue for now.

The rest looks great!!

**Comment by t-b** [comment]
@MichaelHuth CI is broken because it is not rebased to latest main. Please do that.

**Comment by t-b** [comment]
@MichaelHuth I've just merged #1066. Can you solve the conflict? Thanks.

**Comment by t-b** [comment]
Review:
- Code looks mostly good. Just remove `// click code here` and `case -1: // control being killed ... break` from SF_button_sweepFormula_tofront.

Behaviour:
- Whitespace (space and tab) should be ignored in the `and` line. Changing the regexp to 
`static StrConstant SF_SWEEPFORMULA_GRAPHS_REGEXP = "^(.+?)(?:\\r[ \t]*and[ \t]*\\r(.*))?$"` does the trick here but please verify. Or maybe SF_PreprocessInput should call trimstring on every line?

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Comment by MichaelHuth** [comment]
> not necessarily related to this PR, but the epochs function doesn't give an error when the formatting of the epoch name is incorrect. e.g., `epochs([0], channels(DA1),"Inserted TP;Test pulse;)` - no closing quotes. I suspect that error checking might be complicated. If that's the case, let's just make an issue for now.

I think thats a general issue of the current string parsing, if the string is the last element in the code.

**Review by t-b — APPROVED** [review]
LGTM.

**Review by timjarsky — APPROVED** [review]

**Comment by timjarsky** [comment]
thank you @MichaelHuth

**Pull request merged**
