### PR TITLE
Extend GetActiveChannels with two more TTL modes

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1799
close https://github.com/AllenInstitute/MIES/issues/1798

### CODE REVIEW

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
Review:

Once #1791 is merged all ad-hoc TTL channel conversion code should be replaced with GetActiveChannels.

**Comment by t-b** [comment]
I've pushed an obvious fix for ITC18.

But even with that I still get

```
•runwithOpts(testcase = "UnassociatedChannelsAndTTLs", allowdebug=1)
  Start of test "MIES with HardwareBasic"
  Entering test suite "UTF_BasicHardwareTests.ipf"
  Entering test case "BasicHardwareTests#UnassociatedChannelsAndTTLs:ITC"
  Entering reentry "BasicHardwareTests#UnassociatedChannelsAndTTLs_REENTRY"
  Assuming equality using mode WAVE_DATA for waves _free_ (0x36b3b160) and _free_ (0x36b3b540); detailed: Waves difference:
Wave1: _free_ (0x36b3b160)
Wave2: _free_ (0x36b3b540)
 Dimensions | Labels | Value |
------------|--------|-------|
 [1][0]     |        | nan   |
            |        | 1     |
 [1][2]     |        | nan   |
            |        | 1     |
 [1][3]     |        | 3     |
            |        | 1     |
: is false. Assertion "CHECK_EQUAL_WAVES(channelHWtoGUIRef, channelHWtoGUI)" failed in BasicHardwareTests#UnassociatedChannelsAndTTLs_REENTRY (UTF_BasicHardwareTests.ipf, line 671)
  Leaving test case "BasicHardwareTests#UnassociatedChannelsAndTTLs:ITC"
  Failed with 1 errors
  Leaving test suite "UTF_BasicHardwareTests.ipf"
  Test finished with 1 errors
    ▶ Assertion "CHECK_EQUAL_WAVES(channelHWtoGUIRef, channelHWtoGUI)" failed in BasicHardwareTests#UnassociatedChannelsAndTTLs_REENTRY (UTF_BasicHardwareTests.ipf, line 671)
  End of test "MIES with HardwareBasic"
```

and the issues seems to be that in channelHWtoGUI row 1 is completely filled with 1. But we only expect the second and fourth to be set.

**Comment by MichaelHuth** [comment]
@t-b I found an indexing issue, where I was using p but index was running over the second dimension. I changed p -> q. Could you test once more with ITC please?

**Comment by t-b** [comment]
> @t-b I found an indexing issue, where I was using p but index was running over the second dimension. I changed p -> q. Could you test once more with ITC please?

Nice! The test now passes with ITC.

**Review by t-b — APPROVED** [review]
LGTM.

**Pull request merged**
