### PR TITLE
Analysis Browser: Also allow to load stimsets from stimset only files

### PR DESCRIPTION
**Pull request by MichaelHuth**
Files that do not contained any devices were ignored by the analysis browser.
Now they are shown in the list view.

- [x] Get Stimset loading working

close https://github.com/AllenInstitute/MIES/issues/1270

### CODE REVIEW

**Comment by t-b** [comment]
Review:

77ae0736 (Util: Add function to check for free datafolder IsFreeDatafolder, 2022-07-13)

Nice!

6aba46a6 (bugfix: Add support for free datafolders in GetListOfObjects, 2022-07-13)

Needs tests. We already have some.

2847cb8c (bugfix: AB_LoadDataWrapper changed the current DF, but did not restore the old, 2022-07-13)

Good!

bf79c7e6 (Moved non-NWB specific function to AnalysisBrowser procFile, 2022-07-13)

commit mesasge: "are now NWB specific" -> "are not NWB specifix", "revix" -> "prefix"

6f8f01af (Factor out StimSetList Getter and Stimset suffix removal for NWB loading, 2022-07-14)

Good!

f128f13d (AB: Allow to load all Stimsets from files containing only stimsets, 2022-07-13)

 - [ ] 
```
@@ -367,7 +444,6 @@ static Function AB_AddExperimentNameIfReq(expName, list, fileType, index)
     EnsureLargeEnoughWave(list, minimumSize=index, dimension=ROWS)
     list[index][%file][0] = expName
     list[index][%type][0] = fileType
-    index += 1
 End

 /// @brief Creates list-view for AnalysisBrowser
@
```

Unrelated change?

- [ ] There are some unrelated whitespace changes

- [ ] Should be done in the first commit

```
@@ -1513,7 +1607,7 @@ static Function AB_LoadFromFile(AB_LoadType, [sweepBrowserDFR])

     if(AB_LoadType == AB_LOAD_SWEEP)
         ASSERT(!ParamIsDefault(sweepBrowserDFR), "create sweepBrowser DataFolder with SB_OpenSweepBrowser() prior")
-        ASSERT(DataFolderRefStatus(sweepBrowserDFR) == 1, "sweepBrowser DataFolder does not exist")
+        ASSERT(IsGlobalDataFolder(sweepBrowserDFR), "sweepBrowser DataFolder does not exist")
     endif

     WAVE indizes = AB_GetExpandedIndices()
@
```

- [ ] AB_GetStimsetList: No dangling else. All code paths inside the if-statement either return or abort.
- [ ] AB_GetStimsetList: unused fileID variable

- [ ] "Load Stimsets"

When playing around I get an RTE when selecting the `mies-igor\Packages\Testing-MIES` folder:
>  BUG_TS: Encountered pending RTE: 748, WAVE;WAVE reference to "sweepNums" failed.

- [ ] "Load Sweeps" for a stimset only NWB aborts. It should not do anything or complain to the history.

The test failures in CI are unrelated.

**Comment by MichaelHuth** [comment]
I can't reproduce the BUG_TS message here.

**Comment by t-b** [comment]
> I can't reproduce the BUG_TS message here.

I forgot to mention the function involved. It is AB_FillListWave which is called with `$""` for sweepNums in one case.

The tests for new behaviour of GetListOfObjects are also still missing. This did not have a check box.

**Comment by t-b** [comment]
@MichaelHuth Please assign Tim directly once you are done.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
