### PR TITLE
Add demo concept example for changed Analysis Browser

### PR DESCRIPTION
**Pull request by MichaelHuth**
- multi folder support
- better treeview GUI handling

close https://github.com/AllenInstitute/MIES/issues/1099
close https://github.com/AllenInstitute/MIES/issues/1706

Failing Basic.pxp test SICP_EnsureValidGUIs needs PR https://github.com/AllenInstitute/MIES/pull/1732 .

### CODE REVIEW

**Comment by t-b** [comment]
Assigning to me and Tim for discussion.

**Comment by t-b** [comment]
Spoke with Tim about the draft design. Looks very nice!

Two minor modifications:
- Remove "brief view" checkbox and default to full folder path
- Add button to top level folder section to open the selected folders in the explorer (`PathInfo`)

**Comment by MichaelHuth** [comment]
@t-b I think it is in a good state for another round.

**Comment by MichaelHuth** [comment]
I added a bugfix for the nwb1 sweep loading issue. Though, from my tests it looks like the last copy loaded is the most complete. I can't say if it is generally the case, but would using the last loaded sweep be a viable solution as well?

**Comment by t-b** [comment]
Review:

59b49dc2 (Introduce Listbox reserved constants for color layer dimlabels, 2023-04-27)
07e1299a (Util: AskUserForExistingFolder now properly respects user pressing Cancel, 2023-05-09)
97bb5627 (AB: Updated GUI macro with newer design, 2023-04-27)
24eeeb56 (AB: Add constants for AB settings and AB panel name, 2023-05-09)
f2efca1c (AB: Add settings upgrade logic for upcoming multi folder listbox, 2023-05-09)
3240ed60 (AB: Add wave getters for new multi folder/file Listbox, 2023-05-09)
35f9c646 (AB: Adapt initialization for panel recreation, 2023-05-09)
c9fcb1c9 (AB: Revise AB_OpenAnalysisBrowser, 2023-05-09)
63c34e98 (AB: Search in GetMap the map in defined column and evaluate V_row, 2023-05-09)
c9c159fd (AB: Determine new ListBox wave size inside AB_ResetListBoxWaves, 2023-05-09)
9dd62dd0 (AB: On state reset, set list and selection wave to the same size, 2023-05-09)
5a00bdf6 (AB: Adapt AB_AddFile to also store the source entry in a list column, 2023-05-09)
a91c58b2 (AB: Add AB_AddExperimentEntries and AB_RemoveExperimentEntry, 2023-05-09)
512d1f81 (AB: Allow AB_AddMapEntry to use empty rows as well, 2023-05-09)
991b2edc (AB: Add AB_UpdateColors to show reference of experiment to source folder/file, 2023-05-09)
25f6f36d (AB: Add logic for new buttons, Add Files, Add Folders, Open, Remove, 2023-05-09)

All good.

80b80329 (AB: Add Refresh button functionality, 2023-05-09)
e84f8d62 (AB: Adapt BeforeFileOpenHook to new logic, 2023-05-09)
e9826f9a (AB: Fix several issues in experiment listbox event handler, 2023-05-09)
6bc56fa3 (AB: Move AnalysisBrowser Macro to its own procedure file, 2023-05-09)

```
+/// @file MIES_AnalysisBrowser.ipf
+/// @brief __ABM__ Analysis browser Macro
+///
+/// Has no dependencies on any hardware related functions.
```

->

```
+/// @file MIES_AnalysisBrowserMacro.ipf
+/// @brief __ABM__ Analysis browser Macro
```

c665a061 (AB: Increase AB panel version to 2, 2023-05-09)
68a8d0eb (Util: Add Reference Counter memory management functions for data folders, 2023-05-10)

Global variables/strings should always use the global variable getter logic. That should also make the code shorter as in (from the top of my head)

```igorpro
/// @brief For DF memory management, increase reference count
///
/// @param dfr data folder reference of the target df
/// @returns ref count after the increase
Function RefCounterDFIncrease(DFREF dfr)

	NVAR rc = GetDFReferenceCount(dfr)
	rc += 1

	return rc
End

/// @brief For DF memory management, decrease reference count
///
/// @param dfr data folder reference of the target df
/// @returns ref count after the decrease
Function RefCounterDFDecrease(DFREF dfr)

	NVAR rc = GetDFReferenceCount(dfr)
	rc -= 1

	if(rc == 0)
		KillOrMoveToTrash(dfr=dfr)
	endif

	return rc
End

...

Function/S GetDFReferenceCount(DFREF dfr)
	return GetNVARAsString(dfr, MEMORY_REFCOUNTER_DF, initialValue=0)
End
```

This has also removed the part where increasing the reference count kills the folder. In any case please add some tests for the reference count logic. I'm not checking the DFREF as GetNVARAsString does that for us.

70f5a3c7 (AB: Ref count based memory management of loaded DF, 2023-05-10)

The commit message fails to mentions *why* we are doing this.

AB_RemoveEmptyWorkingDF should probably reuse RemoveEmptyDataFolder.

BSP_MemoryFreeMappedDF should be able to combine Duplicate and Redimension as in

```igorpro
    numEntries = GetNumberFromWaveNote(map, NOTE_INDEX)

    if(!numEntries)
       return NaN
    endif

    Duplicate/FREE/RMD=[0, numEntries - 1][dim] map, dfList
    WAVE/T uniqueDF = GetUniqueEntries(dfList, dontDuplicate=1)
    dfABPath = GetDataFolder(1, GetAnalysisFolder())
    for(dfPath : uniqueDF)
        DFREF dfr = $(dfABPath + dfPath)
        RefCounterDFDecrease(dfr)
    endfor
```

38933c10 (bugfix: Catch RTE from IndexedFile/IndexedDir, 2023-05-10)

Good catch.

45d8d12f (AB: bugfix Set treeView column for devices to 3, 2023-05-11)
1ba3ee55 (AB: Change TreeView expansion for persistent tree view elements, 2023-05-11)
6dd63f4a (AB: Create experiment entries in list wave based on disklocation, 2023-05-11)
fb2d1219 (AB: Find the same row in the list based on the hash value, 2023-05-15)
2a5f5085 (Tests: Adapt test for AnalysisBrowser, 2023-05-09)
463fea9a (AB: bugfix handling of doubled waves in nwbv1 was insuffciient, 2023-05-11)

Looks all good. Thanks for these fixes.

IIRC we wanted to adjust the default search path to something else than `C:\` or? How about the user home?

Can you add some more tests for the AB? I'm attaching pxp/nwbv1/nwbv2 with data of two devices for it.
[Basic.zip](https://github.com/AllenInstitute/MIES/files/11508591/Basic.zip)

**Comment by t-b** [comment]
Also ready for @timjarsky for playing around.

**Comment by MichaelHuth** [comment]
@t-b Doe sit make sense that both of your nwb files for testing have doubled waves? From the description of the issue it sounded that should be only the case for nwbv1 files?

**Comment by t-b** [comment]
Rebased to get GH actions CI.

**Comment by t-b** [comment]
> @t-b Doe sit make sense that both of your nwb files for testing have doubled waves? From the description of the issue it sounded that should be only the case for nwbv1 files?

I don't see how AB_SweepsFromMultipleDevices-compressed-V2.nwb has duplicated waves. Can you clarify?

**Comment by MichaelHuth** [comment]
> > @t-b Doe sit make sense that both of your nwb files for testing have doubled waves? From the description of the issue it sounded that should be only the case for nwbv1 files?
> 
> I don't see how AB_SweepsFromMultipleDevices-compressed-V2.nwb has duplicated waves. Can you clarify?

Result from chat: Yes it can happen, because https://github.com/AllenInstitute/MIES/issues/978

**Comment by timjarsky** [comment]
@MichaelHuth, the new analysis browser looks great!

**Review by timjarsky — DISMISSED** [review]

**Review by t-b — DISMISSED** [review]

**Comment by t-b** [comment]
@MichaelHuth CI passes but there is a merge conflict. Please fix that and I can then have a look.

**Review by t-b — APPROVED** [review]

**Pull request merged**
