### PR TITLE
Programmatical stimset access

### LINKED ISSUE #74: Alllow to programmatically change the stimset parameters
- Add functions for modifying the parameters ala `WB_Setparam(stimset, sweep, epoch, paramName. [str, var])`
- Add tests and documentation
-  Allow the user to create a new stimset as well

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add documentation
- [x] Add tests for stimset API
- [x] Decide what to do with empty sets in WB_CreateStimset
- [x] Add mapping for popup menu entries were numbers are used but we would like to have strings
- [x] Add new example to compile testing
- [x] proper use of GetStimSetType

Close #74

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky You can give it a shot as well.

**Comment by t-b** [comment]
@timjarsky Ready

**Comment by timjarsky** [comment]
@t-b I'm uploading a file (stimsets not shown in daephy) to your ftp. Note the stimsets are viewable in the waveBuilder. Stimsets were loaded during the automated experiment config. Let me know if you need more info.

**Comment by t-b** [comment]
@timjarsky Can you post the commands which you used to create the stimset?

**Comment by timjarsky** [comment]
> @timjarsky Can you post the commands which you used to create the stimset?

No; this is a stimset that is loaded from a NWB. Do you want the stimset NWB file?

**Comment by t-b** [comment]
@timjarsky Fixed.

**Comment by timjarsky** [comment]
@t-b I'm still seeing an error in the popupmenu list

image

**Comment by t-b** [comment]
@timjarsky Öhh, yes. I've now really fixed it.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
