### PR TITLE
Add help and check functions for expected analysis function parameters

### LINKED ISSUE #124: Analysis Parameters:  Add a method to validate the input and show help
- [ ] Some analysis parameters have only a couple of known values. We could allow these to be checked in DAP_CheckSettings if it would be possible to set that in `_GetParams`.

One method could be to allow adding a function to the string

```
"DAScales:wave|CheckDAScales"
```

and this function would accept the supplied analysis paramteter values and would need to return true/false.

- [ ] Add new help entry in GetParams() returned text and display that help in the wavebuilder

### PR DESCRIPTION
**Pull request by t-b**
- [x] Implement check function support
- [x] Execute check function somehow earlier in DAP_CheckSettings compared to the pre DAQ event
- [x] Convert the check and help for the patchseq analysis functions
- [x] Add more tests

Close #124.

### CODE REVIEW

**Comment by t-b** [comment]
LGTU, show help in additional column in wavebuilder.

**Comment by t-b** [comment]
@timjarsky I've not converted the check and help for the patchseq analysis functions. Should I?

**Comment by timjarsky** [comment]
> @timjarsky I've not converted the check and help for the patchseq analysis functions. Should I?

@t-b yes, I think that is a good idea.

**Comment by t-b** [comment]
@timjarsky Ready

**Comment by timjarsky** [comment]
@t-b 

The messaging below doesn't seem appropriate for a user-provided parameter.

```
 !!! Assertion FAILED !!!
  Message: "Analysis parameter must be present"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
WBP_ButtonProc_SaveSet(...)#L580 [MIES_WaveBuilderPanel.ipf]
AFH_CheckAnalysisParameter(...)#L822 [MIES_AnalysisFunctionHelpers.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-05-20T14:46:19-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [5]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2020_05_20_104156.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.0_20190602-907-gfb8bb40b
Date and time of last commit: 2020-05-12T23:23:09+02:00
Submodule status: 
160000 44cb0b1fe9ad9fb188d95720573a09cc7825094a 0	Packages/IPNWB
160000 9a3f02fb7d007b4b34b29bda1f3fddc0ce64ad33 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################
```

**Comment by timjarsky** [comment]
@t-b when help messages are obscured when help messages are larger than the help column

**Comment by t-b** [comment]
Note to self: Nice complain/warning on missing parameter on save instead of asserting out.

**Comment by t-b** [comment]
@timjarsky Should be fixed. Please test.

**Pull request merged**
