### PR TITLE
CONF: Add saving and restoring MCC gain values

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1097

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b Do we have any configuration save/load tests for DA_Ephys that include the MCC saving/restoring?
I have only found the general tests. Does the coverage from the Bamboo CI run indicate some?

**Comment by t-b** [comment]
> @t-b Do we have any configuration save/load tests for DA_Ephys that include the MCC saving/restoring?

You could sneak it into RestoreDAEphysPanel.

> Does the coverage from the Bamboo CI run indicate some?

We don't run coverage for PRs.

**Comment by t-b** [comment]
Code style:

Missing newline before

```
	val = 
```

as this is a separate logical block.

If you want to add a test, feel free. Once done please assign Tim.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Comment by MichaelHuth** [comment]
I added a test.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
