### PR TITLE
Feature/add hiding of failed sweeps in pa

### LINKED ISSUE #151: Hide failed sweeps from PA plot
- [x] Checkbox for enabling
- [x] Checkbox for hiding traces without level
- [x] SetVariable for level
- [x] Findlevel on pulses on diagonal (before zeroing). Those without level are color coded red (or hidden depending on checkbox) and the pulses from the same region/sweep/pulse/channelType as well.
- [x] Ignore for average
- [x] Mark the trace set which contains a failed sweep somehow

### PR DESCRIPTION
**Pull request by t-b**
I started reworking the PA code for the speedup enhancements. It was way too **** to be more hacked at.

- [ ] Use a solution which does not crash IP

And I also added documentation what a PA plot is and how it works.

Close #151.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b I'm getting `  ** user function PA_ShowPulses gave error: attempt to use a null string variable` errors

**Comment by timjarsky** [comment]
image

**Comment by t-b** [comment]
@timjarsky Woops. As usual the last minute this-cant-break-anything fix breaks it. Should be good now. (I'm also finishing for today.)

**Comment by timjarsky** [comment]
> @timjarsky Woops. As usual the last minute this-cant-break-anything fix breaks it. Should be good now. (I'm also finishing for today.)

have a good evening @t-b 

for tomorrow:
(1) the symbol indicating a failed sweep only needs to be on the diagonal element
(2) it looks like the level is being applied after zeroing instead of before

**Comment by t-b** [comment]
I'm interpreting "last sweep" as the highest sweep number.

**Comment by t-b** [comment]
>  (3) it looks like the level is being applied after zeroing instead of before

Is that "PA zero traces" or "Browser zero traces"? I can't reproduce with "PA zero traces", but it is the case with "Browser zero traces" (which is how we always done it, but that can of course change).

**Comment by timjarsky** [comment]
> > (3) it looks like the level is being applied after zeroing instead of before
> 
> Is that "PA zero traces" or "Browser zero traces"? I can't reproduce with "PA zero traces", but it is the case with "Browser zero traces" (which is how we always done it, but that can of course change).

@t-b PA zero traces; see image below where a positive crossing level was required to get the right sweeps failing: 
image

**Comment by t-b** [comment]
@timjarsky Hmm, looks like we have a different order of doing things ;) I'll come up with a fix.

**Comment by timjarsky** [comment]
> @timjarsky Hmm, looks like we have a different order of doing things ;) I'll come up with a fix.

@t-b if you have not already fixed this I think it can be left alone

**Comment by t-b** [comment]
@timjarsky The zeroing issue is fixed.

**Comment by t-b** [comment]
@timjarsky Go for it!

**Comment by timjarsky** [comment]
@t-b the following assertion occurs with negative level values e.g. -10

  !!! Assertion FAILED !!!
  Message: "Single pulse wave must not be zeroed here"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
PA_SetVarProc_Common(...)#L1122 [MIES_PulseAveraging.ipf]
PA_Update(...)#L591 [MIES_PulseAveraging.ipf]
PA_ShowPulses(...)#L763 [MIES_PulseAveraging.ipf]
PA_MarkFailedPulses(...)#L662 [MIES_PulseAveraging.ipf]
PA_PulseHasFailed(...)#L954 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-07-28T16:57:38-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-28-gb2d0faa6
Date and time of last commit: 2020-07-28T23:54:27+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################

**Comment by t-b** [comment]
@timjarsky Thanks. The assertion is totally right. I fixed that.

**Comment by timjarsky** [comment]
@t-b there is a temporal offset in the PA plot that shows up when displaying a single sweep:

image

**Comment by timjarsky** [comment]
@t-b when scrolling through sweeps in the analysis browser with the PA plot open, I was expecting the biohazard symbol to show up when a sweep had failed spikes. Is that your expectation as well?

**Comment by t-b** [comment]
@timjarsky I'll investigate the time issue thing. According to https://github.com/AllenInstitute/MIES/pull/583#issuecomment-663248090 I've implemented it so that only if it is the last sweep the biohazard symbol is shown.

**Comment by t-b** [comment]
@timjarsky I can reproduce the x axis placement issue when time alignment is enabled.

**Comment by t-b** [comment]
@timjarsky Next try please.

**Comment by timjarsky** [comment]
@t-b I see this error when closing using igor using `x`

image


not sure if this is PR related

**Pull request merged**
