### PR TITLE
Test reorganization

### LINKED ISSUE #1206: Tests: Unify multiple AcquireData functions into one

### PR DESCRIPTION
**Pull request by t-b**
- [x] Fix clean/smudge filter
- [x] Add bamboo plan with new locations
- [x] Adapt helper scripts
- [x] Check .gitignore/.gitattributes for changes paths
- [x] Add docu about test organization
- [x] Docu for preAcq/preInit/etc functions
- [x] Unify AcquireData/AcquireTestpulse functions:

  HardwareAnalysisFunctions:
  - [x] UTF_MultiPatchSeqDaScale.ipf
  - [x] UTF_MultiPatchSeqFastRheoEstimate.ipf
  - [x] UTF_MultiPatchSeqSpikeControl.ipf
  - [x] UTF_PatchSeqAccessResistanceSmoke.ipf
  - [x] UTF_PatchSeqChirp.ipf
  - [x] UTF_PatchSeqDAScale.ipf
  - [x] UTF_PatchSeqPipetteInBath.ipf
  - [x] UTF_PatchSeqRamp.ipf
  - [x] UTF_PatchSeqRheobase.ipf
  - [x] UTF_PatchSeqSealEvaluation.ipf
  - [x] UTF_PatchSeqSquarePulse.ipf
  - [x] UTF_PatchSeqTrueRestingMembranePotential.ipf
  - [x] UTF_ReachTargetVoltage.ipf
  - [x] UTF_SetControls.ipf

  HardwareBasic:
  - [x] UTF_AnalysisFunctionManagement.ipf
  - [x] UTF_AutoTestpulse.ipf
  - [x] UTF_BasicHardwareTests.ipf
  - [x] UTF_Dashboard.ipf
  - [x] UTF_Epochs.ipf
  - [x] UTF_HardwareTestsWithBUG.ipf
  - [x] UTF_SweepFormulaHardware.ipf
   
Merge Requests:

- [x] #1372

- [x] Check that CI passes
- [x] Check that all tests are being executed

Close #1206

### CODE REVIEW

**Comment by t-b** [comment]
I've also added two additional test suites UTF_ThreadsafeDataSharing.ipf and UTF_JSONWaveNotes.ipf which were previsouly forgotten to run.

**Comment by t-b** [comment]
@timjarsky Ready to review. If the PR overwhelms you, you can also just believe me that it's good ;)

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
NI passes already: http://bamboo.corp.alleninstitute.org/browse/MIES-MPNL-TWNH-29

**Comment by t-b** [comment]
Will merge once CI passes.

**Pull request merged**
