### PR TITLE
PulseAveraging Tests

### PR DESCRIPTION
**Pull request by MichaelHuth**
Some basic tests for PA and more to come.

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b currently the ZeroWave tests fails miserably on my test data. The differentiate/integrate approach does not calculate correctly here.

**Comment by t-b** [comment]
@MichaelHuth Looks good so far.

**Comment by t-b** [comment]
Just as FYI. The new tests are currently not run as I have to tweak the bamboo config for that.

**Review by t-b — APPROVED** [review]
LGTM

**Pull request merged**
