### PR TITLE
Feature/add user writeable location for json config autoloader

### LINKED ISSUE #492: Move configuration to a user writeable folder for ALLUSER installs
From @aleonlein:

>One of the requests that his come up amongst our system engineers is to move the configuration files from C:\Program Files\MIES\Packages\Settings to the C:\ProgramData directory. We are trying to lock down the program files directory so that only users with write access can adjust files under this folder. The users of ephys like to change the configs based on how they like to run their experiments. Would this be possible?

@timjarsky What do you think?

### PR DESCRIPTION
**Pull request by t-b**
Close #492.

@aleonlein Please test.

### CODE REVIEW

**Comment by aleonlein** [comment]
@t-b I will be on a rig this week to test. Thanks!

**Comment by t-b** [comment]
@aleonlein Nice! I also made you an contributor on the MIES repository. In that way you have more rights here and I can also assign PRs to you ;)

**Comment by aleonlein** [comment]
@t-b Awesome! Thank you, Thomas!

**Comment by aleonlein** [comment]
@t-b Well, it looks like I may have taken too long to get to this. The link is no longer good for the installer. Do you have another link to the build artifact?

**Comment by t-b** [comment]
@aleonlein Thanks. I've restarted the build. There should be one available in a sec.

**Comment by aleonlein** [comment]
@t-b Works great!

**Pull request merged**
