### PR TITLE
Installer update for ITC XOP compatibility

### PR DESCRIPTION
**Pull request by MichaelHuth**
If the installer is executed as admin and installation with hardware XOPs is
chosen:

- PSScript to disable ASLR for Igor Pro from ITC XOP is called
- PSScript to fix Office365 bug that makes additional Wow3264Node entries
  ineffective is called
- Registry is set for ITC devices for 32 bit and 64 bit if running a 64 bit OS.

- existing ITC registry entries are overwritten in installation
- ITC registry entries are not removed on uninstallation
- ASLR setting for Igor Pro is not removed upon uninstallation

closes https://github.com/AllenInstitute/MIES/issues/428

requires latest ITC XOP version with the scripts in tools folder

### CODE REVIEW

**Comment by MichaelHuth** [comment]
I tried several times and the keys are always overwritten (as intended). Do you have some special settings (rights maybe) that prevent the keys from being written?

**Comment by MichaelHuth** [comment]
@t-b Could I have a registry dump of the keys that are relevant for ITC1600 ?

**Comment by MichaelHuth** [comment]
@t-b small detail, but probably not critical: When usually creating a key the default value is a string with 'no value set'. The NSIS default API allows only to write a value, so I write an empty string instead.

**Comment by t-b** [comment]
Note to self: Test on fresh Windows 10 on 32bit/64bit in vmware

**Comment by t-b** [comment]
Rebased to latest master.

**Comment by t-b** [comment]
- [ ] Change ALLUSER check to ISADMIN
- [ ] Test

**Comment by timjarsky** [comment]
@t-b has a `clean` installation been tried with this installer?

**Comment by t-b** [comment]
@timjarsky Yes, that is what I meant with `fresh`.

**Pull request merged**
