### PR TITLE
Add TTL support to SF

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1817

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b The CI seems to fail when signing the installer atm.

**Comment by t-b** [comment]
> @t-b The CI seems to fail when signing the installer atm.

Thanks. I've thrown out the RDP user. With an RDP user logged in installer signing is not possible (security feature !!1elf)

**Comment by t-b** [comment]
Review:

7c8c65ec (Util: Add GetUsedHWDACFromLNB helper function to retrieve hardware type from LNB, 2023-07-20)
d5512a4d (Util: Introduce variable for channel type in CreateTiledChannelGraph, 2023-07-15)
adc3ca4f (Util: Add GUI channel number to TUD in CreateTiledChannelGraph, 2023-07-15)
b604f787 (BSP: Use GUI channel number only in BSP_AddTracesForEpochs, 2023-07-15)
efc73ada (BSP: fix splitTTL epochs dependent control not properly toggled by VisEpochs, 2023-07-15)
80776787 (BSP: Always set axis range for TTL channels to 0 - 1 with 2 ticks, 2023-07-15)
6ae4864c (Util: Use GUI channel number for axis names in CreateTiledChannelGraph, 2023-07-15)

Looks all good to me.

1964894e (SF: Add TTL channel support to select operation and unassoc DA support, 2023-07-17)

When you create selectData as in 

```
WAVE selectData = SFH_NewSelectDataWave(numSweeps, NUM_DA_TTL_CHANNELS + NUM_AD_CHANNELS)
```

the size should now be incremented by NUM_DA_TTL_CHANNELS as we can have now all AD/DA/TTL channels active or?

Missing tests for TTL and unassoc DA/AD. Please also make them not require hardware as those run so much faster.

f42e4441 (Util: Add GetDAQDataSingleColumnWaveNG as more generic function, 2023-07-18)
cde09a72 (SF: Adapt SFH_GetSweepsForFormula to support epochs for TTL channels, 2023-07-18)
cb4a7742 (SF: Use EP_FetchEpochs in SF_OperationEpochsImpl instead of direct retrieval, 2023-07-18)
da7dd1db (Tests: Adapt FillFakeDatabrowserWindow to not setup invalid channel numbers, 2023-07-18)
1340c205 (SFH: Remove trailing ; in old epoch name fallback in SFH_GetEpochNamesFromInfo, 2023-07-20)

Looks all good.

I'm wondering if the code for mapping AD to DA when fetching epochs

```
            fetchEpChanType = chanType == XOP_CHANNEL_TYPE_ADC ? XOP_CHANNEL_TYPE_DAC : chanType
            fetchEpChannelNumber = chanType == XOP_CHANNEL_TYPE_ADC ? SFH_GetDAChannel(graph, sweepNo, chanType, chanNr) : chanNr
            if(IsNaN(fetchEpChannelNumber))
                continue
            endif
            WAVE/T/Z epochInfo = EP_GetEpochs(numericalValues, textualValues, sweepNo, fetchEpChanType, fetchEpChannelNumber, allEpochsRegex)
```

should be part of EP_GetEpochs? Maybe as opt-in with an optional parameter? We do have extensive tests in UTF_EpochsWoHardware.ipf. We could then also factor out the channel mappting from SFH_GetDAChannel as fetching the LBN is quite wasteful if we have it already.

**Comment by t-b** [comment]
Please refrain from touching the SF notebook, as I'm doing that in #1468 as well. I've created #1827 to track that task.

**Comment by t-b** [comment]
Review:
7c8c65ec (Util: Add GetUsedHWDACFromLNB helper function to retrieve hardware type from LNB, 2023-07-20)

The changes to NWB_GenerateDeviceDescription are not 100% correct. You removed the ParseDeviceString logic which would kick in for ITC hardware and no "Digitizer Hardware Name" LBN entry.

d5512a4d (Util: Introduce variable for channel type in CreateTiledChannelGraph, 2023-07-15)

Good.

adc3ca4f (Util: Add GUI channel number to TUD in CreateTiledChannelGraph, 2023-07-15)

Jeep.

b604f787 (BSP: Use GUI channel number only in BSP_AddTracesForEpochs, 2023-07-15)

very nice.

efc73ada (BSP: fix splitTTL epochs dependent control not properly toggled by VisEpochs, 2023-07-15)

Jeep.

80776787 (BSP: Always set axis range for TTL channels to 0 - 1 with 2 ticks, 2023-07-15)

Okay.

6ae4864c (Util: Use GUI channel number for axis names in CreateTiledChannelGraph, 2023-07-15)

Hmmh.

b1c8922a (SF: Add TTL channel support to select operation and unassoc DA support, 2023-07-17)

RST docu:

>The clampMode selection is only applied for AD/DA channels.

I would say

The clampMode selection is only applied for associated AD/DA channels.

dd01f030 (Util: Add GetDAQDataSingleColumnWaveNG as more generic function, 2023-07-18)

Nice!

55d8a760 (SF: Adapt SFH_GetSweepsForFormula to support epochs for TTL channels, 2023-07-18)

Looks good.

449ec577 (SF: Use EP_FetchEpochs in SF_OperationEpochsImpl instead of direct retrieval, 2023-07-18)

typo in commit message: fot -> for

7549ed3b (Tests: Adapt FillFakeDatabrowserWindow to not setup invalid channel numbers, 2023-07-18)
764d2b03 (SFH: Remove trailing ; in old epoch name fallback in SFH_GetEpochNamesFromInfo, 2023-07-20)

All good

1f8ca0c3 (EP: Remove unnecessary code in EP_GetEpochs, 2023-07-26)

Jeep.

18726401 (EP: Move AD to DA channel conversion into EP_FetchEpochs, 2023-07-26)

Can you add a test for the AD->DA channel mapping to UTF_EpochswoHardware.ipf?

The test should test EP_GetEpochs but as that uses EP_FetchEpochs we will
ensure that the latter works.

This should be relatively straightforward as PrepareEpochsTable_IGNORE also
uses your now enhanced PrepareLBN_IGNORE.

561a02d0 (Changes select test, 2023-07-27)

Jeep.

From playing around:
- The TTL data in SF should have the same colors as in the DB/SB. For AD/DA we
do preserve the colors, so SF_GetTraceColor needs adaptation for TTL I guess.

Please assign to Tim once done.

**Comment by t-b** [comment]
A screenshot for showing the color coding issue:

image

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
