### PR TITLE
CI: Add ipt format to check formatting for PRs

### PR DESCRIPTION
**Pull request by Garados007**
Thanks for opening a PR in MIES :sparkles:!

- Code can only be merged if the continous integration tests pass
- [x] Please ensure that the branch is named correctly. See
  [here](https://alleninstitute.github.io/MIES/developers.html#branch-naming-scheme) for the detailed explanation.

### CODE REVIEW

**Comment by t-b** [comment]
Looks mostly good. But I think we only want to format files matching `*MIES*.ipf` from `Packages/MIES` and not the other files.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Comment by Garados007** [comment]
Fixed

**Comment by t-b** [comment]
@Garados007 Sorry for being unclear. We want to format all ipf files in the repo (without submodules) except files from Packages/MIES which don't match `*MIES*.ipf`.

**Comment by t-b** [comment]
I would also prefer to have the script do the formatting directly without the config.toml. Yes that does not scale for arbitrary number of files but works right now. Something like:

```
ipt format -i $(git ls-files 'Packages/MIES/*MIES*.ipf' 'Packages/tests/**/*.ipf' 'Packages/doc/**/*.ipf' 'Packages/Conversion/**/*.ipf')
```

**Comment by t-b** [comment]
I've pushed a modification. We are now tagging all files we want to format with the ipt attribute and the script then formats these files. How about that?

**Comment by Garados007** [comment]
There was a reason why I used the config file instead of providing them as arguments. In Windows can be the argument line only up to 8191 characters ([source](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation)) and if the number of files increases it is more likely to hit this limit. On the other hand the config file allows unlimited number of entries and is therefore future proof.

**Comment by Garados007** [comment]
I checked the call in your script and is right now at 7963 characters. 3 files more and the script does not work anymore.

**Comment by Garados007** [comment]
I found [other sources](https://superuser.com/questions/362066/windows-limitation-to-the-length-of-command-line-parameters) saying the limit is between 32683 and 32853 characters. It is a bit higher but not impossible to reach in the foreseeable future.

**Comment by Garados007** [comment]
But I do like the idea about the git tags.

**Comment by t-b** [comment]
We are not using CMD.exe but a bash script so the limit is around 32k, which you already mentioned, which is nearly four times as many files as currently or?

If you insist we can still create a config file from the output of `git ls-files ...`.  But in that case no need to bother with cleaning up in CI of the config.toml.

**Comment by Garados007** [comment]
@t-b Are you okay with my changes? I reintroduced the config file, because I think its better to do so.

**Comment by t-b** [comment]
@Garados007 Jeep.

**Comment by Garados007** [comment]
I rebased all the stuff.

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@Garados007 Thanks. LGTM.

**Pull request merged**
