### PR TITLE
Test config cleanup

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by MichaelHuth** [comment]
LGTM but I don't see how that closes #1976

**Comment by t-b** [comment]
> LGTM but I don't see how that closes #1976

2608fc6a5a195bb7c60f877da6eb1c5a4b0020a0 only closes the panels and removes the MIES folder if wave leak tracking is enabled. As wave leak tracking is disabled by default I thought this would fix our normal usecase when debugging.

**Comment by MichaelHuth** [comment]
Ok.

semi related: Do you think we should disable wave tracking by default when keepDataFolder is enabled?

**Comment by t-b** [comment]
> semi related: Do you think we should disable wave tracking by default when keepDataFolder is enabled?

I don't think this is necessary. `keepDataFolder` is for preserving the temporary DF which igortest creates and makes the CDF. I rarely use that.

**Pull request merged**
