### PR TITLE
Feature/1264 automatic logfile upload

### PR DESCRIPTION
**Pull request by t-b**
- [x] Add configuration support
- [x] Document
- [x] Test again and proofread the code again

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Ready for a first test.

**Comment by timjarsky** [comment]
@t-b i successfully uploaded a log file from the menu option.

When stopping the TP I saw ```  Retrying getting data from thread, keep fingers crossed (1/10)``` but I was not able to replicate.

**Review by timjarsky — APPROVED** [review]
If you are comfortable merging without digging into the thread error message I saw. go ahead.

**Comment by t-b** [comment]
> When stopping the TP I saw Retrying getting data from thread, keep fingers crossed (1/10) but I was not able to replicate.

This message can happen sometimes due to a race condition. It is totally harmless.

> @t-b i successfully uploaded a log file from the menu option.

The menu option was already there before, did you try to add the new experiment configuration entry and trigger a daily logfile upload.

I also fixed some conflicts.

**Comment by t-b** [comment]
Should be fixed.

**Comment by timjarsky** [comment]
@t-b I still get:
``` BUG UploadLogFilesDaily(...)#L6837: Could not upload logfiles!```

with 
```        },
        "Position MCCs": "- none -",
        "Save data to": "C:MiesSave",
        "Stim set file name": "\\\\mp1\\MiesHDF5Files\\SavedStimSets\\Coarse_matrix_prod_stimsets_23.nwb",
        "Automatic logfile upload": 1,
        "User Pressure Devices": {
            "DA": 0,
            "DAC Device": "- none -"
        }
```
or with

```        },
        "Position MCCs": "- none -",
        "Save data to": "C:MiesSave",
        "Stim set file name": "\\\\mp1\\MiesHDF5Files\\SavedStimSets\\Coarse_matrix_prod_stimsets_23.nwb",
        "Automatic logfile upload": true,
        "User Pressure Devices": {
            "DA": 0,
            "DAC Device": "- none -"
        }
```

**Comment by t-b** [comment]
@timjarsky I've fixed the conflicts. But I still can't reproduce the BUG message. We can debug together, or you give it a shot. 
To Debug: Set a breakpoint in UploadLogFilesDaily at the top, execute and investigate in which line it fails. And also post the output of `print JSON_Dump(ROVar(GetSettingsJSONid()), indent = 2)`.

**Comment by t-b** [comment]
Done.

**Comment by timjarsky** [comment]
@t-b i tested by corrupting the date and removing the logfiles entry in the json;

```  },
  "logfiles": {
    "last upload": "2022-02-09T21:48:44Z"
```

in both cases (assert and added new entry) it worked as expected.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
