### PR TITLE
Feature/search string in wavebuilder

### LINKED ISSUE #213: Add search string to loading controls in waveBuilder
Feature: add a setVar control used for searching, like in the DA_ephys panel, DA tab for example [1], to the waveBuilder load controls [2].

[1] 
image

[2]
image

### PR DESCRIPTION
**Pull request by t-b**
Close #213.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b Let's call it `filter` instead of `string'. Drop the `string'. and increase the width of the control.

**Comment by t-b** [comment]
@timjarsky  I've used the same names as in the DAEphys panel. I would propose to have the same names everywhere. Should I rename the DAEphys ones to `filter` as well?

**Comment by timjarsky** [comment]
> @timjarsky I've used the same names as in the DAEphys panel. I would propose to have the same names everywhere. Should I rename the DAEphys ones to `filter` as well?

@t-b ah, okay. I still think `filter` is the right choice (for both). You can rename the DAEphys ones now or when we are doing panel updates at some other time.

**Comment by t-b** [comment]
Will do it now.

**Comment by t-b** [comment]
@timjarsky Done.

**Pull request merged**
