### PR TITLE
Changes for tpfit maxTrail reference

### PR DESCRIPTION
**Pull request by MichaelHuth**
note that negative maxTrails should be enclosed is array brackets, e.g. `[-1]` due to current parser limitations.

close https://github.com/AllenInstitute/MIES/issues/1648

### CODE REVIEW

**Comment by t-b** [comment]
> note that negative maxTrails should be enclosed is array brackets, e.g. [-1] due to current parser limitations.

Please add that to #1527. And why not `(-1)` but `[-1]` instead?

Assigning also to Tim for testing.

**Review by timjarsky — DISMISSED** [review]

**Comment by MichaelHuth** [comment]
Rebased.

**Review by t-b — APPROVED** [review]

**Review by t-b — APPROVED** [review]

**Comment by t-b** [comment]
@MichaelHuth HardwareBasic.pxp does not compile.

**Comment by MichaelHuth** [comment]
@t-b Which HW test is failing on the CI?

**Comment by t-b** [comment]
@MichaelHuth Or even better can you create a separete PR for that fix? MIES main is currently broken due to that.

**Comment by MichaelHuth** [comment]
@t-b I already rebased in the morning, however the still failing HW test was some actual test failing (not the compilation) and it revealed that for one specific case the endTrail calculation was wrong. Should be fixed now.

**Review by t-b — APPROVED** [review]

**Pull request merged**
