### PR TITLE
Pulse Averaging: Pulse starting times are now read from the epoch information from lab notebook

### PR DESCRIPTION
**Pull request by MichaelHuth**
- Pulse starting times are in PA_GetPulseStartTimes extracted from the epoch
  information stored in the lab notebook
- as fallback the pulse starting times are determined the old direct way
  through findlevels.

close https://github.com/AllenInstitute/MIES/issues/207

### CODE REVIEW

**Comment by timjarsky** [comment]
@MichaelHuth The debugger opens, without assertion, when attempting to run the trace plot.
image

The cmd history prints the error message: 
```
UpdtDisplay: recursion attempted
Encountered error/abort (WaveUnits;expected wave name)
```

**Comment by t-b** [comment]
@timjarsky I don't think the error you are seeing is related but we'll have a look tomorrow.

**Comment by timjarsky** [comment]
@MichaelHuth this PR is makeing the PA plot much faster! It used to take about 7sec for my test case. Now it is down to:

Total time: 8.78419, Time in Function code: 1.9326 (22%)
Top function percentages:
Function MIES_PulseAveraging.ipf PA_CalculateAllAverages: 21%
Function MIES_PulseAveraging.ipf PA_MarkFailedPulses: 6%
Function MIES_Cache.ipf CA_WaveCRCs: 6%
Function MIES_PulseAveraging.ipf PA_AutomaticTimeAlignment: 6%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 6%
Function MIES_PulseAveraging.ipf PA_ZeroPulses: 6%
Function MIES_PulseAveraging.ipf PA_GeneratePulseWaveName: 5%
Function MIES_PulseAveraging.ipf PA_GenerateAllPulseWaves: 4%
Function MIES_PulseAveraging.ipf PA_ShowPulses: 4%
Function MIES_PulseAveraging.ipf PA_GetAxes: 2%
Function MIES_Utilities.ipf SetNumberInWaveNote: 2%
Function MIES_Utilities.ipf EnsureLargeEnoughWave: 2%
Function MIES_PulseAveraging.ipf PA_AccelerateAppendTracesImpl: 2%
Function MIES_PulseAveraging.ipf PA_RetrievePulseStartTimesFromEpochs: 2%
Function json_functions.ipf JSON_GetVariable: 2%
Function MIES_Utilities.ipf DataFolderExistsDFR: 2%
Function MIES_WaveDataFolderGetters.ipf GetPulseAverageSetIndizes: 2%
Function MIES_PulseAveraging.ipf PA_GetSetWaves: 2%

**Comment by MichaelHuth** [comment]
@timjarsky 👍

**Comment by MichaelHuth** [comment]
For the AppendToGraph in Averaging and Deconvolution part it does not increase performance when used with grouping as each single trace uses different axes. It also makes no sense to group with the pulsetraces as then use different colors.

**Comment by MichaelHuth** [comment]
- buffer Averaging sums + numberOfWaves for incremental update in average calculation
- keep always all pulse information in properties wave
- for incremental update generally save previous ending index in wave note and iterate from there in following functions (if not sorted)
- idea: save for each sweep: for properties wave where it starts first index and length, in wave note of propertie wave (est. number of sweeps ~100 max.)
-idea: move complete averaging in async

**Comment by timjarsky** [comment]
@MichaelHuth @t-b using my standard test case (I made an Igor template file to facilitate testing) and creating a PA trace plot gets:

Main:
```
Total time: 17.8447, Time in Function code: 11.8193 (66.2%)
Top function percentages:
Function MIES_PulseAveraging.ipf PA_CalculatePulseStartTimes: 51%
Function MIES_PulseAveraging.ipf PA_ShowPulses: 10%
Function MIES_PulseAveraging.ipf PA_CreateAndFillPulseWaveIfReq: 9%
Function MIES_Utilities.ipf SetNumberInWaveNote: 4%
Function MIES_PulseAveraging.ipf PA_CalculateAllAverages: 3%
Function MIES_MiesUtilities.ipf CreateBackupWave: 3%
Function MIES_WaveDataFolderGetters.ipf GetPulseAverageWave: 3%
```

This PR:

**Comment by t-b** [comment]
Review:

- I'm getting  `** JSONXOP_GetKeys gave error: Invalid type specified.` when I use multiple graphs
- I get the same error when unchecking `Show individual pulses`
- You added the following code

```
Redimension/N=(0, -1) traceCountPerGraph
[traceCountIndex, traceCount] = PA_GetTraceCountFromGraph(graph)
```

in PA_ShowPulses which is called for every new graph when not doing a POST_PLOT_ADDED_SWEEPS fast path. But that code clears the trace count for all graphs and not only for the new one. I'm curious why this works.
- Turning deconvolution on/off via the checkbox does not work. This is due to the fact that `PA_UpdateDeconvolution` was not updated to not require trace user data.
- There is a failed pulses updating issue, see https://github.com/AllenInstitute/MIES/issues/684. That is also present in main.
- Please add a comment to `PA_GetTraceCountFromGraph` explaining what it does and what it returns. You can use `@retval` for MRS functions.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Comment by t-b** [comment]
@timjarsky 

> What other files should I delete to simulate a clean start?

Either close the PA plots and the databrowser (in that order), or close the PA plot and remove the folder `root:MIES:HardwareDevices:ITC1600:Device0:DatabrowserXXX:PulseAveraging:`.

**Comment by t-b** [comment]
I've extracted the first commit into https://github.com/AllenInstitute/MIES/pull/685 which allows us to move forward now.

**Comment by MichaelHuth** [comment]
@t-b The JSON_GetKeys error should be gone, graph data storing should be more consistent now, PA_UpdateDeconvolution uses now light-weight user data.

**Comment by t-b** [comment]
Looks mostly good.

I think we should do three things here before more testing and merging:

- Remove 6305b23e (PA_GenerateAllPulseWaves now uses incremental update when new sweeps are added, 2020-10-13). As discussed earlier this does not yet work as the diagonality of a pulse can change with new sweeps. This needs more work.
- Remove the fat user data code currently defed out with `PA_ENABLE_USERDATA`. And also remove the last remaining calls to TUD_.

**Review by t-b — APPROVED** [review]

**Comment by timjarsky** [comment]
@MichaelHuth @t-b with OS, image plot, and incremental updates I get:

image

  Message: "Unexpected abort"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_ButtonProc_ChangeSweep(...)#L1275 [MIES_BrowserSettingsPanel.ipf]
OVS_ChangeSweepSelectionState(...)#L321 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3570 [MIES_MiesUtilities.ipf]
PA_Update(...)#L840 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-10-29T10:43:27-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-340-ga161fa4f
Date and time of last commit: 2020-10-26T19:13:55+01:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 b890ee01f65722475338602ff998abadad66b76f 0	Packages/unit-testing
  ################################

**Comment by t-b** [comment]
@timjarsky That is not yet done, see https://github.com/AllenInstitute/MIES/issues/698. Can you test properly without that fix?

**Comment by timjarsky** [comment]
@MichaelHuth @t-b I'm not sure how to best test this PR. Seems to work with incremental updates without OS and bugs out in the same way **main** does. Good enough?

**Comment by MichaelHuth** [comment]
@t-b rebased

**Comment by t-b** [comment]
@MichaelHuth @timjarsky rebased.

**Comment by t-b** [comment]
@timjarsky @MichaelHuth Rebased and fixed conflicts.

**Comment by timjarsky** [comment]
@timjarsky Incremental update with OS. Starting at sweep 31 in the test file. When adding sweeps quickly (not slowly) using the next sweep button, I get: 

```
  !!! Assertion FAILED !!!
  Message: "Empty string"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
PA_AxisHook(...)#L1533 [MIES_PulseAveraging.ipf]
PA_UpdateScaleBars(...)#L1559 [MIES_PulseAveraging.ipf]
PA_DrawScaleBars(...)#L1583 [MIES_PulseAveraging.ipf]
GetStringFromWaveNote(...)#L1023 [MIES_Utilities.ipf]
ExtractStringFromPair(...)#L1048 [MIES_Utilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-11-06T21:06:30-08:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.3 (36592)
  MIES version:
  Release_2.1_20200723-398-g755e9b1f
Date and time of last commit: 2020-11-06T16:33:20+01:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 4b67466116212d042ca5c7427b51ddcb60630117 0	Packages/unit-testing
  ################################
  Encountered error/abort (note;expected wave name)
```

**Comment by MichaelHuth** [comment]
I also get that in main. It looks like a race condition when PA_AxisHook is called. Here you see that the getters for e.g. GetPulseAverageProperties were called and the GetNumberFromWaveNote even returned 72.
However at the Make statement both wave references are null.

image

**Comment by t-b** [comment]
@timjarsky This will be fixed by me as part of #700.

**Comment by t-b** [comment]
Will be merged as part of #676.

**Pull request closed without merging**
