### PR TITLE
Add Labnotebook entry descriptions 

### PR DESCRIPTION
**Pull request by t-b**
- [x] Implement for numeric labnotebook
- [x]  Add tests in ED_FindIndizesAndRedimension to check added LBN entries
   - [x] description is not empty for stock entries
   - [x] asserts for valid headstage contigency + clampmode
   - [x] check that unit is something known 
   - [x] tolerance is either - or a positive number
- [x] Add documentation by dumping the labnotebook_numerical_description wave to a csv file and include that in sphinx, see https://docutils.sourceforge.io/docs/ref/rst/directives.html#csv-table-1
- [x] Rename RowRange
- [x] Add BUG message for entering a LBN value which does not match DEPEND/INDEP
- [x] "Follower Device" is missing, also change to always create it also for non-yoked. Then it is just empty.
- [x] Document what the description wave can contain
- [x] Think about showing description in settings history again

Successor of #494.
See also #19.

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky 

So I've integrated our year-long documentation project. The code is still WIP but I already have a hacky visualisation of the content.

image

This tooltip is shown when the mouse is hovered over the trace. There are quite a few additional ways we could visualize that.

**Comment by timjarsky** [comment]
> @timjarsky
> 

> This tooltip is shown when the mouse is hovered over the trace. There are quite a few additional ways we could visualize that.

@t-b looks good. What do you think about putting the tooltip on the y-axis label? I'm concerned that hovering over the trace, something often done to manipulate the magnification will be interrupted by a large tooltip.

**Comment by t-b** [comment]
@timjarsky Thanks for the feedback. I'll play a bit around to find something more useful which is also accessible pre-plotting.

**Comment by t-b** [comment]
See labnotebook-descriptions.html in http://bamboo.corp.alleninstitute.org/browse/MIES-PLAYIN456-DD-7/artifact.

**Comment by t-b** [comment]
So this has implemented now everything I wanted to have, let's see if it matches your expectation as well ;)

**Comment by timjarsky** [comment]
@t-b some minor issues and bug that's likely unrelated to this PR

1. the text is getting cut off in the description window/notebook
2. resizing the full window shouldn't cause the buttons to get bigger. If possible, only the plot should scale.
image
3. I got this assertion when trying to look at TP storage data while the first instance of the TP was running
```  !!! Assertion FAILED !!!
  Message: "Unexpected size"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
PEXT_Callback(...)#L466 [MIES_GuiPopupMenuExt.ipf]
LBV_PopMenuProc_TPStorage(...)#L321 [MIES_LogbookViewer.ipf]
LBV_AddTraceToLBGraphTPStorage(...)#L716 [MIES_LogbookViewer.ipf]
TUD_SetUserDataFromWaves(...)#L202 [MIES_TraceUserData.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-02-02T11:51:23-08:00
  Locked device: [ITC1600_Dev_2]
  Current sweep: [NaN]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_BG_MULTI_DEVICE]
  Experiment: 2022_02_02_115054 (Packed)
  Igor Pro version: 9.0.0.10 (37840)
  MIES version:
  Release_2.4_20211216-176-g70438bb3a
Date and time of last commit: 2022-01-30T21:36:45+01:00
Submodule status: 
160000 f3493461480eaafa97939940693ed693860048a6 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 5359bdbaad31451d6ebb9c88cca09d48357a41bb 0	Packages/unit-testing
  ################################```

**Comment by t-b** [comment]
Thanks for testing. I'll investigate.

**Comment by t-b** [comment]
Thanks for testing. All should be fixed. The text cut off in the notebook window is difficult, hopefully my fix works.

**Comment by timjarsky** [comment]
@t-b 

Looks good with a new file and the data browser. With the analysis browser and `results wave` instead of `- none -` in the menu, the following error occurs:

``` ** WAVE gave error: WAVE reference to "textualKeys" failed.```

image

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
