### PR TITLE
IP9 support

### PR DESCRIPTION
**Pull request by t-b**
- [x] Installer needs adaptation as the HDF5 XOP and the HDF5Browser.ipf are not needed anymore
- [x] https://github.com/AllenInstitute/ITCXOP2/pull/8
- [x] https://github.com/AllenInstitute/IPNWB/pull/18

### CODE REVIEW

**Comment by MichaelHuth** [comment]
I have updated the installer script for IP9. Please test.

**Comment by t-b** [comment]
@MichaelHuth Thx.

**Comment by t-b** [comment]
@MichaelHuth Yeep, works here as well.

**Comment by timjarsky** [comment]
@t-b cheers to native hdf5 browsing!

**Pull request merged**
