### PR TITLE
SF: Add with keyword to combine multiple y-formulae with one x-formula

### PR DESCRIPTION
**Pull request by MichaelHuth**
Adds "with" keyword that has to be on its own line to combine multiple y-formulas with one x-formula.

close https://github.com/AllenInstitute/MIES/issues/1141

### CODE REVIEW

**Comment by t-b** [comment]
Review:
- Code/Test/Documentation looks goods
- It will be a bit nasty to resolve the conflicts with #1555 though.

**Comment by timjarsky** [comment]
@MichaelHuth looking good! 
image
(I manually added the trace coloring)
Can the legend in the lower plot be streamlined to a couple of lines?

**Comment by MichaelHuth** [comment]
- rebased
- fixed a bug introduced in 5614e9d86fcf1a35c423f456a6f02c273f08ee55
- apply shrinking of legend per y-formula

**Comment by timjarsky** [comment]
Looks great @MichaelHuth 
image

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
