### PR TITLE
Speedup PA plot

### LINKED ISSUE #119: Speedup PulseAveraging by not removing and reappending existing traces
From Matthias:

> I would recommend to automatically activate that checkbox if OVS causes large (> 300) numbers of traces.
If we want to stick with a single window, then Append/Remove should disappear because Append has 30% time consumption  and Remove 60% time consumption in large graphs.
Recipe to avoid those calls:

> - Call `TraceNameList` and `TraceNameToWaveRef` once with `WAVE/T/Z traceData = PA_GetTraceInfos(win)` as already done.
instead of calling `RemoveTracesFromGraph(graph)` we mark the traces for removal with a list/wave.
> - Before calling `AppendToGraph`, we check if the trace was marked for removal, check if it is the same wave and tracename that we want to append and call `RemoveFromGraph` and subsequently `AppendToGraph` at this stage only if something is not right. 
> Otherwise we simply remove the item from the removal waves without calling Remove/Append because the trace should be already in the graph.
> - After the main for loop, we call `RemoveFromGraph` with the remaining list of traces that has to be removed.

### PR DESCRIPTION
**Pull request by t-b**
Close #119.

- [x] cleanup commits

Setup:
- 4 active Headstages
- Pulse train 900ms long, 10 pulses
- OVS all sweeps (~60)
- PA plot  shown

With IP8, IP9 would be slightly faster in main.

I'm measuring the total time of a sweep acquisition.

Main:
```
Total time: 23.5077, Time in Function code: 14.8426 (63.1%)
Top function percentages:
Function MIES_PulseAveraging.ipf PA_ShowPulses: 29%
Function MIES_EnhancedWMRoutines.ipf MIES_fWaveAverage: 13%
Function MIES_MiesUtilities.ipf RemoveTracesFromGraph: 8%
Function MIES_MiesUtilities.ipf CalculateAverage: 7%
Function MIES_Utilities.ipf DataFolderExistsDFR: 4%
Function MIES_GlobalStringAndVariableAccess.ipf CreateMiesVersion: 4%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 4%
Function MIES_Utilities.ipf NumericWaveToList: 3%
Function MIES_Utilities.ipf createDFWithAllParents: 3%
Function MIES_PulseAveraging.ipf PA_DrawScaleBars: 2%
Function MIES_Utilities.ipf GetSetIntersection: 2%
Function json_functions.ipf JSON_GetVariable: 1%
Function MIES_PulseAveraging.ipf PA_GeneratePulseWaveName: 1%
```

This branch:
```
Total time: 35.5319, Time in Function code: 4.4205 (12.4%)
Top function percentages:
Function MIES_Utilities.ipf DataFolderExistsDFR: 15%
Function MIES_Cache.ipf CA_WaveCRCs: 9%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 9%
Function MIES_Utilities.ipf GetSetIntersection: 5%
Function MIES_PulseAveraging.ipf PA_ShowPulses: 5%
Function MIES_PulseAveraging.ipf PA_GenerateAllPulseWaves: 4%
Function MIES_PulseAveraging.ipf PA_GeneratePulseWaveName: 4%
Function MIES_Utilities.ipf createDFWithAllParents: 4%
Function MIES_PulseAveraging.ipf PA_MarkFailedPulses: 2%
Function MIES_ThreadsafeUtilities.ipf TS_GetNewestFromThreadQueue: 2%
Function MIES_PulseAveraging.ipf PA_CalculateAllAverages: 2%
Function MIES_PulseAveraging.ipf PA_GetAxes: 2%
Function MIES_WaveDataFolderGetters.ipf GetPulseAverageSetIndizes: 2%
Function MIES_MiesUtilities.ipf FindIndizes: 2%
Function MIES_Utilities.ipf EnsureLargeEnoughWave: 2%
Function MIES_Utilities.ipf SetNumberInWaveNote: 2%
Function MIES_MiesUtilities.ipf GetLastSettingNoCache: 1%
Function MIES_Utilities.ipf ASSERT: 1%
Function MIES_PulseAveraging.ipf PA_CalculatePulseStartTimes: 1%
Function MIES_MiesUtilities.ipf GetLastSetting: 1%
Function MIES_AnalysisFunctionHelpers.ipf AFH_GetAnalysisFunctions: 1%
Function MIES_Utilities.ipf IsEmpty: 1%
Function MIES_MiesUtilities.ipf KillOrMoveToTrashPath: 1%
Function MIES_Utilities.ipf ASSERT_TS: 1%
Function MIES_Cache.ipf CA_GetCacheIndex: 1%
Function MIES_WaveDataFolderGetters.ipf GetLBIndexCache: 1%
```

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b (1) enabling/disabling overlay sweeps isn't working after sweeps are overlaid. (2) PA plot is showing spikes in all elements, rather than only along the diagonal. (3) Index out of range error when overlaying sweeps.

image

**Comment by t-b** [comment]
@timjarsky Next try.

**Comment by timjarsky** [comment]
@t-b when selecting a single sweep using the sweep checkbox in overlay sweeps:

  The JSON XOP is developed by www.byte-physics.de.
  !!! Assertion FAILED !!!
  Message: "Unexpected RTE"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
OVS_MainListBoxProc(...)#L771 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3559 [MIES_MiesUtilities.ipf]
PA_Update(...)#L659 [MIES_PulseAveraging.ipf]
PA_ShowPulses(...)#L1011 [MIES_PulseAveraging.ipf]
PA_CalculateAllAverages(...)#L1139 [MIES_PulseAveraging.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-08-14T10:06:32-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-99-ge307d1fc
Date and time of last commit: 2020-08-12T23:53:02+02:00
Submodule status: 
160000 1819408b021250b608c4e5291aebead57654625a 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 9fa72d3741553ec644753f8495efdd5d75e52b59 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################

**Comment by t-b** [comment]
@timjarsky Can you upload the data?

**Comment by t-b** [comment]
@timjarsky Next try.

**Comment by t-b** [comment]
@timjarsky Next version is ready. The window saving will be done in a different PR.

**Pull request merged**
