### PR TITLE
Feature/1322 chirp enhancements

### PR DESCRIPTION
**Pull request by t-b**
- [x] Assertion for new DaScale of zero or smaller
- [x] Find out when PSQ_CR_DetermineBoundsAction broke
- [x] Proper fix for AD_PlotBounds
- [x] Fix dashboard without spikePass wave (see uploaded file)

The first part of #1298.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b chirp may be adjusting the scaling incorrectly when out of bounds; the da scale gets very small and which may be what triggers the assertion;

```
  !!! Assertion FAILED !!!
  Message: "Could not find an edge"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L94 [MIES_DataAcquisition_Multi.ipf]
AS_HandlePossibleTransition(...)#L103 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L135 [MIES_AnalysisFunctionManagement.ipf]
PSQ_Chirp(...)#L4163 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_GetPulseDurations(...)#L189 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_DeterminePulseDuration(...)#L233 [MIES_AnalysisFunctions_PatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-04-04T21:56:26-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [6]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.10 (37840)
  MIES version:
  Release_2.4_20211216-375-ga74d8dfb
Date and time of last commit: 2022-04-01T18:23:44+02:00
Submodule status: 
160000 f3493461480eaafa97939940693ed693860048a6 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 9527061ff259409acd5ebef263857055c6d46f67 0	Packages/unit-testing
  ################################
  The analysis function PSQ_Chirp aborted with error "", this is dangerous and must *not* happen!
```

**Comment by t-b** [comment]
@timjarsky Can you upload the pxp?

**Comment by timjarsky** [comment]
@t-b chirp enhancement testing.pxp is on the way to you.

**Comment by t-b** [comment]
@timjarsky go for it. I did not assert out with DAScale 0 as we already have code which reruns if DaScale is non-finite, so I reused that approach. See aead0331 (PSQ_CR_DetermineBoundsAction: Handle scalingFactor of zero gracefully, 2022-04-06).

**Comment by timjarsky** [comment]
@t-b it's working nicely; I tried with/out a starting auto-bias value and with indexing. The dashboard is also behaving.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
