### PR TITLE
Bugfix/nwb loading labnotebook browser

### LINKED ISSUE #885: drag and drop multiple NWBs and lab notebook browsing
Drag and drop 2 NWBs into Igor (two analysis browsers open)
Load data for each file.
Open lab notebook browser.
Select non-default experimental file in lab notebook browser:

  !!! Assertion FAILED !!!
  Message: "Trying to access non existing numerical keys labnotebook"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
LBN_PopMenuProc_ExpDevSelector(...)#L442 [MIES_AnalysisBrowser_LabNotebookTPStorageBrowser.ipf]
GetAnalysLBNumericalKeys(...)#L5074 [MIES_WaveDataFolderGetters.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-03-16T14:26:11-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-970-g32e39cfde
Date and time of last commit: 2021-03-11T18:48:15+01:00
Submodule status: 
160000 3fa58754bb50a399a190d7eaa014779f72af7ae0 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 a184fae75390ce75149d22313397bd5d82d5189c 0	Packages/doc/doxygen-filter-ipf
160000 4b67466116212d042ca5c7427b51ddcb60630117 0	Packages/unit-testing
  ################################

### PR DESCRIPTION
**Pull request by t-b**
Close #885.

This was broken when the file name contained a semicolon. If there is something else broken, please upload the files so that I can have a look again.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b missing notebook assertions does not occur when the experiment is loaded individually:

  !!! Assertion FAILED !!!
  Message: "Trying to access non existing numerical keys labnotebook"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
LBN_PopMenuProc_ExpDevSelector(...)#L442 [MIES_AnalysisBrowser_LabNotebookTPStorageBrowser.ipf]
GetAnalysLBNumericalKeys(...)#L4708 [MIES_WaveDataFolderGetters.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-03-18T11:26:30-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.4 (37224)
  MIES version:
  Release_2.1_20200723-968-g9bc2c18f8
Date and time of last commit: 2021-03-17T15:34:33+01:00
Submodule status: 
160000 513e97117a6e3ddad22d9299dae817c59ecbd0ea 0	Packages/IPNWB
160000 3979557f487c3e7d54b515ea0e0c384322034892 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 a184fae75390ce75149d22313397bd5d82d5189c 0	Packages/doc/doxygen-filter-ipf
160000 ca5bb0a1bce315a904841df7cbd8c58d869c4059 0	Packages/unit-testing
  ################################

**Comment by t-b** [comment]
Do the experiments you are browsing have different devices? If yes I can reproduce.

**Comment by timjarsky** [comment]
it looks like they do:
image

nice catch!

**Comment by t-b** [comment]
@timjarsky Thx. Next try.

**Comment by timjarsky** [comment]
@t-b won't compile: num2str(writeIgorHistory), IPNWB#CompressionModeToString(compressionMode)})

**Comment by t-b** [comment]
@timjarsky Looks like sourcetree did not update the submodules on your machine. To fix it call `git submodule update --checkout --force` from a git terminal.

**Comment by timjarsky** [comment]
@t-b PR is working nicely. If user selects a different experiment, that has a different device, the following error message is printed:

```
  The selected experiment/device combination does not exist.
```

could the labnotebook browser automatically select the device in that case?

**Comment by t-b** [comment]
@timjarsky Done.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
