### PR TITLE
Incremental labnotebook cache update

### PR DESCRIPTION
**Pull request by t-b**
I've stumpled on that yesterday while working on incremental PA plot update. I deemed it feasable enough to do now.

Some numbers:

OVS with 190 sweeps, 2 HS, PA disabled

using the following profiling code

```diff
commit a65a88e5da34721cf8fee57ef0877f67442906f3 (main)
Author: Thomas Braun <thomas.braun@byte-physics.de>
Date:   Sat Aug 8 18:39:37 2020 +0200

    WIP: Benchmarking

diff --git a/Packages/MIES/MIES_SweepSaving.ipf b/Packages/MIES/MIES_SweepSaving.ipf
index 46bd9accf..517848fac 100644
--- a/Packages/MIES/MIES_SweepSaving.ipf
+++ b/Packages/MIES/MIES_SweepSaving.ipf
@@ -53,7 +53,12 @@ Function SWS_SaveAcquiredData(panelTitle, [forcedStop])
         AFM_CallAnalysisFunctions(panelTitle, POST_SET_EVENT)
     endif

+    BeginFunctionProfiling()
+
     SWS_AfterSweepDataSaveHook(panelTitle)
+
+    EndFunctionProfiling()
+    NoteBook ProfilingResults, selection={startOfFile,startOfFile}, findText={"", 1}
 End

```

main:
```
Total time: 0.651688, Time in Function code: 0.633642 (97.2%)
Top function percentages:
Function MIES_MiesUtilities.ipf FindIndizes: 24%
Function MIES_MiesUtilities.ipf GetLastSettingNoCache: 23%
Function MIES_Utilities.ipf createDFWithAllParents: 11%
Function MIES_Utilities.ipf GetSetIntersection: 9%
Function MIES_OverlaySweeps.ipf OVS_UpdatePanel: 3%
Function MIES_WaveDataFolderGetters.ipf GetCacheFolderAS: 2%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 2%
Function MIES_Utilities.ipf DataFolderExistsDFR: 2%
Function MIES_Utilities.ipf IsEmpty: 2%
Function MIES_Cache.ipf CA_GetCacheIndex: 2%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 2%
```

this PR:
```
Total time: 0.217811, Time in Function code: 0.209744 (96.3%)
Top function percentages:
Function MIES_MiesUtilities.ipf GetLastSetting: 13%
Function MIES_OverlaySweeps.ipf OVS_UpdatePanel: 9%
Function MIES_Utilities.ipf createDFWithAllParents: 9%
Function MIES_MiesUtilities.ipf FindIndizes: 8%
Function MIES_Utilities.ipf str2numSafe: 5%
Function MIES_Utilities.ipf DataFolderExistsDFR: 4%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 3%
Function MIES_MiesUtilities.ipf ExtractOneDimDataFromSweep: 3%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 3%
Function MIES_Utilities.ipf EnsureLargeEnoughWave: 3%
Function MIES_GuiUtilities.ipf GetCheckBoxState: 3%
Function MIES_Utilities.ipf GetSetIntersection: 3%
Function MIES_GuiUtilities.ipf GetAxisOrientation: 2%
Function MIES_MiesUtilities.ipf GetLastSettingNoCache: 2%
Function MIES_Utilities.ipf GetAllObjects: 2%
Function MIES_MiesUtilities.ipf GetHardwareType: 2%
Function MIES_WaveDataFolderGetters.ipf GetLBIndexCache: 2%
Function MIES_MiesUtilities.ipf RemoveFreeAxisFromGraph: 2%
Function MIES_Cache.ipf CA_GetCacheIndex: 2%
Function MIES_WaveDataFolderGetters.ipf UpgradeDataFolderLocation: 2%
```

latest incarnation:
```
Total time: 0.0716026, Time in Function code: 0.0695568 (97.1%)
Top function percentages:
Function MIES_MiesUtilities.ipf FindIndizes: 9%
Function MIES_MiesUtilities.ipf ParseDeviceString: 9%
Function MIES_DataBrowser.ipf DB_GetPlainSweepList: 9%
Function MIES_Utilities.ipf GetSetIntersection: 6%
Function MIES_WaveDataFolderGetters.ipf UpgradeWaveLocationAndGetIt: 6%
Function MIES_GuiUtilities.ipf GetCheckBoxState: 6%
Function MIES_BrowserSettingsPanel.ipf BSP_GetDevice: 6%
Function MIES_Utilities.ipf createDFWithAllParents: 3%
Function MIES_MiesUtilities.ipf GetLastSettingNoCache: 3%
Function MIES_Utilities.ipf IsValidObjectName: 3%
Function MIES_WaveDataFolderGetters.ipf UpgradeDataFolderLocation: 3%
Function MIES_Utilities.ipf DataFolderExistsDFR: 3%
Function MIES_MiesUtilities.ipf GetLastSetting: 3%
Function MIES_AnalysisFunctionHelpers.ipf AFH_GetLastSweepAcquired: 3%
Function MIES_MiesUtilities.ipf ExtractOneDimDataFromSweep: 3%
Function MIES_WaveDataFolderGetters.ipf GetMiesPathAsString: 3%
Function MIES_Utilities.ipf str2numSafe: 3%
```

This seems a bit tangent to the PA plot speedup, but it makes DAQ with RA in general faster with less overhead. And therefore also the PA plot update.

I deemed this kind of incremental update unfeasible when I implemented the LBN caching, but turns out it is doable.

### CODE REVIEW

**Comment by t-b** [comment]
I'm investigating an issue raised by the tests.

**Comment by t-b** [comment]
@timjarsky Should be fixed.

**Comment by timjarsky** [comment]
@t-b I might not be testing correctly but I'm seeing that the main branch is a little quicker:

LN cache PR Total time: 11.6025, Time in Function code: 2.49936 (21.5%)
Main Total time: 10.3187, Time in Function code: 2.31173 (22.4%)

PA disabled 
26 sweeps overlaid (AD only)
4 headstages

**Comment by t-b** [comment]
I'm still seeing

PR:
```
Total time: 0.0636469, Time in Function code: 0.0595406 (93.5%)
Top function percentages:
Function MIES_MiesUtilities.ipf ParseDeviceString: 17%
Function MIES_MiesUtilities.ipf FindIndizes: 10%
Function MIES_BrowserSettingsPanel.ipf BSP_GetDevice: 7%
Function MIES_WaveDataFolderGetters.ipf UpgradeWaveLocationAndGetIt: 3%
Function MIES_Utilities.ipf createDFWithAllParents: 3%
Function MIES_Utilities.ipf str2numSafe: 3%
Function MIES_GuiUtilities.ipf GetPopupMenuString: 3%
Function MIES_WaveDataFolderGetters.ipf GetLBNumericalValues: 3%
Function MIES_MiesUtilities.ipf ExtractSweepNumber: 3%
Function MIES_WaveDataFolderGetters.ipf GetCacheKeyWave: 3%
Function MIES_GuiUtilities.ipf GetAxisRange: 3%
Function MIES_OverlaySweeps.ipf OVS_UpdatePanel: 3%
Function MIES_Utilities.ipf IsEmpty: 3%
Function MIES_MiesUtilities.ipf GetHardwareType: 3%
Function MIES_DataBrowser.ipf DB_GetPlainSweepList: 3%
Function MIES_WaveDataFolderGetters.ipf GetITCDevicesFolder: 3%
Function MIES_MiesUtilities.ipf ExtractOneDimDataFromSweep: 3%
Function MIES_AnalysisFunctionHelpers.ipf AFH_GetLastSweepAcquired: 3%
Function FunctionProfiling.ipf BeginFunctionProfiling: 3%
```

main:
```
Total time: 1.15687, Time in Function code: 1.12684 (97.4%)
Top function percentages:
Function MIES_Utilities.ipf GetSetIntersection: 38%
Function MIES_MiesUtilities.ipf FindIndizes: 37%
Function MIES_MiesUtilities.ipf GetLastSettingNoCache: 3%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 2%
Function MIES_Utilities.ipf createDFWithAllParents: 2%
```

**Comment by t-b** [comment]
@timjarsky Retested with the PA image plot support

100 sweeps, OVS all of them, 12 pulses per sweep, each pulse is 10k points long

without incremental labnotebook update
```
Total time: 1.94295, Time in Function code: 1.89442 (97.5%)
Top function percentages:
Function MIES_Utilities.ipf GetSetIntersection: 27%
Function MIES_PulseAveraging.ipf PA_CalculateAllAverages: 26%
Function MIES_PulseAveraging.ipf PA_GenerateAllPulseWaves: 5%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 5%
Function MIES_MiesUtilities.ipf FindIndizes: 4%
Function MIES_Utilities.ipf DataFolderExistsDFR: 3%
Function MIES_Cache.ipf CA_WaveCRCs: 2%
Function MIES_PulseAveraging.ipf PA_ShowImage: 2%
Function MIES_Utilities.ipf SetNumberInWaveNote: 2%
Function MIES_WaveDataFolderGetters.ipf GetPulseAverageSetIndizes: 1%
Function MIES_PulseAveraging.ipf PA_GeneratePulseWaveName: 1%
Function MIES_Cache.ipf CA_GetCacheIndex: 1%
Function MIES_PulseAveraging.ipf PA_CalculatePulseStartTimes: 1%
Function MIES_WaveDataFolderGetters.ipf GetCacheKeyWave: 1%
```

with incremental labnotebook update

```
Total time: 1.22762, Time in Function code: 1.1867 (96.7%)
Top function percentages:
Function MIES_PulseAveraging.ipf PA_CalculateAllAverages: 29%
Function MIES_PulseAveraging.ipf PA_GenerateAllPulseWaves: 11%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 8%
Function MIES_Utilities.ipf DataFolderExistsDFR: 5%
Function MIES_MiesUtilities.ipf GetLastSetting: 4%
Function MIES_Utilities.ipf SetNumberInWaveNote: 3%
Function MIES_Cache.ipf CA_WaveCRCs: 3%
Function MIES_PulseAveraging.ipf PA_GeneratePulseWaveName: 2%
Function MIES_Utilities.ipf createDFWithAllParents: 2%
Function MIES_Utilities.ipf IsEmpty: 2%
Function MIES_PulseAveraging.ipf PA_ShowImage: 2%
Function MIES_Utilities.ipf EnsureLargeEnoughWave: 2%
Function MIES_WaveDataFolderGetters.ipf GetCacheKeyWave: 2%
Function MIES_Utilities.ipf GetSetIntersection: 2%
Function MIES_PulseAveraging.ipf PA_CreateAndFillPulseWaveIfReq: 2%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 2%
```

**Pull request closed without merging**
