### PR TITLE
Add logging to disk for better debugging

### LINKED ISSUE #726: Store error messages and assertion in textual LBN
- Introduce helper function for outputting error messages
- Convert print calls to new helper
- Store these and assertions (short version) in LBN

### LINKED ISSUE #858: Investigate excessive hook execution times
Some users report that "NewExperiment" and NWB export takes a long time (~ 5 minutes).

- [x] Create log file in package settings folder 
- [x] Log timestamps with experiment name and name of hook into that for all hooks in MIES_IgorHooks.ipf

NWB:
- [x] Log file size, type (compressed yes/no) and time it took to export

- [x] Save it in NWB, e.g. in `data_collection`, see https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=script#id146. We already store the IP history there.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Finish
- [x] Add menu option to open log file read-only
- [x] Add option to upload log file, same approach as crash dumps
- [x] Add "start of session" separator , maybe `{}`
- [x] Add computer name, user name, MIES version, etc. on init
- [x] Remove logging on locking
- [x] Is that safe to use when multiple IP instances write into the same file
- [x] Add igor instance id to every entry

Close #858
Close #726

### CODE REVIEW

**Comment by t-b** [comment]
Example:
```json
{"action":"start","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:26:03.053+01:00"}
{"action":"end","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:26:03.095+01:00"}
{"action":"start","source":"IgorBeforeNewHook","ts":"2021-03-08T19:26:03.360+01:00"}
{"action":"start","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:26:03.493+01:00"}
{"action":"end","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:26:03.525+01:00"}
{"action":"end","source":"IgorBeforeNewHook","ts":"2021-03-08T19:26:03.860+01:00"}
{"action":"locking","source":"DAP_LockDevice","ts":"2021-03-08T19:52:38.892+01:00","version":"Release_2.1_20200723-942-gdc3eefb0d"}
{"action":"start","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:54:03.053+01:00"}
{"action":"end","source":"BeforeExperimentSaveHook","ts":"2021-03-08T19:54:03.082+01:00"}
```

**Comment by t-b** [comment]
@timjarsky This is a first version to play around with.

I've now added logging for:
- Igor Hooks to trace newexperiment taking a long time
- ASSERT/ASSERT_TS
- device locking with MIES version
- NWB file export

The log file is also exported to NWB.

I've also reorganized the menu a bit.

**Comment by t-b** [comment]
@timjarsky From #726 I've only implemented logging assertions. I can't think of any obvious errors to log right now. Do you?

**Comment by t-b** [comment]
I've tried reproducing the slow NewExperiment calls and here it takes around 10s. I've done some more in depth profiling but could not find anything really suspicous. I've openend https://www.wavemetrics.com/forum/general/better-way-handle-temporary-data-and-panels to gather some more heads on the question if we can skip the saveExperiment call which also makes closing experiments slow.

**Comment by timjarsky** [comment]
@t-b Log files look good. Thanks for adding a MIES menu item to access them. Is it possible to log what computer was used? - I'm wondering if we could use the computer ID to "untangle" logs from multiple computers.

**Comment by t-b** [comment]
- [ ] Add option to upload log file, same approach as crash dumps
- [ ] Add "start of session" separator , maybe `{}`
- [ ] Add computer name, user name, MIES version, etc. on init

**Comment by t-b** [comment]
The startup entries on IP start now looks like

```jsonl
{}
{"action":"start","computername":"WIN10-THOMAS-PC","exp":"Untitled","igorinfo":"IGORVERS:9.00;BUILD:37206;IGORKIND:pro64;FREEMEM:140732317732864;PHYSMEM:68656934912;USEDPHYSMEM:286785536;NSCREENS:3;SCREEN1:DEPTH=32,RECT=0,0,1200,1920;SCREEN2:DEPTH=32,RECT=2400,-3,3600,1917;SCREEN3:DEPTH=32,RECT=1200,0,2400,1920;","source":"IgorStartOrNewHook","ts":"2021-03-16T17:00:40.143+01:00","username":"thomas","version":"Release_2.1_20200723-983-g8818427b3"}
{"action":"end","exp":"Untitled","source":"IgorStartOrNewHook","ts":"2021-03-16T17:00:40.189+01:00"}
{"action":"start","exp":"Untitled","source":"AfterCompiledHook","ts":"2021-03-16T17:00:40.203+01:00"}
{"action":"end","exp":"Untitled","source":"AfterCompiledHook","ts":"2021-03-16T17:00:40.215+01:00"}
```

**Comment by t-b** [comment]
@timjarsky Next version is ready.

**Comment by timjarsky** [comment]
@t-b since this is a hardware/engineering log, do we want to log other hardware (on device lock)? E.g., hardware dac, and/or devices used for pressure, amplifier?

**Comment by t-b** [comment]
@timjarsky Something like that?

**Comment by timjarsky** [comment]
@t-b 
during autoconfig the following assertion was triggered 
image

**Comment by t-b** [comment]
@timjarsky Sorry for the trouble. Fixed.

**Comment by timjarsky** [comment]
@t-b there is an amp connected but the log entry isn't showing any amps:

```
{"action":"amplifiers","exp":"Untitled","list":"","source":"AI_FindConnectedAmps","ts":"2021-03-17T12:51:53.366-07:00"}
{"action":"locking","device":"ITC1600_Dev_1","exp":"Untitled","source":"DAP_LockDevice","ts":"2021-03-17T12:51:53.730-07:00"}
{"action":"amplifiers","exp":"Untitled","list":"","source":"AI_FindConnectedAmps","ts":"2021-03-17T12:52:01.587-07:00"}
```

**Comment by t-b** [comment]
@t-b Thanks, fixed.

**Comment by t-b** [comment]
I've added the instance ID and a gracefull fallback for the unlikely case that the log file is currently open.

**Review by timjarsky — APPROVED** [review]
very nice!

**Pull request merged**
