### PR TITLE
ITC XOP: Add more resilient closing

### PR DESCRIPTION
**Pull request by t-b**
While digging through the code I found something interesting. For TP MD we have done 0c2a541d (TP MD: Avoid endless loop in case the monitoring thread dies, 2018-01-12) which looks exactly like our current issue. So if we did the same for DAQ MD, i.e. stopping DAQ when we did not receive any FIFO data for 10 times, we could avoid the endless looping. An alternative solution could be restart DAQ, and then also TP, in this case. But that would mean that restarting would work.

Now:
- [x] Update ITCXOP
- [x] Cleanup commits
- [x] Try restarting DAQ in this case for at most 10 tries. Write to log file before attempting to restart and after.
- [x] Add new DQ_STOP_REASON for that with test
- [x] Redirect ITC XOP debug output to JSON logfile as ZeroMQ does, reuse https://github.com/AllenInstitute/ZeroMQ-XOP/blob/main/src/Logging.h and Logging.cpp
- [x] Add menu option to load ITCXOP2 logfile
- [x] Handle stuck FIFO

When ready:
- [x] Get approved by Tim
- [x] Rebase against main
- [x] Merge https://github.com/AllenInstitute/ITCXOP2/pull/17
- [x] Update ITCXOP2 from ITCXOP2/main
- [x] Try figure out why 2022_10_19_172305.pxp failed from the log file
- [x] Pass that to Tim for final ITC1600 testing once CI passes
- [ ] Merge

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Should work better now.

**Comment by t-b** [comment]
@timjarsky I'm confused about your two comments. In the first it works and in the second totally not?! Is that really so?

**Comment by timjarsky** [comment]
Yes, that's right. I updated the PR to pull in the most recent commit and it stopped working.

**Comment by t-b** [comment]
@timjarsky I've added some debug output to ITCOpenDevice2. Let's look into that together the next time we chat,

**Comment by t-b** [comment]
@timjarsky Next try. Found the issue :)

**Comment by t-b** [comment]
@timjarsky I've now properly implemented our hacks from monday regarding fifo being 0 and a timeout when querying the thread queue.

**Comment by t-b** [comment]
@timjarsky I've included the changes from #1474 here as well. This avoids the "impossible state transition" assertion.

**Comment by t-b** [comment]
2022_08_24_113306.pxp
2022_08_24_153522.pxp

Errored out due to a bug in the first version of the PR #1474 which was included here. This was fixed in #1474 before being merged and is fixed here as well already.

2022_08_24_193107.pxp

This is the interesting one:

```
  [...]
  TFH_FifoLoop: Looped 523399, fifoPos 0
  HW_ITC_MoreData_TS: Looped 0, V_ITCXOPError 10004, V_ITCError 0
  The ITC XOP returned the following errors: ITCError=0, ITCXOPError=10004
  XOP error message: Tried to access an unused DeviceID.
  Responsible function: HW_ITC_MoreData_TS
  Complete call stack: TFH_FifoLoop,MIES_ThreadedFIFOHandling.ipf,109;HW_ITC_MoreData_TS,MIES_DAC-Hardware.ipf,1483;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,826;
  BUG_TS: The ITC XOP was called incorrectly!
  BUG_TS: Should never be called during automated testing.
  TFH_FifoLoop: Looped 523400, fifoPos 9223372036854775807
  The ITC XOP returned the following errors: ITCError=0, ITCXOPError=10004
  XOP error message: Tried to access an unused DeviceID.
  Responsible function: HW_ITC_StopAcq_TS
  Complete call stack: TFH_FifoLoop,MIES_ThreadedFIFOHandling.ipf,130;HW_ITC_StopAcq_TS,MIES_DAC-Hardware.ipf,1055;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,826;
  BUG_TS: The ITC XOP was called incorrectly!
  BUG_TS: Should never be called during automated testing.
  !!! Threadsafe assertion FAILED !!!
  Message: "DAC error"
```

We do get only 0s from HW_ITC_MoreData_TS for the fifo position for a long time. When at some point it returns an "DAC error" from the ITCXOP2 and asserts out. And then data acquisition is stopped as DQM_FifoMonitor thinks it is done.

While digging through the code I found something interesting. For TP MD we have done 0c2a541d (TP MD: Avoid endless loop in case the monitoring thread dies, 2018-01-12) which looks exactly like our current issue. So if we did the same for DAQ MD, i.e. stopping DAQ when we did not receive any FIFO data for 10 times, we could avoid the endless looping. An alternative solution could be restart DAQ, and then also TP, in this case. But that would mean that restarting would work.

**Comment by t-b** [comment]
- [ ] Redirect ITC XOP debug output to JSON logfile as ZeroMQ does

**Comment by t-b** [comment]
2022_09_01_171633.pxp:

Failing tests:
- UnassociatedChannelsAndTTLs
- UnassocChannelsDuplicatedEntry: One DSP timeout

2022_09_01_142727.pxp:

Failing tests:
- UnassociatedChannelsAndTTLs
- SF_InsertedTPVersusTP with `BUG_TS: Encountered pending RTE: 393229, MCC_SetMode;Message timeout.` Seems like an MCC issue.

Both JUNIT files also had invalid UTF8 symbols, we track that in https://github.com/byte-physics/igor-unit-testing-framework/issues/236. Could be your PC.

**Comment by t-b** [comment]
@timjarsky Ready for another try. We now restart DAQ in case of FIFO timeout issues. And that also works in the test here. (I'll be available later for a chat, as I have to grab some food first).

**Comment by t-b** [comment]
Last uploaded test: 

```
2022_09_30_094914.pxp
Log.jsonl
```

It fails at the end due to UTF background monitor timeout.

The logfile has:

```
{"exp":"Untitled","id":"79fe266","source":"XOP","str":"(thread 9388)\rCaller ITC_GetDataAvailable\rsizeof(ITCChannelDataEx)=24\rchanDataEx[0].ChannelType=1\rchanDataEx[0].Command=0\rchanDataEx[0].ChannelNumber=0\rchanDataEx[0].Status=0\rchanDataEx[0].Value=262144\rchanDataEx[0].DataPointer=0x0\rchanDataEx[1].ChannelType=0\rchanDataEx[1].Command=0\rchanDataEx[1].ChannelNumber=1\rchanDataEx[1].Status=0\rchanDataEx[1].Value=0\rchanDataEx[1].DataPointer=0x0\r","ts":"2022-09-30T09:30:48-0700"}
```

And a lot of those lines

```
$ grep -c 262144 Log.jsonl
824531
```

so I think we also need to add a check for not moving fifo. In the same spirit as a fifo timeout.

**Comment by t-b** [comment]
@timjarsky Ready for next try.

Changes:
- Handles stuck FIFO. If the FIFO does not move in 2s we restart DAQ
- Includes ITCXOP2 fixes which *might* have been introduced in early 2022 and *could* be responsible for some CI crashes, see https://github.com/AllenInstitute/ITCXOP2/pull/25

**Comment by t-b** [comment]
Reviewing tests results from TJ:

2022_10_04_123732.pxp
2022_10_04_152609.pxp

Both Passing :)

2022_10_05_085258.pxp

DSP timeout in very first test case:

```
Entering test case "MD0_RA0_I0_L0_BKG_0:ITC1600"
  The ITC XOP returned the following errors: ITCError=0x80303004, ITCXOPError=0
  DSP timeout (0x80303004);Place: User Layer; Connection: User Layer; Error Type: Power / Timeout; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x4
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Responsible function: HW_ITC_GetState
```

As this is single device, none of the new auto-restart hacks kicked in. I would
say this is also not required as single device is neither the default nor
suggested to use.

2022_10_05_101840.pxp

```
  Entering test case "PatchSeqSealEvaluation#PS_SE2:ITC1600"
  The ITC XOP returned the following errors: ITCError=0x80303001, ITCXOPError=0
  DSP timeout (0x80303001);Place: User Layer; Connection: User Layer; Error Type: Power / Timeout; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Responsible function: HW_ITC_WriteDAC
  Complete call stack: DQM_FIFOMonitor,MIES_DataAcquisition_Multi.ipf,106;DQ_StopOngoingDAQ,MIES_DataAcquisition.ipf,44;DQ_StopOngoingDAQHelper,MIES_DataAcquisition.ipf,91;DQM_TerminateOngoingDAQHelper,MIES_DataAcquisition_Multi.ipf,183;HW_StopAcq,MIES_DAC-Hardware.ipf,381;HW_ITC_StopAcq,MIES_DAC-Hardware.ipf,1124;HW_ITC_WriteDAC,MIES_DAC-Hardware.ipf,1368;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,827;
  BUG_TS: The ITC XOP returned an error!
  BUG_TS: Should never be called during automated testing.
  !!! Threadsafe assertion FAILED !!!
  Message: "DAC error"
```

2022_10_06_105312.pxp

```
  Entering test case "PatchSeqTestRamp#PS_RA1:ITC1600"
  (ITC1600_Dev_1) The analysis function preDAQ_MP_ChirpBlowout for stim set Ramp_DA_0 and event type "Pre DAQ" has an invalid signature or is in an unlisted location
  Encountered "Abort" in test case "PatchSeqTestRamp#PS_RA1", procedure file "UTF_PatchSeqRamp.ipf"
  Entering reentry "PatchSeqTestRamp#PS_RA1_REENTRY"
```

I have never seen this error. The function preDAQ_MP_ChirpBlowout is available in MIES_AnalysisFunctions.ipf. This looks like a transient bug.

2022_10_06_131042.pxp

Same as above.

2022_10_06_175615.pxp

No error, but it is prematurely stopped.

**Comment by timjarsky** [comment]
@t-b I checked the approved checkbox.

**Comment by t-b** [comment]
For reference here as the last results from last week.

2022_10_19_113153.pxp:

Passed

2022_10_19_135717.pxp:

Recovered from DSP timeout.

2022_10_19_161158.pxp:

DAQ did not finish due to "UTF background monitor has reached the timeout for reentry"

2022_10_19_172305.pxp

ITC errors: DSP timeout/DSP timeout/System is not initialized

**Comment by t-b** [comment]
Check why `CheckIfConfigurationRestoresMCCFilterGain` fails again..

**Comment by t-b** [comment]
The experiment 2022_10_19_172305.pxp failed due to DSP timeout followed by System not initialized.

```
  Entering test case "CheckTPStorage2:ITC1600"
  The ITC XOP returned the following errors: ITCError=0x80303001, ITCXOPError=0
  DSP timeout (0x80303001);Place: User Layer; Connection: User Layer; Error Type: Power / Timeout; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Responsible function: HW_ITC_GetState
  Complete call stack: StopTP_IGNORE,UTF_HardwareMain.ipf,771;PGC_SetAndActivateControl,MIES_ProgrammaticGUIControl.ipf,230;DAP_ButtonProc_TPDAQ,MIES_DAEphys.ipf,4295;TP_StopTestPulse,MIES_TestPulse.ipf,1204;TP_StopTestPulseWrapper,MIES_TestPulse.ipf,1238;TPM_StopTestPulseMultiDevice,MIES_TestPulse_Multi.ipf,142;DQM_CallFuncForDevicesYoked,MIES_DataAcquisition_Multi.ipf,334;CallFunctionForEachListItem,MIES_Utilities.ipf,1751;TPM_StopTPMD,MIES_TestPulse_Multi.ipf,334;TPM_StopTPMDWrapper,MIES_TestPulse_Multi.ipf,361;HW_IsRunning,MIES_DAC-Hardware.ipf,404;HW_ITC_IsRunning,MIES_DAC-Hardware.ipf,1299;HW_ITC_GetState,MIES_DAC-Hardware.ipf,1323;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,827;
  BUG_TS: The ITC XOP returned an error!
  BUG_TS: Should never be called during automated testing.
  !!! Threadsafe assertion FAILED !!!
  Message: "DAC error"
  Retrying getting data from thread, keep fingers crossed (1/10)
  Retrying getting data from thread, keep fingers crossed (2/10)
  Retrying getting data from thread, keep fingers crossed (3/10)
  Retrying getting data from thread, keep fingers crossed (4/10)
  Retrying getting data from thread, keep fingers crossed (5/10)
  Retrying getting data from thread, keep fingers crossed (6/10)
  Retrying getting data from thread, keep fingers crossed (7/10)
  Retrying getting data from thread, keep fingers crossed (8/10)
  Retrying getting data from thread, keep fingers crossed (9/10)
  Retrying getting data from thread, keep fingers crossed (10/10)
  The ITC XOP returned the following errors: ITCError=0x80303001, ITCXOPError=0
  DSP timeout (0x80303001);Place: User Layer; Connection: User Layer; Error Type: Power / Timeout; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Responsible function: HW_ITC_GetState
  Complete call stack: TPM_BkrdTPFuncMD,MIES_TestPulse_Multi.ipf,296;TPM_StopTestPulseMultiDevice,MIES_TestPulse_Multi.ipf,142;DQM_CallFuncForDevicesYoked,MIES_DataAcquisition_Multi.ipf,334;CallFunctionForEachListItem,MIES_Utilities.ipf,1751;TPM_StopTPMD,MIES_TestPulse_Multi.ipf,334;TPM_StopTPMDWrapper,MIES_TestPulse_Multi.ipf,361;HW_IsRunning,MIES_DAC-Hardware.ipf,404;HW_ITC_IsRunning,MIES_DAC-Hardware.ipf,1299;HW_ITC_GetState,MIES_DAC-Hardware.ipf,1323;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,827;
  BUG_TS: The ITC XOP returned an error!
  BUG_TS: Should never be called during automated testing.
  !!! Threadsafe assertion FAILED !!!
  Message: "DAC error"
  The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0
  System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  Responsible function: HW_ITC_GetState
  Complete call stack: IgorBeforeQuitHook,MIES_IgorHooks.ipf,192;IH_Cleanup,MIES_IgorHooks.ipf,168;DAP_UnlockAllDevices,MIES_DAEphys.ipf,4195;DAP_UnlockDevice,MIES_DAEphys.ipf,5130;TP_StopTestPulse,MIES_TestPulse.ipf,1204;TP_StopTestPulseWrapper,MIES_TestPulse.ipf,1238;TPM_StopTestPulseMultiDevice,MIES_TestPulse_Multi.ipf,142;DQM_CallFuncForDevicesYoked,MIES_DataAcquisition_Multi.ipf,334;CallFunctionForEachListItem,MIES_Utilities.ipf,1751;TPM_StopTPMD,MIES_TestPulse_Multi.ipf,334;TPM_StopTPMDWrapper,MIES_TestPulse_Multi.ipf,361;HW_IsRunning,MIES_DAC-Hardware.ipf,404;HW_ITC_IsRunning,MIES_DAC-Hardware.ipf,1299;HW_ITC_GetState,MIES_DAC-Hardware.ipf,1323;HW_ITC_HandleReturnValues,MIES_DAC-Hardware.ipf,827;
  BUG_TS: The ITC XOP returned an error!
  BUG_TS: Should never be called during automated testing.
  !!! Threadsafe assertion FAILED !!!
  Message: "DAC error"
  BUG IH_Cleanup(...)#L179: Caught runtime error or assertion: 0
  BUG: Should never be called during automated testing.
```

**Comment by t-b** [comment]
That the ITC test passes is I'm afraid pure luck.

**Comment by timjarsky** [comment]
@t-b 
```
  Leaving test case "CheckSweepSavingCompatible:ITC1600"
  Finished with no errors
  Leaving test suite "UTF_HardwareTestsWithBUG.ipf"
  Test finished with no errors
  End of test "MIES with Hardware"

```

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
