### PR TITLE
Bugfix/1237 various

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky Fixed on error with powerSpectrum and TP which could explain the crash.

**Comment by timjarsky** [comment]
@t-b I still get the Igor crash with a 1000ms TP, but I think I figured out a way to prevent the computer crash. Let's screen share in the next couple of days when you have some time.

**Comment by timjarsky** [comment]
> @t-b I still get the Igor crash with a 1000ms TP, but I think I figured out a way to prevent the computer crash. Let's screen share in the next couple of days when you have some time.

with TP % duration = 35%, but not 25%

**Comment by t-b** [comment]
@timjarsky I've removed the power spectrum fixes from this PR and extracted them into #1238. Please check if this PR still crashes.

**Comment by t-b** [comment]
@timjarsky Is that good to go?

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
