### PR TITLE
Tests: Check TP Storage wave

### PR DESCRIPTION
**Pull request by t-b**
- [x]  Check in tests that gain is 1

Successor of #1105.

### CODE REVIEW

**Review by timjarsky — APPROVED** [review]

**Comment by t-b** [comment]
@timjarsky This PR requires that the cabling on the ITC18 and NI used on the CI machines is 1:1. IIRC this needs to be still done or?

**Comment by t-b** [comment]
The tests with NI hardware still fail. The second headstage has DAC 0 and ADC 0 connected but these seem to be not connected.

**Comment by timjarsky** [comment]
- [ ] check wiring on NI DAQ

**Comment by t-b** [comment]
Will merge once CI passes.

**Comment by t-b** [comment]
@timjarsky I added support for the gains and filters to `AI_SendToAmp` here. I needed the gains already, so I thought while at it, I do the filters.

**Pull request merged**
