### PR TITLE
Nicify epoch tooltips

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
image

@t-b What do you think about putting the shortname at the top of the list and adding the time unit to the start and end times?

**Comment by t-b** [comment]
@timjarsky Jeep, I can do that.

**Comment by t-b** [comment]
Shortname is the top entry in the list.
If there is no shortname output `ShortName: NA`, otherwise just have the shortname in one line and make it bold.

**Comment by timjarsky** [comment]
very nice;

**Comment by timjarsky** [comment]
very nice;
image

**Pull request merged**
