### PR TITLE
Make analyzing TP faster

### PR DESCRIPTION
**Pull request by t-b**
I just noticed that TP_AnalyzeTP takes a lot of time here. So I went out and did some changes. Totally WIP and not much tested.

### CODE REVIEW

**Comment by t-b** [comment]
Now I know why I was confused with TPStorage. Its documentation for the columns was wrong.

**Comment by timjarsky** [comment]
@t-b function profiling doesn't show a difference between the master and this branch. [the branch was slightly slower in two tests with 2 and 4 channels active]

**Comment by t-b** [comment]
@t-b Have you tried TP during DAQ on one channel and a long stimset on the other?

**Comment by timjarsky** [comment]
@t-b I still can't get this to perform faster on my work desktop (with TP during DAQ).

**Comment by t-b** [comment]
@timjarsky I've tried to reproduce my speeding up here. And I could not according to function profiling values. But that also says

```
// Your test function may call functions that are ThreadSafe and those that reside in an independent module
//	but only functions in the main thread are profiled. 
```

so we can't use function profiling numbers here.

As we want to use more complex TP fitting in the future, this PR might be a step in the right direction, if you feel this PR is at least as good as master.

**Comment by timjarsky** [comment]
@t-b 
Leaving FP results here for future reference.

PR:
Total time: 21.3233, Time in Function code: 7.36835 (34.6%)
Top function percentages:
Function MIES_AmplifierInteraction.ipf AI_SelectMultiClamp: 10%
Function MIES_Utilities.ipf createDFWithAllParents: 10%
Function MIES_ThreadsafeUtilities.ipf TS_ThreadGroupPutDFR: 9%
Function MIES_ThreadsafeUtilities.ipf TS_GetNewestFromThreadQueue: 6%
Function MIES_Async.ipf ASYNC_PrepareDF: 5%
Function MIES_Oscilloscope.ipf SCOPE_UpdateOscilloscopeData: 5%
Function MIES_Async.ipf ASYNC_AddParam: 5%
Function MIES_MiesUtilities.ipf ParseDeviceString: 4%
Function MIES_Oscilloscope.ipf SCOPE_ITC_UpdateOscilloscope: 3%
Function MIES_Utilities.ipf DataFolderExistsDFR: 3%
Function MIES_DataConfiguratorITC.ipf DC_PlaceDataInHardwareDataWave: 3%
Function MIES_Async.ipf ASYNC_Execute: 2%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 2%
Function MIES_AmplifierInteraction.ipf AI_EnsureCorrectMode: 2%
Function MIES_Async.ipf ASYNC_ThreadReadOut: 2%
Function MIES_DataConfiguratorITC.ipf DC_CheckIfDataWaveHasBorderVals: 1%
Function MIES_Utilities.ipf IsEmpty: 1%
Function MIES_MiesUtilities.ipf KillOrMoveToTrashPath: 1%
Function MIES_Async.ipf DataFolderExistsDFR: 1%
Function MIES_Oscilloscope.ipf SCOPE_CreateGraph: 1%
Function MIES_TestPulse.ipf TP_AnalyzeTP: 1%
Function MIES_AmplifierInteraction.ipf AI_FillAndSendAmpliferSettings: 1%
Function MIES_TestPulse.ipf TP_ROAnalysis: 1%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 1%
Function MIES_WaveDataFolderGetters.ipf GetLBIndexCache: 1%

MASTER:
Total time: 43.0573, Time in Function code: 15.3328 (35.6%)
Top function percentages:
Function MIES_Utilities.ipf createDFWithAllParents: 10%
Function MIES_ThreadsafeUtilities.ipf TS_ThreadGroupPutDFR: 10%
Function MIES_AmplifierInteraction.ipf AI_SelectMultiClamp: 9%
Function MIES_Async.ipf ASYNC_AddParam: 6%
Function MIES_ThreadsafeUtilities.ipf TS_GetNewestFromThreadQueue: 5%
Function MIES_Async.ipf ASYNC_PrepareDF: 5%
Function MIES_Oscilloscope.ipf SCOPE_UpdateOscilloscopeData: 5%
Function MIES_MiesUtilities.ipf ParseDeviceString: 4%
Function MIES_DataConfiguratorITC.ipf DC_PlaceDataInHardwareDataWave: 3%
Function MIES_Utilities.ipf DataFolderExistsDFR: 3%
Function MIES_Oscilloscope.ipf SCOPE_ITC_UpdateOscilloscope: 3%
Function MIES_Async.ipf ASYNC_Execute: 3%
Function MIES_TestPulse.ipf TP_AnalyzeTP: 2%
Function MIES_TestPulse.ipf TP_ROAnalysis: 2%
Function MIES_Async.ipf ASYNC_ThreadReadOut: 2%
Function MIES_Cache.ipf CA_TryFetchingEntryFromCache: 2%
Function MIES_Utilities.ipf GetNumberFromWaveNote: 1%
Function MIES_WaveDataFolderGetters.ipf GetLBIndexCache: 1%
Function MIES_MiesUtilities.ipf KillOrMoveToTrashPath: 1%
Function MIES_Utilities.ipf FloatWithMinSigDigits: 1%
Function MIES_DAC-Hardware.ipf HW_ITC_StartAcq: 1%
Function MIES_MiesUtilities.ipf DecimateWithMethod: 1%
Function MIES_AmplifierInteraction.ipf AI_EnsureCorrectMode: 1%

**Pull request merged**
