### PR TITLE
Correct handling of large log files

### PR DESCRIPTION
**Pull request by MichaelHuth**
- Make it possible to load > 2 GB log files and performant evaluation
- Add archiving of uploaded logs to chunks.
- Better upload handling in chunks and some progress output
- Use new functions also for log data in NWB files

close https://github.com/AllenInstitute/MIES/issues/1714
close https://github.com/AllenInstitute/MIES/pull/1715

### CODE REVIEW

**Comment by t-b** [comment]
Review:

1fddb99a (Util: Add function LoadTextFileToWave that supports > 2 GB files, 2023-05-25)

Missing tests.

a113a908 (Util: Update LoadTextFile function description, noting the < 2 GB limit, 2023-05-25)

Jeep.

c2342d80 (Util: Move JSON Parsing in seperatate function in FilterByDate, 2023-05-25)

Fine.

5bbd611d (Util: FilterLogfileByDate replace LoadTextFile with LoadTextFileToWave, 2023-05-25)

Makes sense.

7354b205 (Rewrite FilterByDate using BinarySearch, 2023-05-25)

That's very terse. FindFirstLogEntryElementByDate/FindLastLogEntryElementByDate should have documentation.

The commit message does also not explain any potential differences of the new implementation vs the old one. As you have removed part of the old test `// non-matching entries are included` this is especially important.

The case

```
9 | 8009 |   | if(!IsNaN(ts))
-- | -- | -- | --
  | 0 | 8010 |   | break
  | 9 | 8011 |   | endif
```

is not covered in the tests for FindFirstLogEntryElementByDate/FindLastLogEntryElementByDate.
Double whitespace after equal sign in `ts =  ParseISO8601TimeStamp`.

a89b81e4 (Util: New LogToStrings that splits a logData text wave to size limited strings, 2023-05-25)

Missing documentation and tests. Is there anything MIES specific in these functions? If not they should be moved to MIES_Utilities.ipf.
Why does LogToStrings not return a wave reference wave? The current approach seems to work, but it's quite confusing and also slow with the TExtWaveToList in LogToStringsPutPart.j

7175c89a (Util: Add function base64EncodeSafe with proper size check, 2023-05-25)
be83f1f7 (ParseISO8601TimeStamp: Add eraly return if argument is empty string, 2023-05-25)

eraly -> early

6e5fc54c (GenerateJSONTemplateForUpload: Add optional argument to set timeStamp, 2023-05-25)

okay

b0c8c808 (UploadLogFiles: Upload in chunks, 2023-05-25)

Bad commit message as it does not explain anything.
The new code ignores the verbose flag. Why?

Add a separate function for calculating the base64 overhead.

```
		fSize = GetFileSize(file)
		if(IsNaN(fSize))
			continue
		endif
```

That drops non-existing files a la `XXX-does-not-exist`. It is also quite expensive to query the filesize just for the print out.

Can we have one upload only for the common case of no splitting?

a3932026 (Remove unused function FilterLogfileByDate, 2023-05-25)

This should be merged with the commit not requiring the function as otherwise future readers don't understand why this function is now obsolete finding this commit.

53c074d3 (Add archiving of uploaded parts of the Log files, 2023-05-26)

ArchiveLogFile must *not* duplicate the custom zeromq flags!!

```
+        endif
+        if(FileExists(newFullFilePath))
```

-> elseif

65470c45 (Revise NWB_AppendLogFileToString to use new FilterByDate, 2023-05-27)

I think we chatted about that, but you can assume that the data from one day is below 2GB.

```
+        now = GetISO8601TimeStamp(localTimeZone = 1)
+        firstDate = ParseISO8601TimeStamp(now[0, 9] + "T00:00:00Z")
```

It's heavily confusing to have `localTimeZone` in one line and `Z` in the other.

47ff67ba (Add constant for log file line ending, 2023-05-27)

Makes sense.

358caed2 (CONF: Make uploading of logfiles on Configuration restore more resilient, 2023-06-01)

Good point, although you might want to clear the RTE before calling BUG.

11754da5 (ASSERT on too large files in LoadTextFile for more resilience, 2023-06-01)
4907b6a0 (Add ASSERTions for RTEs of GetFileFolderInfo in common utility functions, 2023-06-01)

Both are good.

**Comment by MichaelHuth** [comment]
> Why does LogToStrings not return a wave reference wave? The current approach seems to work, but it's quite confusing and also slow with the TExtWaveToList in LogToStringsPutPart.j

I have rewritten the functions such that the splitting function returns a wave reference wave.
If the caller works further with a string as logData TextWaveToList is now called in these callers.
The only way I see to mitigate TextWaveToList calls could be for cases where the resulting data is written to disk. Instead of writing a string through FBinWrite, a text wave through wfprintf.
We could also consider to use wfprintf in TextWaveToList for the case of 1D waves, if that is faster (not tested).

> The new code ignores the verbose flag. Why?

Nothing has changed in the new code regarding the verbose flag.

> Can we have one upload only for the common case of no splitting?

If nothing is split there is only a single json created and uploaded.

**Comment by t-b** [comment]
Needs conflict resultion and rebase for Historic Data CI.

**Comment by t-b** [comment]
Very nice! Thanks a lot for the effort!

**Review by t-b — APPROVED** [review]

**Pull request merged**
