### PR TITLE
Feature/preset configuration loading saving to settings folder

### LINKED ISSUE #482: auto config fails with databrowser and overlay sweeps enabled
!!! Assertion FAILED !!!
  Message: "Expected a text wave"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
CONF_AutoLoader(...)#L251 [MIES_Configuration.ipf]
CONF_RestoreWindow(...)#L363 [MIES_Configuration.ipf]
CONF_JSONToWindow(...)#L992 [MIES_Configuration.ipf]
CONF_RestoreControl(...)#L1191 [MIES_Configuration.ipf]
PGC_SetAndActivateControl(...)#L238 [MIES_ProgrammaticGUIControl.ipf]
SetPopupMenuString(...)#L469 [MIES_GuiUtilities.ipf]
OVS_GetSweepSelectionChoices(...)#L86 [MIES_OverlaySweeps.ipf]
TextWaveToList(...)#L3070 [MIES_Utilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-03-12T13:57:35-07:00
  Locked device: [ITC1600_Dev_0]
  Current sweep: [NaN]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_BG_MULTI_DEVICE]
  Experiment: 2020_03_12_134202.pxp
  Igor Pro version: 8.0.5.1 (34845)
  MIES version:
  Release_2.0_20190602-698-g4893c076
Date and time of last commit: 2020-02-27T20:38:06+01:00
Submodule status: 
160000 44cb0b1fe9ad9fb188d95720573a09cc7825094a 0	Packages/IPNWB
160000 9a3f02fb7d007b4b34b29bda1f3fddc0ce64ad33 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 7d239dad06bf51220cc63460373d21afcec0da91 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing

### PR DESCRIPTION
**Pull request by t-b**
Close https://github.com/AllenInstitute/MIES/issues/451.
Close #482.

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b this may be SF related rather than config related. The following assertion occurs before the first sweep is acquired and the SF is enabled.

```
  !!! Assertion FAILED !!!
  Message: "Wave must be 1D"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L104 [MIES_DataAcquisition_Multi.ipf]
DQM_StopDataAcq(...)#L358 [MIES_DataAcquisition_Multi.ipf]
SWS_SaveAcquiredData(...)#L55 [MIES_SweepSaving.ipf]
SWS_AfterSweepDataSaveHook(...)#L80 [MIES_SweepSaving.ipf]
DB_UpdateToLastSweep(...)#L597 [MIES_DataBrowser.ipf]
PGC_SetAndActivateControl(...)#L229 [MIES_ProgrammaticGUIControl.ipf]
SF_button_sweepFormula_display(...)#L1504 [MIES_SweepFormula.ipf]
SF_FormulaPlotter(...)#L1001 [MIES_SweepFormula.ipf]
SF_FormulaExecutor(...)#L751 [MIES_SweepFormula.ipf]
SF_FormulaExecutor(...)#L728 [MIES_SweepFormula.ipf]
GetUniqueEntries(...)#L733 [MIES_Utilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-03-12T13:27:00-07:00
  Locked device: [ITC1600_Dev_0]
  Current sweep: [0]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (34845)
  MIES version:
  Release_2.0_20190602-698-g4893c076
Date and time of last commit: 2020-02-27T20:38:06+01:00
Submodule status: 
160000 44cb0b1fe9ad9fb188d95720573a09cc7825094a 0	Packages/IPNWB
160000 9a3f02fb7d007b4b34b29bda1f3fddc0ce64ad33 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 7d239dad06bf51220cc63460373d21afcec0da91 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################
```

**Comment by t-b** [comment]
@timjarsky THanks. That is the original bug from Steph. Can you attach your json config files?

**Comment by timjarsky** [comment]
@t-b I'm also noticing that the hardware isn't being closed in this branch

[2_ITC1600_DEV_0_DB.zip](https://github.com/AllenInstitute/MIES/files/4327093/2_ITC1600_DEV_0_DB.zip)

**Comment by t-b** [comment]
@timjarsky Ready for getting hit hard :)

**Comment by t-b** [comment]
@timjarsky I fixed the test.

**Pull request merged**
