### PR TITLE
Add epoch range support for SweepFormula data operation

### PR DESCRIPTION
**Pull request by MichaelHuth**
close https://github.com/AllenInstitute/MIES/issues/1056

### CODE REVIEW

**Comment by t-b** [comment]
Review:

f8964e54 (EP_GetEpochs: Allow NaN for treelevel to ignore treelevel as filter, 2021-11-22)

Please make treelevel an optional parameter, not giving this should ignore treelevel.

eca0eb97 (SweepFormula: Change data operation to accept a epoch name for the range spec, 2021-11-22)

- BSP_GetLBNWave can return $"" and this is not handled. IMHO BSP_GetLBNWave is missing \@return documentation to mention that.
- SF_GetRangeFromEpoch: Should use SF_ASSERT when getting multiple epochs

132279db (SweepFormula: Add documentation for data operations epoch range support., 2021-11-22)

`data(""E1"` -> `data("E1"`

03ebdcd8 (SweepFormula tests: Add Test for data with epoch information, 2021-11-22)


Playing around shows though that it does not handle AD channels.

Recipe:
- HardwareTests.pxp with runwithOpts(testcase = "PS_CR1")
- Display first sweep, Visualize epochs + AD + DA

SF Formula:
```
data(
cursors(A,B),
channels(DA0),
sweeps()
)

and

data(
ST,
channels(DA0),
sweeps()
)

and

data(
ST,
channels(AD1),
sweeps()
)
```

I would expect data to figure out the DA channel for each sweep from the AD channel. To my suprise we don't seem to have a function to answer that in general, so we have to add it here. Signature could look like `Function GetHeadstageForChannel(WAVE numericalValues, variable channelType, variable channelNumber)`.

**Review by t-b — CHANGES_REQUESTED** [review]
See comment

**Comment by t-b** [comment]
Review:

f8964e54 (EP_GetEpochs: Allow NaN for treelevel to ignore treelevel as filter, 2021-11-22)

Please make treelevel an optional parameter, not giving this should ignore treelevel.

eca0eb97 (SweepFormula: Change data operation to accept a epoch name for the range spec, 2021-11-22)

- BSP_GetLBNWave can return $"" and this is not handled. IMHO BSP_GetLBNWave is missing \@return documentation to mention that.
- SF_GetRangeFromEpoch: Should use SF_ASSERT when getting multiple epochs

132279db (SweepFormula: Add documentation for data operations epoch range support., 2021-11-22)

`data(""E1"` -> `data("E1"`

03ebdcd8 (SweepFormula tests: Add Test for data with epoch information, 2021-11-22)


Playing around shows though that it does not handle AD channels.

Recipe:
- HardwareTests.pxp with runwithOpts(testcase = "PS_CR1")
- Display first sweep, Visualize epochs + AD + DA

SF Formula:
```
data(
cursors(A,B),
channels(DA0),
sweeps()
)

and

data(
ST,
channels(DA0),
sweeps()
)

and

data(
ST,
channels(AD1),
sweeps()
)
```

I would expect data to figure out the DA channel for each sweep from the AD channel. To my suprise we don't seem to have a function to answer that in general, so we have to add it here. Signature could look like `Function GetHeadstageForChannel(WAVE numericalValues, variable channelType, variable channelNumber)`.

**Comment by MichaelHuth** [comment]
> SF_GetRangeFromEpoch: Should use SF_ASSERT when getting multiple epochs

I also thought about that, though epoch short names should be unique. If that is violated it is not an error of the SweepFormula evaluation but a programmer (data) error. Thats why I thought a regular ASSERT is best fitting there.

**Comment by t-b** [comment]
> I also thought about that, though epoch short names should be unique. If that is violated it is not an error of the SweepFormula evaluation but a programmer (data) error. Thats why I thought a regular ASSERT is best fitting there.

You already support regexps without really saying so. So `"E*"` gives multiple epochs or?

**Comment by t-b** [comment]
If you want to prevent support regexps without doing so intentionally you need to enclose the given shortname into `\\Q` and `\\E`.

**Comment by t-b** [comment]
@MichaelHuth LGTM.

**Review by t-b — APPROVED** [review]

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
