### PR TITLE
SF: Add select argument for clamp mode

### PR DESCRIPTION
**Pull request by MichaelHuth**
e.g. select(channels(AD),sweeps(),all,<clampMode>) with all, vc, ic, izero

close https://github.com/AllenInstitute/MIES/issues/1465

### CODE REVIEW

**Comment by MichaelHuth** [comment]
@t-b This is good for review. I will update the SF notebook from the docu change in this PR after the other related PR was merged.

**Comment by t-b** [comment]
Review:

- [ ]

```
 +                        if(V_Value >= 0 && (clampMode == SF_OP_SELECT_CLAMPCODE_ALL || (clampMode != SF_OP_SELECT_CLAMPCODE_ALL && clampMode == clampModes[V_Value])))
```
 
 I think this can be simplified as `A && (B || (!B && C))` is the same as `A && (B || C)`.
 
- [ ] Missing tests

**Review by t-b — CHANGES_REQUESTED** [review]
See comment.

**Review by t-b — APPROVED** [review]

**Comment by timjarsky** [comment]
works great!

```data("Inserted TP;Test Pulse;",select(channels(AD0), sweeps(), all,ic))```

image

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
