### PR TITLE
Bugfix/1132 fix pa plot extraction

### LINKED ISSUE #1088: DB/SB: Require modifier key for changing sweeps via mouse wheel

### LINKED ISSUE #1118: PA plot failure
FTP: `2021-10-22 Spike Control Failures/spike control miscounting spikes.pxp`

grafik

### PR DESCRIPTION
**Pull request by t-b**
- [x] Commit cleanup
- [x] Add units tests for PA_RetrievePulseInfosFromEpochs with all three epoch info versions (no level 3, old naming, new naming)

Close #1118
Close #1088
Close https://github.com/AllenInstitute/MIES/issues/1069

### CODE REVIEW

**Comment by t-b** [comment]
@timjarsky This fixes the PA plot pulse extraction from https://github.com/AllenInstitute/MIES/issues/1118#issuecomment-949965436. If possible it would be nice if you could check that already now. I'll make the MSQ_SpikeControl changes later.

**Comment by t-b** [comment]
@timjarsky Ready.

**Comment by timjarsky** [comment]
@t-b i believe the behavior is the same i.e., the pulse length is too short but I'm not 100% sure. The min pulse to pulse time in the mixed frequency stimulus is 6.67 ms but the average (pink line) is ~5.3 ms long.
image
If `fixed pulse length` is turned on and set to 5ms the PA plot looks correct
image
other spikes show up when the override length is set to 8 ms

**Comment by timjarsky** [comment]
@t-b alt-scroll only goes down. The modified help message on `override length` indicating the traces are dropped didn't make it in.

**Comment by timjarsky** [comment]
@t-b also getting  !!! Assertion FAILED !!!
  Message: "Left over space"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
BSP_CheckProc_ChangedSetting(...)#L1155 [MIES_BrowserSettingsPanel.ipf]
UpdateSweepPlot(...)#L5720 [MIES_MiesUtilities.ipf]
SB_UpdateSweepPlot(...)#L332 [MIES_AnalysisBrowser_SweepBrowser.ipf]
PostPlotTransformations(...)#L3660 [MIES_MiesUtilities.ipf]
LayoutGraph(...)#L2408 [MIES_MiesUtilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-11-04T13:25:56-07:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled ()
  Igor Pro version: 9.0.0.10 (37840)
  MIES version:
  Release_2.3_20210908-191-gc206f5b9b
Date and time of last commit: 2021-11-04T18:47:34+01:00
Submodule status: 
160000 3c125f148c12e579a52c8b730d54dac5ffca2322 0	Packages/IPNWB
160000 56f1da31d786a593892280c2d2b2b1190def0fb5 0	Packages/doc/doxygen-filter-ipf
160000 e79dec5762733aefd3af3a36dda73d040ae2ce62 0	Packages/unit-testing
  ################################
image

**Comment by t-b** [comment]
@timjarsky Thanks for testing. Fixed.

**Review by timjarsky — APPROVED** [review]

**Pull request merged**
