### PR TITLE
Bugfix/search string breakage

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by timjarsky** [comment]
@t-b 

(1) The search string in All, V-Clamp, and I-Clamp isn't being applied to the Indexing End Set.
(2) Indexing (with repeat sets) is not indexing at the correct sweep. I can demo.

**Comment by timjarsky** [comment]
> @t-b
> 
> (1) The search string in All, V-Clamp, and I-Clamp isn't being applied to the Indexing End Set.
> (2) Indexing (with repeat sets) is not indexing at the correct sweep. I can demo.

@t-b ignore (1); user error.

**Comment by timjarsky** [comment]
> > @t-b

> > (2) Indexing (with repeat sets) is not indexing at the correct sweep. I can demo.

Actually, it repeats the sets after completing an indexing cycle. This was likely a design choice I may want to change.

**Comment by t-b** [comment]
The search string not being applied to the all controls is fixed. 

And yes the indexing is tied to the locked/unlocked logic. The cycles are shown at https://alleninstitute.github.io/MIES/.

And of course I'm happy to implement a "semi"-locked indexing mode.

**Comment by timjarsky** [comment]
> The search string not being applied to the all controls is fixed.
> 
> And yes the indexing is tied to the locked/unlocked logic. The cycles are shown at https://alleninstitute.github.io/MIES/.
> 
> And of course I'm happy to implement a "semi"-locked indexing mode.

@t-b That's okay; we'll increase the number of sweeps in the stimset instead.

**Pull request merged**
